package com.onlinejudge.learning.standardlibrary.application;

import com.onlinejudge.learning.standardlibrary.domain.AiStandardLibraryLayer;

import java.util.List;

final class AiStandardLibraryV16DensityExpansionSeeds {

    private static final List<String> LANGUAGES = List.of("PYTHON", "CPP17");

    private AiStandardLibraryV16DensityExpansionSeeds() {
    }

    static void addTo(List<AiStandardLibrarySeed> seeds) {
        addLinkedListOperations(seeds);
        addIntervalScheduling(seeds);
        addPrefixSumQueries(seeds);
        addCountingSortFrequency(seeds);
        addRunLengthEncoding(seeds);
        addMajorityVote(seeds);
        addPrimeJudgement(seeds);
        addTopologicalDependency(seeds);
    }

    private static void addLinkedListOperations(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V16_LINKED_LIST_PREV_NEXT",
                "能力点/V16链表",
                "维护链表前驱、后继和头尾边界",
                "能用指针或下标模拟链表节点关系，说明每个节点的前驱、后继、头节点、尾节点和删除后连接关系。",
                "链表题先画节点关系图，再写每次插入删除前后哪些连接要改变。",
                List.of("DS.LINEAR.LIST.前驱后继", "DS.LINEAR.LIST.插入删除",
                        "DS.LINEAR.LIST.指针_下标模拟"),
                List.of("BASIC.ARRAY.INDEX.下标映射"),
                "HIGH",
                List.of(
                        m("MP_V16_LIST_DELETE_ONLY_MOVES_CURRENT",
                                "删除节点时只移动当前指针",
                                "链表删除节点时只把当前节点跳走，却没有修改前驱的 next 或后继的 prev，导致后续遍历仍会经过已删除节点。",
                                "把删除理解成变量移动，没有意识到链表结构要改的是相邻节点之间的连接。",
                                "STATE",
                                List.of("DS.LINEAR.LIST.插入删除", "DS.LINEAR.LIST.前驱后继"),
                                List.of("ENG.DEBUG.TRACE.数组状态"),
                                "HIGH"),
                        m("MP_V16_LIST_HEAD_TAIL_SENTINEL_MISUSED",
                                "头尾哨兵和真实节点混用",
                                "使用头尾哨兵、虚拟头节点或循环链表时，把哨兵当作真实数据节点处理，导致首尾元素重复、漏处理或约瑟夫类删除错位。",
                                "只看到链表里有节点，没有区分辅助边界节点和题目中的真实对象。",
                                "BOUNDARY",
                                List.of("DS.LINEAR.LIST.头尾节点", "DS.LINEAR.LIST.边界节点"),
                                List.of("BASIC.BRANCH.CASE.边界归属"),
                                "HIGH"),
                        m("MP_V16_LIST_INSERT_ORDER_BREAKS_NEXT_POINTER",
                                "插入节点时更新顺序断开原链",
                                "在两个节点之间插入新节点时，先覆盖原 next 指针却没有保存旧后继，导致后半段链表丢失。",
                                "没有把插入前的前驱、后继、新节点三者关系同时画出来。",
                                "ORDER",
                                List.of("DS.LINEAR.LIST.插入删除", "DS.LINEAR.LIST.指针_下标模拟"),
                                List.of("BASIC.TYPE.VARIABLE.赋值覆盖"),
                                "HIGH")),
                "IP_V16_LIST_POINTER_TABLE",
                "用前驱后继表复盘链表操作",
                "适用于学生能说出链表概念，但插入、删除、循环链表边界经常错。",
                "让学生列出每个节点的 prev、next、是否真实节点、是否已删除，再逐步更新表格。",
                "教师可通过表格追问删除或插入时哪些连接必须同时改变。",
                List.of("MP_V16_LIST_DELETE_ONLY_MOVES_CURRENT", "MP_V16_LIST_INSERT_ORDER_BREAKS_NEXT_POINTER"));
    }

    private static void addIntervalScheduling(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V16_INTERVAL_SELECT_MERGE",
                "能力点/V16区间调度与合并",
                "区分区间排序、合并和不相交选择",
                "能根据题目目标判断是合并重叠区间、选择最多不相交区间、覆盖目标区间，还是按右端点做贪心选择。",
                "区间题先写每个区间端点含义，再判断边界相等算重叠还是不相交。",
                List.of("ALGO.GREEDY.INTERVAL.按右端点排序", "ALGO.GREEDY.INTERVAL.区间合并",
                        "ALGO.GREEDY.INTERVAL.不相交选择"),
                List.of("ALGO.SORT.APPLICATION.区间排序"),
                "HIGH",
                List.of(
                        m("MP_V16_INTERVAL_SORTS_BY_LEFT_FOR_ACTIVITY_SELECTION",
                                "不相交区间选择误按左端点排序",
                                "目标是选择尽量多的不相交区间，却按左端点或区间长度排序，导致早开始但结束很晚的区间挡住后续可选区间。",
                                "把区间调度和普通区间排序混在一起，没有说明当前贪心要尽早释放右端点。",
                                "MODELING",
                                List.of("ALGO.GREEDY.INTERVAL.按右端点排序", "ALGO.GREEDY.INTERVAL.不相交选择"),
                                List.of("ALGO.GREEDY.CHOICE.排序依据"),
                                "HIGH"),
                        m("MP_V16_INTERVAL_TOUCH_BOUNDARY_CLASSIFIED_WRONG",
                                "端点相等时重叠关系判断错",
                                "两个区间刚好在端点相接时，代码没有根据题意判断能否共存，导致预约、时间段或不相交集合多选或少选。",
                                "把所有端点相等都当成同一种情况，没有区分闭区间、半开区间和题面是否允许相接。",
                                "BOUNDARY",
                                List.of("ALGO.GREEDY.INTERVAL.边界重叠", "BASIC.EXPR.COMPARE.边界比较"),
                                List.of("BASIC.BRANCH.CASE.边界归属"),
                                "HIGH"),
                        m("MP_V16_INTERVAL_MERGE_FORGETS_LAST_SEGMENT",
                                "区间合并后漏加入最后一段",
                                "遍历区间时只在发现新区间时保存上一段，循环结束后没有把当前维护的最后一段加入答案。",
                                "只关注循环中发生重叠或断开的时刻，忘记循环结束时仍有一段待输出。",
                                "ORDER",
                                List.of("ALGO.GREEDY.INTERVAL.区间合并", "BASIC.LOOP.BOUNDARY.最后一次迭代"),
                                List.of("BASIC.ARRAY.TRAVERSE.全量遍历"),
                                "HIGH")),
                "IP_V16_INTERVAL_ENDPOINT_TABLE",
                "用端点关系表检查区间题",
                "适用于学生能写排序，但分不清合并、覆盖和不相交选择的区间题。",
                "让学生记录排序依据、当前区间、已选右端点、是否重叠、相等端点归属和当前答案。",
                "教师可用端点表确认学生是否把题目目标和比较符号对齐。",
                List.of("MP_V16_INTERVAL_SORTS_BY_LEFT_FOR_ACTIVITY_SELECTION", "MP_V16_INTERVAL_TOUCH_BOUNDARY_CLASSIFIED_WRONG"));
    }

    private static void addPrefixSumQueries(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V16_PREFIX_SUM_RANGE_QUERY",
                "能力点/V16前缀和",
                "维护前缀定义、空前缀和区间查询公式",
                "能说明 prefix[i] 表示前多少项的累计结果，并根据 0 基或 1 基下标写出区间和、空区间和累计类型。",
                "前缀和题先固定 prefix 的含义，再用长度为 1 的区间验证公式。",
                List.of("ALGO.PREFIX.SUM.前缀定义", "ALGO.PREFIX.SUM.区间查询",
                        "ALGO.PREFIX.SUM.空前缀"),
                List.of("BASIC.ARRAY.INDEX.下标映射"),
                "HIGH",
                List.of(
                        m("MP_V16_PREFIX_QUERY_OFF_BY_ONE",
                                "区间和公式左右端点差一",
                                "求 [l,r] 或 [l,r) 的区间和时，前缀数组下标少减一或多减一，导致单点区间、首段区间或尾段区间错误。",
                                "没有先说明 prefix[i] 是前 i 项还是到下标 i 为止。",
                                "BOUNDARY",
                                List.of("ALGO.PREFIX.SUM.区间查询", "ALGO.PREFIX.SUM.下标偏移"),
                                List.of("BASIC.LOOP.BOUNDARY.0_基下标循环"),
                                "HIGH"),
                        m("MP_V16_PREFIX_MISSING_ZERO_PREFIX",
                                "没有设置空前缀导致首段查询特判混乱",
                                "前缀数组没有保留 prefix[0]=0 或等价空前缀，查询从第一个元素开始的区间时需要额外分支，容易漏处理或写错。",
                                "只从第一个元素开始累计，没有把空集合累计值作为统一公式的一部分。",
                                "INITIALIZATION",
                                List.of("ALGO.PREFIX.SUM.空前缀", "ALGO.PREFIX.SUM.前缀定义"),
                                List.of("BASIC.ARRAY.INDEX.1_基下标"),
                                "HIGH"),
                        m("MP_V16_PREFIX_SUM_INTEGER_OVERFLOW",
                                "前缀累计变量范围不足",
                                "单个元素范围不大，但累计很多项后超过 int 或普通整数范围，导致区间和、平均值或比较结果错误。",
                                "只看单项数据范围，没有估算 n 项累计后的最大可能值。",
                                "TYPE",
                                List.of("BASIC.TYPE.INTEGER.计数变量类型选择", "ALGO.PREFIX.SUM.前缀定义"),
                                List.of("ENG.COMPLEXITY.TIME.数据范围反推"),
                                "HIGH")),
                "IP_V16_PREFIX_DEFINITION_CARD",
                "用前缀定义卡统一区间公式",
                "适用于学生会背前缀和，但公式下标、首段查询和累计范围经常不稳。",
                "让学生写清 prefix[i] 含义、数组基准、区间端点类型、单点区间验证和最大累计值。",
                "教师可用定义卡判断错误来自下标体系、空前缀还是数据范围。",
                List.of("MP_V16_PREFIX_QUERY_OFF_BY_ONE", "MP_V16_PREFIX_MISSING_ZERO_PREFIX"));
    }

    private static void addCountingSortFrequency(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V16_COUNTING_SORT_FREQUENCY",
                "能力点/V16计数排序与频次统计",
                "维护值域、频次数组和按值还原顺序",
                "能根据数据值域建立计数数组，统计每个值出现次数，并按值域顺序还原排序结果或频次统计结果。",
                "计数排序题先写值域范围、偏移量、计数含义和还原顺序。",
                List.of("ALGO.SORT.BASIC.计数排序", "BASIC.ARRAY.PREFIX.计数数组",
                        "BASIC.ARRAY.PREFIX.频次统计"),
                List.of("BASIC.ARRAY.INDEX.下标映射"),
                "HIGH",
                List.of(
                        m("MP_V16_COUNT_ARRAY_VALUE_OFFSET_MISSING",
                                "计数数组没有处理值域偏移",
                                "输入值不是从 0 开始或包含负数时，直接把值当下标，没有做值域偏移，导致越界或频次落到错误位置。",
                                "只想到用值作为下标，没有先求最小值、最大值和偏移映射。",
                                "BOUNDARY",
                                List.of("BASIC.ARRAY.PREFIX.计数数组", "ALGO.SORT.BASIC.计数排序"),
                                List.of("BASIC.ARRAY.INDEX.下标映射"),
                                "HIGH"),
                        m("MP_V16_COUNTING_SORT_OUTPUTS_COUNTS_NOT_VALUES",
                                "还原排序结果时输出频次而不是原值",
                                "统计频次数组后，输出了每个桶的计数或桶下标缺失，导致结果不是排序后的原始数据序列。",
                                "把计数表当成最终答案，没有区分桶编号和值、桶内容数量和还原动作。",
                                "ORDER",
                                List.of("ALGO.SORT.BASIC.计数排序", "BASIC.ARRAY.PREFIX.频次统计"),
                                List.of("BASIC.LOOP.NESTED.内外层变量区分"),
                                "MEDIUM"),
                        m("MP_V16_FREQUENCY_RESET_MISSING_BETWEEN_CASES",
                                "多组数据频次数组未重置",
                                "上一组数据的频次残留到下一组，导致统计、计数排序或投票结果混入旧状态。",
                                "把计数数组当成一次性全局变量，没有在每组输入开始前恢复为空状态。",
                                "STATE",
                                List.of("BASIC.ARRAY.PREFIX.频次统计", "BASIC.IO.MULTI_CASE.每组状态重置"),
                                List.of("CONTEST.SUBMIT.CHECKLIST.多组状态复查"),
                                "HIGH")),
                "IP_V16_FREQUENCY_TABLE_TRACE",
                "用频次表检查计数排序",
                "适用于学生知道要计数，但值域偏移、还原顺序和多组重置经常错。",
                "让学生列出原值、映射下标、当前频次、还原输出值和每组开始时计数表状态。",
                "教师可用频次表确认学生是否把计数数组当成中间结构而非最终结果。",
                List.of("MP_V16_COUNT_ARRAY_VALUE_OFFSET_MISSING", "MP_V16_FREQUENCY_RESET_MISSING_BETWEEN_CASES"));
    }

    private static void addRunLengthEncoding(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V16_RUN_LENGTH_ENCODING",
                "能力点/V16游程编码",
                "维护连续段字符、长度和最后一段输出",
                "能按顺序扫描字符串，把连续相同字符合并成字符加长度的游程，并正确处理首段、切换段和最后一段。",
                "游程编码题先记录当前字符、当前长度、何时输出上一段。",
                List.of("BASIC.STRING.BUILD.游程编码", "BASIC.STRING.CHAR.字符遍历",
                        "BASIC.STRING.BUILD.结果顺序"),
                List.of("BASIC.LOOP.BOUNDARY.最后一次迭代"),
                "MEDIUM",
                List.of(
                        m("MP_V16_RLE_LAST_RUN_NOT_FLUSHED",
                                "游程编码漏输出最后一段",
                                "只在发现字符变化时输出上一段，循环结束后没有输出当前维护的最后一段。",
                                "把段切换当成唯一输出时机，忘记字符串结束本身也是一段结束。",
                                "ORDER",
                                List.of("BASIC.STRING.BUILD.游程编码", "BASIC.LOOP.BOUNDARY.最后一次迭代"),
                                List.of("BASIC.ARRAY.TRAVERSE.全量遍历"),
                                "HIGH"),
                        m("MP_V16_RLE_COUNT_STARTS_AT_ZERO",
                                "连续段长度初值错误",
                                "开始新段时计数从 0 开始或没有把当前字符算入，导致每段长度少一。",
                                "没有明确当前字符被归入新段还是旧段。",
                                "INITIALIZATION",
                                List.of("BASIC.STRING.BUILD.游程编码", "BASIC.TYPE.VARIABLE.声明与初始化"),
                                List.of("BASIC.LOOP.FOR.起点设计"),
                                "MEDIUM"),
                        m("MP_V16_RLE_EMPTY_STRING_ACCESS",
                                "空串时直接访问第一个字符",
                                "输入可能为空或处理子串为空时，代码直接读取 s[0] 或首字符，导致运行错误。",
                                "默认字符串至少有一个字符，没有把空串作为合法边界。",
                                "RUNTIME",
                                List.of("BASIC.STRING.SUBSTRING.空串处理", "BASIC.STRING.BUILD.游程编码"),
                                List.of("BASIC.BRANCH.GUARD.空结果处理"),
                                "HIGH")),
                "IP_V16_RLE_SEGMENT_TRACE",
                "用连续段表检查游程编码",
                "适用于学生能遍历字符串，但首段、段切换和最后一段经常漏。",
                "让学生列出当前位置字符、当前段字符、当前段长度、是否输出上一段和结果串。",
                "教师可用连续段表追问最后一段为什么也需要输出。",
                List.of("MP_V16_RLE_LAST_RUN_NOT_FLUSHED", "MP_V16_RLE_EMPTY_STRING_ACCESS"));
    }

    private static void addMajorityVote(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V16_MAJORITY_VOTE_CANDIDATE",
                "能力点/V16多数投票",
                "维护候选值、票数抵消和最终验证",
                "能解释 Boyer-Moore 多数投票中候选值和计数的含义，并在题目未保证存在多数元素时完成二次验证。",
                "投票题先确认题目是否保证过半，再决定是否需要统计候选真实次数。",
                List.of("ALGO.SIM.STATE.多数投票算法", "ALGO.SIM.STATE.状态变量选择",
                        "ALGO.SIM.STATE.状态同步"),
                List.of("BASIC.ARRAY.TRAVERSE.全量遍历"),
                "MEDIUM",
                List.of(
                        m("MP_V16_MAJORITY_VOTE_NO_FINAL_VERIFY",
                                "题目不保证多数时缺少最终验证",
                                "投票过程得到候选值后直接输出，但题目没有保证存在超过一半的元素，也没有做二次验证，导致没有多数元素的数据被误判。",
                                "把候选值当成一定正确的答案，没有区分候选产生和答案验证。",
                                "VALIDATION",
                                List.of("ALGO.SIM.STATE.多数投票算法", "BASIC.ARRAY.PREFIX.频次统计"),
                                List.of("ENG.DEBUG.BOUNDARY.重复元素"),
                                "HIGH"),
                        m("MP_V16_MAJORITY_COUNT_RESET_WITHOUT_CANDIDATE",
                                "票数归零后没有同步更新候选值",
                                "计数抵消到 0 后继续沿用旧候选，或先比较再设候选，导致后续票数围绕错误对象累计。",
                                "没有把 count 为 0 理解成当前没有候选，需要用新元素重新开始。",
                                "STATE",
                                List.of("ALGO.SIM.STATE.多数投票算法", "ALGO.SIM.STATE.状态同步"),
                                List.of("ENG.DEBUG.TRACE.循环状态"),
                                "HIGH"),
                        m("MP_V16_MAJORITY_THRESHOLD_USES_AT_LEAST_HALF",
                                "过半阈值误写成不少于一半",
                                "需要超过 n/2 的多数元素时，代码把等于一半也当成多数，偶数长度数据容易误判。",
                                "没有区分“大于一半”和“不少于一半”。",
                                "BOUNDARY",
                                List.of("ALGO.SIM.STATE.多数投票算法", "BASIC.EXPR.COMPARE.边界比较"),
                                List.of("BASIC.BRANCH.CASE.边界归属"),
                                "MEDIUM")),
                "IP_V16_MAJORITY_TRACE_AND_VERIFY",
                "用候选票数表检查多数投票",
                "适用于学生会写投票循环，但候选更新、抵消含义和最终验证不稳定。",
                "让学生记录当前元素、候选值、票数变化、归零时机和最终真实出现次数。",
                "教师可用票数表区分算法过程正确和题目保证条件缺失。",
                List.of("MP_V16_MAJORITY_VOTE_NO_FINAL_VERIFY", "MP_V16_MAJORITY_COUNT_RESET_WITHOUT_CANDIDATE"));
    }

    private static void addPrimeJudgement(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V16_PRIME_TRIAL_DIVISION",
                "能力点/V16素数判断",
                "维护质数定义、试除范围和特殊值处理",
                "能说明质数只对大于 1 的整数成立，并用试除到平方根或筛法判断多个数的质数状态。",
                "素数题先处理 0、1、2，再确定试除上界和是否需要批量筛法。",
                List.of("MATH.NUMBER.PRIME.试除判定", "MATH.NUMBER.PRIME.1_不是质数",
                        "MATH.NUMBER.PRIME.筛法"),
                List.of("MATH.NUMBER.DIVISIBILITY.因子枚举"),
                "MEDIUM",
                List.of(
                        m("MP_V16_PRIME_TREATS_ONE_AS_PRIME",
                                "把 1 当成质数",
                                "代码只检查能否被其他数整除，没有先排除 1，导致 1 被归入质数。",
                                "把没有找到因子误认为就是质数，没有回到质数定义中的大于 1。",
                                "CONCEPT",
                                List.of("MATH.NUMBER.PRIME.1_不是质数", "MATH.NUMBER.PRIME.试除判定"),
                                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                                "HIGH"),
                        m("MP_V16_PRIME_LOOP_STOPS_BEFORE_SQRT_FACTOR",
                                "试除循环漏掉平方根因子",
                                "判断完全平方数或含平方根因子的合数时，循环条件没有包含 i*i 等于 n 的情况，导致合数被判为质数。",
                                "只写到小于平方根，没有把刚好等于平方根的因子单独验证。",
                                "BOUNDARY",
                                List.of("MATH.NUMBER.PRIME.试除判定", "MATH.NUMBER.DIVISIBILITY.平方根优化"),
                                List.of("BASIC.EXPR.COMPARE.边界比较"),
                                "HIGH"),
                        m("MP_V16_PRIME_BATCH_REPEATS_TRIAL_DIVISION",
                                "批量质数判断仍逐个试除超时",
                                "需要判断大量数或多次查询时，每个数都从头试除，数据范围较大时容易超时。",
                                "没有把多次查询和单次数判断区分开，也没有考虑筛法预处理。",
                                "COMPLEXITY",
                                List.of("MATH.NUMBER.PRIME.筛法", "ENG.COMPLEXITY.TRADEOFF.预处理"),
                                List.of("CONTEST.READING.CONSTRAINT.数据范围"),
                                "MEDIUM")),
                "IP_V16_PRIME_BOUNDARY_AND_SIEVE_CARD",
                "用定义和上界卡检查素数题",
                "适用于学生会试除，但 1、平方根边界和多次查询复杂度经常错。",
                "让学生写出特殊值、试除条件、最大检查因子、查询次数和是否需要筛法。",
                "教师可用这张卡判断错误来自定义、边界还是复杂度。",
                List.of("MP_V16_PRIME_TREATS_ONE_AS_PRIME", "MP_V16_PRIME_LOOP_STOPS_BEFORE_SQRT_FACTOR"));
    }

    private static void addTopologicalDependency(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V16_TOPOLOGICAL_DEPENDENCY",
                "能力点/V16拓扑依赖",
                "维护入度、依赖边方向和队列推进",
                "能把任务依赖关系建成有向图，维护每个节点入度，并用队列推进当前没有前置依赖的节点。",
                "拓扑题先确定边方向：谁必须先做，谁依赖谁，再更新被影响节点的入度。",
                List.of("ALGO.GRAPH.TOPO.入度", "ALGO.GRAPH.TOPO.队列推进",
                        "ALGO.GRAPH.TOPO.依赖关系"),
                List.of("DS.GRAPH.STORE.邻接表"),
                "HIGH",
                List.of(
                        m("MP_V16_TOPO_EDGE_DIRECTION_REVERSED",
                                "依赖边方向建反",
                                "题目说 A 是 B 的前置任务，但代码把边建成 B 指向 A，导致入度含义反转，队列起点和结果顺序都错。",
                                "没有把“先做谁”和“谁依赖谁”分别转成有向边。",
                                "MODELING",
                                List.of("ALGO.GRAPH.TOPO.依赖关系", "DS.GRAPH.MODEL.有向无向"),
                                List.of("CONTEST.READING.INPUT.图结构"),
                                "HIGH"),
                        m("MP_V16_TOPO_INDEGREE_NOT_DECREMENTED_ON_POP",
                                "弹出节点后没有降低后继入度",
                                "队列取出当前可执行节点后，没有遍历它指向的后继并减少入度，导致后续节点一直无法入队。",
                                "把入度当成静态属性，没有把完成一个前置任务后的状态变化同步到后继。",
                                "STATE",
                                List.of("ALGO.GRAPH.TOPO.入度", "ALGO.GRAPH.TOPO.队列推进"),
                                List.of("DS.LINEAR.QUEUE.先进先出"),
                                "HIGH"),
                        m("MP_V16_TOPO_CYCLE_NOT_DETECTED",
                                "拓扑排序没有检测环",
                                "存在循环依赖时，队列提前为空但仍直接输出已有顺序，没有比较处理节点数和总节点数。",
                                "只把拓扑当成排序流程，没有检查是否所有节点都被释放。",
                                "VALIDATION",
                                List.of("ALGO.GRAPH.TOPO.环检测", "ALGO.GRAPH.TOPO.队列推进"),
                                List.of("BASIC.BRANCH.CASE.覆盖所有情况"),
                                "HIGH")),
                "IP_V16_TOPO_INDEGREE_TABLE",
                "用入度表检查依赖图",
                "适用于学生能写队列，但边方向、入度更新和环检测容易错。",
                "让学生记录每条依赖边、每个节点入度、入队时刻、弹出节点和处理数量。",
                "教师可用入度表追问当前节点为什么可以入队，是否还有未处理环。",
                List.of("MP_V16_TOPO_EDGE_DIRECTION_REVERSED", "MP_V16_TOPO_INDEGREE_NOT_DECREMENTED_ON_POP"));
    }

    private static MistakeSpec m(String code,
                                 String name,
                                 String description,
                                 String misconception,
                                 String mistakeType,
                                 List<String> knowledgeNodeCodes,
                                 List<String> prerequisites,
                                 String severity) {
        return new MistakeSpec(code, name, description, misconception, mistakeType,
                knowledgeNodeCodes, prerequisites, severity);
    }

    private static void addTheme(List<AiStandardLibrarySeed> seeds,
                                 String skillCode,
                                 String category,
                                 String skillName,
                                 String skillDescription,
                                 String learningGoal,
                                 List<String> skillKnowledgeNodes,
                                 List<String> skillPrerequisites,
                                 String severity,
                                 List<MistakeSpec> mistakes,
                                 String improvementCode,
                                 String improvementName,
                                 String improvementDescription,
                                 String studentBenefit,
                                 String teacherExplanation,
                                 List<String> relatedMistakeCodes) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                skillCode,
                category,
                skillName,
                skillDescription,
                learningGoal,
                skillKnowledgeNodes,
                skillPrerequisites,
                severity,
                LANGUAGES);
        mistakes.forEach(mistake -> AiStandardLibrarySeedCatalog.mistake(seeds,
                mistake.code(),
                category.replace("能力点/", "易错点/"),
                mistake.name(),
                mistake.description(),
                mistake.misconception(),
                skillCode,
                mistake.mistakeType(),
                mistake.knowledgeNodeCodes(),
                mistake.prerequisites(),
                mistake.severity(),
                LANGUAGES));
        seeds.add(new AiStandardLibrarySeed(
                AiStandardLibraryLayer.IMPROVEMENT_POINT,
                improvementCode,
                category.replace("能力点/", "提升点/"),
                improvementName,
                improvementDescription,
                "",
                teacherExplanation,
                skillCode,
                "",
                "",
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                improvementDescription,
                studentBenefit,
                "",
                "",
                "",
                skillCode,
                "MEDIUM",
                LANGUAGES,
                relatedMistakeCodes,
                skillKnowledgeNodes,
                skillPrerequisites,
                "用表格化复盘把高频真题错因转化为可迁移检查动作。",
                AiStandardLibrarySeedCatalog.VERSION
        ));
    }

    private record MistakeSpec(
            String code,
            String name,
            String description,
            String misconception,
            String mistakeType,
            List<String> knowledgeNodeCodes,
            List<String> prerequisites,
            String severity
    ) {
    }
}
