package com.onlinejudge.integration;

import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import javax.sql.DataSource;
import java.io.IOException;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(properties = {
        "spring.jpa.hibernate.ddl-auto=validate",
        "app.profile=school",
        "app.content-seed.enabled=false",
        "AI_ENABLED=false",
        "TEACHER_DEV_AUTO_AUTH=false",
        "security.bootstrap-admin.username=bootstrap-admin",
        "security.bootstrap-admin.password=Bootstrap123",
        "security.bootstrap-admin.display-name=测试管理员"
})
@AutoConfigureMockMvc
class PostgresMigrationValidationTest {
    private static final EmbeddedPostgres POSTGRES = startPostgres();

    @DynamicPropertySource
    static void postgresProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", () -> POSTGRES.getJdbcUrl("postgres", "postgres"));
        registry.add("spring.datasource.username", () -> "postgres");
        registry.add("spring.datasource.password", () -> "");
        registry.add("spring.datasource.driver-class-name", () -> "org.postgresql.Driver");
    }

    @Autowired Flyway flyway;
    @Autowired DataSource dataSource;
    @Autowired MockMvc mockMvc;

    @Test
    void emptyPostgresMigratesToV5AndHibernateValidatesTheSchema() throws Exception {
        assertThat(flyway.info().current().getVersion().getVersion()).isEqualTo("5");
        try (var connection = dataSource.getConnection(); var statement = connection.createStatement()) {
            assertThat(count(statement, "select count(*) from information_schema.tables where table_schema='public' and table_name='teacher_accounts'"))
                    .isEqualTo(1);
            assertThat(count(statement, "select count(*) from teacher_accounts where status='ACTIVE' and role='ADMIN' and username_normalized='bootstrap-admin'"))
                    .isEqualTo(1);
        }
    }

    @Test
    void existingNonEmptySchemaIsBaselinedAtV1ThenMigratedWithoutDataLoss() throws Exception {
        try (var connection = dataSource.getConnection(); var statement = connection.createStatement()) {
            statement.execute("create schema legacy_copy");
            statement.execute("set search_path to legacy_copy");
            statement.execute("create table class_groups (id bigint generated by default as identity primary key, name varchar(255) not null, grade varchar(255), teacher_name varchar(255), created_at timestamp not null default current_timestamp)");
            statement.execute("create table assignments (id bigint generated by default as identity primary key, title varchar(255) not null, description text, class_group_id bigint, hint_policy varchar(20) not null default 'L2', status varchar(20) not null default 'ACTIVE', starts_at timestamp, ends_at timestamp, created_at timestamp not null default current_timestamp)");
            statement.execute("create table student_profiles (id bigint generated by default as identity primary key, class_group_id bigint, display_name varchar(255) not null, student_no varchar(255), note varchar(255), identity_key varchar(255) not null, created_at timestamp not null default current_timestamp, last_seen_at timestamp not null default current_timestamp)");
            statement.execute("create table problems (id bigint generated by default as identity primary key, title varchar(255) not null, description text not null, difficulty varchar(20) not null, time_limit integer not null, memory_limit integer not null, created_at timestamp default current_timestamp)");
            statement.execute("insert into class_groups (name, created_at) values ('保留班级', current_timestamp)");
            statement.execute("insert into problems (title, description, difficulty, time_limit, memory_limit) values ('保留题目', '旧库题目', 'EASY', 1000, 128000)");
        }

        Flyway existing = Flyway.configure().dataSource(dataSource)
                .schemas("legacy_copy").defaultSchema("legacy_copy")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true).baselineVersion("1").load();
        existing.migrate();

        assertThat(existing.info().current().getVersion().getVersion()).isEqualTo("5");
        try (var connection = dataSource.getConnection(); var statement = connection.createStatement()) {
            statement.execute("set search_path to legacy_copy");
            assertThat(count(statement, "select count(*) from class_groups where name='保留班级'")) .isEqualTo(1);
            assertThat(count(statement, "select count(*) from teacher_accounts where id='00000000-0000-0000-0000-000000000001'"))
                    .isEqualTo(1);
            assertThat(count(statement, "select count(*) from problems where title='保留题目' and scope='PUBLIC' and version_state='PUBLISHED'"))
                    .isEqualTo(1);
        }
    }

    @Test
    void schoolProfileRequiresCsrfForAuthenticatedTeacherMutations() throws Exception {
        MvcResult login = mockMvc.perform(post("/api/auth/teacher/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"username\":\"bootstrap-admin\",\"password\":\"Bootstrap123\"}"))
                .andExpect(status().isOk()).andReturn();
        String teacherCookie = login.getResponse().getHeaders("Set-Cookie").stream()
                .map(value -> value.split(";", 2)[0])
                .filter(value -> value.startsWith("OJ_TEACHER_SESSION="))
                .findFirst().orElseThrow();

        mockMvc.perform(post("/api/teacher/classes").header("Cookie", teacherCookie)
                        .contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"CSRF班\"}"))
                .andExpect(status().isForbidden());
        mockMvc.perform(post("/api/teacher/classes").with(csrf()).header("Cookie", teacherCookie)
                        .contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"CSRF班\"}"))
                .andExpect(status().isOk());
    }

    private long count(java.sql.Statement statement, String sql) throws Exception {
        try (var result = statement.executeQuery(sql)) {
            result.next();
            return result.getLong(1);
        }
    }

    private static EmbeddedPostgres startPostgres() {
        try {
            return EmbeddedPostgres.builder().setPort(0).start();
        } catch (IOException failure) {
            throw new ExceptionInInitializerError(failure);
        }
    }

    @AfterAll
    static void stopPostgres() throws IOException {
        POSTGRES.close();
    }
}
