package com.onlinejudge.learning.standardlibrary.application;

import com.onlinejudge.learning.standardlibrary.domain.AiStandardLibraryLayer;

import java.util.List;

final class AiStandardLibraryV10AbsorptionSeeds {

    private static final List<String> LANGUAGES = List.of("PYTHON", "CPP17");

    private AiStandardLibraryV10AbsorptionSeeds() {
    }

    static void addTo(List<AiStandardLibrarySeed> seeds) {
        addVariableLifecycle(seeds);
        addFloatPrecision(seeds);
        addBooleanLogic(seeds);
        addFunctionContract(seeds);
        addNumberTheory(seeds);
        addCountingModel(seeds);
        addDebugTriage(seeds);
        addComplexitySpace(seeds);
    }

    private static void addVariableLifecycle(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V10_VARIABLE_LIFECYCLE_CONTRACT",
                "能力点/兜底吸收-变量生命周期",
                "维护变量初始化、赋值覆盖和作用域生命周期",
                "能说明变量第一次获得合法值的位置、每次赋值是否覆盖仍需使用的旧值，以及同名变量是否处在同一作用域。",
                "变量题先画生命周期：声明、初始化、读取、覆盖和离开作用域，每一次读取都必须能追到最近一次有效赋值。",
                List.of("BASIC.TYPE.VARIABLE.声明与初始化", "BASIC.TYPE.VARIABLE.赋值覆盖", "BASIC.TYPE.VARIABLE.作用域"),
                List.of("BASIC.TYPE.VARIABLE.变量命名", "ENG.STYLE.NAME.变量含义"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_VARIABLE_READ_BEFORE_VALID_ASSIGNMENT",
                "易错点/兜底吸收-变量生命周期",
                "变量在有效赋值前被读取",
                "分支、循环或多组数据中某条路径没有给变量赋值，但后续仍读取它，导致默认值、旧值或未定义值参与计算。",
                "只看到了普通样例会经过赋值路径，没有检查每个分支和每组数据开始时变量是否都有合法来源。",
                "SK_V10_VARIABLE_LIFECYCLE_CONTRACT",
                "INITIALIZATION",
                List.of("BASIC.TYPE.VARIABLE.声明与初始化", "BASIC.BRANCH.CASE.覆盖所有情况", "BASIC.IO.MULTI_CASE.每组状态重置"),
                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_VARIABLE_OVERWRITES_VALUE_NEEDED_LATER",
                "易错点/兜底吸收-变量生命周期",
                "变量被提前覆盖导致后续仍需的旧值丢失",
                "同一个变量先保存原始输入、中间状态或上一次答案，后面又被复用为新含义，导致后续计算读不到原来的值。",
                "为了少建变量把多个含义塞进同一个名字，没有确认旧值是否还会被后续代码使用。",
                "SK_V10_VARIABLE_LIFECYCLE_CONTRACT",
                "STATE",
                List.of("BASIC.TYPE.VARIABLE.赋值覆盖", "ENG.STYLE.NAME.变量含义", "BASIC.ARRAY.UPDATE.读旧写新分离"),
                List.of("BASIC.TYPE.VARIABLE.变量命名"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_SCOPE_SHADOWS_OUTER_ACCUMULATOR",
                "易错点/兜底吸收-变量生命周期",
                "局部同名变量遮蔽外层累计量",
                "内层循环、函数或代码块重新声明了和外层同名的变量，更新发生在局部变量上，外层答案或累计量没有真正改变。",
                "看到变量名一样就以为改的是同一个值，没有区分局部作用域和外层作用域。",
                "SK_V10_VARIABLE_LIFECYCLE_CONTRACT",
                "STATE",
                List.of("BASIC.TYPE.VARIABLE.作用域", "BASIC.TYPE.VARIABLE.变量命名", "BASIC.LOOP.NESTED.内外层变量区分"),
                List.of("BASIC.FUNCTION.DEF.局部变量"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V10_VARIABLE_LIFECYCLE_TABLE",
                "提升点/兜底吸收-变量生命周期",
                "用变量生命周期表检查初始化、覆盖和作用域",
                "适用于学生经常出现变量旧值残留、未初始化、复用变量含义或作用域遮蔽问题。",
                "修复后让学生为关键变量写出五列：在哪里声明、在哪里第一次赋值、在哪里读取、在哪里覆盖、属于哪个作用域。",
                "教师可用生命周期表判断学生是否能把代码里的变量值来源说清楚，而不是只凭变量名猜含义。",
                "SK_V10_VARIABLE_LIFECYCLE_CONTRACT",
                List.of("MP_V10_VARIABLE_READ_BEFORE_VALID_ASSIGNMENT", "MP_V10_VARIABLE_OVERWRITES_VALUE_NEEDED_LATER"),
                List.of("BASIC.TYPE.VARIABLE.声明与初始化", "BASIC.TYPE.VARIABLE.作用域"));
    }

    private static void addFloatPrecision(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V10_FLOAT_PRECISION_CONTRACT",
                "能力点/兜底吸收-浮点精度",
                "维护浮点误差、整数除法和输出精度契约",
                "能区分整数除法、浮点计算、误差比较和最终格式输出，避免中间计算已经丢失精度却只调整答案变量。",
                "浮点题要分三步检查：计算是否进入浮点、比较是否使用误差、输出是否符合题面精度。",
                List.of("BASIC.TYPE.FLOAT.浮点误差", "BASIC.TYPE.FLOAT.小数比较", "BASIC.TYPE.FLOAT.整数除法误用", "BASIC.IO.STDOUT.小数精度控制"),
                List.of("BASIC.EXPR.ARITH.整数除法", "ENG.ERROR.FORMAT.小数位错误"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_FLOAT_EQUALITY_COMPARE_USED",
                "易错点/兜底吸收-浮点精度",
                "浮点结果直接用等号比较",
                "代码用 a == b 或 while (l != r) 判断浮点结果是否相等，实际误差让应当相等的值走到错误分支或循环无法停止。",
                "把浮点数当成精确整数使用，没有按误差范围比较差值。",
                "SK_V10_FLOAT_PRECISION_CONTRACT",
                "BOUNDARY",
                List.of("BASIC.TYPE.FLOAT.浮点误差", "BASIC.TYPE.FLOAT.小数比较", "BASIC.EXPR.COMPARE.浮点比较"),
                List.of("ALGO.BINARY.ANSWER.精度二分"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_INTEGER_DIVISION_BEFORE_FLOAT_CAST",
                "易错点/兜底吸收-浮点精度",
                "整数除法先截断再参与浮点计算",
                "表达式中两个整数先相除得到截断结果，再赋值给 double 或参与小数公式，导致比例、平均值或概率偏小。",
                "只检查了接收变量是浮点类型，没有检查除法发生时两边操作数是否已经是浮点。",
                "SK_V10_FLOAT_PRECISION_CONTRACT",
                "VALUE_RANGE",
                List.of("BASIC.TYPE.FLOAT.整数除法误用", "BASIC.EXPR.ARITH.整数除法", "BASIC.TYPE.FLOAT.取整策略"),
                List.of("BASIC.TYPE.INTEGER.int_范围"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_FLOAT_OUTPUT_PRECISION_MISMATCH",
                "易错点/兜底吸收-浮点精度",
                "小数输出精度和题面要求不一致",
                "内部计算接近正确，但输出没有保留指定小数位、使用了默认格式或四舍五入方式不符合题意，导致格式或精度错误。",
                "以为算对数值就结束，没有把输出格式本身视为判题要求的一部分。",
                "SK_V10_FLOAT_PRECISION_CONTRACT",
                "IO_FORMAT",
                List.of("BASIC.IO.STDOUT.小数精度控制", "BASIC.TYPE.FLOAT.精度输出", "ENG.ERROR.FORMAT.小数位错误"),
                List.of("BASIC.IO.STDOUT.按要求换行"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V10_FLOAT_PRECISION_CHECKLIST",
                "提升点/兜底吸收-浮点精度",
                "用浮点三段清单检查计算、比较和输出",
                "适用于学生算法思路正确，但经常因为整数除法、浮点比较或输出精度丢分。",
                "修复后让学生分别写出：哪一步转成浮点、比较时 eps 是多少、输出需要几位小数。",
                "教师可用这张清单区分是计算精度、判断精度还是输出格式造成错误。",
                "SK_V10_FLOAT_PRECISION_CONTRACT",
                List.of("MP_V10_INTEGER_DIVISION_BEFORE_FLOAT_CAST", "MP_V10_FLOAT_OUTPUT_PRECISION_MISMATCH"),
                List.of("BASIC.TYPE.FLOAT.浮点误差", "BASIC.IO.STDOUT.小数精度控制"));
    }

    private static void addBooleanLogic(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V10_BOOLEAN_BRANCH_CONTRACT",
                "能力点/兜底吸收-布尔条件",
                "维护布尔标志、短路求值和条件组合契约",
                "能说明每个布尔变量何时变为 true/false、复杂条件中与或非的优先级，以及短路求值是否会跳过必要动作。",
                "布尔条件先翻译成自然语言，再用真值表检查每个分支是否覆盖题意。",
                List.of("BASIC.TYPE.CHAR_BOOL.逻辑标志变量", "BASIC.EXPR.LOGIC.与或非", "BASIC.EXPR.LOGIC.短路求值", "BASIC.EXPR.LOGIC.条件组合"),
                List.of("BASIC.BRANCH.CASE.互斥条件", "BASIC.EXPR.PRIORITY.逻辑优先级"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_BOOLEAN_FLAG_NOT_RESET_PER_CASE",
                "易错点/兜底吸收-布尔条件",
                "布尔标志没有在每组或每轮重新初始化",
                "flag 在上一组数据、上一轮循环或上一条路径中被置为 true/false，下一次判断前没有重置，导致当前数据沿用旧结论。",
                "把 flag 当成一次性变量，没有把它的生命周期和每组数据、每轮循环绑定。",
                "SK_V10_BOOLEAN_BRANCH_CONTRACT",
                "INITIALIZATION",
                List.of("BASIC.TYPE.CHAR_BOOL.逻辑标志变量", "BASIC.IO.MULTI_CASE.每组状态重置", "ALGO.SIM.STATE.状态初始化"),
                List.of("BASIC.TYPE.VARIABLE.声明与初始化"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_AND_OR_CONDITION_GROUPING_WRONG",
                "易错点/兜底吸收-布尔条件",
                "与或条件组合缺少括号导致分支含义改变",
                "题意要求 A 且 (B 或 C)，但代码缺少括号并写成 A && B || C 或类似表达式，使某些不满足 A 的情况也进入分支。",
                "按口头表达顺序写条件，没有用括号明确逻辑优先级和互斥范围。",
                "SK_V10_BOOLEAN_BRANCH_CONTRACT",
                "LOGIC",
                List.of("BASIC.EXPR.LOGIC.条件组合", "BASIC.EXPR.PRIORITY.逻辑优先级", "BASIC.BRANCH.CASE.互斥条件"),
                List.of("BASIC.EXPR.LOGIC.德摩根变换"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_SHORT_CIRCUIT_SKIPS_REQUIRED_CHECK",
                "易错点/兜底吸收-布尔条件",
                "短路求值跳过了必须执行的检查或更新",
                "条件表达式依赖函数调用、计数更新或边界检查的副作用，但短路求值使后半段没有执行，状态没有被维护。",
                "把条件里的函数调用当成普通判断，没有意识到与或短路会决定它是否执行。",
                "SK_V10_BOOLEAN_BRANCH_CONTRACT",
                "LOGIC",
                List.of("BASIC.EXPR.LOGIC.短路求值", "BASIC.FUNCTION.RETURN.返回布尔", "BASIC.EXPR.LOGIC.条件组合"),
                List.of("BASIC.FUNCTION.RETURN.输出与返回分离"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V10_BOOLEAN_TRUTH_TABLE_REVIEW",
                "提升点/兜底吸收-布尔条件",
                "用真值表复盘布尔条件和分支覆盖",
                "适用于学生经常把与或非、flag 生命周期或复杂条件写错。",
                "修复后让学生列出关键变量的真假组合、期望进入的分支和代码实际进入的分支。",
                "教师可用真值表让学生发现括号缺失、flag 未重置或短路副作用问题。",
                "SK_V10_BOOLEAN_BRANCH_CONTRACT",
                List.of("MP_V10_BOOLEAN_FLAG_NOT_RESET_PER_CASE", "MP_V10_AND_OR_CONDITION_GROUPING_WRONG"),
                List.of("BASIC.EXPR.LOGIC.条件组合", "BASIC.TYPE.CHAR_BOOL.逻辑标志变量"));
    }

    private static void addFunctionContract(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V10_FUNCTION_RETURN_SIDE_EFFECT_CONTRACT",
                "能力点/兜底吸收-函数契约",
                "维护函数返回值、参数副作用和调用契约",
                "能说明函数输入参数、返回值、是否修改外部状态，以及调用方应该使用返回值还是读取副作用结果。",
                "写函数前先写契约：传什么、改什么、返回什么、调用方拿什么继续算。",
                List.of("BASIC.FUNCTION.DEF.参数设计", "BASIC.FUNCTION.DEF.返回值设计", "BASIC.FUNCTION.RETURN.输出与返回分离", "BASIC.FUNCTION.PARAM.可变对象风险"),
                List.of("BASIC.FUNCTION.DEF.单一职责", "ENG.STYLE.STRUCTURE.函数拆分"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_FUNCTION_PRINTS_INSTEAD_OF_RETURNING_VALUE",
                "易错点/兜底吸收-函数契约",
                "函数把中间结果打印出来但没有返回给调用方",
                "函数内部 print/cout 了结果，调用方却需要继续使用这个值进行判断或组合，最终拿到空值、默认值或错误状态。",
                "把给人看的输出和给程序继续计算的返回值混为一类。",
                "SK_V10_FUNCTION_RETURN_SIDE_EFFECT_CONTRACT",
                "LOGIC",
                List.of("BASIC.FUNCTION.RETURN.输出与返回分离", "BASIC.FUNCTION.DEF.返回值设计", "BASIC.IO.STDOUT.禁止多余调试输出"),
                List.of("ENG.STYLE.STRUCTURE.输出分离"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_FUNCTION_MUTATES_ARGUMENT_UNEXPECTEDLY",
                "易错点/兜底吸收-函数契约",
                "函数意外修改了调用方仍需使用的可变参数",
                "函数接收数组、列表、map 或引用参数后在内部排序、删除或修改，调用方后续仍按原数据理解，导致状态被悄悄改变。",
                "只关注函数内部能完成任务，没有说明这个函数是否允许改变传入对象。",
                "SK_V10_FUNCTION_RETURN_SIDE_EFFECT_CONTRACT",
                "STATE",
                List.of("BASIC.FUNCTION.PARAM.可变对象风险", "BASIC.FUNCTION.PARAM.引用传递", "BASIC.ARRAY.UPDATE.原地修改"),
                List.of("BASIC.ARRAY.UPDATE.临时数组"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_FUNCTION_RETURN_COLLECTION_ALIAS_SHARED",
                "易错点/兜底吸收-函数契约",
                "返回集合和内部缓存共享导致后续修改互相影响",
                "函数返回列表、数组或 map 后继续复用同一个对象作为缓存，调用方保存的结果随下一次调用被改写。",
                "以为 return 代表复制了一份结果，没有意识到返回的是同一个可变对象引用。",
                "SK_V10_FUNCTION_RETURN_SIDE_EFFECT_CONTRACT",
                "STATE",
                List.of("BASIC.FUNCTION.RETURN.返回集合", "BASIC.FUNCTION.PARAM.可变对象风险", "BASIC.TYPE.VARIABLE.赋值覆盖"),
                List.of("BASIC.FUNCTION.DEF.局部变量"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V10_FUNCTION_CONTRACT_CARD",
                "提升点/兜底吸收-函数契约",
                "用函数契约卡片检查输入、输出和副作用",
                "适用于学生开始拆函数，但经常把打印、返回值、参数修改和全局状态混在一起。",
                "修复后让学生为每个函数写四行：输入参数、返回值、会修改的外部对象、不会修改的对象。",
                "教师可用契约卡片检查学生是否真正理解函数边界，而不是只把代码搬进函数。",
                "SK_V10_FUNCTION_RETURN_SIDE_EFFECT_CONTRACT",
                List.of("MP_V10_FUNCTION_PRINTS_INSTEAD_OF_RETURNING_VALUE", "MP_V10_FUNCTION_MUTATES_ARGUMENT_UNEXPECTEDLY"),
                List.of("BASIC.FUNCTION.RETURN.输出与返回分离", "BASIC.FUNCTION.PARAM.可变对象风险"));
    }

    private static void addNumberTheory(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V10_NUMBER_MOD_GCD_CONTRACT",
                "能力点/兜底吸收-数论取模",
                "维护整除、取模、最大公约数和溢出边界",
                "能说明取模结果的数学意义、负数修正方式、gcd/lcm 的除零边界，以及乘法取模或 lcm 计算中的溢出风险。",
                "数论题不要只套公式，要先写清每个公式要求的值域、零值和溢出边界。",
                List.of("MATH.NUMBER.MOD.负数取模修正", "MATH.NUMBER.MOD.乘法取模", "MATH.NUMBER.GCD.除零边界", "MATH.NUMBER.GCD.最小公倍数"),
                List.of("BASIC.EXPR.ARITH.取模含义", "BASIC.TYPE.INTEGER.整型溢出"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_NEGATIVE_MOD_USED_AS_ARRAY_INDEX",
                "易错点/兜底吸收-数论取模",
                "负数取模结果直接当作非负余数使用",
                "语言里的负数取模可能得到负值，代码直接用它当数组下标、桶编号或状态编号，导致越界或分类错误。",
                "把数学里的非负余数和编程语言的 % 结果当成同一件事，没有做二次修正。",
                "SK_V10_NUMBER_MOD_GCD_CONTRACT",
                "BOUNDARY",
                List.of("MATH.NUMBER.MOD.负数取模修正", "BASIC.EXPR.ARITH.负数取模", "BASIC.ARRAY.INDEX.越界访问"),
                List.of("BASIC.EXPR.ARITH.取模含义"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_LCM_MULTIPLIES_BEFORE_DIVIDE_OVERFLOW",
                "易错点/兜底吸收-数论取模",
                "最小公倍数先乘后除导致中间溢出",
                "计算 lcm(a,b) 时先执行 a*b 再除以 gcd，虽然最终答案可能在范围内，中间乘法已经溢出。",
                "只检查最终结果范围，没有检查公式中间表达式的最大值。",
                "SK_V10_NUMBER_MOD_GCD_CONTRACT",
                "VALUE_RANGE",
                List.of("MATH.NUMBER.GCD.最小公倍数", "BASIC.TYPE.INTEGER.整型溢出", "MATH.NUMBER.MOD.大数防溢出"),
                List.of("MATH.NUMBER.GCD.欧几里得算法"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_GCD_ZERO_CASE_NOT_DEFINED",
                "易错点/兜底吸收-数论取模",
                "gcd 或约分逻辑没有定义零值边界",
                "输入中可能出现 0 或分子分母为 0 的边界，但代码直接取模、递归或约分，导致除零、死递归或错误结果。",
                "只按正整数样例写 gcd，没有先定义 gcd(0,x)、gcd(x,0) 和非法分母如何处理。",
                "SK_V10_NUMBER_MOD_GCD_CONTRACT",
                "BOUNDARY",
                List.of("MATH.NUMBER.GCD.除零边界", "ENG.ERROR.RUNTIME.除零", "MATH.NUMBER.GCD.约分"),
                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                "HIGH",
                LANGUAGES);
        improvement(seeds,
                "IP_V10_NUMBER_BOUNDARY_FORMULA_TABLE",
                "提升点/兜底吸收-数论取模",
                "用数论公式边界表检查取模、gcd 和 lcm",
                "适用于学生会背数论公式，但容易在负数、零值和中间溢出上失败。",
                "修复后让学生为每个公式列出允许输入、特殊值、最大中间表达式和返回值含义。",
                "教师可用公式边界表区分是数学定义没想清楚，还是代码类型和语言取模行为没处理。",
                "SK_V10_NUMBER_MOD_GCD_CONTRACT",
                List.of("MP_V10_NEGATIVE_MOD_USED_AS_ARRAY_INDEX", "MP_V10_LCM_MULTIPLIES_BEFORE_DIVIDE_OVERFLOW"),
                List.of("MATH.NUMBER.MOD.负数取模修正", "MATH.NUMBER.GCD.最小公倍数"));
    }

    private static void addCountingModel(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V10_COUNTING_OBJECT_ORDER_CONTRACT",
                "能力点/兜底吸收-计数建模",
                "维护计数对象、顺序、重复和容斥边界",
                "能说明计数对象是下标、数值还是方案，顺序是否重要，重复元素如何处理，以及多个条件重叠时是否需要容斥。",
                "计数题先写清数的是什么对象，再决定排列、组合、去重还是容斥。",
                List.of("MATH.COUNT.PERM.顺序是否重要", "MATH.COUNT.PERM.重复选择", "MATH.COUNT.PERM.除重", "MATH.COUNT.INCLUSION.集合重叠"),
                List.of("CONTEST.READING.OUTPUT.输出方案数", "ALGO.ENUM.LOOP.组合枚举"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_COUNT_ORDER_IMPORTANCE_MISMODELED",
                "易错点/兜底吸收-计数建模",
                "把有顺序方案和无顺序组合混为一类",
                "题目要求统计排列、路径或操作序列，但代码按组合去重；或题目要求组合，却把不同顺序重复计入答案。",
                "没有先判断交换两个选择后是否仍算同一个方案。",
                "SK_V10_COUNTING_OBJECT_ORDER_CONTRACT",
                "MODELING",
                List.of("MATH.COUNT.PERM.顺序是否重要", "MATH.COUNT.PERM.排列", "MATH.COUNT.PERM.组合"),
                List.of("CONTEST.READING.OUTPUT.输出方案数"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_COUNT_DUPLICATE_VALUES_OVERCOUNTED",
                "易错点/兜底吸收-计数建模",
                "重复值被当成不同对象导致方案数多算",
                "输入中有相同数值或相同状态，题目按值去重或按唯一方案计数，但代码按下标枚举把等价方案重复计入。",
                "没有区分相同数值的多个位置是否应该视为不同对象。",
                "SK_V10_COUNTING_OBJECT_ORDER_CONTRACT",
                "STATE",
                List.of("MATH.COUNT.PERM.除重", "MATH.COUNT.PERM.重复选择", "ALGO.ENUM.LOOP.去重枚举"),
                List.of("ALGO.SORT.APPLICATION.去重统计"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_INCLUSION_EXCLUSION_OVERLAP_OMITTED",
                "易错点/兜底吸收-计数建模",
                "多条件计数漏减重叠部分",
                "分别统计满足 A、满足 B 的数量后直接相加，没有减去同时满足 A 和 B 的对象，导致交集被重复计数。",
                "把条件分类当成互斥，没有检查两个条件是否可能同时成立。",
                "SK_V10_COUNTING_OBJECT_ORDER_CONTRACT",
                "LOGIC",
                List.of("MATH.COUNT.INCLUSION.集合重叠", "MATH.COUNT.INCLUSION.二集合容斥", "MATH.COUNT.INCLUSION.多条件计数"),
                List.of("BASIC.BRANCH.CASE.互斥条件"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V10_COUNTING_OBJECT_CARD",
                "提升点/兜底吸收-计数建模",
                "用计数对象卡片检查排列、组合和容斥",
                "适用于学生知道要计数，但经常数错对象、顺序、重复或重叠条件。",
                "修复后让学生写出：计数对象是什么，两个方案何时相同，顺序是否重要，重复值是否合并，条件是否互斥。",
                "教师可用这张卡片帮助学生把样例中的方案数拆成可验证的数学对象。",
                "SK_V10_COUNTING_OBJECT_ORDER_CONTRACT",
                List.of("MP_V10_COUNT_ORDER_IMPORTANCE_MISMODELED", "MP_V10_INCLUSION_EXCLUSION_OVERLAP_OMITTED"),
                List.of("MATH.COUNT.PERM.顺序是否重要", "MATH.COUNT.INCLUSION.集合重叠"));
    }

    private static void addDebugTriage(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V10_DEBUG_ERROR_TRIAGE_CONTRACT",
                "能力点/兜底吸收-错误定位",
                "区分错误类型并用最小反例和状态轨迹定位",
                "能根据编译错误、运行错误、答案错误、超时和格式错误选择不同排查证据，并把失败样例缩小到能手算的最小反例。",
                "调试先定错误类型，再选证据；不要所有失败都靠重跑样例或随手改格式。",
                List.of("ENG.ERROR.WRONG_ANSWER.样例通过隐藏失败", "ENG.ERROR.RUNTIME.数组越界", "ENG.DEBUG.SAMPLE.最小反例", "ENG.DEBUG.TRACE.循环状态"),
                List.of("CONTEST.SUBMIT.REVIEW.错误类型定位", "ENG.DEBUG.SAMPLE.手算对照"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_DEBUG_WA_TREATED_AS_FORMAT_ONLY",
                "易错点/兜底吸收-错误定位",
                "把答案错误只当成输出格式问题处理",
                "隐藏数据 WA 后只改空格、换行或大小写，没有构造反例检查边界、状态转移和算法目标，真正错因被拖延。",
                "看到样例输出接近就默认逻辑正确，把所有差异都归因于格式。",
                "SK_V10_DEBUG_ERROR_TRIAGE_CONTRACT",
                "DEBUGGING",
                List.of("ENG.ERROR.WRONG_ANSWER.样例通过隐藏失败", "ENG.ERROR.FORMAT.多余空格", "CONTEST.SUBMIT.REVIEW.错误类型定位"),
                List.of("ENG.DEBUG.SAMPLE.最小反例"),
                "MEDIUM",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_DEBUG_COUNTEREXAMPLE_NOT_MINIMIZED",
                "易错点/兜底吸收-错误定位",
                "失败样例没有缩小到可手算反例",
                "代码在大输入或复杂隐藏数据上失败后，直接盯着原始数据调试，没有删减到最少元素、最小边界或最短路径来定位第一处偏差。",
                "以为数据越完整越接近真实问题，没有意识到最小反例更容易暴露错因。",
                "SK_V10_DEBUG_ERROR_TRIAGE_CONTRACT",
                "DEBUGGING",
                List.of("ENG.DEBUG.SAMPLE.最小反例", "ENG.DEBUG.SAMPLE.手算对照", "ENG.DEBUG.BOUNDARY.最小输入"),
                List.of("CONTEST.SUBMIT.REVIEW.最小反例构造"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_DEBUG_TRACE_WITHOUT_EXPECTED_VALUES",
                "易错点/兜底吸收-错误定位",
                "打印变量但没有对应手算期望值",
                "调试时输出了很多中间变量，却没有为每一步写出应当是多少，最后只能看见数字变化，无法判断哪一步开始偏离。",
                "把打印本身当成调试，没有把实际值和期望值逐步对齐。",
                "SK_V10_DEBUG_ERROR_TRIAGE_CONTRACT",
                "DEBUGGING",
                List.of("ENG.DEBUG.TRACE.循环状态", "ENG.DEBUG.TRACE.数组状态", "ENG.DEBUG.SAMPLE.手算对照"),
                List.of("ENG.STYLE.INVARIANT.循环不变量"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V10_DEBUG_TRIAGE_WORKSHEET",
                "提升点/兜底吸收-错误定位",
                "用错误类型和证据表组织调试",
                "适用于学生失败后反复改代码但缺少稳定排查路径。",
                "修复后让学生填写错误类型、最小反例、手算答案、实际输出、第一处偏差和对应知识点。",
                "教师可用这张表把调试从猜测改成证据链。",
                "SK_V10_DEBUG_ERROR_TRIAGE_CONTRACT",
                List.of("MP_V10_DEBUG_COUNTEREXAMPLE_NOT_MINIMIZED", "MP_V10_DEBUG_TRACE_WITHOUT_EXPECTED_VALUES"),
                List.of("ENG.DEBUG.SAMPLE.最小反例", "CONTEST.SUBMIT.REVIEW.错误类型定位"));
    }

    private static void addComplexitySpace(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V10_COMPLEXITY_SPACE_CONTRACT",
                "能力点/兜底吸收-复杂度空间",
                "维护时间复杂度、空间规模和预处理收益边界",
                "能把最大数据范围转成操作次数、数组元素数、哈希键数量和递归栈深度，再判断预处理或缓存是否真的可行。",
                "复杂度检查要同时算时间和空间；能省时间的表，也可能先把内存打爆。",
                List.of("ENG.COMPLEXITY.TIME.数据范围反推", "ENG.COMPLEXITY.SPACE.数组规模", "ENG.COMPLEXITY.SPACE.二维空间", "ENG.COMPLEXITY.TRADEOFF.空间换时间边界"),
                List.of("CONTEST.READING.CONSTRAINT.内存限制", "CONTEST.READING.CONSTRAINT.时间限制"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_SPACE_TABLE_SIZE_NOT_ESTIMATED",
                "易错点/兜底吸收-复杂度空间",
                "没有估算数组或表的总元素数",
                "代码开了二维、高维 DP、预处理表或邻接矩阵，但没有用最大 n、m、状态数和单元素字节估算内存，导致内存超限。",
                "只看到数组维度能表达状态，没有把维度相乘后的规模和内存限制对应起来。",
                "SK_V10_COMPLEXITY_SPACE_CONTRACT",
                "COMPLEXITY",
                List.of("ENG.COMPLEXITY.SPACE.数组规模", "ENG.COMPLEXITY.SPACE.二维空间", "CONTEST.READING.CONSTRAINT.内存限制"),
                List.of("ALGO.DP.STATE.维度选择"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_CACHE_KEY_EXPLODES_STATE_SPACE",
                "易错点/兜底吸收-复杂度空间",
                "缓存 key 维度过多导致状态空间爆炸",
                "为了避免重复计算加入记忆化或哈希缓存，但 key 包含路径、完整集合或无关变量，状态数接近指数级，仍然超时或超内存。",
                "以为加缓存就一定优化，没有估算不同 key 的最大数量。",
                "SK_V10_COMPLEXITY_SPACE_CONTRACT",
                "COMPLEXITY",
                List.of("ENG.COMPLEXITY.TRADEOFF.缓存", "ENG.COMPLEXITY.SPACE.哈希空间", "ALGO.SEARCH.STATE.状态编码"),
                List.of("ALGO.ENUM.COMPLEXITY.指数枚举"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V10_ROLLING_ARRAY_OVERWRITES_REQUIRED_LAYER",
                "易错点/兜底吸收-复杂度空间",
                "滚动优化覆盖了后续仍需使用的上一层状态",
                "为了省空间把多层 DP 压成一维或两行，但遍历顺序错误，使当前层新值覆盖了后续转移还要读取的旧层状态。",
                "只知道滚动数组能省内存，没有重新检查读旧写新关系和遍历方向。",
                "SK_V10_COMPLEXITY_SPACE_CONTRACT",
                "STATE",
                List.of("ENG.COMPLEXITY.SPACE.滚动优化", "ALGO.DP.STATE.状态压缩直觉", "BASIC.ARRAY.UPDATE.读旧写新分离"),
                List.of("BASIC.ARRAY.TRAVERSE.逆序遍历"),
                "HIGH",
                LANGUAGES);
        improvement(seeds,
                "IP_V10_COMPLEXITY_BUDGET_SHEET",
                "提升点/兜底吸收-复杂度空间",
                "用复杂度预算表检查时间、空间和缓存收益",
                "适用于学生能想到预处理、缓存或滚动优化，但缺少实际规模估算。",
                "修复后让学生填写最大数据、操作次数、状态数、单元素字节、总内存和是否需要滚动优化。",
                "教师可用预算表判断学生是在优化瓶颈，还是只把复杂度问题从时间转移到了空间。",
                "SK_V10_COMPLEXITY_SPACE_CONTRACT",
                List.of("MP_V10_SPACE_TABLE_SIZE_NOT_ESTIMATED", "MP_V10_ROLLING_ARRAY_OVERWRITES_REQUIRED_LAYER"),
                List.of("ENG.COMPLEXITY.SPACE.数组规模", "ENG.COMPLEXITY.TRADEOFF.空间换时间边界"));
    }

    private static void improvement(List<AiStandardLibrarySeed> seeds,
                                    String code,
                                    String category,
                                    String name,
                                    String description,
                                    String studentBenefit,
                                    String teacherExplanation,
                                    String skillUnitCode,
                                    List<String> relatedMistakeCodes,
                                    List<String> knowledgeNodeCodes) {
        seeds.add(new AiStandardLibrarySeed(
                AiStandardLibraryLayer.IMPROVEMENT_POINT,
                code,
                category,
                name,
                description,
                "",
                teacherExplanation,
                skillUnitCode,
                "",
                "",
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                description,
                studentBenefit,
                "",
                "",
                "",
                skillUnitCode,
                "MEDIUM",
                LANGUAGES,
                relatedMistakeCodes,
                knowledgeNodeCodes,
                List.of(),
                "把兜底标签升级为可复用诊断后，用结构化复盘巩固迁移能力。",
                AiStandardLibrarySeedCatalog.VERSION
        ));
    }
}
