package com.onlinejudge.learning.standardlibrary.application;

import com.onlinejudge.learning.standardlibrary.domain.AiStandardLibraryLayer;

import java.util.List;

final class AiStandardLibraryV8ExpansionSeeds {

    private static final List<String> LANGUAGES = List.of("PYTHON", "CPP17");

    private AiStandardLibraryV8ExpansionSeeds() {
    }

    static void addTo(List<AiStandardLibrarySeed> seeds) {
        addArrayUpdate(seeds);
        addStringMatching(seeds);
        addSimulationConflict(seeds);
        addGraphStorage(seeds);
        addOppositePointers(seeds);
        addSubmissionGuard(seeds);
    }

    private static void addArrayUpdate(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V8_ARRAY_UPDATE_OLD_NEW_CONTRACT",
                "能力点/数组更新细节",
                "区分数组更新中的旧值来源和新值目标",
                "能判断当前更新是否必须先读旧数组、写入临时数组，再统一替换，避免原地覆盖破坏后续计算。",
                "数组更新前先问：这一轮每个位置依赖的是更新前的值，还是可以立即使用更新后的值。",
                List.of("BASIC.ARRAY.UPDATE.读旧写新分离", "BASIC.ARRAY.UPDATE.临时数组", "BASIC.ARRAY.UPDATE.批量更新后还原顺序"),
                List.of("BASIC.ARRAY.UPDATE.原地修改", "BASIC.LOOP.NESTED.重复初始化位置"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_ARRAY_UPDATE_OVERWRITES_SOURCE_BEFORE_READ",
                "易错点/数组更新细节",
                "原地更新提前覆盖后续位置需要的旧值",
                "同一轮更新中，后续位置仍需要读取上一轮数组值，但代码先把前面位置覆盖，导致之后读到的是新值而不是旧值。",
                "把逐个位置修改当成彼此独立，没有意识到这一轮所有转移都应来自同一份旧状态。",
                "SK_V8_ARRAY_UPDATE_OLD_NEW_CONTRACT",
                "STATE",
                List.of("BASIC.ARRAY.UPDATE.读旧写新分离", "BASIC.ARRAY.UPDATE.覆盖风险", "BASIC.ARRAY.UPDATE.临时数组"),
                List.of("BASIC.ARRAY.TRAVERSE.同步遍历"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_ARRAY_BATCH_RESTORE_ORDER_WRONG",
                "易错点/数组更新细节",
                "批量更新后还原顺序和题意顺序不一致",
                "先缓存变化再统一还原时，代码按错误顺序应用修改，使交换、移动或批量赋值结果与题意规定的同时更新不一致。",
                "只记录了要改哪些位置，没有区分收集变更、应用变更和恢复临时状态的先后。",
                "SK_V8_ARRAY_UPDATE_OLD_NEW_CONTRACT",
                "LOGIC",
                List.of("BASIC.ARRAY.UPDATE.批量更新后还原顺序", "BASIC.ARRAY.UPDATE.交换元素", "ALGO.SIM.PROCESS.状态更新先后"),
                List.of("ALGO.SIM.CORNER.同一时刻冲突"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_ARRAY_ACCUMULATOR_NOT_SYNCED_WITH_UPDATE",
                "易错点/数组更新细节",
                "数组值更新后累计量没有同步维护",
                "数组元素发生增减后，维护的总和、最大值、频次数或有效数量没有同步更新，导致后续判断仍使用旧统计。",
                "只改了数组本身，没有把依赖该数组的派生状态一起视为同一份状态。",
                "SK_V8_ARRAY_UPDATE_OLD_NEW_CONTRACT",
                "STATE",
                List.of("BASIC.ARRAY.UPDATE.累计量同步更新", "BASIC.ARRAY.PREFIX.频次统计", "ENG.STYLE.INVARIANT.循环不变量"),
                List.of("DS.SET_MAP.MAP.频次统计"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V8_ARRAY_UPDATE_INVARIANT_TESTING",
                "提升点/数组更新细节",
                "用旧值来源和派生状态不变量检查数组更新",
                "适用于已经能修复数组更新错误，但还容易在模拟、DP 滚动或批量修改中再次覆盖旧状态的学生。",
                "修复后让学生写出两个检查：本轮读取的是旧值还是新值，数组外的累计量是否和数组保持一致。",
                "教师可引导学生画出 old/new 两列，并要求每条赋值语句标明读旧还是写新。",
                "SK_V8_ARRAY_UPDATE_OLD_NEW_CONTRACT",
                List.of("MP_V8_ARRAY_UPDATE_OVERWRITES_SOURCE_BEFORE_READ", "MP_V8_ARRAY_ACCUMULATOR_NOT_SYNCED_WITH_UPDATE"),
                List.of("BASIC.ARRAY.UPDATE.读旧写新分离", "ENG.STYLE.INVARIANT.循环不变量"));
    }

    private static void addStringMatching(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V8_STRING_MATCH_SENTINEL_OVERLAP",
                "能力点/字符串匹配细节",
                "处理字符串查找失败、重叠匹配和边界哨兵",
                "能区分未找到的返回值、重叠出现次数、前后缀边界和切片终点，避免把字符串函数结果直接当合法下标。",
                "字符串查找前先约定：找不到是什么，找到后是否允许重叠，起止位置是否包含。",
                List.of("BASIC.STRING.MATCH.未找到结果哨兵", "BASIC.STRING.MATCH.重叠匹配计数", "BASIC.STRING.MATCH.前后缀边界"),
                List.of("BASIC.STRING.SUBSTRING.起止位置", "BASIC.ARRAY.INDEX.越界访问"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_STRING_FIND_SENTINEL_USED_AS_INDEX",
                "易错点/字符串匹配细节",
                "字符串未找到哨兵值被当作合法下标",
                "查找结果为 -1、npos 或空结果时，代码继续用它访问字符串或切片，导致越界、错误匹配或运行错误。",
                "只记得 find 会返回位置，没有为找不到的分支单独处理。",
                "SK_V8_STRING_MATCH_SENTINEL_OVERLAP",
                "RUNTIME",
                List.of("BASIC.STRING.MATCH.未找到结果哨兵", "ENG.ERROR.RUNTIME.数组越界", "BASIC.ARRAY.INDEX.越界访问"),
                List.of("BASIC.BRANCH.GUARD.非法输入保护"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_STRING_OVERLAP_MATCH_SKIPPED",
                "易错点/字符串匹配细节",
                "统计子串出现次数时跳过重叠匹配",
                "题目允许重叠出现，但代码每次匹配后直接跳过整个模式串长度，漏掉相邻重叠的出现位置。",
                "把不重叠替换或分段处理的经验套到计数题，没有读清是否允许重叠。",
                "SK_V8_STRING_MATCH_SENTINEL_OVERLAP",
                "BOUNDARY",
                List.of("BASIC.STRING.MATCH.重叠匹配计数", "BASIC.STRING.MATCH.统计出现次数", "CONTEST.READING.CONSTRAINT.隐藏特殊条件"),
                List.of("BASIC.LOOP.FOR.步长变化"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_STRING_PREFIX_SUFFIX_EMPTY_CASE_IGNORED",
                "易错点/字符串匹配细节",
                "前后缀判断漏掉空串或整串边界",
                "判断前缀、后缀或回文边界时，没有处理长度为 0、长度为 1 或整串本身，导致边界样例错误。",
                "只按普通长度手推，没有把空串、单字符和整串作为特殊但合法的边界。",
                "SK_V8_STRING_MATCH_SENTINEL_OVERLAP",
                "BOUNDARY",
                List.of("BASIC.STRING.MATCH.前后缀边界", "BASIC.STRING.SUBSTRING.空串处理", "BASIC.STRING.MATCH.回文判断"),
                List.of("ENG.DEBUG.BOUNDARY.最小输入"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V8_STRING_MATCH_BOUNDARY_TABLE",
                "提升点/字符串匹配细节",
                "为字符串查找写一张失败、边界和重叠样例表",
                "适用于学生已能写基本字符串处理，但经常在找不到、重叠、空串和前后缀边界上漏样例。",
                "修复后补四类自测：找不到、刚好在开头、刚好在结尾、允许重叠。",
                "教师可要求学生把库函数返回值翻译成分支表，再决定是否访问下标。",
                "SK_V8_STRING_MATCH_SENTINEL_OVERLAP",
                List.of("MP_V8_STRING_FIND_SENTINEL_USED_AS_INDEX", "MP_V8_STRING_OVERLAP_MATCH_SKIPPED"),
                List.of("BASIC.STRING.MATCH.未找到结果哨兵", "BASIC.STRING.MATCH.重叠匹配计数"));
    }

    private static void addSimulationConflict(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V8_SIM_EVENT_CONFLICT_ORDER",
                "能力点/模拟边界细节",
                "处理模拟中的同一时刻事件、空状态和并列规则",
                "能把模拟过程拆成事件收集、冲突判定、状态更新和终止检查，避免按代码书写顺序替代题意顺序。",
                "模拟题先排规则优先级，再写循环；同一时刻发生的事不能靠碰巧的 if 顺序决定。",
                List.of("ALGO.SIM.PROCESS.状态更新先后", "ALGO.SIM.CORNER.并列规则冲突", "ALGO.SIM.CORNER.空队列空集合状态"),
                List.of("BASIC.BRANCH.CASE.互斥条件", "BASIC.LOOP.WHILE.循环条件"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_SIM_SIMULTANEOUS_EVENT_APPLIED_SEQUENTIALLY",
                "易错点/模拟边界细节",
                "同一时刻事件被顺序执行成先后发生",
                "题目要求同一时刻的变化同时生效，但代码边遍历边修改状态，让后处理的对象看到了前面对象的新状态。",
                "把循环顺序当成事件发生顺序，没有先收集所有本轮变化。",
                "SK_V8_SIM_EVENT_CONFLICT_ORDER",
                "STATE",
                List.of("ALGO.SIM.CORNER.同一时刻冲突", "ALGO.SIM.PROCESS.状态更新先后", "BASIC.ARRAY.UPDATE.读旧写新分离"),
                List.of("BASIC.ARRAY.UPDATE.临时数组"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_SIM_EMPTY_STATE_NOT_CHECKED_BEFORE_PEEK",
                "易错点/模拟边界细节",
                "空队列或空集合状态下仍读取首元素",
                "模拟过程中队列、集合或候选列表可能为空，但代码仍访问队首、最小值或第一个元素，导致运行错误或错误终止。",
                "只按样例中有数据的状态推演，没有把过程中的空状态当作合法中间态。",
                "SK_V8_SIM_EVENT_CONFLICT_ORDER",
                "RUNTIME",
                List.of("ALGO.SIM.CORNER.空队列空集合状态", "ENG.ERROR.RUNTIME.空容器访问保护", "BASIC.BRANCH.GUARD.空结果处理"),
                List.of("DS.LINEAR.QUEUE.队空判断"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_SIM_TIE_RULE_FALLS_THROUGH_TO_DEFAULT",
                "易错点/模拟边界细节",
                "并列规则没有覆盖而落入默认分支",
                "两个事件、对象或候选值并列时题目有明确规则，但代码没有单独处理，最后被默认分支或输入顺序决定。",
                "只处理大于小于，没有认真读等于、同分、同时发生时的规则。",
                "SK_V8_SIM_EVENT_CONFLICT_ORDER",
                "MODELING",
                List.of("ALGO.SIM.CORNER.并列规则冲突", "BASIC.BRANCH.CASE.覆盖所有情况", "CONTEST.READING.CONSTRAINT.隐藏特殊条件"),
                List.of("BASIC.EXPR.COMPARE.边界比较"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V8_SIM_PHASE_TABLE",
                "提升点/模拟边界细节",
                "把模拟过程整理成阶段表和冲突表",
                "适用于学生能写出大致模拟流程，但经常被同一时刻、空状态和并列规则打乱。",
                "修复后让学生列出每一轮的四列：本轮输入状态、要发生的事件、冲突处理、写回后的状态。",
                "教师可用阶段表检查学生是否把题意顺序、代码顺序和状态写回顺序混在一起。",
                "SK_V8_SIM_EVENT_CONFLICT_ORDER",
                List.of("MP_V8_SIM_SIMULTANEOUS_EVENT_APPLIED_SEQUENTIALLY", "MP_V8_SIM_TIE_RULE_FALLS_THROUGH_TO_DEFAULT"),
                List.of("ALGO.SIM.PROCESS.状态更新先后", "ALGO.SIM.CORNER.并列规则冲突"));
    }

    private static void addGraphStorage(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V8_GRAPH_STORAGE_RESET_WEIGHT_CONTRACT",
                "能力点/图存储细节",
                "维护图存储中的方向、权值和多组清空契约",
                "能根据题意判断边是否双向、权值字段绑定到哪条边，以及多组数据时邻接表、距离和访问状态是否全部清空。",
                "图存储不是把边塞进去就结束，方向、权值和生命周期都要写成契约。",
                List.of("DS.GRAPH.STORE.无向边双向建边", "DS.GRAPH.STORE.权值字段绑定", "DS.GRAPH.STORE.多组图清空"),
                List.of("DS.GRAPH.MODEL.有向无向", "BASIC.IO.MULTI_CASE.每组状态重置"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_GRAPH_UNDIRECTED_EDGE_STORED_ONE_WAY",
                "易错点/图存储细节",
                "无向边只加入了一个方向",
                "题目给的是无向关系，但邻接表只添加 u 到 v，没有添加 v 到 u，导致从另一端出发时边不存在。",
                "读入边时只照输入顺序建边，没有把无向关系翻译成两个方向的邻接记录。",
                "SK_V8_GRAPH_STORAGE_RESET_WEIGHT_CONTRACT",
                "MODELING",
                List.of("DS.GRAPH.STORE.无向边双向建边", "DS.GRAPH.MODEL.有向无向", "ALGO.GRAPH.CONNECT.连通块"),
                List.of("CONTEST.READING.INPUT.图结构"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_GRAPH_WEIGHT_BOUND_TO_WRONG_EDGE_FIELD",
                "易错点/图存储细节",
                "边权字段绑定到错误的邻接记录",
                "读入 u、v、w 后，代码把权值存到错误字段、错误方向或覆盖成节点编号，导致最短路和排序按错误权值运行。",
                "把邻接表元素当成普通 pair/tuple，没有固定每一列的含义。",
                "SK_V8_GRAPH_STORAGE_RESET_WEIGHT_CONTRACT",
                "STATE",
                List.of("DS.GRAPH.STORE.权值字段绑定", "DS.GRAPH.MODEL.权值含义", "ALGO.GRAPH.SHORTEST.松弛操作"),
                List.of("BASIC.TYPE.VARIABLE.变量命名"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_GRAPH_MULTICASE_ADJACENCY_NOT_CLEARED",
                "易错点/图存储细节",
                "多组图数据没有清空上一组邻接表",
                "下一组测试开始时，邻接表、距离数组或访问标记仍保留上一组边和状态，导致隐藏数据串组。",
                "只重置了答案变量，没有把图结构本身视为每组独立数据。",
                "SK_V8_GRAPH_STORAGE_RESET_WEIGHT_CONTRACT",
                "INITIALIZATION",
                List.of("DS.GRAPH.STORE.多组图清空", "BASIC.IO.MULTI_CASE.每组状态重置", "CONTEST.SUBMIT.CHECKLIST.多组状态复查"),
                List.of("BASIC.ARRAY.UPDATE.批量更新后还原顺序"),
                "HIGH",
                LANGUAGES);
        improvement(seeds,
                "IP_V8_GRAPH_STORAGE_LIFECYCLE_CHECKLIST",
                "提升点/图存储细节",
                "用图生命周期清单检查建图、用图和清图",
                "适用于图算法已经能写出主体逻辑，但经常在方向、权值或多组数据状态上出错的学生。",
                "修复后让学生按建图前、建图中、跑算法前、下一组开始前四个时刻检查图状态。",
                "教师可要求学生为邻接表元素写出字段说明，例如 to、weight、nextState。",
                "SK_V8_GRAPH_STORAGE_RESET_WEIGHT_CONTRACT",
                List.of("MP_V8_GRAPH_UNDIRECTED_EDGE_STORED_ONE_WAY", "MP_V8_GRAPH_MULTICASE_ADJACENCY_NOT_CLEARED"),
                List.of("DS.GRAPH.STORE.无向边双向建边", "DS.GRAPH.STORE.多组图清空"));
    }

    private static void addOppositePointers(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V8_TWO_POINTERS_OPPOSITE_INVARIANT",
                "能力点/对向双指针细节",
                "维护对向双指针的移动依据、去重和终止不变量",
                "能说明左指针和右指针分别代表什么，什么时候移动哪一侧，重复值应该在计数前还是计数后跳过。",
                "双指针不是两个循环变量，而是一段仍可能包含答案的候选区间。",
                List.of("ALGO.TWO_POINTERS.OPPOSITE.左右指针移动依据", "ALGO.TWO_POINTERS.OPPOSITE.相等元素去重策略", "ALGO.TWO_POINTERS.OPPOSITE.终止条件"),
                List.of("ALGO.SORT.BASIC.升序降序", "BASIC.EXPR.COMPARE.边界比较"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_TWO_POINTERS_MOVES_SIDE_WITHOUT_INVARIANT",
                "易错点/对向双指针细节",
                "没有依据当前和目标关系移动正确指针",
                "有序数组中当前和偏小应移动左指针、偏大应移动右指针，但代码移动了相反一侧，候选区间被错误丢弃。",
                "只记得一左一右往中间走，没有把移动动作和单调性关系绑定。",
                "SK_V8_TWO_POINTERS_OPPOSITE_INVARIANT",
                "MODELING",
                List.of("ALGO.TWO_POINTERS.OPPOSITE.左右指针移动依据", "ALGO.TWO_POINTERS.OPPOSITE.有序数组配对", "ALGO.SORT.BASIC.升序降序"),
                List.of("ALGO.TWO_POINTERS.OPPOSITE.最优性判断"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_TWO_POINTERS_DUPLICATE_SKIPPED_BEFORE_COUNT",
                "易错点/对向双指针细节",
                "重复值在计数前被跳过导致方案数漏算",
                "需要统计所有配对或组合数时，代码先去重移动指针，再计算重复值数量，导致多个相同元素贡献被漏掉。",
                "把去重输出答案和统计所有方案混为一类，没有先判断题目要唯一值还是所有下标组合。",
                "SK_V8_TWO_POINTERS_OPPOSITE_INVARIANT",
                "STATE",
                List.of("ALGO.TWO_POINTERS.OPPOSITE.相等元素去重策略", "MATH.COUNT.PERM.重复选择", "CONTEST.READING.OUTPUT.输出方案数"),
                List.of("ALGO.SORT.APPLICATION.去重统计"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_TWO_POINTERS_TERMINATION_ALLOWS_SAME_INDEX",
                "易错点/对向双指针细节",
                "双指针终止条件允许同一元素被使用两次",
                "需要两个不同位置时，循环条件使用 left <= right 或更新后未检查交叉，导致同一下标被配对两次。",
                "只关注数值是否满足，没有把两个指针必须代表不同元素作为不变量。",
                "SK_V8_TWO_POINTERS_OPPOSITE_INVARIANT",
                "BOUNDARY",
                List.of("ALGO.TWO_POINTERS.OPPOSITE.终止条件", "BASIC.ARRAY.INDEX.下标映射", "CONTEST.READING.CONSTRAINT.隐藏特殊条件"),
                List.of("BASIC.EXPR.COMPARE.边界比较"),
                "HIGH",
                LANGUAGES);
        improvement(seeds,
                "IP_V8_TWO_POINTERS_INVARIANT_TRACE",
                "提升点/对向双指针细节",
                "用候选区间不变量复盘每次指针移动",
                "适用于学生能写出双指针框架，但经常在移动方向、重复值或终止条件上摇摆。",
                "修复后让学生在表格里记录 left、right、当前和、移动原因和被排除的候选范围。",
                "教师可用这张表检查学生是否真的理解指针移动的单调依据。",
                "SK_V8_TWO_POINTERS_OPPOSITE_INVARIANT",
                List.of("MP_V8_TWO_POINTERS_MOVES_SIDE_WITHOUT_INVARIANT", "MP_V8_TWO_POINTERS_TERMINATION_ALLOWS_SAME_INDEX"),
                List.of("ALGO.TWO_POINTERS.OPPOSITE.左右指针移动依据", "ALGO.TWO_POINTERS.OPPOSITE.终止条件"));
    }

    private static void addSubmissionGuard(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V8_SUBMISSION_RUNTIME_COMPLEXITY_GUARD",
                "能力点/提交检查细节",
                "提交前检查运行错误、溢出和复杂度边界",
                "能在提交前主动检查空容器访问、递归深度、整数溢出、多组状态和时空复杂度，而不是只复测样例。",
                "提交前最后一遍不是只观察答案形态，而是按风险清单主动检查最可能触发失败的边界。",
                List.of("CONTEST.SUBMIT.CHECKLIST.多组状态复查", "CONTEST.SUBMIT.CHECKLIST.溢出风险复查", "ENG.ERROR.RUNTIME.空容器访问保护", "ENG.COMPLEXITY.TRADEOFF.预处理收益判断"),
                List.of("ENG.DEBUG.BOUNDARY.最大输入", "BASIC.TYPE.INTEGER.long_long_范围"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_SUBMIT_EMPTY_CONTAINER_GUARD_MISSING",
                "易错点/提交检查细节",
                "提交前没有检查空容器访问路径",
                "队列、栈、集合或候选数组可能为空，但代码在某些分支中仍访问首尾元素，样例未覆盖时提交后运行错误。",
                "只按正常流程验证，没有沿着删除完、过滤完或没有候选的路径走一遍。",
                "SK_V8_SUBMISSION_RUNTIME_COMPLEXITY_GUARD",
                "RUNTIME",
                List.of("ENG.ERROR.RUNTIME.空容器访问保护", "BASIC.BRANCH.GUARD.空结果处理", "CONTEST.SUBMIT.CHECKLIST.边界复测"),
                List.of("DS.LINEAR.STACK.空栈检查"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_SUBMIT_OVERFLOW_CHECK_ONLY_ON_FINAL_ANSWER",
                "易错点/提交检查细节",
                "只检查最终答案类型而忽略中间表达式溢出",
                "最终变量使用 long long 或 Python 大整数思路正确，但 C++ 中乘法、平方或前缀累计等中间表达式先在 int 中溢出再赋值。",
                "把类型检查停在答案变量，没有检查每个可能超过范围的中间表达式。",
                "SK_V8_SUBMISSION_RUNTIME_COMPLEXITY_GUARD",
                "VALUE_RANGE",
                List.of("CONTEST.SUBMIT.CHECKLIST.溢出风险复查", "BASIC.TYPE.INTEGER.整型溢出", "BASIC.TYPE.INTEGER.long_long_范围"),
                List.of("CONTEST.READING.CONSTRAINT.值域范围"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V8_SUBMIT_PRECOMPUTE_EXCEEDS_MEMORY_LIMIT",
                "易错点/提交检查细节",
                "预处理数组规模超过内存限制",
                "为了降低查询时间预处理了二维或高维表，但没有估算总元素数和单元素字节，导致内存超限。",
                "只看到预处理能省时间，没有把空间成本和内存限制一起算。",
                "SK_V8_SUBMISSION_RUNTIME_COMPLEXITY_GUARD",
                "COMPLEXITY",
                List.of("ENG.COMPLEXITY.TRADEOFF.预处理收益判断", "ENG.COMPLEXITY.TRADEOFF.空间换时间边界", "CONTEST.READING.CONSTRAINT.内存限制"),
                List.of("ENG.COMPLEXITY.SPACE.数组规模"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V8_SUBMISSION_RISK_CHECKLIST",
                "提升点/提交检查细节",
                "建立提交前风险清单而不是只复测样例",
                "适用于学生代码主体已经接近正确，但经常在隐藏数据上因运行错误、溢出、多组状态或复杂度失败。",
                "修复后让学生按四类风险复查：空状态、最大值、中间表达式、多组状态和内存规模。",
                "教师可要求学生每次提交前写出一个最大数据估算和一个最容易触发失败的边界样例。",
                "SK_V8_SUBMISSION_RUNTIME_COMPLEXITY_GUARD",
                List.of("MP_V8_SUBMIT_EMPTY_CONTAINER_GUARD_MISSING", "MP_V8_SUBMIT_OVERFLOW_CHECK_ONLY_ON_FINAL_ANSWER", "MP_V8_SUBMIT_PRECOMPUTE_EXCEEDS_MEMORY_LIMIT"),
                List.of("CONTEST.SUBMIT.CHECKLIST.溢出风险复查", "ENG.COMPLEXITY.TRADEOFF.空间换时间边界"));
    }

    private static void improvement(List<AiStandardLibrarySeed> seeds,
                                    String code,
                                    String category,
                                    String name,
                                    String description,
                                    String studentBenefit,
                                    String teacherExplanation,
                                    String skillUnitCode,
                                    List<String> relatedMistakeCodes,
                                    List<String> knowledgeNodeCodes) {
        seeds.add(new AiStandardLibrarySeed(
                AiStandardLibraryLayer.IMPROVEMENT_POINT,
                code,
                category,
                name,
                description,
                "",
                teacherExplanation,
                skillUnitCode,
                "",
                "",
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                description,
                studentBenefit,
                "",
                "",
                "",
                skillUnitCode,
                "MEDIUM",
                LANGUAGES,
                relatedMistakeCodes,
                knowledgeNodeCodes,
                List.of(),
                "修复基础错误后，用结构化自测和复盘提升迁移能力。",
                AiStandardLibrarySeedCatalog.VERSION
        ));
    }
}
