package com.onlinejudge.learning.standardlibrary.application;

import java.util.List;

final class AiStandardLibraryV6ExpansionSeeds {

    private static final List<String> LANGUAGES = List.of("PYTHON", "CPP17");

    private AiStandardLibraryV6ExpansionSeeds() {
    }

    static void addTo(List<AiStandardLibrarySeed> seeds) {
        addDynamicProgramming(seeds);
        addBinarySearch(seeds);
        addPrefixAndDifference(seeds);
        addGreedyAndEnumeration(seeds);
        addGraphAlgorithms(seeds);
        addDataStructures(seeds);
        addMathCountingAndNumberTheory(seeds);
        addRecursionAndSearch(seeds);
        addSortingAndIntervals(seeds);
        addDebuggingAndSubmissionReview(seeds);
        addGridAndCoordinateModeling(seeds);
        addInputOutputMultiCase(seeds);
        addFunctionContractAndSideEffects(seeds);
    }

    private static void addDynamicProgramming(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_DP_CLASSIC_TRANSITION_ORDER",
                "能力点/DP经典模型",
                "区分经典 DP 的状态、转移和遍历顺序",
                "能根据 01 背包、完全背包、计数 DP、区间 DP 等模型，判断状态含义、初值、转移来源和遍历方向。",
                "DP 不是先套数组，而是先判断当前模型需要旧层、本层、区间长度还是方案计数。",
                List.of("ALGO.DP.CLASSIC.背包_DP", "ALGO.DP.CLASSIC.线性_DP", "ALGO.DP.CLASSIC.区间_DP_入门", "ALGO.DP.TRANSITION.从前往后", "ALGO.DP.TRANSITION.从后往前"),
                List.of("ALGO.DP.STATE.状态含义", "ALGO.DP.INIT.初始值"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_DP_01_KNAPSACK_FORWARD_REUSES_ITEM",
                "易错点/DP经典模型",
                "01 背包正序遍历导致物品被重复选",
                "01 背包压成一维后容量正序遍历，使当前物品刚更新的状态又被本轮继续使用，等价于同一物品选了多次。",
                "只记得一维数组省空间，没有判断转移必须来自上一轮物品。",
                "SK_V6_DP_CLASSIC_TRANSITION_ORDER",
                "TRANSITION",
                List.of("ALGO.DP.CLASSIC.背包_DP", "ALGO.DP.TRANSITION.从后往前", "ALGO.DP.STATE.状态压缩直觉"),
                List.of("BASIC.LOOP.FOR.步长变化"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_DP_COMPLETE_KNAPSACK_REVERSE_BLOCKS_REUSE",
                "易错点/DP经典模型",
                "完全背包逆序遍历导致无法重复选",
                "完全背包需要允许同一物品在本轮被多次使用，但容量逆序遍历阻断了本轮状态继续转移。",
                "把 01 背包和完全背包的遍历方向混用，没有回到物品是否可重复的题意。",
                "SK_V6_DP_CLASSIC_TRANSITION_ORDER",
                "TRANSITION",
                List.of("ALGO.DP.CLASSIC.背包_DP", "ALGO.DP.TRANSITION.从前往后", "ALGO.DP.STATE.状态压缩直觉"),
                List.of("CONTEST.READING.CONSTRAINT.隐藏特殊条件"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_DP_INTERVAL_LENGTH_ORDER_WRONG",
                "易错点/DP经典模型",
                "区间 DP 没有按区间长度递增计算",
                "较大区间的转移依赖更短子区间，但代码枚举顺序让子区间尚未计算就被使用。",
                "只枚举了左右端点，没有先确定依赖关系要求先算短区间。",
                "SK_V6_DP_CLASSIC_TRANSITION_ORDER",
                "TRANSITION",
                List.of("ALGO.DP.CLASSIC.区间_DP_入门", "ALGO.DP.TRANSITION.枚举决策", "ALGO.DP.TRANSITION.转移边界"),
                List.of("BASIC.LOOP.NESTED.内外层变量区分"),
                "HIGH",
                LANGUAGES);
    }

    private static void addBinarySearch(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_BINARY_BOUND_RETURN_CONTRACT",
                "能力点/二分",
                "定义二分边界、循环不变量和返回含义",
                "能说明左右边界是否闭合、循环结束时 left/right 分别代表什么，以及 check 为真时应该移动哪一侧。",
                "二分模板的核心不是背代码，而是保持答案始终在你定义的不变量里。",
                List.of("ALGO.BINARY.INDEX.闭区间模板", "ALGO.BINARY.INDEX.半开区间模板", "ALGO.BINARY.INDEX.lower_bound", "ALGO.BINARY.INDEX.upper_bound", "ALGO.BINARY.INDEX.边界返回", "ALGO.BINARY.ANSWER.check_函数"),
                List.of("BASIC.EXPR.COMPARE.边界比较"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_BINARY_LOWER_UPPER_BOUND_MIXED",
                "易错点/二分",
                "lower_bound 和 upper_bound 返回含义混用",
                "题目需要第一个大于等于或第一个大于的位置，但代码使用了相反边界，导致重复值附近答案偏移。",
                "只看到要二分位置，没有明确等于目标值时应该归到左侧还是右侧。",
                "SK_V6_BINARY_BOUND_RETURN_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.BINARY.INDEX.lower_bound", "ALGO.BINARY.INDEX.upper_bound", "BASIC.EXPR.COMPARE.边界比较"),
                List.of("ALGO.SORT.APPLICATION.去重统计"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_BINARY_CHECK_DIRECTION_REVERSED",
                "易错点/二分",
                "check 为真时边界移动方向反了",
                "答案二分中 check(mid) 已经满足可行性，但代码扩大了错误边界或缩小了错误边界，最终错过最优答案。",
                "没有先判断自己是在找最小可行值还是最大可行值。",
                "SK_V6_BINARY_BOUND_RETURN_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.BINARY.ANSWER.check_函数", "ALGO.BINARY.ANSWER.最大最小答案", "ALGO.BINARY.ANSWER.左右边界"),
                List.of("ALGO.BINARY.ANSWER.单调性证明"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_BINARY_LOOP_STALLS_ON_MID",
                "易错点/二分",
                "二分边界更新不推进导致死循环",
                "mid 等于某个边界时，代码又把该边界赋回 mid，循环区间没有缩小，导致死循环或超时。",
                "没有检查每次循环后候选区间是否严格变小。",
                "SK_V6_BINARY_BOUND_RETURN_CONTRACT",
                "RUNTIME",
                List.of("ALGO.BINARY.INDEX.闭区间模板", "ALGO.BINARY.ANSWER.左右边界", "BASIC.LOOP.WHILE.死循环识别"),
                List.of("BASIC.EXPR.ARITH.整数除法"),
                "HIGH",
                LANGUAGES);
    }

    private static void addPrefixAndDifference(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_PREFIX_DIFF_BOUNDARY_FORMULA",
                "能力点/前缀差分",
                "定义前缀、差分和二维容斥的边界公式",
                "能写清前缀数组含义、差分端点加减、二维前缀补零和容斥符号，避免只凭记忆套公式。",
                "区间公式先画出端点，再决定要减掉谁、补回谁。",
                List.of("ALGO.PREFIX.DIFF.区间加", "ALGO.PREFIX.DIFF.边界加减", "ALGO.PREFIX.DIFF.差分还原", "ALGO.PREFIX.MATRIX.容斥公式", "ALGO.PREFIX.MATRIX.边界补零"),
                List.of("ALGO.PREFIX.SUM.前缀定义", "BASIC.ARRAY.INDEX.下标映射"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_DIFF_RIGHT_PLUS_ONE_MISSING",
                "易错点/前缀差分",
                "差分区间右端后一位漏减",
                "对 [l, r] 做区间加时只在 l 加值，没有在 r+1 减值，导致影响范围延续到后续所有位置。",
                "只记住差分要在起点加，没有把区间结束位置也作为事件处理。",
                "SK_V6_PREFIX_DIFF_BOUNDARY_FORMULA",
                "BOUNDARY",
                List.of("ALGO.PREFIX.DIFF.区间加", "ALGO.PREFIX.DIFF.边界加减", "BASIC.ARRAY.INDEX.长度与最后下标"),
                List.of("BASIC.LOOP.BOUNDARY.最后一次迭代"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_DIFF_RESTORE_START_INDEX_WRONG",
                "易错点/前缀差分",
                "差分还原起点和初值错误",
                "从错误下标开始累加差分，或没有设置原数组首项，导致整个还原数组整体偏移。",
                "只写了累加循环，没有定义 diff[i] 与 a[i] 的关系。",
                "SK_V6_PREFIX_DIFF_BOUNDARY_FORMULA",
                "INITIALIZATION",
                List.of("ALGO.PREFIX.DIFF.差分还原", "ALGO.PREFIX.SUM.空前缀", "BASIC.ARRAY.INDEX.下标映射"),
                List.of("BASIC.ARRAY.TRAVERSE.全量遍历"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_PREFIX_MATRIX_INCLUSION_SIGN_WRONG",
                "易错点/前缀差分",
                "二维前缀容斥符号写反",
                "子矩阵查询时该减的上方或左方区域没有减，或交叠区域没有加回，导致结果偏大或偏小。",
                "背了二维前缀公式，但没有用图形理解四块区域的加减关系。",
                "SK_V6_PREFIX_DIFF_BOUNDARY_FORMULA",
                "BOUNDARY",
                List.of("ALGO.PREFIX.MATRIX.容斥公式", "ALGO.PREFIX.MATRIX.子矩阵查询", "ALGO.PREFIX.MATRIX.坐标偏移"),
                List.of("BASIC.ARRAY.MATRIX.行列含义"),
                "HIGH",
                LANGUAGES);
    }

    private static void addGreedyAndEnumeration(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_GREEDY_ENUM_PROOF_AND_PRUNE",
                "能力点/贪心枚举",
                "说明贪心依据并保护枚举剪枝完整性",
                "能用排序依据、交换直觉、枚举对象、去重策略和剪枝安全性解释当前搜索或贪心是否覆盖所有候选。",
                "贪心要防反例，剪枝要防漏解，两者都不能只靠样例感觉。",
                List.of("ALGO.GREEDY.CHOICE.排序依据", "ALGO.GREEDY.CHOICE.反例检查", "ALGO.GREEDY.INTERVAL.按右端点排序", "ALGO.ENUM.LOOP.枚举对象", "ALGO.ENUM.PRUNE.不可能条件", "ALGO.ENUM.LOOP.去重枚举"),
                List.of("ALGO.SORT.BASIC.自定义比较", "ENG.DEBUG.SAMPLE.最小反例"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_GREEDY_INTERVAL_SORTS_BY_LEFT_ENDPOINT",
                "易错点/贪心枚举",
                "区间选择题误按左端点排序",
                "题目目标是选择最多不相交区间或最早结束，但代码按左端点排序，导致后续可选空间被过早占用。",
                "只看到区间有起点和终点，没有分析哪个关键字能保留更多未来选择。",
                "SK_V6_GREEDY_ENUM_PROOF_AND_PRUNE",
                "MODELING",
                List.of("ALGO.GREEDY.INTERVAL.按右端点排序", "ALGO.GREEDY.INTERVAL.不相交选择", "ALGO.SORT.BASIC.升序降序"),
                List.of("ALGO.GREEDY.CHOICE.交换论证"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_ENUM_OBJECT_RANGE_MISSING_CASE",
                "易错点/贪心枚举",
                "枚举对象或范围漏掉候选",
                "代码只枚举了部分变量、部分起点或部分长度，导致合法方案没有进入判断。",
                "没有先写出完整候选空间，而是边想边写循环范围。",
                "SK_V6_GREEDY_ENUM_PROOF_AND_PRUNE",
                "BOUNDARY",
                List.of("ALGO.ENUM.LOOP.枚举对象", "ALGO.ENUM.LOOP.枚举范围", "ALGO.ENUM.LOOP.组合枚举"),
                List.of("BASIC.LOOP.NESTED.枚举组合"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_PRUNE_CONDITION_REMOVES_VALID_BRANCH",
                "易错点/贪心枚举",
                "剪枝条件过强删掉合法分支",
                "剪枝判断把仍可能得到答案的状态提前排除，导致搜索结果缺失或最优值偏差。",
                "把当前看起来不优当成一定不可能，没有证明后续状态无法弥补。",
                "SK_V6_GREEDY_ENUM_PROOF_AND_PRUNE",
                "LOGIC",
                List.of("ALGO.ENUM.PRUNE.不可能条件", "ALGO.ENUM.PRUNE.当前最优界", "ALGO.SEARCH.DFS.剪枝位置"),
                List.of("ENG.DEBUG.SAMPLE.最小反例"),
                "HIGH",
                LANGUAGES);
    }

    private static void addGraphAlgorithms(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_GRAPH_ALGORITHM_PRECONDITIONS",
                "能力点/图算法",
                "检查图算法的前提条件和状态更新",
                "能根据边权、方向、连通性、访问标记和松弛规则，判断应使用 BFS、Dijkstra、拓扑或最小生成树。",
                "图算法先检查前提：无权还是带权，有向还是无向，是否必须覆盖所有点。",
                List.of("ALGO.GRAPH.SHORTEST.BFS_最短路", "ALGO.GRAPH.SHORTEST.Dijkstra", "ALGO.GRAPH.SHORTEST.负权限制", "ALGO.GRAPH.MST.Kruskal", "ALGO.GRAPH.MST.连通性检查", "DS.GRAPH.TRAVERSE.访问标记"),
                List.of("DS.GRAPH.MODEL.有向无向", "DS.GRAPH.MODEL.权值含义"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_BFS_MARKS_VISITED_AFTER_POP_DUPLICATES",
                "易错点/图算法",
                "BFS 出队才标记导致重复入队",
                "节点被多个前驱同时发现时，因为没有在入队时标记 visited，导致重复入队、距离覆盖或复杂度膨胀。",
                "把访问成功理解成出队时才发生，没有区分发现节点和处理节点。",
                "SK_V6_GRAPH_ALGORITHM_PRECONDITIONS",
                "STATE",
                List.of("ALGO.SEARCH.BFS.访问标记", "ALGO.SEARCH.BFS.状态入队", "DS.GRAPH.TRAVERSE.重复入队"),
                List.of("DS.LINEAR.QUEUE.BFS_队列"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_DIJKSTRA_NEGATIVE_EDGE_USED",
                "易错点/图算法",
                "含负权边仍使用 Dijkstra",
                "图中存在负权边或可降低已确定距离的边，但代码仍使用 Dijkstra，导致最短路结果不可靠。",
                "只看到是带权最短路，没有检查边权是否满足 Dijkstra 的非负前提。",
                "SK_V6_GRAPH_ALGORITHM_PRECONDITIONS",
                "MODELING",
                List.of("ALGO.GRAPH.SHORTEST.Dijkstra", "ALGO.GRAPH.SHORTEST.负权限制", "DS.GRAPH.MODEL.权值含义"),
                List.of("CONTEST.READING.CONSTRAINT.值域范围"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_MST_DOES_NOT_VERIFY_CONNECTED",
                "易错点/图算法",
                "最小生成树没有检查图是否连通",
                "Kruskal 或 Prim 结束后没有确认选边数或访问点数，非连通图也被输出为生成树答案。",
                "只累计了选到的边权，没有确认是否真正连接了所有点。",
                "SK_V6_GRAPH_ALGORITHM_PRECONDITIONS",
                "MODELING",
                List.of("ALGO.GRAPH.MST.Kruskal", "ALGO.GRAPH.MST.连通性检查", "ALGO.GRAPH.CONNECT.连通块"),
                List.of("ALGO.GRAPH.CONNECT.并查集"),
                "HIGH",
                LANGUAGES);
    }

    private static void addDataStructures(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_DATA_STRUCTURE_OPERATION_CONTRACT",
                "能力点/数据结构",
                "按操作语义维护栈队列堆和映射",
                "能根据题目操作选择栈、队列、堆、set、map，并明确入出顺序、优先级、键值含义和空结构保护。",
                "数据结构不是换个容器名，而是让容器操作语义和题目动作一致。",
                List.of("DS.LINEAR.STACK.后进先出", "DS.LINEAR.QUEUE.先进先出", "DS.LINEAR.STACK.空栈检查", "DS.SET_MAP.MAP.键值关系", "DS.SET_MAP.SET.成员判断", "DS.TREE.BINARY.堆结构直觉"),
                List.of("ENG.COMPLEXITY.TIME.数据范围反推"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_STACK_QUEUE_ORDER_CONFUSED",
                "易错点/数据结构",
                "栈和队列出入顺序混用",
                "题目需要最近未匹配对象或层次扩展，但代码使用了不匹配的 LIFO/FIFO 结构，导致处理顺序错误。",
                "只看到要存一批元素，没有根据题目动作判断先处理新元素还是旧元素。",
                "SK_V6_DATA_STRUCTURE_OPERATION_CONTRACT",
                "MODELING",
                List.of("DS.LINEAR.STACK.后进先出", "DS.LINEAR.QUEUE.先进先出", "DS.LINEAR.QUEUE.BFS_队列"),
                List.of("CONTEST.PATTERN.STRUCTURE.有序性"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_HEAP_PRIORITY_DIRECTION_REVERSED",
                "易错点/数据结构",
                "堆的优先级方向写反",
                "题目需要每次取最小值却建成最大堆，或需要最大值却取了最小值，导致贪心过程整体反向。",
                "没有把优先级规则写成比较函数，只凭默认堆行为使用。",
                "SK_V6_DATA_STRUCTURE_OPERATION_CONTRACT",
                "MODELING",
                List.of("DS.TREE.BINARY.堆结构直觉", "ALGO.GREEDY.STRUCTURE.优先队列辅助", "ALGO.SORT.BASIC.升序降序"),
                List.of("ALGO.GREEDY.CHOICE.排序依据"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_SET_MAP_ERASE_WHILE_ITERATING",
                "易错点/数据结构",
                "遍历容器时删除导致迭代状态失效",
                "遍历 set、map、list 或数组时直接删除当前元素，导致跳过元素、迭代器失效或运行错误。",
                "只关注删除结果，没有处理遍历指针在删除后的合法位置。",
                "SK_V6_DATA_STRUCTURE_OPERATION_CONTRACT",
                "RUNTIME",
                List.of("DS.SET_MAP.SET.有序遍历", "DS.SET_MAP.MAP.遍历键值", "DS.LINEAR.VECTOR.删除移动"),
                List.of("BASIC.ARRAY.UPDATE.原地修改"),
                "HIGH",
                LANGUAGES);
    }

    private static void addMathCountingAndNumberTheory(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_MATH_COUNT_NUMBER_BOUNDARY",
                "能力点/数学计数",
                "处理计数、取模和数论定义边界",
                "能区分排列组合是否有序、是否允许重复、何时取模、质数和 gcd/lcm 的特殊值边界。",
                "数学题先写定义和边界，再写公式，不要让公式脱离题意。",
                List.of("MATH.COUNT.PERM.顺序是否重要", "MATH.COUNT.PERM.重复选择", "MATH.COUNT.INCLUSION.集合重叠", "MATH.NUMBER.PRIME.1_不是质数", "MATH.NUMBER.GCD.除零边界", "MATH.NUMBER.MOD.模意义保持"),
                List.of("BASIC.EXPR.ARITH.取模含义"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_COUNT_ORDER_IMPORTANCE_MISREAD",
                "易错点/数学计数",
                "把排列和组合的顺序要求读反",
                "题目要求不考虑顺序却按排列计数，或要求不同顺序算不同方案却按组合去重。",
                "只看到要计数，没有追问两个方案换顺序后是否仍是同一个方案。",
                "SK_V6_MATH_COUNT_NUMBER_BOUNDARY",
                "MODELING",
                List.of("MATH.COUNT.PERM.排列", "MATH.COUNT.PERM.组合", "MATH.COUNT.PERM.顺序是否重要"),
                List.of("CONTEST.READING.OUTPUT.输出方案数"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_MOD_APPLIED_ONLY_AT_FINAL_OVERFLOWS",
                "易错点/数学计数",
                "只在最终答案取模导致中间溢出",
                "计数或乘法过程中中间结果已超过整数范围，最后再取模已经无法恢复正确结果。",
                "把取模看成输出格式，而不是每次加乘都要保持数值安全的运算规则。",
                "SK_V6_MATH_COUNT_NUMBER_BOUNDARY",
                "VALUE_RANGE",
                List.of("MATH.NUMBER.MOD.乘法取模", "MATH.NUMBER.MOD.大数防溢出", "BASIC.TYPE.INTEGER.整型溢出"),
                List.of("BASIC.TYPE.INTEGER.long_long_范围"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_INCLUSION_EXCLUSION_OVERLAP_COUNTED_TWICE",
                "易错点/数学计数",
                "容斥中交集加减方向错误",
                "多个条件计数时没有正确减去重复交集或补回多减部分，导致重叠对象被多算或漏算。",
                "只分别统计了每个条件，没有画出集合重叠区域。",
                "SK_V6_MATH_COUNT_NUMBER_BOUNDARY",
                "LOGIC",
                List.of("MATH.COUNT.INCLUSION.集合重叠", "MATH.COUNT.INCLUSION.二集合容斥", "MATH.COUNT.INCLUSION.多条件计数"),
                List.of("MATH.COUNT.INCLUSION.边界全集"),
                "HIGH",
                LANGUAGES);
    }

    private static void addRecursionAndSearch(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_SEARCH_RECURSION_STATE_SPACE",
                "能力点/搜索递归",
                "定义搜索状态、选择顺序和恢复规则",
                "能把搜索状态、候选生成、递归出口、访问标记和回溯恢复写成完整闭环。",
                "搜索题先定义状态空间，再决定怎么扩展状态、怎么判重、什么时候恢复。",
                List.of("ALGO.SEARCH.DFS.递归参数", "ALGO.SEARCH.DFS.搜索边界", "ALGO.SEARCH.DFS.路径记录", "ALGO.SEARCH.STATE.状态编码", "ALGO.SEARCH.STATE.非法状态过滤", "BASIC.RECURSION.STATE.回溯恢复"),
                List.of("BASIC.RECURSION.BASE.终止条件"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_DFS_CHOICE_LIST_MUTATED_ACROSS_BRANCHES",
                "易错点/搜索递归",
                "DFS 候选列表在分支间被错误共享",
                "递归分支修改了候选列表、路径或可用集合，但没有复制或恢复，导致兄弟分支看到被污染的状态。",
                "把可变对象当成每层独立状态，没有意识到引用会被多个分支共享。",
                "SK_V6_SEARCH_RECURSION_STATE_SPACE",
                "STATE",
                List.of("ALGO.SEARCH.DFS.路径记录", "BASIC.RECURSION.STATE.回溯恢复", "BASIC.FUNCTION.PARAM.可变对象风险"),
                List.of("BASIC.FUNCTION.PARAM.值传递"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_SEARCH_GOAL_CHECK_AFTER_EXPANSION",
                "易错点/搜索递归",
                "终点判断放在扩展之后导致漏解或多走一步",
                "状态已经满足目标时没有及时收集答案，而是继续扩展下一层，导致答案缺失、重复或步数偏大。",
                "没有区分进入状态时检查目标，还是生成下一状态后检查目标。",
                "SK_V6_SEARCH_RECURSION_STATE_SPACE",
                "BOUNDARY",
                List.of("ALGO.SEARCH.STATE.终点判断", "ALGO.SEARCH.DFS.搜索边界", "ALGO.SEARCH.BFS.最短步数"),
                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_SEARCH_INVALID_STATE_FILTER_TOO_LATE",
                "易错点/搜索递归",
                "非法状态过滤过晚",
                "越界、冲突或不满足约束的状态已经进入递归或队列，导致运行错误、重复处理或错误答案。",
                "先生成状态再慢慢判断，没有把合法性作为入队或递归前置门槛。",
                "SK_V6_SEARCH_RECURSION_STATE_SPACE",
                "RUNTIME",
                List.of("ALGO.SEARCH.STATE.非法状态过滤", "ALGO.SEARCH.BFS.状态入队", "BASIC.BRANCH.GUARD.非法输入保护"),
                List.of("BASIC.ARRAY.MATRIX.边界检查"),
                "HIGH",
                LANGUAGES);
    }

    private static void addSortingAndIntervals(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_SORT_INTERVAL_CONTRACT",
                "能力点/排序区间",
                "设计排序、分组和区间边界规则",
                "能根据题目目标确定排序关键字、并列规则、区间开闭和合并条件，并让排序后的遍历保持原题语义。",
                "排序不是改变题意，而是把题意中的优先级显式写成比较规则。",
                List.of("ALGO.SORT.BASIC.自定义比较", "ALGO.SORT.BASIC.稳定排序", "ALGO.SORT.APPLICATION.区间排序", "ALGO.GREEDY.INTERVAL.区间合并", "ALGO.GREEDY.INTERVAL.边界重叠"),
                List.of("BASIC.EXPR.COMPARE.边界比较"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_SORT_COMPARATOR_NOT_STRICT_WEAK_ORDER",
                "易错点/排序区间",
                "比较函数不满足严格弱序",
                "自定义比较在相等、传递性或双向比较上不一致，导致排序结果不稳定甚至运行异常。",
                "比较函数只考虑某个样例里的前后关系，没有定义所有相等和并列情况。",
                "SK_V6_SORT_INTERVAL_CONTRACT",
                "LOGIC",
                List.of("ALGO.SORT.BASIC.自定义比较", "ALGO.SORT.BASIC.稳定排序", "BASIC.EXPR.LOGIC.条件组合"),
                List.of("BASIC.FUNCTION.RETURN.返回布尔"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_INTERVAL_TOUCHING_BOUNDARY_MERGED_WRONG",
                "易错点/排序区间",
                "区间端点相接时合并规则错误",
                "题目对 [l,r] 和 [r,next] 是否重叠有明确语义，但代码把相接区间错误地合并或拆开。",
                "没有先确认区间是闭区间、半开区间，还是端点相接也算冲突。",
                "SK_V6_SORT_INTERVAL_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.GREEDY.INTERVAL.区间合并", "ALGO.GREEDY.INTERVAL.边界重叠", "BASIC.EXPR.COMPARE.边界比较"),
                List.of("BASIC.LOOP.BOUNDARY.左闭右闭"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_GROUP_AFTER_SORT_FORGETS_LAST_GROUP",
                "易错点/排序区间",
                "排序分组后最后一组漏处理",
                "按关键字排序并扫描分组时，只在遇到新组时结算上一组，循环结束后忘记结算最后一组。",
                "把分组结算写成组切换事件，没有处理没有下一组触发的最后一段。",
                "SK_V6_SORT_INTERVAL_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.SORT.BASIC.排序后遍历", "BASIC.LOOP.BOUNDARY.最后一次迭代", "BASIC.ARRAY.TRAVERSE.全量遍历"),
                List.of("ENG.DEBUG.BOUNDARY.最小输入"),
                "HIGH",
                LANGUAGES);
    }

    private static void addDebuggingAndSubmissionReview(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_DEBUG_SUBMISSION_FEEDBACK_LOOP",
                "能力点/调试复盘",
                "根据判题结果建立最小反例和修复验证闭环",
                "能根据 CE、RE、WA、TLE 和格式错误选择调试路径，构造最小反例，修改后用边界和复杂度复测。",
                "一次提交失败不是只改一行，而是要定位证据、验证假设、复测边界。",
                List.of("ENG.ERROR.COMPILE.语法拼写", "ENG.ERROR.RUNTIME.数组越界", "ENG.ERROR.WRONG_ANSWER.边界遗漏", "ENG.ERROR.TIME.复杂度过高", "ENG.DEBUG.SAMPLE.最小反例", "CONTEST.SUBMIT.REVIEW.再次提交策略"),
                List.of("ENG.DEBUG.SAMPLE.手算对照"),
                "MEDIUM",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_DEBUG_FIX_WITHOUT_REPRODUCING_FAILURE",
                "易错点/调试复盘",
                "没有复现失败就直接改代码",
                "学生根据猜测修改代码，但没有先构造能稳定复现错误的输入，导致改动无法验证甚至引入新问题。",
                "把调试看成试错，没有建立错误输入、错误输出和关键状态之间的证据链。",
                "SK_V6_DEBUG_SUBMISSION_FEEDBACK_LOOP",
                "DEBUGGING",
                List.of("ENG.DEBUG.SAMPLE.最小反例", "ENG.DEBUG.SAMPLE.手算对照", "CONTEST.SUBMIT.REVIEW.错误类型定位"),
                List.of("ENG.DEBUG.TRACE.循环状态"),
                "MEDIUM",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_DEBUG_ONLY_CHECKS_CHANGED_SAMPLE",
                "易错点/调试复盘",
                "修复后只复测刚失败的样例",
                "代码修改后只验证一个失败点，没有重新跑边界、多组、最大规模或原有样例，导致回归问题未发现。",
                "把修复等同于让当前样例通过，没有检查修改是否破坏其他情况。",
                "SK_V6_DEBUG_SUBMISSION_FEEDBACK_LOOP",
                "DEBUGGING",
                List.of("CONTEST.SUBMIT.CHECKLIST.样例复测", "CONTEST.SUBMIT.CHECKLIST.边界复测", "CONTEST.SUBMIT.CHECKLIST.复杂度检查"),
                List.of("ENG.DEBUG.BOUNDARY.最大输入"),
                "MEDIUM",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_TLE_OPTIMIZES_CONSTANT_NOT_COMPLEXITY",
                "易错点/调试复盘",
                "TLE 后只优化常数不改复杂度",
                "最大数据下算法复杂度已经不匹配，但修复只换输入方式、微调循环或删输出，没有改变核心算法规模。",
                "把超时归因于机器慢或语言慢，没有用数据范围重新估算操作次数。",
                "SK_V6_DEBUG_SUBMISSION_FEEDBACK_LOOP",
                "COMPLEXITY",
                List.of("ENG.ERROR.TIME.复杂度过高", "ENG.COMPLEXITY.TIME.数据范围反推", "CONTEST.SUBMIT.CHECKLIST.复杂度检查"),
                List.of("ALGO.ENUM.COMPLEXITY.数据范围反推"),
                "HIGH",
                LANGUAGES);
    }

    private static void addGridAndCoordinateModeling(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_GRID_COORDINATE_TRANSFORM",
                "能力点/网格坐标",
                "统一网格坐标、方向数组和边界变换",
                "能把题面坐标、矩阵行列、方向数组、障碍判断和越界保护统一到一套坐标系统里。",
                "网格题先确认 r/c 和 x/y 的对应，再写方向、边界和访问条件。",
                List.of("BASIC.ARRAY.MATRIX.行列含义", "BASIC.ARRAY.MATRIX.方向遍历", "BASIC.ARRAY.MATRIX.边界检查", "MATH.GEOMETRY.COORD.x_y_坐标", "MATH.GEOMETRY.COORD.方向数组", "MATH.GEOMETRY.COORD.坐标偏移"),
                List.of("BASIC.ARRAY.INDEX.下标映射"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_GRID_INPUT_COORDINATE_NOT_NORMALIZED",
                "易错点/网格坐标",
                "题面坐标没有转换成数组下标",
                "题面给出的坐标从 1 开始或使用 x/y 表示，但代码直接当作 0 基 row/col 使用，导致整体偏移或行列互换。",
                "没有先建立题面坐标到 grid[r][c] 的映射表。",
                "SK_V6_GRID_COORDINATE_TRANSFORM",
                "BOUNDARY",
                List.of("MATH.GEOMETRY.COORD.x_y_坐标", "BASIC.ARRAY.MATRIX.行列含义", "BASIC.ARRAY.INDEX.下标映射"),
                List.of("BASIC.ARRAY.INDEX.0_基下标"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_GRID_DIRECTION_DELTA_PAIR_SWAPPED",
                "易错点/网格坐标",
                "方向数组行列增量配对错误",
                "dr/dc 或 dx/dy 的配对顺序写错，导致移动方向和题意不一致，搜索或模拟走到错误格子。",
                "只分别写了两个数组，没有检查同一个下标下两个增量是否组成正确方向。",
                "SK_V6_GRID_COORDINATE_TRANSFORM",
                "BOUNDARY",
                List.of("MATH.GEOMETRY.COORD.方向数组", "MATH.GEOMETRY.COORD.坐标偏移", "BASIC.ARRAY.MATRIX.方向遍历"),
                List.of("ENG.DEBUG.TRACE.数组状态"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_GRID_OBSTACLE_CHECK_AFTER_VISIT",
                "易错点/网格坐标",
                "障碍或越界判断晚于访问标记",
                "代码先标记 visited、入队或访问数组，再检查越界和障碍，导致非法格子污染搜索状态。",
                "没有把合法性判断作为进入格子的前置条件。",
                "SK_V6_GRID_COORDINATE_TRANSFORM",
                "RUNTIME",
                List.of("BASIC.ARRAY.MATRIX.边界检查", "ALGO.SEARCH.STATE.非法状态过滤", "ALGO.SEARCH.BFS.状态入队"),
                List.of("BASIC.BRANCH.GUARD.非法输入保护"),
                "HIGH",
                LANGUAGES);
    }

    private static void addInputOutputMultiCase(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_IO_MULTICASE_FORMAT_CONTRACT",
                "能力点/输入输出",
                "完整映射多组输入、输出格式和状态重置",
                "能区分显式 T 组、读到 EOF、每组输出格式和每组内部状态重置位置。",
                "多组数据题先圈出外层循环，再决定哪些变量必须每组重新初始化。",
                List.of("BASIC.IO.MULTI_CASE.显式_T_组循环", "BASIC.IO.MULTI_CASE.未知组数读到_EOF", "BASIC.IO.MULTI_CASE.每组状态重置", "BASIC.IO.MULTI_CASE.多组输出格式", "BASIC.IO.STDOUT.按要求换行"),
                List.of("BASIC.IO.STDIN.输入顺序映射"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_IO_TREATED_T_AS_DATA_VALUE",
                "易错点/输入输出",
                "把组数 T 当作普通数据参与计算",
                "第一行表示测试组数，但代码把它当作第一组数据的一部分，导致读入错位。",
                "没有先判断第一行是控制循环次数还是业务数据。",
                "SK_V6_IO_MULTICASE_FORMAT_CONTRACT",
                "IO_FORMAT",
                List.of("BASIC.IO.MULTI_CASE.显式_T_组循环", "CONTEST.READING.INPUT.数据组数", "BASIC.IO.STDIN.输入顺序映射"),
                List.of("BASIC.LOOP.FOR.循环次数计算"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_IO_EOF_LOOP_DROPS_LAST_RECORD",
                "易错点/输入输出",
                "读到 EOF 循环漏处理最后一条记录",
                "读取驱动循环把处理逻辑放在下一次读取之后，导致最后一次成功读取的数据没有被处理。",
                "没有区分读取成功、处理当前记录、再读取下一记录这三个时刻。",
                "SK_V6_IO_MULTICASE_FORMAT_CONTRACT",
                "IO_FORMAT",
                List.of("BASIC.IO.MULTI_CASE.未知组数读到_EOF", "BASIC.LOOP.WHILE.读入驱动循环", "BASIC.IO.STDIN.多行读取"),
                List.of("ENG.DEBUG.BOUNDARY.最小输入"),
                "MEDIUM",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_IO_CASE_OUTPUT_SEPARATOR_WRONG",
                "易错点/输入输出",
                "多组输出分隔格式错误",
                "题面要求每组一行、空行分隔或 Case 编号，但代码少输出、多输出或位置错误。",
                "只关注每组答案数值，没有把组间格式也视为判题内容。",
                "SK_V6_IO_MULTICASE_FORMAT_CONTRACT",
                "IO_FORMAT",
                List.of("BASIC.IO.MULTI_CASE.多组输出格式", "BASIC.IO.STDOUT.按要求换行", "BASIC.IO.STDOUT.空格分隔"),
                List.of("ENG.ERROR.FORMAT.缺少换行"),
                "MEDIUM",
                LANGUAGES);
    }

    private static void addFunctionContractAndSideEffects(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V6_FUNCTION_RECURSION_CONTRACT",
                "能力点/函数递归",
                "定义函数契约、可变参数和递归返回路径",
                "能说明函数输入、输出、是否修改外部状态、递归返回值如何合并，以及所有路径是否都有返回。",
                "函数不是把代码包起来，而是给调用者一个稳定的输入输出契约。",
                List.of("BASIC.FUNCTION.DEF.参数设计", "BASIC.FUNCTION.DEF.返回值设计", "BASIC.FUNCTION.PARAM.可变对象风险", "BASIC.FUNCTION.RETURN.完整返回路径", "BASIC.RECURSION.STATE.递归转移"),
                List.of("BASIC.TYPE.VARIABLE.作用域"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_FUNCTION_MUTABLE_DEFAULT_STATE_LEAKS",
                "易错点/函数递归",
                "可变默认状态在多次调用间泄漏",
                "函数参数、全局列表或静态容器在多次调用之间复用，导致上一题、上一组或上一分支的状态残留。",
                "把可变对象当作临时变量，没有意识到它会跨调用共享。",
                "SK_V6_FUNCTION_RECURSION_CONTRACT",
                "STATE",
                List.of("BASIC.FUNCTION.PARAM.可变对象风险", "BASIC.TYPE.VARIABLE.作用域", "BASIC.IO.MULTI_CASE.每组状态重置"),
                List.of("ENG.DEBUG.TRACE.递归栈"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_FUNCTION_MISSING_RETURN_ON_BRANCH",
                "易错点/函数递归",
                "函数某些分支没有返回值",
                "函数在部分条件下返回结果，但其他合法分支没有 return，调用处拿到空值、默认值或未定义结果。",
                "只沿着样例路径检查返回，没有覆盖所有分支的返回契约。",
                "SK_V6_FUNCTION_RECURSION_CONTRACT",
                "RUNTIME",
                List.of("BASIC.FUNCTION.RETURN.完整返回路径", "BASIC.BRANCH.CASE.覆盖所有情况", "BASIC.BRANCH.CASE.默认分支"),
                List.of("ENG.ERROR.RUNTIME.非法内存"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V6_RECURSION_MERGE_IGNORES_CHILD_RESULT",
                "易错点/函数递归",
                "递归子问题结果没有正确合并",
                "递归调用返回了子结果，但父层没有累加、取最值、合并列表或向上返回，导致最终答案缺失。",
                "只写了递归调用，没有定义子问题结果如何贡献到父问题。",
                "SK_V6_FUNCTION_RECURSION_CONTRACT",
                "STATE",
                List.of("BASIC.RECURSION.STATE.递归转移", "BASIC.FUNCTION.RETURN.返回集合", "BASIC.FUNCTION.RETURN.完整返回路径"),
                List.of("ALGO.DP.TRANSITION.取_max_min_sum"),
                "HIGH",
                LANGUAGES);
    }
}
