package com.onlinejudge.learning.standardlibrary.application;

import com.onlinejudge.learning.standardlibrary.domain.AiStandardLibraryLayer;

import java.util.List;

final class AiStandardLibraryV13QualityExpansionSeeds {

    private static final List<String> LANGUAGES = List.of("PYTHON", "CPP17");

    private AiStandardLibraryV13QualityExpansionSeeds() {
    }

    static void addTo(List<AiStandardLibrarySeed> seeds) {
        addArrayUpdate(seeds);
        addStringMatch(seeds);
        addMatrixPrefix(seeds);
        addDpTransition(seeds);
        addGreedyProof(seeds);
        addBitmaskState(seeds);
        addShortestPath(seeds);
        addEnumerationPruning(seeds);
        addFunctionParameters(seeds);
        addLinkedSimulation(seeds);
        addGeometryDistance(seeds);
        addPrimeFactorRange(seeds);
    }

    private static void addArrayUpdate(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_ARRAY_UPDATE_SNAPSHOT_CONTRACT",
                "能力点/V13数组批量更新",
                "维护原数组、临时数组、批量更新和累计量同步契约",
                "能区分读旧值、写新值、批量更新生效顺序和累计量同步时机，避免原地修改破坏后续判断。",
                "写更新逻辑前先标出每一步读取哪个旧状态、写入哪个新状态、何时统一提交。",
                List.of("BASIC.ARRAY.UPDATE.读旧写新分离", "BASIC.ARRAY.UPDATE.批量更新后还原顺序",
                        "BASIC.ARRAY.UPDATE.累计量同步更新", "BASIC.ARRAY.UPDATE.覆盖风险"),
                List.of("BASIC.ARRAY.TRAVERSE.全量遍历"),
                "HIGH",
                List.of(
                        m("MP_V13_ARRAY_UPDATE_READS_ALREADY_MODIFIED_VALUE",
                                "原地更新时读到了已经改过的值",
                                "同一轮更新既读数组又写数组，后面的元素使用了前面刚改出的新值，导致本应同时发生的变化被串行化。",
                                "没有区分本轮输入状态和本轮输出状态，以为数组当前位置改完不会影响后续读取。",
                                "STATE",
                                List.of("BASIC.ARRAY.UPDATE.读旧写新分离", "BASIC.ARRAY.UPDATE.原地修改"),
                                List.of("BASIC.ARRAY.TRAVERSE.全量遍历"),
                                "HIGH"),
                        m("MP_V13_BATCH_UPDATE_RESTORE_ORDER_WRONG",
                                "批量更新后按错误顺序还原状态",
                                "离线更新、差分恢复或模拟回滚时，代码先覆盖关键状态再使用它还原其他字段，导致回滚后的数组不等于更新前状态。",
                                "只记得要恢复，没有记录恢复依赖谁必须先保留旧值。",
                                "STATE",
                                List.of("BASIC.ARRAY.UPDATE.批量更新后还原顺序", "BASIC.ARRAY.UPDATE.临时数组"),
                                List.of("ENG.DEBUG.TRACE.数组状态"),
                                "HIGH"),
                        m("MP_V13_ACCUMULATED_SUM_NOT_SYNCED_WITH_UPDATE",
                                "数组变更后累计量没有同步更新",
                                "数组元素被替换、删除或批量加减后，维护的总和、最大值、计数或窗口统计仍使用旧值。",
                                "把数组内容和派生统计量当成两套互不影响的数据，没有写出同步更新规则。",
                                "STATE",
                                List.of("BASIC.ARRAY.UPDATE.累计量同步更新", "ALGO.TWO_POINTERS.WINDOW.计数维护"),
                                List.of("BASIC.TYPE.VARIABLE.赋值覆盖"),
                                "HIGH")),
                "IP_V13_ARRAY_UPDATE_STATE_TABLE",
                "用数组更新状态表区分读旧、写新和同步统计",
                "适用于学生会遍历数组，但原地修改、批量提交或累计量维护经常相互污染。",
                "修复后让学生为每次更新写出旧数组、新数组、派生统计量和提交时机四列。",
                "教师可用状态表判断错误来自原地覆盖、恢复顺序还是统计量未同步。",
                List.of("MP_V13_ARRAY_UPDATE_READS_ALREADY_MODIFIED_VALUE", "MP_V13_ACCUMULATED_SUM_NOT_SYNCED_WITH_UPDATE"));
    }

    private static void addStringMatch(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_STRING_MATCH_BOUNDARY_CONTRACT",
                "能力点/V13字符串匹配边界",
                "维护查找位置、重叠匹配、未找到哨兵和前后缀边界契约",
                "能判断匹配窗口的起止位置、下一次查找从哪里开始、未找到时返回什么，以及前后缀是否允许空串或整串。",
                "写字符串匹配前先列出匹配窗口、失败返回值、重叠是否计数和边界样例。",
                List.of("BASIC.STRING.MATCH.查找出现位置", "BASIC.STRING.MATCH.统计出现次数",
                        "BASIC.STRING.MATCH.重叠匹配计数", "BASIC.STRING.MATCH.未找到结果哨兵",
                        "BASIC.STRING.MATCH.前后缀边界"),
                List.of("BASIC.STRING.CHAR.字符遍历"),
                "MEDIUM",
                List.of(
                        m("MP_V13_STRING_MATCH_SKIPS_OVERLAP",
                                "统计子串时跳过了重叠出现",
                                "找到一次匹配后直接把起点跳到匹配串末尾，题目要求重叠计数时漏掉相邻重叠窗口。",
                                "把不重叠分段统计当成所有匹配统计，没有先确认下一次查找应移动 1 位还是移动模式串长度。",
                                "BOUNDARY",
                                List.of("BASIC.STRING.MATCH.统计出现次数", "BASIC.STRING.MATCH.重叠匹配计数"),
                                List.of("BASIC.LOOP.FOR.步长变化"),
                                "HIGH"),
                        m("MP_V13_STRING_NOT_FOUND_SENTINEL_USED_AS_INDEX",
                                "未找到哨兵被继续当作下标使用",
                                "查找结果为 -1、npos 或空结果时，代码仍用它切片、访问数组或计算长度，导致越界或答案错位。",
                                "只测试了能找到的样例，没有把查找失败作为正常分支处理。",
                                "RUNTIME",
                                List.of("BASIC.STRING.MATCH.未找到结果哨兵", "BASIC.ARRAY.INDEX.越界访问"),
                                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                                "HIGH"),
                        m("MP_V13_PREFIX_SUFFIX_ACCEPTS_WHOLE_STRING_UNEXPECTEDLY",
                                "前后缀判断误把整串当成合法边界",
                                "题目要求真前缀或真后缀时，代码允许长度等于原串，导致整串被当成可删除或可匹配部分。",
                                "只比较了内容相等，没有把前后缀长度限制写入判断。",
                                "BOUNDARY",
                                List.of("BASIC.STRING.MATCH.前后缀边界", "BASIC.STRING.SUBSTRING.长度参数"),
                                List.of("BASIC.EXPR.COMPARE.边界比较"),
                                "MEDIUM")),
                "IP_V13_STRING_MATCH_CASE_CARD",
                "用字符串匹配样例卡覆盖成功、失败和重叠窗口",
                "适用于学生匹配逻辑能过样例，但隐藏数据在重叠、未找到或前后缀边界失败。",
                "修复后让学生构造三个最小样例：找得到、找不到、两个匹配窗口重叠。",
                "教师可用样例卡判断错误来自窗口移动、失败分支还是边界长度。",
                List.of("MP_V13_STRING_MATCH_SKIPS_OVERLAP", "MP_V13_STRING_NOT_FOUND_SENTINEL_USED_AS_INDEX"));
    }

    private static void addMatrixPrefix(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_MATRIX_PREFIX_INCLUSION_CONTRACT",
                "能力点/V13二维前缀容斥",
                "维护二维前缀坐标偏移、容斥公式和边界补零契约",
                "能定义二维前缀的行列含义，并用四个角推导子矩阵查询公式，处理 0 行 0 列补位和行列顺序。",
                "写二维前缀前先画出查询矩形四角，标明哪些区域要加、哪些重叠区域要减。",
                List.of("ALGO.PREFIX.MATRIX.容斥公式", "ALGO.PREFIX.MATRIX.坐标偏移",
                        "ALGO.PREFIX.MATRIX.子矩阵查询", "ALGO.PREFIX.MATRIX.边界补零",
                        "ALGO.PREFIX.MATRIX.行列混淆"),
                List.of("BASIC.ARRAY.MATRIX.行列含义"),
                "HIGH",
                List.of(
                        m("MP_V13_MATRIX_PREFIX_MISSES_OVERLAP_SUBTRACTION",
                                "二维前缀容斥漏减重叠区域",
                                "查询子矩阵时只加了右下、左上相关前缀，没有把被重复计算的左上重叠区域减回一次。",
                                "把二维前缀当成一维区间相减，没有画出两个被排除区域的交集。",
                                "LOGIC",
                                List.of("ALGO.PREFIX.MATRIX.容斥公式", "ALGO.PREFIX.MATRIX.子矩阵查询"),
                                List.of("ALGO.PREFIX.SUM.区间查询"),
                                "HIGH"),
                        m("MP_V13_MATRIX_PREFIX_ROW_COL_SWAPPED",
                                "二维前缀查询时行列坐标互换",
                                "读入或查询使用 r、c，但公式中把行当列、列当行，导致非正方形数据或非对称查询出错。",
                                "没有固定 matrix[row][col] 与题面 x/y 或 r/c 的对应关系。",
                                "MODELING",
                                List.of("ALGO.PREFIX.MATRIX.行列混淆", "BASIC.ARRAY.MATRIX.行列含义"),
                                List.of("MATH.GEOMETRY.COORD.行列坐标"),
                                "HIGH"),
                        m("MP_V13_MATRIX_PREFIX_ZERO_PADDING_MISSING",
                                "二维前缀缺少边界补零导致首行首列特判混乱",
                                "前缀表没有预留第 0 行或第 0 列，查询贴边矩形时需要多层特判，部分边界漏处理。",
                                "只按原矩阵大小建表，没有用补零行列统一公式。",
                                "BOUNDARY",
                                List.of("ALGO.PREFIX.MATRIX.边界补零", "ALGO.PREFIX.MATRIX.坐标偏移"),
                                List.of("BASIC.ARRAY.INDEX.0_基下标"),
                                "HIGH")),
                "IP_V13_MATRIX_PREFIX_CORNER_REHEARSAL",
                "用四角容斥复盘二维前缀公式",
                "适用于学生会写一维前缀，但二维查询公式、行列顺序或贴边矩形反复出错。",
                "修复后让学生在图上标出查询矩形、四个前缀点、重复区域和补零边界。",
                "教师可用四角图判断错误来自容斥、坐标偏移还是行列建模。",
                List.of("MP_V13_MATRIX_PREFIX_MISSES_OVERLAP_SUBTRACTION", "MP_V13_MATRIX_PREFIX_ROW_COL_SWAPPED"));
    }

    private static void addDpTransition(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_DP_STATE_TRANSITION_ORDER_CONTRACT",
                "能力点/V13 DP状态转移顺序",
                "维护状态含义、转移来源、初始化边界和遍历顺序契约",
                "能说明 dp 每一维代表什么、当前值从哪些旧状态转移而来、非法状态如何表示，以及循环顺序是否会读到本轮新值。",
                "写 DP 前先用自然语言定义状态，再列初始化、转移来源、遍历方向和答案位置。",
                List.of("ALGO.DP.STATE.状态含义", "ALGO.DP.STATE.维度选择",
                        "ALGO.DP.TRANSITION.枚举决策", "ALGO.DP.TRANSITION.转移边界",
                        "ALGO.DP.INIT.边界状态"),
                List.of("BASIC.ARRAY.INDEX.下标映射"),
                "HIGH",
                List.of(
                        m("MP_V13_DP_STATE_MISSES_REQUIRED_DIMENSION",
                                "DP 状态少了一维导致不同情况混在一起",
                                "题目需要区分位置、次数、是否使用过操作或上一个选择，但 dp 只保存其中一部分，使互相不能转移的状态被合并。",
                                "只追求数组更小，没有先判断哪些信息会影响未来决策。",
                                "MODELING",
                                List.of("ALGO.DP.STATE.维度选择", "ALGO.DP.STATE.状态含义"),
                                List.of("CONTEST.PATTERN.STRUCTURE.重叠子问题"),
                                "HIGH"),
                        m("MP_V13_DP_LOOP_ORDER_READS_CURRENT_ROUND_VALUE",
                                "DP 遍历顺序读到了本轮刚更新的值",
                                "滚动数组或一维优化时循环方向错误，读到了本轮刚更新的值，使同一物品、同一步操作或同一层状态被重复使用。",
                                "记住了可以压缩空间，没有说明当前转移应该读取上一层还是当前层。",
                                "STATE",
                                List.of("ALGO.DP.TRANSITION.从后往前", "ALGO.DP.INIT.滚动数组初始化"),
                                List.of("BASIC.ARRAY.UPDATE.读旧写新分离"),
                                "HIGH"),
                        m("MP_V13_DP_ILLEGAL_STATE_INITIALIZED_AS_VALID",
                                "非法 DP 状态被初始化成可转移值",
                                "本应不可达的状态被设为 0 或普通值，后续转移把它当作合法来源，生成不存在的方案。",
                                "把默认数组值当成无害初值，没有区分可达、不可达和边界状态。",
                                "INITIALIZATION",
                                List.of("ALGO.DP.INIT.无穷大", "ALGO.DP.STATE.非法状态", "ALGO.DP.INIT.边界状态"),
                                List.of("BASIC.TYPE.VARIABLE.声明与初始化"),
                                "HIGH")),
                "IP_V13_DP_STATE_TRANSFER_TABLE",
                "用 DP 状态转移表固定含义、来源和遍历顺序",
                "适用于学生知道要用 DP，但状态少维、初始化和循环方向经常不稳定。",
                "修复后让学生写出状态定义、合法初值、每条转移来源、遍历方向和最终答案所在格。",
                "教师可用转移表判断错误来自状态建模、初始化还是读旧写新顺序。",
                List.of("MP_V13_DP_STATE_MISSES_REQUIRED_DIMENSION", "MP_V13_DP_LOOP_ORDER_READS_CURRENT_ROUND_VALUE"));
    }

    private static void addGreedyProof(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_GREEDY_PROOF_COUNTEREXAMPLE_CONTRACT",
                "能力点/V13贪心证明与反例",
                "维护排序依据、选择时机、交换论证和反例检查契约",
                "能判断当前局部选择是否有单调依据，能用交换论证或最小反例说明为什么该选择不会破坏全局最优。",
                "写贪心前先说明排序键、每一步选择什么、被放弃对象为什么不会更优。",
                List.of("ALGO.GREEDY.CHOICE.排序依据", "ALGO.GREEDY.CHOICE.选择时机",
                        "ALGO.GREEDY.CHOICE.交换论证", "ALGO.GREEDY.CHOICE.反例检查",
                        "ALGO.GREEDY.INTERVAL.边界重叠"),
                List.of("ALGO.SORT.BASIC.自定义比较"),
                "HIGH",
                List.of(
                        m("MP_V13_GREEDY_SORT_KEY_IGNORES_TIE_BREAKER",
                                "贪心排序键缺少必要的并列规则",
                                "主要排序字段相同的对象会影响可行性或答案，但比较函数没有处理并列情况，导致顺序不稳定或选择错误。",
                                "只找到了一个看似重要的字段，没有分析字段相等时谁应该先被处理。",
                                "MODELING",
                                List.of("ALGO.GREEDY.CHOICE.排序依据", "ALGO.SORT.BASIC.自定义比较"),
                                List.of("ALGO.SORT.BASIC.稳定排序"),
                                "HIGH"),
                        m("MP_V13_GREEDY_LOCAL_CHOICE_WITHOUT_EXCHANGE_ARGUMENT",
                                "只凭直觉选择局部最优但没有交换依据",
                                "代码每次做当前最小、最大或最早的局部选择，但存在小反例说明该选择会堵住后续更优方案。",
                                "把样例中成立的选择当成通用规律，没有尝试交换两个相邻决策。",
                                "MODELING",
                                List.of("ALGO.GREEDY.CHOICE.局部最优", "ALGO.GREEDY.CHOICE.交换论证"),
                                List.of("ALGO.GREEDY.CHOICE.反例检查"),
                                "HIGH"),
                        m("MP_V13_INTERVAL_GREEDY_BOUNDARY_OVERLAP_MISCLASSIFIED",
                                "区间贪心把边界相接误判为重叠或不重叠",
                                "题目对端点是否闭合有要求，但代码用统一的 <、<= 判断所有区间，导致刚好相接的区间被错误选择或排除。",
                                "只记得按端点排序，没有把区间开闭和边界归属写进可行性判断。",
                                "BOUNDARY",
                                List.of("ALGO.GREEDY.INTERVAL.边界重叠", "BASIC.EXPR.COMPARE.边界比较"),
                                List.of("BASIC.BRANCH.CASE.边界归属"),
                                "HIGH")),
                "IP_V13_GREEDY_EXCHANGE_AND_COUNTEREXAMPLE_DRILL",
                "用交换论证和最小反例检验贪心规则",
                "适用于学生会想到排序或局部选择，但无法证明规则，隐藏数据被反例击穿。",
                "修复后让学生写一段交换论证，并构造一个专门攻击并列、边界或选择时机的最小反例。",
                "教师可用该练习判断学生是比较函数错误，还是贪心规则本身不成立。",
                List.of("MP_V13_GREEDY_SORT_KEY_IGNORES_TIE_BREAKER", "MP_V13_GREEDY_LOCAL_CHOICE_WITHOUT_EXCHANGE_ARGUMENT"));
    }

    private static void addBitmaskState(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_BITMASK_STATE_TRANSITION_CONTRACT",
                "能力点/V13位运算状态压缩",
                "维护集合掩码、位数限制、状态判断和掩码转移契约",
                "能把集合元素映射到二进制位，判断某位是否存在，添加或删除元素，并控制枚举子集和掩码范围。",
                "写位运算前先固定第 i 位代表谁、合法 mask 范围和每次转移改变哪一位。",
                List.of("MATH.BIT.MASK.集合掩码", "MATH.BIT.MASK.枚举子集",
                        "MATH.BIT.MASK.状态判断", "MATH.BIT.MASK.位数限制", "MATH.BIT.MASK.掩码转移"),
                List.of("MATH.BIT.BINARY.位权"),
                "MEDIUM",
                List.of(
                        m("MP_V13_BITMASK_SHIFT_USES_ONE_BASED_INDEX",
                                "集合元素编号和二进制位偏移差一",
                                "题面元素从 1 编号，但代码直接使用 1 << id，导致第 0 位空置、最高位越界或状态映射整体错位。",
                                "没有把元素编号转换成从 0 开始的位下标。",
                                "BOUNDARY",
                                List.of("MATH.BIT.MASK.集合掩码", "MATH.BIT.OP.设置清除位"),
                                List.of("BASIC.ARRAY.INDEX.下标映射"),
                                "HIGH"),
                        m("MP_V13_SUBSET_ENUMERATION_MISSES_EMPTY_OR_FULL_SET",
                                "枚举子集时漏掉空集或全集",
                                "子集循环的初值、终止条件或 do-while 写法不对，导致空集、全集或最后一个子集没有被处理。",
                                "只关注非空中间状态，没有把边界集合当成合法状态。",
                                "BOUNDARY",
                                List.of("MATH.BIT.MASK.枚举子集", "MATH.BIT.MASK.位数限制"),
                                List.of("BASIC.LOOP.BOUNDARY.最后一次迭代"),
                                "HIGH"),
                        m("MP_V13_BITWISE_PRECEDENCE_CHANGES_MASK_TEST",
                                "位运算判断缺少括号导致条件含义改变",
                                "表达式混合 ==、&、| 或移位时未加括号，实际判断顺序和想检查的某一位不同。",
                                "把位运算表达式按口头含义阅读，没有按语言优先级拆分。",
                                "LOGIC",
                                List.of("MATH.BIT.OP.取某一位", "BASIC.EXPR.PRIORITY.位运算优先级"),
                                List.of("BASIC.EXPR.PRIORITY.括号明确意图"),
                                "HIGH")),
                "IP_V13_BITMASK_MAPPING_CARD",
                "用位映射卡检查编号、范围和每次转移",
                "适用于学生想用状态压缩，但编号偏移、子集边界或位判断表达式不稳定。",
                "修复后让学生写出元素到位的映射表、合法 mask 范围、空集全集样例和每条转移公式。",
                "教师可用映射卡判断错误来自编号、枚举边界还是表达式优先级。",
                List.of("MP_V13_BITMASK_SHIFT_USES_ONE_BASED_INDEX", "MP_V13_BITWISE_PRECEDENCE_CHANGES_MASK_TEST"));
    }

    private static void addShortestPath(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_SHORTEST_DISTANCE_RELAXATION_CONTRACT",
                "能力点/V13最短路距离维护",
                "维护距离初始化、边权限制、松弛操作和过期队列项契约",
                "能根据边权选择 BFS 或 Dijkstra，定义 dist 的含义，并在每次松弛后保证队列或堆中的状态与最新距离一致。",
                "写最短路前先说明边权是否相同、dist 初值、松弛条件和旧堆项如何跳过。",
                List.of("ALGO.GRAPH.SHORTEST.BFS_最短路", "ALGO.GRAPH.SHORTEST.Dijkstra",
                        "ALGO.GRAPH.SHORTEST.负权限制", "ALGO.GRAPH.SHORTEST.距离初始化",
                        "ALGO.GRAPH.SHORTEST.松弛操作"),
                List.of("DS.GRAPH.MODEL.权值含义"),
                "HIGH",
                List.of(
                        m("MP_V13_SHORTEST_DISTANCE_INITIALIZED_TO_ZERO_FOR_ALL_NODES",
                                "最短路距离把所有点初始化为 0",
                                "除起点外的节点本应不可达或无穷大，但代码全设为 0，松弛时无法区分已到达和未到达。",
                                "把默认值当成方便初值，没有用 dist 表达从起点到当前点的最短已知距离。",
                                "INITIALIZATION",
                                List.of("ALGO.GRAPH.SHORTEST.距离初始化", "ALGO.DP.INIT.无穷大"),
                                List.of("DS.GRAPH.MODEL.点的定义"),
                                "HIGH"),
                        m("MP_V13_DIJKSTRA_PROCESSES_STALE_HEAP_ENTRY",
                                "Dijkstra 没有跳过堆中的过期距离",
                                "同一个点被多次入堆后，代码处理了较旧的较大距离，继续扩展出错误路径或大量无效松弛。",
                                "只知道距离变小就入堆，没有检查出堆距离是否仍等于当前 dist。",
                                "STATE",
                                List.of("ALGO.GRAPH.SHORTEST.Dijkstra", "ALGO.GRAPH.SHORTEST.松弛操作"),
                                List.of("ALGO.GREEDY.STRUCTURE.优先队列辅助"),
                                "HIGH"),
                        m("MP_V13_SHORTEST_NEGATIVE_EDGE_USES_DIJKSTRA",
                                "含负权边时仍使用 Dijkstra",
                                "图中存在负边或边权会变负，但代码仍按最小堆贪心确定最短距离，导致已确定节点后续又被更短路径更新。",
                                "只看到是最短路题，没有先检查边权限制是否满足 Dijkstra 前提。",
                                "MODELING",
                                List.of("ALGO.GRAPH.SHORTEST.负权限制", "DS.GRAPH.MODEL.权值含义"),
                                List.of("CONTEST.READING.CONSTRAINT.隐藏特殊条件"),
                                "HIGH")),
                "IP_V13_SHORTEST_DISTANCE_TRACE",
                "用最短路距离追踪表复核初始化、松弛和过期项",
                "适用于学生会套 BFS 或 Dijkstra，但距离初值、负权判断或堆中旧状态处理出错。",
                "修复后让学生记录每次出队点、出队距离、当前 dist、被松弛边和是否跳过过期项。",
                "教师可用追踪表判断错误来自算法选择、初始化还是松弛状态维护。",
                List.of("MP_V13_SHORTEST_DISTANCE_INITIALIZED_TO_ZERO_FOR_ALL_NODES", "MP_V13_DIJKSTRA_PROCESSES_STALE_HEAP_ENTRY"));
    }

    private static void addEnumerationPruning(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_ENUMERATION_PRUNING_CONTRACT",
                "能力点/V13枚举范围与剪枝",
                "维护枚举对象、去重策略、剪枝安全性和复杂度边界契约",
                "能说明枚举的是对象、位置还是选择序列，判断剪枝条件是否只删除不可能分支，并根据数据范围估算复杂度。",
                "写枚举前先列枚举对象、合法范围、去重依据、剪枝条件和最坏分支数。",
                List.of("ALGO.ENUM.LOOP.枚举对象", "ALGO.ENUM.LOOP.枚举范围",
                        "ALGO.ENUM.LOOP.去重枚举", "ALGO.ENUM.PRUNE.不可能条件",
                        "ALGO.ENUM.PRUNE.重复状态跳过", "ALGO.ENUM.COMPLEXITY.指数枚举"),
                List.of("CONTEST.READING.CONSTRAINT.数据范围"),
                "HIGH",
                List.of(
                        m("MP_V13_ENUMERATES_POSITION_WHEN_OBJECT_IDENTITY_REQUIRED",
                                "需要按对象去重却按位置枚举",
                                "多个位置代表同一个值或同一类对象时，代码按下标组合枚举，生成重复方案或重复计数。",
                                "没有区分位置不同和对象不同，把数组下标当成题目对象身份。",
                                "MODELING",
                                List.of("ALGO.ENUM.LOOP.枚举对象", "ALGO.ENUM.LOOP.去重枚举"),
                                List.of("DS.SET_MAP.SET.去重"),
                                "HIGH"),
                        m("MP_V13_PRUNE_CONDITION_REMOVES_POSSIBLE_ANSWER",
                                "剪枝条件过强删掉了可能答案",
                                "当前状态看似不优，但后续仍可能通过负数、排序变化或额外选择变成合法答案，代码提前返回导致漏解。",
                                "把当前局部状态当成最终结论，没有证明剪掉的分支一定不可能变好。",
                                "LOGIC",
                                List.of("ALGO.ENUM.PRUNE.不可能条件", "ALGO.ENUM.PRUNE.当前最优界"),
                                List.of("ALGO.GREEDY.CHOICE.反例检查"),
                                "HIGH"),
                        m("MP_V13_ENUM_COMPLEXITY_IGNORES_NESTED_BRANCH_FACTOR",
                                "枚举复杂度只看循环层数漏算分支数",
                                "递归、组合或排列枚举中，每层分支数相乘后超过限制，但代码只把它估成一两重循环。",
                                "没有把选择数、递归深度和去重前分支数一起估算。",
                                "COMPLEXITY",
                                List.of("ALGO.ENUM.COMPLEXITY.指数枚举", "ENG.COMPLEXITY.TIME.数据范围反推"),
                                List.of("CONTEST.PATTERN.RANGE.指数搜索边界"),
                                "HIGH")),
                "IP_V13_ENUMERATION_DECISION_TREE",
                "用枚举决策树检查对象、去重、剪枝和复杂度",
                "适用于学生能写暴力搜索，但容易重复计数、错误剪枝或低估复杂度。",
                "修复后让学生画前三层决策树，标出每层候选数、去重规则和剪枝原因。",
                "教师可用决策树判断错误来自建模对象、剪枝证明还是复杂度估算。",
                List.of("MP_V13_ENUMERATES_POSITION_WHEN_OBJECT_IDENTITY_REQUIRED", "MP_V13_PRUNE_CONDITION_REMOVES_POSSIBLE_ANSWER"));
    }

    private static void addFunctionParameters(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_FUNCTION_PARAMETER_SIDE_EFFECT_CONTRACT",
                "能力点/V13函数参数与副作用",
                "维护值传递、引用传递、可变对象和返回结果契约",
                "能判断函数参数是否会修改调用者状态，区分输入、输出和临时工作变量，并用返回值或副作用表达清楚结果来源。",
                "写函数前先标注每个参数是只读输入、会被修改的输出，还是函数内部临时状态。",
                List.of("BASIC.FUNCTION.DEF.参数设计", "BASIC.FUNCTION.PARAM.值传递",
                        "BASIC.FUNCTION.PARAM.引用传递", "BASIC.FUNCTION.PARAM.数组参数",
                        "BASIC.FUNCTION.PARAM.可变对象风险"),
                List.of("BASIC.TYPE.VARIABLE.作用域"),
                "MEDIUM",
                List.of(
                        m("MP_V13_FUNCTION_EXPECTS_CALLER_STATE_CHANGE_FROM_VALUE_PARAM",
                                "以为值传递参数会修改调用者变量",
                                "函数内部改变了形参，但调用处的原变量没有变化，后续代码仍使用旧值。",
                                "把形参名字和调用者变量看成同一个存储位置，没有区分值拷贝和引用。",
                                "STATE",
                                List.of("BASIC.FUNCTION.PARAM.值传递", "BASIC.FUNCTION.DEF.参数设计"),
                                List.of("BASIC.TYPE.VARIABLE.作用域"),
                                "MEDIUM"),
                        m("MP_V13_FUNCTION_MUTABLE_PARAM_REUSED_ACROSS_BRANCHES",
                                "可变参数在多个分支间残留修改",
                                "列表、数组或容器作为参数传入后被函数修改，另一个分支或下一次调用继续看到被污染的状态。",
                                "只关注函数当前返回结果，没有说明传入对象是否会被原地改动。",
                                "STATE",
                                List.of("BASIC.FUNCTION.PARAM.可变对象风险", "BASIC.FUNCTION.PARAM.数组参数"),
                                List.of("BASIC.ARRAY.UPDATE.原地修改"),
                                "HIGH"),
                        m("MP_V13_FUNCTION_OUTPUT_AND_RETURN_MIXED",
                                "函数同时输出和返回导致调用方重复处理结果",
                                "函数内部已经打印或修改全局结果，调用方又根据返回值再次输出或累加，造成重复答案或格式错误。",
                                "没有约定结果是通过返回值、输出语句还是副作用传递。",
                                "MODELING",
                                List.of("BASIC.FUNCTION.RETURN.输出与返回分离", "BASIC.FUNCTION.RETURN.返回集合"),
                                List.of("ENG.STYLE.STRUCTURE.输出分离"),
                                "MEDIUM")),
                "IP_V13_FUNCTION_PARAMETER_CONTRACT_REVIEW",
                "用函数参数契约表分离输入、输出和临时状态",
                "适用于学生开始拆函数后，值传递、引用传递和可变对象副作用变得不稳定。",
                "修复后让学生给每个函数写参数用途、是否修改调用者、返回值含义和输出责任。",
                "教师可用契约表判断错误来自参数传递、状态污染还是输出返回混用。",
                List.of("MP_V13_FUNCTION_EXPECTS_CALLER_STATE_CHANGE_FROM_VALUE_PARAM", "MP_V13_FUNCTION_MUTABLE_PARAM_REUSED_ACROSS_BRANCHES"));
    }

    private static void addLinkedSimulation(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_LINKED_SIMULATION_BOUNDARY_CONTRACT",
                "能力点/V13链式下标模拟",
                "维护前驱后继、头尾节点、插入删除和边界节点契约",
                "能用数组或指针模拟链式结构，保证插入删除后前驱、后继、头尾和哨兵节点同步更新。",
                "写链式模拟前先画出被操作节点的前驱、后继和头尾变化。",
                List.of("DS.LINEAR.LIST.前驱后继", "DS.LINEAR.LIST.插入删除",
                        "DS.LINEAR.LIST.指针_下标模拟", "DS.LINEAR.LIST.头尾节点", "DS.LINEAR.LIST.边界节点"),
                List.of("BASIC.ARRAY.INDEX.下标映射"),
                "MEDIUM",
                List.of(
                        m("MP_V13_LINK_DELETE_UPDATES_ONLY_ONE_DIRECTION",
                                "链式删除只更新了前驱或后继一侧",
                                "删除中间节点时只改了 next 或 prev，另一侧仍指向被删节点，后续遍历出现断链、重复节点或死循环。",
                                "把删除看成移走当前点，没有同步维护相邻两个节点的互相指向。",
                                "STATE",
                                List.of("DS.LINEAR.LIST.前驱后继", "DS.LINEAR.LIST.插入删除"),
                                List.of("BASIC.ARRAY.UPDATE.累计量同步更新"),
                                "HIGH"),
                        m("MP_V13_LINK_HEAD_TAIL_NOT_UPDATED_ON_BOUNDARY_DELETE",
                                "删除头尾节点时没有更新边界指针",
                                "删除第一个或最后一个节点后，head 或 tail 仍指向旧节点，下一次插入、输出或遍历从错误位置开始。",
                                "只按中间节点模板写删除，没有把头尾作为单独边界状态。",
                                "BOUNDARY",
                                List.of("DS.LINEAR.LIST.头尾节点", "DS.LINEAR.LIST.边界节点"),
                                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                                "HIGH"),
                        m("MP_V13_LINK_INDEX_ZERO_USED_AS_REAL_NODE",
                                "哨兵下标和真实节点编号混用",
                                "使用 0、-1 或 n+1 表示空节点或哨兵，但后续访问时把它当作真实节点更新数据。",
                                "没有固定哪个编号代表不存在，哪个编号代表真实元素。",
                                "BOUNDARY",
                                List.of("DS.LINEAR.LIST.指针_下标模拟", "DS.LINEAR.LIST.边界节点"),
                                List.of("BASIC.ARRAY.INDEX.0_基下标"),
                                "HIGH")),
                "IP_V13_LINKED_POINTER_SNAPSHOT",
                "用前驱后继快照复盘每次链式操作",
                "适用于学生用数组模拟链表，但插入删除后链条断裂或边界节点失效。",
                "修复后让学生记录操作前后 prev、next、head、tail 和哨兵含义。",
                "教师可用快照判断错误来自单向更新、头尾边界还是哨兵混用。",
                List.of("MP_V13_LINK_DELETE_UPDATES_ONLY_ONE_DIRECTION", "MP_V13_LINK_HEAD_TAIL_NOT_UPDATED_ON_BOUNDARY_DELETE"));
    }

    private static void addGeometryDistance(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_GEOMETRY_COORD_DISTANCE_CONTRACT",
                "能力点/V13几何坐标距离",
                "维护行列坐标、x/y 坐标、距离公式和边界包含契约",
                "能区分矩阵行列与平面 x/y，选择曼哈顿、欧氏平方或切比雪夫距离，并判断边界点是否属于目标区域。",
                "写几何判断前先固定坐标顺序、距离类型、是否开闭边界和比较是否需要开方。",
                List.of("MATH.GEOMETRY.COORD.行列坐标", "MATH.GEOMETRY.COORD.x_y_坐标",
                        "MATH.GEOMETRY.DIST.曼哈顿距离", "MATH.GEOMETRY.DIST.欧氏距离平方",
                        "MATH.GEOMETRY.RELATION.边界包含"),
                List.of("BASIC.ARRAY.MATRIX.行列含义"),
                "MEDIUM",
                List.of(
                        m("MP_V13_GEOMETRY_ROW_COL_TREATED_AS_XY",
                                "把矩阵行列坐标当成平面 x/y 使用",
                                "移动方向、距离或输出坐标时把 row/col 与 x/y 互换，在非对称数据上方向和距离都错。",
                                "没有说明第一维是行还是横坐标，直接套用了平面坐标公式。",
                                "MODELING",
                                List.of("MATH.GEOMETRY.COORD.行列坐标", "MATH.GEOMETRY.COORD.x_y_坐标"),
                                List.of("BASIC.ARRAY.MATRIX.行列含义"),
                                "HIGH"),
                        m("MP_V13_GEOMETRY_USES_EUCLIDEAN_WHEN_MANHATTAN_REQUIRED",
                                "网格最短步数误用欧氏距离",
                                "只能上下左右移动或按网格步数计数时，代码使用直线距离或平方距离，低估实际步数。",
                                "看到坐标距离就套两点距离公式，没有根据允许移动方式选择距离模型。",
                                "MODELING",
                                List.of("MATH.GEOMETRY.DIST.曼哈顿距离", "MATH.GEOMETRY.DIST.欧氏距离平方"),
                                List.of("MATH.GEOMETRY.COORD.方向数组"),
                                "HIGH"),
                        m("MP_V13_GEOMETRY_BOUNDARY_POINT_EXCLUDED_BY_STRICT_COMPARE",
                                "边界点应包含却被严格比较排除",
                                "点刚好落在矩形边、圆周或区间端点上时，代码用严格不等号导致合法边界被判到外部。",
                                "没有把题目中的包含、覆盖、碰到边界转成 <= 或 >= 的测试点。",
                                "BOUNDARY",
                                List.of("MATH.GEOMETRY.RELATION.边界包含", "BASIC.EXPR.COMPARE.边界比较"),
                                List.of("BASIC.BRANCH.CASE.边界归属"),
                                "HIGH")),
                "IP_V13_GEOMETRY_COORD_CASE_SET",
                "用坐标距离样例组检查轴顺序、距离模型和边界",
                "适用于学生几何代码样例能过，但换成非对称坐标、网格移动或边界点就失败。",
                "修复后让学生构造三个样例：行列不相等、两种距离结果不同、点正好在边界上。",
                "教师可用样例组判断错误来自坐标系统、距离模型还是边界包含。",
                List.of("MP_V13_GEOMETRY_ROW_COL_TREATED_AS_XY", "MP_V13_GEOMETRY_BOUNDARY_POINT_EXCLUDED_BY_STRICT_COMPARE"));
    }

    private static void addPrimeFactorRange(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V13_PRIME_FACTOR_RANGE_CONTRACT",
                "能力点/V13质数因子范围",
                "维护质数判定、筛法边界、因子枚举和大数范围契约",
                "能根据数据范围选择试除、筛法或质因数分解，处理 1、平方根边界和大数乘法比较。",
                "写数论判断前先标出 n 的范围、是否多次查询、1 是否特殊、循环到 sqrt(n) 的包含关系。",
                List.of("MATH.NUMBER.PRIME.试除判定", "MATH.NUMBER.PRIME.筛法",
                        "MATH.NUMBER.PRIME.质因数分解", "MATH.NUMBER.PRIME.1_不是质数",
                        "MATH.NUMBER.DIVISIBILITY.平方根优化", "MATH.NUMBER.DIVISIBILITY.因子枚举"),
                List.of("BASIC.TYPE.INTEGER.long_long_范围"),
                "MEDIUM",
                List.of(
                        m("MP_V13_PRIME_ONE_CLASSIFIED_AS_PRIME",
                                "把 1 误判为质数",
                                "质数判断只检查能否被 2 到 sqrt(n) 整除，n=1 时循环不执行，直接返回真。",
                                "只记得没有其他因子就是质数，没有把质数必须大于 1 写成前置条件。",
                                "BOUNDARY",
                                List.of("MATH.NUMBER.PRIME.1_不是质数", "MATH.NUMBER.PRIME.试除判定"),
                                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                                "HIGH"),
                        m("MP_V13_FACTOR_LOOP_STOPS_BEFORE_SQUARE_ROOT",
                                "因子枚举漏掉平方根边界",
                                "循环条件使用 i * i < n，完全平方数的平方根因子没有被检查，质数判断或约数计数错误。",
                                "把小于平方根和不超过平方根混在一起，没有用完全平方数样例验证。",
                                "BOUNDARY",
                                List.of("MATH.NUMBER.DIVISIBILITY.平方根优化", "MATH.NUMBER.DIVISIBILITY.完全平方"),
                                List.of("BASIC.EXPR.COMPARE.边界比较"),
                                "HIGH"),
                        m("MP_V13_SIEVE_MARKS_FROM_TOO_SMALL_OR_TOO_LARGE_START",
                                "筛法标记起点错误导致漏筛或重复超时",
                                "埃氏筛从错误位置开始标记倍数，可能把质数自身标掉、漏掉平方起点前的合数，或重复做大量无效标记。",
                                "只知道要标记倍数，没有区分从 2p 还是 p*p 开始的含义和边界。",
                                "COMPLEXITY",
                                List.of("MATH.NUMBER.PRIME.筛法", "MATH.NUMBER.PRIME.大数范围"),
                                List.of("ENG.COMPLEXITY.TIME.数据范围反推"),
                                "MEDIUM")),
                "IP_V13_NUMBER_THEORY_BOUNDARY_SET",
                "用数论边界样例组复核 1、完全平方和多次查询",
                "适用于学生会写试除或筛法，但 1、平方根边界、筛法起点和大数范围经常错。",
                "修复后让学生固定测试 1、2、完全平方数、大质数和多次查询上限。",
                "教师可用样例组判断错误来自特殊值、边界比较还是算法选择。",
                List.of("MP_V13_PRIME_ONE_CLASSIFIED_AS_PRIME", "MP_V13_FACTOR_LOOP_STOPS_BEFORE_SQUARE_ROOT"));
    }

    private static MistakeSpec m(String code,
                                 String name,
                                 String description,
                                 String misconception,
                                 String mistakeType,
                                 List<String> knowledgeNodeCodes,
                                 List<String> prerequisites,
                                 String severity) {
        return new MistakeSpec(code, name, description, misconception, mistakeType,
                knowledgeNodeCodes, prerequisites, severity);
    }

    private static void addTheme(List<AiStandardLibrarySeed> seeds,
                                 String skillCode,
                                 String category,
                                 String skillName,
                                 String skillDescription,
                                 String learningGoal,
                                 List<String> skillKnowledgeNodes,
                                 List<String> skillPrerequisites,
                                 String severity,
                                 List<MistakeSpec> mistakes,
                                 String improvementCode,
                                 String improvementName,
                                 String improvementDescription,
                                 String studentBenefit,
                                 String teacherExplanation,
                                 List<String> relatedMistakeCodes) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                skillCode,
                category,
                skillName,
                skillDescription,
                learningGoal,
                skillKnowledgeNodes,
                skillPrerequisites,
                severity,
                LANGUAGES);
        mistakes.forEach(mistake -> AiStandardLibrarySeedCatalog.mistake(seeds,
                mistake.code(),
                category.replace("能力点/", "易错点/"),
                mistake.name(),
                mistake.description(),
                mistake.misconception(),
                skillCode,
                mistake.mistakeType(),
                mistake.knowledgeNodeCodes(),
                mistake.prerequisites(),
                mistake.severity(),
                LANGUAGES));
        seeds.add(new AiStandardLibrarySeed(
                AiStandardLibraryLayer.IMPROVEMENT_POINT,
                improvementCode,
                category.replace("能力点/", "提升点/"),
                improvementName,
                improvementDescription,
                "",
                teacherExplanation,
                skillCode,
                "",
                "",
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                improvementDescription,
                studentBenefit,
                "",
                "",
                "",
                skillCode,
                "MEDIUM",
                LANGUAGES,
                relatedMistakeCodes,
                skillKnowledgeNodes,
                skillPrerequisites,
                "通过边界样例、状态表或检查表把错误点转化为可迁移的解题习惯。",
                AiStandardLibrarySeedCatalog.VERSION
        ));
    }

    private record MistakeSpec(
            String code,
            String name,
            String description,
            String misconception,
            String mistakeType,
            List<String> knowledgeNodeCodes,
            List<String> prerequisites,
            String severity
    ) {
    }
}
