package com.onlinejudge.learning.standardlibrary.application;

import com.onlinejudge.learning.standardlibrary.domain.AiStandardLibraryLayer;

import java.util.List;

final class AiStandardLibraryV11AbsorptionSeeds {

    private static final List<String> LANGUAGES = List.of("PYTHON", "CPP17");

    private AiStandardLibraryV11AbsorptionSeeds() {
    }

    static void addTo(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V11_INPUT_BLOCK_CONTRACT",
                "能力点/兜底吸收-输入结构",
                "维护输入块、EOF 和混合读取契约",
                "能把题面输入拆成外层组数、每组字段、矩阵或字符串块、EOF 终止和混合类型读取，并保证读取次数和输出次数一致。",
                "写读取代码前先画输入块：每一层循环读什么、读几次、何时结束。",
                List.of("BASIC.IO.STDIN.多行读取", "BASIC.IO.STDIN.读到文件结束", "BASIC.IO.STDIN.混合数字与字符串读取", "BASIC.IO.STDIN.输入顺序映射"),
                List.of("CONTEST.READING.INPUT.数据组数"),
                "HIGH",
                List.of(
                        m("MP_V11_INPUT_BLOCK_LOOP_COUNT_MISMATCH",
                                "输入块循环次数和题面层级不一致",
                                "题面给出 T、n、q 或矩阵行列，但代码只按其中一层循环读取，导致后续字段错位或输出次数不匹配。",
                                "把样例里的行数当成固定结构，没有把每个控制变量绑定到对应读取循环。",
                                "IO_FORMAT",
                                List.of("BASIC.IO.STDIN.输入顺序映射", "CONTEST.READING.INPUT.数据组数", "BASIC.IO.MULTI_CASE.显式_T_组循环"),
                                List.of("BASIC.LOOP.FOR.循环次数计算"),
                                "HIGH"),
                        m("MP_V11_EOF_READING_STOPS_TOO_EARLY",
                                "读到文件结束场景提前停止或多读一行",
                                "题面要求处理到 EOF，但代码用固定次数、空行判断或单次读取结束流程，导致最后一组漏处理或多处理无效行。",
                                "没有区分 EOF、空行和本组数据结束，把本地样例结束方式当成通用规则。",
                                "IO_FORMAT",
                                List.of("BASIC.IO.STDIN.读到文件结束", "BASIC.IO.STDIN.多行读取"),
                                List.of("CONTEST.READING.INPUT.数据组数"),
                                "MEDIUM"),
                        m("MP_V11_MIXED_NUMERIC_STRING_READ_DESYNC",
                                "数字和字符串混合读取导致字段错位",
                                "数字读取后紧接整行字符串、含空格字段或字符块时，代码没有处理换行残留或分隔方式，导致字符串读成空行或少字段。",
                                "把所有输入都当作空格分隔 token，没有检查题面是否要求整行读取或保留空格。",
                                "IO_FORMAT",
                                List.of("BASIC.IO.STDIN.混合数字与字符串读取", "BASIC.STRING.CHAR.特殊字符处理"),
                                List.of("BASIC.IO.STDIN.多值同行读取"),
                                "HIGH")),
                "IP_V11_INPUT_BLOCK_READING_MAP",
                "用输入块地图复核读入和输出次数",
                "适用于学生经常读错 T、q、矩阵行列、EOF 或混合字符串输入。",
                "修复后让学生写出每个读取循环的控制变量、读入字段、输出动作和结束条件。",
                "教师可用输入块地图判断学生是在改算法，还是其实还没读对题目给的数据。",
                List.of("MP_V11_INPUT_BLOCK_LOOP_COUNT_MISMATCH", "MP_V11_MIXED_NUMERIC_STRING_READ_DESYNC"));

        addTheme(seeds,
                "SK_V11_CHAR_CONVERSION_CONTRACT",
                "能力点/兜底吸收-字符转换",
                "维护字符编码、数字字符和布尔含义契约",
                "能区分字符本身、字符编码、数字字符转数值和布尔真假含义，避免把显示形式和计算值混在一起。",
                "字符题先写三列：读到的字符、它的编码或数值、题目真正需要比较的含义。",
                List.of("BASIC.TYPE.CHAR_BOOL.字符编码", "BASIC.TYPE.CHAR_BOOL.字符数字转换", "BASIC.TYPE.CHAR_BOOL.真假值隐式转换", "BASIC.STRING.CHAR.数字字符转换"),
                List.of("BASIC.EXPR.COMPARE.字符比较"),
                "MEDIUM",
                List.of(
                        m("MP_V11_DIGIT_CHAR_USED_AS_NUMBER",
                                "数字字符直接当数值参与计算",
                                "代码把 '7' 或字符数组中的数字位直接加减乘除，没有先转成 7，导致字符编码值或字符串拼接结果进入计算。",
                                "看到字符长得像数字就当成数值，没有区分字符编码和整数值。",
                                "VALUE_RANGE",
                                List.of("BASIC.TYPE.CHAR_BOOL.字符数字转换", "BASIC.STRING.CHAR.数字字符转换"),
                                List.of("BASIC.TYPE.INTEGER.int_范围"),
                                "HIGH"),
                        m("MP_V11_CHAR_CASE_COMPARE_IGNORES_NORMALIZATION",
                                "大小写或编码比较前没有统一标准",
                                "题目要求大小写无关、字母范围或字符顺序判断，但代码直接比较原字符，使大小写、编码顺序或特殊字符破坏判断。",
                                "只看样例字符，没有先说明比较前是否需要统一大小写或过滤非目标字符。",
                                "LOGIC",
                                List.of("BASIC.STRING.CHAR.大小写转换", "BASIC.TYPE.CHAR_BOOL.字符编码", "BASIC.EXPR.COMPARE.字符比较"),
                                List.of("BASIC.STRING.CHAR.字母判断"),
                                "MEDIUM"),
                        m("MP_V11_BOOL_CHAR_TRUTHINESS_MIXED",
                                "字符真假值和题目布尔含义混用",
                                "代码用字符是否非空、是否为 '0' 或是否等于某个字符直接代表真假，但题目定义的有效/无效条件并不等同。",
                                "把语言里的 truthy/falsy 规则当成题目规则，没有显式写出布尔变量的来源。",
                                "LOGIC",
                                List.of("BASIC.TYPE.CHAR_BOOL.真假值隐式转换", "BASIC.TYPE.CHAR_BOOL.布尔表达式", "BASIC.TYPE.CHAR_BOOL.逻辑标志变量"),
                                List.of("BASIC.EXPR.LOGIC.条件组合"),
                                "MEDIUM")),
                "IP_V11_CHAR_VALUE_TABLE",
                "用字符值表区分显示字符、编码和题意数值",
                "适用于学生在字符数字转换、大小写判断或布尔标志上反复混淆。",
                "修复后让学生列出样例中每个关键字符的原字符、编码/数值、题目含义和代码比较条件。",
                "教师可用字符值表快速定位错误来自转换、比较还是布尔解释。",
                List.of("MP_V11_DIGIT_CHAR_USED_AS_NUMBER", "MP_V11_BOOL_CHAR_TRUTHINESS_MIXED"));

        addTheme(seeds,
                "SK_V11_EXPRESSION_PRIORITY_CONTRACT",
                "能力点/兜底吸收-表达式优先级",
                "维护算术、逻辑、位运算和复合赋值优先级",
                "能判断复杂表达式中每一步实际先算什么，并用括号或拆分变量表达题意。",
                "表达式超过两个运算符时先写计算顺序，再决定是否加括号或拆成中间变量。",
                List.of("BASIC.EXPR.PRIORITY.算术优先级", "BASIC.EXPR.PRIORITY.逻辑优先级", "BASIC.EXPR.PRIORITY.位运算优先级", "BASIC.EXPR.PRIORITY.括号明确意图"),
                List.of("BASIC.EXPR.ARITH.复合赋值"),
                "HIGH",
                List.of(
                        m("MP_V11_ARITH_PRIORITY_CHANGES_FORMULA",
                                "算术优先级让公式含义偏离题意",
                                "题意中的整体平均、比例或括号内差值被直接写成线性表达式，乘除加减顺序改变了公式含义。",
                                "按口头公式从左到右写代码，没有把题面里的整体量用括号保护。",
                                "VALUE_RANGE",
                                List.of("BASIC.EXPR.PRIORITY.算术优先级", "BASIC.EXPR.PRIORITY.括号明确意图", "BASIC.EXPR.ARITH.加减乘除顺序"),
                                List.of("BASIC.TYPE.FLOAT.整数除法误用"),
                                "HIGH"),
                        m("MP_V11_BIT_PRIORITY_COMPARE_BEFORE_SHIFT",
                                "位运算和比较优先级混淆",
                                "代码在判断某一位、构造 mask 或组合状态时缺少括号，使比较、移位、按位与的实际顺序和预期不同。",
                                "只记住位运算符号，没有确认它和比较、加减之间谁先执行。",
                                "LOGIC",
                                List.of("BASIC.EXPR.PRIORITY.位运算优先级", "MATH.BIT.OP.取某一位", "MATH.BIT.MASK.状态判断"),
                                List.of("BASIC.EXPR.PRIORITY.括号明确意图"),
                                "HIGH"),
                        m("MP_V11_COMPOUND_ASSIGNMENT_REUSES_UPDATED_VALUE",
                                "复合赋值中误用已更新的新值",
                                "代码用 +=、*= 或链式赋值更新多个变量时，后一个表达式读取到已经变化的值，破坏原本需要的旧值关系。",
                                "把复合赋值当作简写，没有检查右侧表达式依赖的是旧值还是新值。",
                                "STATE",
                                List.of("BASIC.EXPR.ARITH.复合赋值", "BASIC.TYPE.VARIABLE.赋值覆盖", "BASIC.EXPR.PRIORITY.表达式拆分"),
                                List.of("BASIC.ARRAY.UPDATE.读旧写新分离"),
                                "MEDIUM")),
                "IP_V11_EXPRESSION_EVALUATION_TRACE",
                "用表达式求值轨迹检查括号和旧值依赖",
                "适用于学生写出一行很长的公式、位运算判断或复合赋值后结果不稳定。",
                "修复后让学生把表达式拆成每一步实际求值顺序，并标出哪些变量必须读取旧值。",
                "教师可用求值轨迹判断学生是否真正理解代码实际执行顺序。",
                List.of("MP_V11_ARITH_PRIORITY_CHANGES_FORMULA", "MP_V11_BIT_PRIORITY_COMPARE_BEFORE_SHIFT"));

        addTheme(seeds,
                "SK_V11_STRING_SLICE_MATCH_CONTRACT",
                "能力点/兜底吸收-字符串切片匹配",
                "维护子串起止、未找到哨兵和重叠匹配契约",
                "能说明子串起点、终点、长度参数、空串和未找到返回值，并判断匹配是否允许重叠。",
                "字符串题先画位置轴：字符下标、切片区间、返回位置和下一次搜索起点。",
                List.of("BASIC.STRING.SUBSTRING.起止位置", "BASIC.STRING.SUBSTRING.长度参数", "BASIC.STRING.MATCH.未找到结果哨兵", "BASIC.STRING.MATCH.重叠匹配计数"),
                List.of("BASIC.ARRAY.INDEX.0_基下标"),
                "HIGH",
                List.of(
                        m("MP_V11_SUBSTRING_LENGTH_TREATED_AS_END_INDEX",
                                "子串长度参数被当作结束下标",
                                "在 C++ substr 或类似接口中把第二个参数当成右端下标，导致子串过长、过短或越界。",
                                "记住了要截取到某个位置，但没有区分长度参数和结束位置。",
                                "BOUNDARY",
                                List.of("BASIC.STRING.SUBSTRING.长度参数", "BASIC.STRING.SUBSTRING.起止位置", "BASIC.STRING.SUBSTRING.Python_CPP_切片差异"),
                                List.of("BASIC.ARRAY.INDEX.长度与最后下标"),
                                "HIGH"),
                        m("MP_V11_FIND_NOT_FOUND_SENTINEL_REUSED_AS_POSITION",
                                "未找到哨兵值被继续当作有效位置",
                                "find/index 查询没有命中时，代码仍用返回值切片、访问或继续搜索，导致越界、异常或错误计数。",
                                "只在样例命中时测试，没有单独处理未找到分支。",
                                "RUNTIME",
                                List.of("BASIC.STRING.MATCH.未找到结果哨兵", "BASIC.STRING.SUBSTRING.越界保护"),
                                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                                "HIGH"),
                        m("MP_V11_OVERLAP_MATCH_COUNT_SKIPS_VALID_START",
                                "重叠匹配时下一次搜索起点推进过远",
                                "统计出现次数或查找所有位置时，每次命中后直接跳过整个模式串，漏掉允许重叠的匹配。",
                                "默认匹配之间不能重叠，没有按题意确认下一次搜索应该从哪里开始。",
                                "BOUNDARY",
                                List.of("BASIC.STRING.MATCH.重叠匹配计数", "BASIC.STRING.MATCH.查找出现位置"),
                                List.of("BASIC.STRING.MATCH.逐位比较"),
                                "MEDIUM")),
                "IP_V11_STRING_POSITION_AXIS",
                "用字符串位置轴复核切片和匹配推进",
                "适用于学生在子串长度、未找到返回值或重叠匹配上反复漏边界。",
                "修复后让学生画出字符下标、每次切片区间、find 返回值和下一轮起点。",
                "教师可用位置轴判断学生是否混淆了右端点、长度和有效位置。",
                List.of("MP_V11_SUBSTRING_LENGTH_TREATED_AS_END_INDEX", "MP_V11_FIND_NOT_FOUND_SENTINEL_REUSED_AS_POSITION"));

        addTheme(seeds,
                "SK_V11_MATRIX_COORDINATE_CONTRACT",
                "能力点/兜底吸收-矩阵坐标",
                "维护行列、方向偏移和矩阵输入契约",
                "能区分 row/col、x/y、矩阵行列规模、方向数组顺序和边界检查位置。",
                "二维题先写坐标约定：第一维是什么、第二维是什么、方向数组如何改变它们。",
                List.of("BASIC.ARRAY.MATRIX.行列含义", "BASIC.ARRAY.MATRIX.矩阵输入", "BASIC.ARRAY.MATRIX.方向遍历", "BASIC.ARRAY.MATRIX.边界检查"),
                List.of("BASIC.ARRAY.INDEX.下标映射"),
                "HIGH",
                List.of(
                        m("MP_V11_MATRIX_ROW_COL_SWAPPED_IN_ACCESS",
                                "矩阵访问时行列下标交换",
                                "读入或遍历时用 grid[col][row] 访问二维数组，使非方阵、边界行列或方向移动时结果错误。",
                                "把 x/y 直觉直接套到数组下标，没有确认第一维代表行还是列。",
                                "BOUNDARY",
                                List.of("BASIC.ARRAY.MATRIX.行列含义", "BASIC.ARRAY.MATRIX.坐标转换"),
                                List.of("BASIC.ARRAY.INDEX.0_基下标"),
                                "HIGH"),
                        m("MP_V11_DIRECTION_DELTA_ORDER_REVERSED",
                                "方向数组的行列增量顺序写反",
                                "方向遍历中 dr/dc 或 dx/dy 对应关系反了，导致向上、向下、左右移动落到错误位置。",
                                "只背了方向数组模板，没有把每个方向代入一个坐标验证。",
                                "STATE",
                                List.of("BASIC.ARRAY.MATRIX.方向遍历", "BASIC.ARRAY.MATRIX.边界检查"),
                                List.of("BASIC.LOOP.NESTED.内外层变量区分"),
                                "HIGH"),
                        m("MP_V11_MATRIX_BOUNDARY_CHECK_AFTER_ACCESS",
                                "矩阵边界检查发生在访问之后",
                                "代码先访问 grid[nr][nc] 再判断坐标是否合法，使越界输入或边界移动直接触发运行错误。",
                                "以为 if 条件会保护访问，但危险访问已经发生在条件判断之前。",
                                "RUNTIME",
                                List.of("BASIC.ARRAY.MATRIX.边界检查", "BASIC.ARRAY.INDEX.越界访问"),
                                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                                "HIGH")),
                "IP_V11_MATRIX_COORDINATE_CARD",
                "用矩阵坐标卡片固定行列和方向含义",
                "适用于学生在二维数组、方向数组或非方阵输入中反复交换坐标。",
                "修复后让学生写出 row、col、x、y 各自含义，并用一个角落格子验证四个方向。",
                "教师可用坐标卡片判断错误来自输入维度、访问顺序还是方向增量。",
                List.of("MP_V11_MATRIX_ROW_COL_SWAPPED_IN_ACCESS", "MP_V11_DIRECTION_DELTA_ORDER_REVERSED"));

        addTheme(seeds,
                "SK_V11_GRAPH_EDGE_MODEL_CONTRACT",
                "能力点/兜底吸收-图边建模",
                "维护点边定义、有向无向和权值字段契约",
                "能把题面对象映射为点，把关系映射为边，并说明方向、权值、邻接结构和多组清空规则。",
                "建图前先写四句话：点是什么、边是什么、方向是什么、权值代表什么。",
                List.of("DS.GRAPH.MODEL.点的定义", "DS.GRAPH.MODEL.边的定义", "DS.GRAPH.MODEL.有向无向", "DS.GRAPH.MODEL.权值含义"),
                List.of("DS.GRAPH.STORE.邻接表"),
                "HIGH",
                List.of(
                        m("MP_V11_GRAPH_EDGE_DIRECTION_REVERSED_FROM_DEPENDENCY",
                                "依赖关系建边方向和题意相反",
                                "题面描述 A 依赖 B、A 到 B 或 B 先于 A 时，代码把边方向建反，导致遍历、拓扑或最短路含义错误。",
                                "只看文字中的先后顺序，没有说明边从前置条件指向结果，还是从当前对象指向依赖对象。",
                                "MODELING",
                                List.of("DS.GRAPH.MODEL.有向无向", "ALGO.GRAPH.TOPO.依赖关系", "DS.GRAPH.MODEL.边的定义"),
                                List.of("ALGO.GRAPH.TOPO.入度"),
                                "HIGH"),
                        m("MP_V11_UNDIRECTED_EDGE_ADDED_ONLY_ONE_WAY",
                                "无向边只加入单向邻接关系",
                                "题面是双向道路、互相可达或无向关系，但代码只添加 u 到 v，导致从 v 出发无法回到 u。",
                                "把输入的一行边当作一个方向，没有把无向关系展开成两条邻接记录。",
                                "MODELING",
                                List.of("DS.GRAPH.MODEL.有向无向", "DS.GRAPH.STORE.双向边添加", "DS.GRAPH.STORE.无向边双向建边"),
                                List.of("DS.GRAPH.STORE.邻接表"),
                                "HIGH"),
                        m("MP_V11_GRAPH_WEIGHT_FIELD_BOUND_TO_WRONG_VALUE",
                                "权值字段绑定到错误输入列或错误含义",
                                "输入边包含距离、费用、时间或容量时，代码把权值读错列、漏存或用节点编号当权值，导致路径代价失真。",
                                "只关注连通关系，没有单独确认边权代表什么以及存在哪个字段。",
                                "VALUE_RANGE",
                                List.of("DS.GRAPH.MODEL.权值含义", "DS.GRAPH.STORE.权值字段绑定"),
                                List.of("ALGO.GRAPH.SHORTEST.松弛操作"),
                                "HIGH")),
                "IP_V11_GRAPH_MODEL_SHEET",
                "用建图四问检查点、边、方向和权值",
                "适用于学生图算法模板会写，但建图方向、无向边或权值含义经常错。",
                "修复后让学生用一条样例边写出邻接表中实际保存的记录，并解释方向和权值。",
                "教师可用建图四问判断问题在模型，而不是在后面的图算法模板。",
                List.of("MP_V11_GRAPH_EDGE_DIRECTION_REVERSED_FROM_DEPENDENCY", "MP_V11_GRAPH_WEIGHT_FIELD_BOUND_TO_WRONG_VALUE"));

        addTheme(seeds,
                "SK_V11_RECURSION_BACKTRACK_CONTRACT",
                "能力点/兜底吸收-递归回溯",
                "维护递归出口、规模推进和回溯恢复契约",
                "能说明递归参数表示什么状态、每次调用如何靠近出口、边界返回值是什么，以及回溯后哪些状态必须恢复。",
                "递归题先画三层调用树，再标注出口、参数变化和恢复动作。",
                List.of("BASIC.RECURSION.BASE.终止条件", "BASIC.RECURSION.STATE.规模缩小", "BASIC.RECURSION.STATE.回溯恢复", "BASIC.RECURSION.BASE.边界返回值"),
                List.of("BASIC.FUNCTION.DEF.参数设计"),
                "HIGH",
                List.of(
                        m("MP_V11_RECURSION_PARAMETER_NOT_PROGRESSING",
                                "递归参数没有向终止条件推进",
                                "递归调用传入的下标、剩余规模或状态没有变小，也没有改变到更接近出口的方向，导致无限递归或重复搜索。",
                                "只写了递归调用形式，没有检查每条路径是否都能靠近终止条件。",
                                "RUNTIME",
                                List.of("BASIC.RECURSION.STATE.规模缩小", "BASIC.RECURSION.BASE.防止无限递归"),
                                List.of("BASIC.RECURSION.BASE.终止条件"),
                                "HIGH"),
                        m("MP_V11_BACKTRACK_STATE_NOT_RESTORED",
                                "回溯后选择状态没有恢复",
                                "递归分支里修改了 visited、路径、计数或棋盘状态，但返回上一层前没有撤销，导致后续分支继承错误状态。",
                                "以为递归返回会自动恢复所有变量，没有区分局部变量和共享可变状态。",
                                "STATE",
                                List.of("BASIC.RECURSION.STATE.回溯恢复", "ALGO.SEARCH.DFS.回溯恢复", "BASIC.FUNCTION.PARAM.可变对象风险"),
                                List.of("BASIC.TYPE.VARIABLE.作用域"),
                                "HIGH"),
                        m("MP_V11_RECURSION_BASE_RETURN_VALUE_INCONSISTENT",
                                "递归边界返回值和状态定义不一致",
                                "最小规模、空路径或非法状态的返回值没有对应状态定义，使计数、最值或可行性递归在边界处出错。",
                                "只关心递归式，没有先问出口那一刻应该返回什么含义。",
                                "INITIALIZATION",
                                List.of("BASIC.RECURSION.BASE.边界返回值", "BASIC.RECURSION.BASE.最小规模", "BASIC.RECURSION.BASE.多边界条件"),
                                List.of("ALGO.DP.INIT.初始值"),
                                "HIGH")),
                "IP_V11_RECURSION_CALL_TREE_REVIEW",
                "用三层调用树复盘出口、推进和恢复",
                "适用于学生递归会写但经常爆栈、漏解或回溯状态污染。",
                "修复后让学生画出前三层调用，标注每层参数变化、出口条件和返回前恢复动作。",
                "教师可用调用树判断学生是出口不清、参数不推进，还是共享状态未恢复。",
                List.of("MP_V11_RECURSION_PARAMETER_NOT_PROGRESSING", "MP_V11_BACKTRACK_STATE_NOT_RESTORED"));

        addTheme(seeds,
                "SK_V11_SUBMISSION_REVIEW_CONTRACT",
                "能力点/兜底吸收-提交复盘",
                "维护提交前检查、失败复盘和同类错因记录契约",
                "能在提交前检查样例、边界、初始化、输出、复杂度、多组状态和溢出风险，失败后能构造最小反例并记录同类错因。",
                "提交前先过七项清单；失败后先缩小反例，再决定改格式、边界、状态还是算法。",
                List.of("CONTEST.SUBMIT.CHECKLIST.样例复测", "CONTEST.SUBMIT.CHECKLIST.边界复测", "CONTEST.SUBMIT.CHECKLIST.复杂度检查", "CONTEST.SUBMIT.REVIEW.最小反例构造"),
                List.of("ENG.DEBUG.SAMPLE.最小反例"),
                "MEDIUM",
                List.of(
                        m("MP_V11_SUBMIT_ONLY_RETESTS_SAMPLE",
                                "提交前只复测样例没有覆盖边界",
                                "代码能通过公开样例，但提交前没有测试最小规模、重复值、多组数据、最大范围或特殊格式，隐藏数据暴露同类问题。",
                                "把样例通过当成一般正确，没有主动构造和样例结构不同的检查点。",
                                "DEBUGGING",
                                List.of("CONTEST.SUBMIT.CHECKLIST.样例复测", "CONTEST.SUBMIT.CHECKLIST.边界复测", "ENG.DEBUG.BOUNDARY.最小输入"),
                                List.of("CONTEST.READING.CONSTRAINT.隐藏特殊条件"),
                                "MEDIUM"),
                        m("MP_V11_SUBMIT_COMPLEXITY_CHECK_SKIPPED",
                                "提交前没有代入最大数据检查复杂度",
                                "样例运行很快，但提交前没有把最大 n、m、q 代入循环层数或状态数，导致大数据超时或超内存。",
                                "用本地小样例速度替代复杂度估算，没有看题面约束上限。",
                                "COMPLEXITY",
                                List.of("CONTEST.SUBMIT.CHECKLIST.复杂度检查", "CONTEST.READING.CONSTRAINT.数据范围", "ENG.COMPLEXITY.TIME.数据范围反推"),
                                List.of("ENG.COMPLEXITY.SPACE.数组规模"),
                                "HIGH"),
                        m("MP_V11_REVIEW_COUNTEREXAMPLE_NOT_RECORDED",
                                "失败后没有沉淀最小反例和同类错因",
                                "改代码时只追当前提交，没有记录触发错误的最小输入、首个偏差和对应知识点，后续题目继续重复同类错误。",
                                "把每次失败当成单题偶然问题，没有把反例转化为可迁移的检查项。",
                                "DEBUGGING",
                                List.of("CONTEST.SUBMIT.REVIEW.最小反例构造", "CONTEST.SUBMIT.REVIEW.同类错因记录", "CONTEST.SUBMIT.REVIEW.知识点回补"),
                                List.of("ENG.DEBUG.SAMPLE.最小反例"),
                                "MEDIUM")),
                "IP_V11_SUBMISSION_REVIEW_CARD",
                "用提交复盘卡连接检查清单和错因沉淀",
                "适用于学生能改过当前题，但下一题继续重复同类边界、复杂度或格式错误。",
                "修复后让学生填写失败输入、首个偏差、命中的知识点、修复动作和下次提交前检查项。",
                "教师可用复盘卡把一次失败沉淀成标准库成长或个人错因记忆。",
                List.of("MP_V11_SUBMIT_ONLY_RETESTS_SAMPLE", "MP_V11_REVIEW_COUNTEREXAMPLE_NOT_RECORDED"));
    }

    private static MistakeSpec m(String code,
                                 String name,
                                 String description,
                                 String misconception,
                                 String mistakeType,
                                 List<String> knowledgeNodeCodes,
                                 List<String> prerequisites,
                                 String severity) {
        return new MistakeSpec(code, name, description, misconception, mistakeType,
                knowledgeNodeCodes, prerequisites, severity);
    }

    private static void addTheme(List<AiStandardLibrarySeed> seeds,
                                 String skillCode,
                                 String category,
                                 String skillName,
                                 String skillDescription,
                                 String learningGoal,
                                 List<String> skillKnowledgeNodes,
                                 List<String> skillPrerequisites,
                                 String severity,
                                 List<MistakeSpec> mistakes,
                                 String improvementCode,
                                 String improvementName,
                                 String improvementDescription,
                                 String studentBenefit,
                                 String teacherExplanation,
                                 List<String> relatedMistakeCodes) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                skillCode,
                category,
                skillName,
                skillDescription,
                learningGoal,
                skillKnowledgeNodes,
                skillPrerequisites,
                severity,
                LANGUAGES);
        mistakes.forEach(mistake -> AiStandardLibrarySeedCatalog.mistake(seeds,
                mistake.code(),
                category.replace("能力点/", "易错点/"),
                mistake.name(),
                mistake.description(),
                mistake.misconception(),
                skillCode,
                mistake.mistakeType(),
                mistake.knowledgeNodeCodes(),
                mistake.prerequisites(),
                mistake.severity(),
                LANGUAGES));
        seeds.add(new AiStandardLibrarySeed(
                AiStandardLibraryLayer.IMPROVEMENT_POINT,
                improvementCode,
                category.replace("能力点/", "提升点/"),
                improvementName,
                improvementDescription,
                "",
                teacherExplanation,
                skillCode,
                "",
                "",
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                improvementDescription,
                studentBenefit,
                "",
                "",
                "",
                skillCode,
                "MEDIUM",
                LANGUAGES,
                relatedMistakeCodes,
                skillKnowledgeNodes,
                skillPrerequisites,
                "把兜底素材升级为手写智能条目后，用复盘练习巩固迁移能力。",
                AiStandardLibrarySeedCatalog.VERSION
        ));
    }

    private record MistakeSpec(
            String code,
            String name,
            String description,
            String misconception,
            String mistakeType,
            List<String> knowledgeNodeCodes,
            List<String> prerequisites,
            String severity
    ) {
    }
}
