package com.onlinejudge.learning.standardlibrary.application;

import com.onlinejudge.learning.standardlibrary.domain.AiStandardLibraryLayer;

import java.util.List;

final class AiStandardLibraryV9ExpansionSeeds {

    private static final List<String> LANGUAGES = List.of("PYTHON", "CPP17");

    private AiStandardLibraryV9ExpansionSeeds() {
    }

    static void addTo(List<AiStandardLibrarySeed> seeds) {
        addSlidingWindow(seeds);
        addDisjointSet(seeds);
        addBacktracking(seeds);
        addPriorityQueue(seeds);
        addTopologicalSort(seeds);
        addPrefixDiff(seeds);
        addBinaryAnswer(seeds);
        addTreeTraversal(seeds);
        addMapFrequency(seeds);
        addOutputConstruction(seeds);
    }

    private static void addSlidingWindow(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V9_WINDOW_VALIDITY_COUNT_CONTRACT",
                "能力点/滑动窗口细节",
                "维护滑动窗口的合法性、计数和答案时机",
                "能说明窗口左右端点表示的区间、哪些计数属于当前窗口、何时收缩窗口以及在收缩前还是收缩后更新答案。",
                "写滑动窗口前先定义窗口合法条件，再标出每次 right 扩张、left 收缩和答案更新的先后。",
                List.of("ALGO.TWO_POINTERS.WINDOW.窗口扩张", "ALGO.TWO_POINTERS.WINDOW.窗口收缩", "ALGO.TWO_POINTERS.WINDOW.计数维护", "ALGO.TWO_POINTERS.WINDOW.答案更新时机"),
                List.of("BASIC.ARRAY.INDEX.下标映射", "DS.SET_MAP.MAP.频次统计"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_WINDOW_SHRINKS_BEFORE_RECORDING_ANSWER",
                "易错点/滑动窗口细节",
                "窗口答案在错误时机更新",
                "题目要求记录当前合法窗口的长度、和或计数，但代码先移动 left 破坏当前窗口，再更新答案，导致最优窗口被漏掉。",
                "只记得窗口不合法就收缩，没有区分记录答案应该发生在合法窗口形成后还是收缩前。",
                "SK_V9_WINDOW_VALIDITY_COUNT_CONTRACT",
                "STATE",
                List.of("ALGO.TWO_POINTERS.WINDOW.答案更新时机", "ALGO.TWO_POINTERS.WINDOW.合法性判断"),
                List.of("BASIC.EXPR.COMPARE.边界比较"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_WINDOW_COUNT_NOT_DECREMENTED_ON_LEFT_MOVE",
                "易错点/滑动窗口细节",
                "左端移出窗口时计数没有同步减少",
                "left 向右移动后，频次、窗口和、不同元素数或违规数量仍保留被移出元素的贡献，后续合法性判断使用了过期状态。",
                "把 left 的移动当成下标变化，没有把窗口内统计量也视为同一份状态。",
                "SK_V9_WINDOW_VALIDITY_COUNT_CONTRACT",
                "STATE",
                List.of("ALGO.TWO_POINTERS.WINDOW.计数维护", "DS.SET_MAP.MAP.频次统计", "ALGO.TWO_POINTERS.WINDOW.窗口收缩"),
                List.of("BASIC.ARRAY.UPDATE.累计量同步更新"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_WINDOW_FIXED_LENGTH_TREATED_AS_VARIABLE",
                "易错点/滑动窗口细节",
                "定长窗口被写成可变窗口",
                "题目要求长度固定为 k 的连续区间，但代码只按合法性收缩窗口，没有保证窗口长度恰好等于 k，导致短窗口或长窗口参与答案。",
                "看到连续区间就套滑动窗口模板，没有先判断窗口长度是固定、至多还是至少。",
                "SK_V9_WINDOW_VALIDITY_COUNT_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.TWO_POINTERS.WINDOW.合法性判断", "BASIC.ARRAY.INDEX.长度与最后下标", "CONTEST.READING.CONSTRAINT.隐藏特殊条件"),
                List.of("BASIC.LOOP.BOUNDARY.最后一次迭代"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V9_WINDOW_TRACE_TABLE",
                "提升点/滑动窗口细节",
                "用窗口轨迹表复盘扩张、收缩和答案更新",
                "适用于学生能写出双指针框架，但经常搞混窗口边界、计数维护和答案更新时机。",
                "修复后让学生记录每一步 left、right、窗口内容、计数状态、是否合法和当前答案。",
                "教师可用轨迹表检查学生是否把窗口内状态和端点移动保持同步。",
                "SK_V9_WINDOW_VALIDITY_COUNT_CONTRACT",
                List.of("MP_V9_WINDOW_SHRINKS_BEFORE_RECORDING_ANSWER", "MP_V9_WINDOW_COUNT_NOT_DECREMENTED_ON_LEFT_MOVE"),
                List.of("ALGO.TWO_POINTERS.WINDOW.窗口扩张", "ALGO.TWO_POINTERS.WINDOW.计数维护"));
    }

    private static void addDisjointSet(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V9_DSU_PARENT_ROOT_CONTRACT",
                "能力点/并查集细节",
                "维护并查集的根、合并和连通性查询契约",
                "能区分节点编号、父节点、集合根和集合大小，所有连通性判断都通过 find 后的根来比较。",
                "并查集不是比较 parent 数组表面值，而是维护每个集合的代表根和合并后的不变量。",
                List.of("ALGO.GRAPH.CONNECT.并查集", "ALGO.GRAPH.CONNECT.路径压缩", "ALGO.GRAPH.CONNECT.合并方向", "ALGO.GRAPH.CONNECT.连通块"),
                List.of("BASIC.ARRAY.INDEX.下标映射", "DS.GRAPH.MODEL.点的定义"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_DSU_CHECKS_PARENT_WITHOUT_FIND",
                "易错点/并查集细节",
                "未调用 find 直接比较 parent 值",
                "代码用 parent[x] == parent[y] 判断连通性，但 parent 可能只是中间父节点，不一定是集合根，导致同一集合被误判为不连通。",
                "把 parent 数组当前值当作最终答案，没有意识到路径压缩前父链可能有多层。",
                "SK_V9_DSU_PARENT_ROOT_CONTRACT",
                "STATE",
                List.of("ALGO.GRAPH.CONNECT.并查集", "ALGO.GRAPH.CONNECT.路径压缩", "ALGO.GRAPH.CONNECT.连通块"),
                List.of("BASIC.FUNCTION.RETURN.返回集合"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_DSU_UNION_DIRECTION_BREAKS_SIZE",
                "易错点/并查集细节",
                "合并方向和集合大小维护不一致",
                "union 时把一个根挂到另一个根上，但 size、rank 或连通块数量更新到了错误根，后续按集合大小或数量判断时出错。",
                "只关注两个集合连起来了，没有固定谁成为新根以及派生信息跟随哪个根。",
                "SK_V9_DSU_PARENT_ROOT_CONTRACT",
                "STATE",
                List.of("ALGO.GRAPH.CONNECT.合并方向", "ALGO.GRAPH.CONNECT.连通块", "ALGO.GRAPH.CONNECT.并查集"),
                List.of("BASIC.ARRAY.UPDATE.累计量同步更新"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_DSU_REINITIALIZED_INSIDE_EDGE_LOOP",
                "易错点/并查集细节",
                "并查集在处理边的循环中被反复初始化",
                "parent 或 size 数组被放在读边、排序后遍历边或每次查询内部重新初始化，导致之前合并的信息全部丢失。",
                "没有区分每组数据初始化一次和每条边处理一次，把生命周期写进了过深的循环。",
                "SK_V9_DSU_PARENT_ROOT_CONTRACT",
                "INITIALIZATION",
                List.of("ALGO.GRAPH.CONNECT.并查集", "ALGO.GRAPH.MST.Kruskal", "BASIC.IO.MULTI_CASE.每组状态重置"),
                List.of("BASIC.LOOP.NESTED.重复初始化位置"),
                "HIGH",
                LANGUAGES);
        improvement(seeds,
                "IP_V9_DSU_COMPONENT_INVARIANT_CHECK",
                "提升点/并查集细节",
                "用根节点和连通块不变量检查并查集",
                "适用于学生能写出 find/union，但经常在连通性查询、size 维护或初始化位置上出错。",
                "修复后让学生列出每次 union 前后的 root、parent、size 和 componentCount。",
                "教师可要求学生解释任意时刻 parent、root 和集合大小分别代表什么。",
                "SK_V9_DSU_PARENT_ROOT_CONTRACT",
                List.of("MP_V9_DSU_CHECKS_PARENT_WITHOUT_FIND", "MP_V9_DSU_UNION_DIRECTION_BREAKS_SIZE"),
                List.of("ALGO.GRAPH.CONNECT.并查集", "ALGO.GRAPH.CONNECT.连通块"));
    }

    private static void addBacktracking(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V9_BACKTRACK_RESTORE_AND_PRUNE_CONTRACT",
                "能力点/递归回溯细节",
                "维护递归参数、选择恢复和剪枝位置",
                "能说明递归函数参数表示的状态、终止条件返回什么、选择后修改了哪些状态以及回溯时必须恢复哪些状态。",
                "回溯每做一次选择，就要能说清进入下一层前改变了什么，退出这一层后恢复什么。",
                List.of("BASIC.RECURSION.STATE.参数表示状态", "BASIC.RECURSION.STATE.回溯恢复", "ALGO.SEARCH.DFS.递归参数", "ALGO.SEARCH.DFS.剪枝位置"),
                List.of("BASIC.RECURSION.BASE.终止条件", "BASIC.ARRAY.UPDATE.原地修改"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_BACKTRACK_FORGETS_RESTORE_AFTER_CHOICE",
                "易错点/递归回溯细节",
                "递归返回后没有恢复选择前状态",
                "搜索分支中修改了 visited、路径、计数或当前和，但递归返回后没有撤销，导致兄弟分支继承了上一分支状态。",
                "只关注向下递归能否走通，没有把回到上一层后的状态恢复看成对称动作。",
                "SK_V9_BACKTRACK_RESTORE_AND_PRUNE_CONTRACT",
                "STATE",
                List.of("BASIC.RECURSION.STATE.回溯恢复", "ALGO.SEARCH.DFS.路径记录", "ALGO.SEARCH.DFS.递归参数"),
                List.of("BASIC.ARRAY.UPDATE.读旧写新分离"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_RECURSION_BASE_CASE_RETURNS_WRONG_VALUE",
                "易错点/递归回溯细节",
                "递归边界返回值和状态含义不一致",
                "递归到最小规模时返回了默认 0、空集合或 false，但当前状态定义要求返回 1、当前路径或 true，导致整棵递归结果偏差。",
                "把终止条件当成停止递归的符号，没有根据函数含义推导边界返回值。",
                "SK_V9_BACKTRACK_RESTORE_AND_PRUNE_CONTRACT",
                "BOUNDARY",
                List.of("BASIC.RECURSION.BASE.边界返回值", "BASIC.RECURSION.BASE.最小规模", "BASIC.FUNCTION.RETURN.返回布尔"),
                List.of("BASIC.RECURSION.BASE.终止条件"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_DFS_PRUNE_BEFORE_RECORDING_SOLUTION",
                "易错点/递归回溯细节",
                "剪枝位置放在记录答案之前",
                "当前状态已经构成合法答案，但代码先执行剪枝或越界返回，导致边界上的合法方案没有被记录。",
                "把所有提前返回都当成优化，没有区分答案检查、非法状态过滤和继续扩展的顺序。",
                "SK_V9_BACKTRACK_RESTORE_AND_PRUNE_CONTRACT",
                "LOGIC",
                List.of("ALGO.SEARCH.DFS.剪枝位置", "ALGO.SEARCH.DFS.搜索边界", "CONTEST.READING.OUTPUT.输出方案数"),
                List.of("ALGO.ENUM.PRUNE.提前终止"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V9_BACKTRACK_STATE_TABLE",
                "提升点/递归回溯细节",
                "用递归层级表检查选择、递归和恢复",
                "适用于学生能写 DFS，但经常在恢复状态、边界返回和剪枝位置上丢方案。",
                "修复后让学生为每一层写出参数、已选路径、进入前修改、返回后恢复和是否记录答案。",
                "教师可用层级表定位是状态污染、边界返回值错误还是剪枝顺序错误。",
                "SK_V9_BACKTRACK_RESTORE_AND_PRUNE_CONTRACT",
                List.of("MP_V9_BACKTRACK_FORGETS_RESTORE_AFTER_CHOICE", "MP_V9_DFS_PRUNE_BEFORE_RECORDING_SOLUTION"),
                List.of("BASIC.RECURSION.STATE.回溯恢复", "ALGO.SEARCH.DFS.剪枝位置"));
    }

    private static void addPriorityQueue(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V9_PRIORITY_QUEUE_ORDER_AND_LAZY_DELETE",
                "能力点/优先队列细节",
                "维护优先队列的排序键、弹出契约和过期状态过滤",
                "能说明堆里每个元素的优先级字段、弹出时是否仍有效，以及同一对象多次入堆时如何跳过过期状态。",
                "优先队列不是自动给出正确答案，弹出的元素必须先通过当前状态校验。",
                List.of("ALGO.GREEDY.STRUCTURE.优先队列辅助", "ALGO.GREEDY.STRUCTURE.延迟选择", "DS.TREE.BINARY.堆结构直觉", "ALGO.GREEDY.STRUCTURE.可行性维护"),
                List.of("ALGO.SORT.BASIC.自定义比较", "BASIC.TYPE.VARIABLE.变量命名"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_HEAP_COMPARATOR_REVERSES_PRIORITY",
                "易错点/优先队列细节",
                "优先队列比较方向写反",
                "题目需要每次取最小代价、最早时间或最高收益，但堆的比较函数、负号转换或 pair 排序方向写反，弹出了相反优先级的元素。",
                "只知道要用堆，没有用两个元素手算比较器到底谁会先弹出。",
                "SK_V9_PRIORITY_QUEUE_ORDER_AND_LAZY_DELETE",
                "MODELING",
                List.of("ALGO.GREEDY.STRUCTURE.优先队列辅助", "ALGO.SORT.BASIC.升序降序", "ALGO.SORT.BASIC.自定义比较"),
                List.of("DS.TREE.BINARY.堆结构直觉"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_HEAP_STALE_STATE_NOT_SKIPPED",
                "易错点/优先队列细节",
                "堆中旧状态弹出后没有跳过",
                "同一对象被多次更新并重复入堆，弹出旧距离、旧时间或旧收益时没有用惰性校验与当前数组状态比较，导致过期状态继续参与转移。",
                "以为堆会自动删除旧元素，没有意识到常见写法依赖弹出时的惰性校验。",
                "SK_V9_PRIORITY_QUEUE_ORDER_AND_LAZY_DELETE",
                "STATE",
                List.of("ALGO.GREEDY.STRUCTURE.延迟选择", "ALGO.GRAPH.SHORTEST.松弛操作", "ALGO.GREEDY.STRUCTURE.可行性维护"),
                List.of("BASIC.ARRAY.UPDATE.累计量同步更新"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_PRIORITY_QUEUE_MISSING_RESOURCE_KEY",
                "易错点/优先队列细节",
                "堆元素缺少区分状态的资源字段",
                "题目状态还依赖剩余资源、次数、时间或来源，但堆里只存节点和代价，弹出后无法判断该状态是否仍然完整有效。",
                "把同一个点的所有到达方式合并成一个状态，没有把资源维度放进堆元素和判重键。",
                "SK_V9_PRIORITY_QUEUE_ORDER_AND_LAZY_DELETE",
                "STATE",
                List.of("ALGO.SEARCH.STATE.状态编码", "ALGO.GREEDY.STRUCTURE.资源分配", "ALGO.SEARCH.STATE.判重"),
                List.of("ALGO.SEARCH.STATE.状态转移生成"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V9_HEAP_POP_CONTRACT_CHECKLIST",
                "提升点/优先队列细节",
                "为每次堆弹出写有效性检查清单",
                "适用于学生能用优先队列，但经常被比较器方向、旧状态和状态字段遗漏影响正确性。",
                "修复后让学生写出堆元素字段、排序方向、弹出后校验条件和丢弃旧状态的依据。",
                "教师可要求学生用两个候选元素手算弹出顺序，并说明旧状态如何被过滤。",
                "SK_V9_PRIORITY_QUEUE_ORDER_AND_LAZY_DELETE",
                List.of("MP_V9_HEAP_COMPARATOR_REVERSES_PRIORITY", "MP_V9_HEAP_STALE_STATE_NOT_SKIPPED"),
                List.of("ALGO.GREEDY.STRUCTURE.优先队列辅助", "ALGO.GREEDY.STRUCTURE.延迟选择"));
    }

    private static void addTopologicalSort(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V9_TOPO_INDEGREE_QUEUE_CONTRACT",
                "能力点/拓扑排序细节",
                "维护拓扑排序的入度、队列推进和环检测",
                "能把依赖关系建成有向边，初始化所有入度为 0 的点，并在删除每条出边时准确减少后继入度。",
                "拓扑排序的核心不是队列本身，而是入度代表剩余前置依赖数量。",
                List.of("ALGO.GRAPH.TOPO.入度", "ALGO.GRAPH.TOPO.队列推进", "ALGO.GRAPH.TOPO.环检测", "ALGO.GRAPH.TOPO.依赖关系"),
                List.of("DS.GRAPH.MODEL.有向无向", "DS.GRAPH.STORE.邻接表"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_TOPO_INDEGREE_NOT_DECREMENTED_FOR_ALL_EDGES",
                "易错点/拓扑排序细节",
                "处理一个点后没有遍历全部出边减少入度",
                "节点出队后只减少了部分后继入度，或把入度减在错误节点上，导致本该入队的节点一直无法进入队列。",
                "只关注当前出队点，没有把它的每一条依赖解除动作落实到对应后继。",
                "SK_V9_TOPO_INDEGREE_QUEUE_CONTRACT",
                "STATE",
                List.of("ALGO.GRAPH.TOPO.入度", "ALGO.GRAPH.TOPO.队列推进", "DS.GRAPH.STORE.邻接表"),
                List.of("BASIC.LOOP.FOR.循环次数计算"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_TOPO_CYCLE_NOT_DETECTED",
                "易错点/拓扑排序细节",
                "拓扑排序结束后没有检查是否存在环",
                "队列处理结束后没有比较输出节点数和总节点数，导致有环图被当成合法拓扑序继续输出或计算。",
                "以为队列为空就代表任务完成，没有意识到队列为空也可能是剩余节点互相依赖。",
                "SK_V9_TOPO_INDEGREE_QUEUE_CONTRACT",
                "MODELING",
                List.of("ALGO.GRAPH.TOPO.环检测", "ALGO.GRAPH.TOPO.依赖关系", "DS.GRAPH.MODEL.有向无向"),
                List.of("CONTEST.READING.OUTPUT.输出是否可行"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_TOPO_TIE_RULE_IGNORES_REQUIRED_ORDER",
                "易错点/拓扑排序细节",
                "多个零入度节点的输出顺序不符合题意",
                "题目要求字典序、编号最小或特定优先级的拓扑序，但代码使用普通队列或遍历顺序，导致多解时输出不符合要求。",
                "只满足了任意拓扑序，没有继续读并列节点的输出规则。",
                "SK_V9_TOPO_INDEGREE_QUEUE_CONTRACT",
                "MODELING",
                List.of("ALGO.GRAPH.TOPO.多解顺序", "CONTEST.READING.OUTPUT.多答案要求", "ALGO.SORT.BASIC.自定义比较"),
                List.of("ALGO.GREEDY.STRUCTURE.优先队列辅助"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V9_TOPO_TRACE_TABLE",
                "提升点/拓扑排序细节",
                "用入度表和队列表复盘拓扑排序",
                "适用于学生能写拓扑排序模板，但经常在边方向、入度减少、环检测或多解顺序上出错。",
                "修复后让学生记录每轮出队点、被删除的边、变化后的入度和新入队节点。",
                "教师可用表格检查依赖方向是否反了，以及是否遗漏环检测。",
                "SK_V9_TOPO_INDEGREE_QUEUE_CONTRACT",
                List.of("MP_V9_TOPO_INDEGREE_NOT_DECREMENTED_FOR_ALL_EDGES", "MP_V9_TOPO_CYCLE_NOT_DETECTED"),
                List.of("ALGO.GRAPH.TOPO.入度", "ALGO.GRAPH.TOPO.环检测"));
    }

    private static void addPrefixDiff(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V9_PREFIX_DIFF_QUERY_UPDATE_CONTRACT",
                "能力点/前缀差分细节",
                "维护前缀查询、差分更新和二维边界补零契约",
                "能说明前缀数组下标偏移、区间查询公式、差分加减位置和二维前缀容斥中的边界补零。",
                "前缀和差分题先统一编号体系，再写查询或更新公式。",
                List.of("ALGO.PREFIX.SUM.区间查询", "ALGO.PREFIX.SUM.下标偏移", "ALGO.PREFIX.DIFF.边界加减", "ALGO.PREFIX.MATRIX.边界补零"),
                List.of("BASIC.ARRAY.INDEX.下标映射", "BASIC.TYPE.INTEGER.long_long_范围"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_PREFIX_QUERY_FORGETS_LEFT_MINUS_ONE",
                "易错点/前缀差分细节",
                "区间查询漏减左端前一位前缀",
                "查询 [l,r] 时只使用 prefix[r] 或减错位置，没有减去 l 之前的累计量，导致区间左侧数据混入答案。",
                "只记得前缀保存到当前位置的累计，没有把查询区间外的左侧部分剔除。",
                "SK_V9_PREFIX_DIFF_QUERY_UPDATE_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.PREFIX.SUM.区间查询", "ALGO.PREFIX.SUM.下标偏移", "ALGO.PREFIX.SUM.空前缀"),
                List.of("BASIC.ARRAY.INDEX.长度与最后下标"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_DIFF_RESTORE_ORDER_WRONG",
                "易错点/前缀差分细节",
                "差分数组还原顺序错误",
                "多次区间更新后，代码没有按从左到右累计差分，或在还原前就读取结果，导致最终数组没有反映全部更新。",
                "把差分数组当成最终数组，没有意识到差分需要再做一次前缀还原。",
                "SK_V9_PREFIX_DIFF_QUERY_UPDATE_CONTRACT",
                "LOGIC",
                List.of("ALGO.PREFIX.DIFF.差分还原", "ALGO.PREFIX.DIFF.多次更新", "ALGO.PREFIX.DIFF.离线处理"),
                List.of("BASIC.LOOP.FOR.起点设计"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_MATRIX_PREFIX_BOUNDARY_PADDING_MISSING",
                "易错点/前缀差分细节",
                "二维前缀和缺少边界补零导致越界或公式特判混乱",
                "二维前缀查询使用 r1-1、c1-1 等位置，但没有建立第 0 行第 0 列补零，导致边界子矩阵需要大量特判且容易越界。",
                "只背了容斥公式，没有为公式中的空前缀位置预留合法下标。",
                "SK_V9_PREFIX_DIFF_QUERY_UPDATE_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.PREFIX.MATRIX.边界补零", "ALGO.PREFIX.MATRIX.容斥公式", "ALGO.PREFIX.MATRIX.坐标偏移"),
                List.of("BASIC.ARRAY.INDEX.越界访问"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V9_PREFIX_DIFF_BOUNDARY_CASES",
                "提升点/前缀差分细节",
                "用边界区间和公式表检查前缀差分",
                "适用于学生能写出前缀或差分公式，但经常在左端、右端和二维边界上差一位。",
                "修复后让学生列出单点区间、从 1 开始的区间、到 n 结束的区间和整段区间四类样例。",
                "教师可要求学生把每个公式项对应到图上的矩形或线段，再写代码。",
                "SK_V9_PREFIX_DIFF_QUERY_UPDATE_CONTRACT",
                List.of("MP_V9_PREFIX_QUERY_FORGETS_LEFT_MINUS_ONE", "MP_V9_MATRIX_PREFIX_BOUNDARY_PADDING_MISSING"),
                List.of("ALGO.PREFIX.SUM.区间查询", "ALGO.PREFIX.MATRIX.容斥公式"));
    }

    private static void addBinaryAnswer(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V9_BINARY_ANSWER_CHECK_MONOTONIC_CONTRACT",
                "能力点/二分答案细节",
                "维护答案二分的单调性、check 含义和边界收缩",
                "能说明 check(x) 表示 x 是否可行、可行集合在数轴上的方向，以及每次边界更新后仍保留哪一侧候选答案。",
                "二分答案前先画出不可行和可行区间，再决定找最小可行还是最大可行。",
                List.of("ALGO.BINARY.ANSWER.单调性证明", "ALGO.BINARY.ANSWER.check_函数", "ALGO.BINARY.ANSWER.左右边界", "ALGO.BINARY.ANSWER.最大最小答案"),
                List.of("BASIC.EXPR.COMPARE.边界比较", "ENG.COMPLEXITY.TIME.数据范围反推"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_BINARY_CHECK_DIRECTION_REVERSED",
                "易错点/二分答案细节",
                "check 可行方向理解反了",
                "check(mid) 为 true 时应该保留左侧或右侧候选，但代码更新了相反边界，导致答案向错误方向收敛。",
                "没有先说明 true 代表过大、过小还是刚好可行，只机械套模板。",
                "SK_V9_BINARY_ANSWER_CHECK_MONOTONIC_CONTRACT",
                "LOGIC",
                List.of("ALGO.BINARY.ANSWER.check_函数", "ALGO.BINARY.ANSWER.单调性证明", "ALGO.BINARY.ANSWER.左右边界"),
                List.of("BASIC.EXPR.COMPARE.边界比较"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_BINARY_ANSWER_BOUNDARY_EXCLUDES_VALID_VALUE",
                "易错点/二分答案细节",
                "答案二分初始边界排除了合法答案",
                "最小可行值或最大可行值本身没有包含在初始 low/high 中，后续循环再正确也无法返回真实答案。",
                "只凭直觉设置上下界，没有用题目最小值、最大值和极端样例验证答案一定落在区间内。",
                "SK_V9_BINARY_ANSWER_CHECK_MONOTONIC_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.BINARY.ANSWER.左右边界", "ALGO.BINARY.ANSWER.最大最小答案", "CONTEST.READING.CONSTRAINT.数据范围"),
                List.of("ENG.DEBUG.BOUNDARY.最大输入"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_BINARY_PRECISION_STOP_TOO_EARLY",
                "易错点/二分答案细节",
                "实数二分停止条件过早或精度不足",
                "浮点答案需要达到指定误差，但循环次数、eps 或输出精度设置不足，导致样例接近正确但判题误差超限。",
                "把整数二分的相等终止习惯带到实数二分，没有按题面误差要求设计迭代次数。",
                "SK_V9_BINARY_ANSWER_CHECK_MONOTONIC_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.BINARY.ANSWER.精度二分", "BASIC.IO.STDOUT.小数精度控制", "BASIC.EXPR.COMPARE.浮点比较"),
                List.of("ENG.ERROR.FORMAT.小数位错误"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V9_BINARY_MONOTONIC_PROOF_TABLE",
                "提升点/二分答案细节",
                "用单调性证明表检查答案二分",
                "适用于学生会写二分模板，但经常搞反 check 方向、边界和答案含义。",
                "修复后让学生写出三列：候选 x、check(x) 的含义、true 时保留哪一侧。",
                "教师可用表格追问为什么边界更新后真实答案仍然没有被丢掉。",
                "SK_V9_BINARY_ANSWER_CHECK_MONOTONIC_CONTRACT",
                List.of("MP_V9_BINARY_CHECK_DIRECTION_REVERSED", "MP_V9_BINARY_ANSWER_BOUNDARY_EXCLUDES_VALID_VALUE"),
                List.of("ALGO.BINARY.ANSWER.单调性证明", "ALGO.BINARY.ANSWER.左右边界"));
    }

    private static void addTreeTraversal(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V9_TREE_TRAVERSAL_PARENT_CHILD_CONTRACT",
                "能力点/树遍历细节",
                "维护树遍历中的父子方向、子树结果和访问顺序",
                "能说明根、父节点、子节点和子树分别代表什么，DFS 或 BFS 中何时进入子节点、何时合并子树结果。",
                "树题先定根和父子方向，再写遍历顺序；否则无向边会在递归中变成来回走。",
                List.of("DS.TREE.BASIC.根节点", "DS.TREE.BASIC.父子节点", "DS.TREE.BASIC.子树", "DS.TREE.TRAVERSAL.DFS_遍历"),
                List.of("DS.GRAPH.STORE.无向边双向建边", "BASIC.RECURSION.STATE.递归转移"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_TREE_DFS_RETURNS_BEFORE_VISITING_CHILDREN",
                "易错点/树遍历细节",
                "树 DFS 在处理完当前节点后提前返回",
                "代码在当前节点完成初始化或局部判断后直接 return，没有遍历所有子节点，导致子树贡献没有被统计。",
                "把访问当前节点当成访问整棵子树，没有区分节点自身处理和子节点递归。",
                "SK_V9_TREE_TRAVERSAL_PARENT_CHILD_CONTRACT",
                "LOGIC",
                List.of("DS.TREE.TRAVERSAL.DFS_遍历", "DS.TREE.BASIC.子树", "BASIC.RECURSION.STATE.递归转移"),
                List.of("BASIC.FUNCTION.RETURN.提前返回"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_TREE_PARENT_REVISIT_CAUSES_CYCLE",
                "易错点/树遍历细节",
                "无向树遍历时没有排除父节点导致递归回头",
                "树以无向边存储，但 DFS 子节点时没有跳过 parent 或 visited，导致从孩子回到父亲形成无限递归或重复统计。",
                "把树当成天然有方向，没有意识到邻接表里的父节点也会作为相邻点出现。",
                "SK_V9_TREE_TRAVERSAL_PARENT_CHILD_CONTRACT",
                "RUNTIME",
                List.of("DS.TREE.BASIC.父子节点", "DS.GRAPH.TRAVERSE.访问标记", "ENG.ERROR.RUNTIME.递归爆栈"),
                List.of("DS.GRAPH.STORE.双向边添加"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_TREE_SUBTREE_SIZE_INITIALIZED_ZERO",
                "易错点/树遍历细节",
                "子树大小没有包含当前节点",
                "计算子树大小、节点数或路径贡献时把初值设为 0，递归只累加孩子，漏掉当前节点自身贡献。",
                "只把子树理解成孩子集合，没有把当前节点也属于自己的子树。",
                "SK_V9_TREE_TRAVERSAL_PARENT_CHILD_CONTRACT",
                "INITIALIZATION",
                List.of("DS.TREE.BASIC.子树", "DS.TREE.BASIC.根节点", "BASIC.RECURSION.BASE.边界返回值"),
                List.of("ALGO.DP.INIT.初始值"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V9_TREE_TRACE_AND_SUBTREE_CHECK",
                "提升点/树遍历细节",
                "用父子表和子树返回值检查树遍历",
                "适用于学生会写 DFS/BFS，但经常在父节点排除、子树统计和递归返回上出错。",
                "修复后让学生列出每个节点的 parent、children、进入顺序、返回值和合并后的子树结果。",
                "教师可用父子表检查学生是否把无向边转成了明确的根树结构。",
                "SK_V9_TREE_TRAVERSAL_PARENT_CHILD_CONTRACT",
                List.of("MP_V9_TREE_PARENT_REVISIT_CAUSES_CYCLE", "MP_V9_TREE_SUBTREE_SIZE_INITIALIZED_ZERO"),
                List.of("DS.TREE.BASIC.父子节点", "DS.TREE.BASIC.子树"));
    }

    private static void addMapFrequency(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V9_MAP_FREQUENCY_KEY_LIFECYCLE",
                "能力点/map 频次细节",
                "维护映射键、默认值、频次变化和遍历生命周期",
                "能说明 map/dict 的 key 应包含哪些状态维度，首次出现如何初始化，计数归零后是否删除，以及遍历时能否修改容器。",
                "map 题先定义 key 的完整含义，再写增删查；否则默认值和遍历修改会藏住错误。",
                List.of("DS.SET_MAP.MAP.键值关系", "DS.SET_MAP.MAP.频次统计", "DS.SET_MAP.MAP.默认值", "DS.SET_MAP.MAP.键不存在处理"),
                List.of("DS.SET_MAP.HASH.字符串键", "BASIC.LOOP.FOR.循环变量不被破坏"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_MAP_DEFAULT_VALUE_SKIPS_FIRST_COUNT",
                "易错点/map 频次细节",
                "首次出现的元素没有计入频次",
                "遇到新 key 时只创建默认值或分支返回，没有把第一次出现的贡献加进去，导致频次整体少一。",
                "把初始化和本次计数拆成互斥分支，忘记新 key 也代表一次真实出现。",
                "SK_V9_MAP_FREQUENCY_KEY_LIFECYCLE",
                "INITIALIZATION",
                List.of("DS.SET_MAP.MAP.默认值", "DS.SET_MAP.MAP.频次统计", "DS.SET_MAP.MAP.键不存在处理"),
                List.of("BASIC.BRANCH.CASE.覆盖所有情况"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_MAP_KEY_MISSING_STATE_DIMENSION",
                "易错点/map 频次细节",
                "map 的 key 缺少必要状态维度",
                "本应按位置、颜色、方向、余数或时间层级区分的状态，只用一个字段作为 key，导致不同状态的计数或最优值被合并。",
                "只看到了某个表面标识相同，没有追问题目后续决策还依赖哪些状态维度。",
                "SK_V9_MAP_FREQUENCY_KEY_LIFECYCLE",
                "STATE",
                List.of("DS.SET_MAP.MAP.键值关系", "ALGO.SEARCH.STATE.状态编码", "ALGO.DP.STATE.维度选择"),
                List.of("BASIC.TYPE.VARIABLE.变量命名"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_MAP_ERASE_WHILE_ITERATING_BREAKS_TRAVERSAL",
                "易错点/map 频次细节",
                "遍历 map 时直接删除导致漏项或迭代失效",
                "代码在遍历键值对时直接删除当前或其他 key，使迭代器失效、遍历顺序改变或部分键没有被处理。",
                "没有区分收集待删除键和真正修改容器两个阶段。",
                "SK_V9_MAP_FREQUENCY_KEY_LIFECYCLE",
                "RUNTIME",
                List.of("DS.SET_MAP.MAP.遍历键值", "DS.SET_MAP.MAP.键不存在处理", "BASIC.LOOP.FOR.循环变量不被破坏"),
                List.of("BASIC.ARRAY.UPDATE.批量更新后还原顺序"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V9_MAP_KEY_COUNT_AUDIT",
                "提升点/map 频次细节",
                "用 key 定义表和频次生命周期检查 map 逻辑",
                "适用于学生能使用 map/dict，但经常在 key 维度、首次计数和删除时机上出错。",
                "修复后让学生写出 key 的字段组成、每次增减频次的触发条件、归零后的处理和遍历期间是否允许修改。",
                "教师可用这张表判断学生是否把题目状态完整映射到了 key。",
                "SK_V9_MAP_FREQUENCY_KEY_LIFECYCLE",
                List.of("MP_V9_MAP_DEFAULT_VALUE_SKIPS_FIRST_COUNT", "MP_V9_MAP_KEY_MISSING_STATE_DIMENSION"),
                List.of("DS.SET_MAP.MAP.键值关系", "DS.SET_MAP.MAP.频次统计"));
    }

    private static void addOutputConstruction(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V9_OUTPUT_CONSTRUCTION_FORMAT_CONTRACT",
                "能力点/输出构造细节",
                "维护输出格式、方案重建和多答案规则",
                "能把题目要求的换行、空格、大小写、路径顺序、方案数量和多答案规则落实到最终输出。",
                "输出不是把内部状态打印出来，而是按题面要求把答案重建成指定格式。",
                List.of("BASIC.IO.STDOUT.按要求换行", "BASIC.IO.STDOUT.空格分隔", "CONTEST.READING.OUTPUT.输出路径", "CONTEST.READING.OUTPUT.多答案要求"),
                List.of("BASIC.STRING.BUILD.结果顺序", "ENG.ERROR.FORMAT.多余空格"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_OUTPUT_EXTRA_DEBUG_TEXT_LEFT",
                "易错点/输出构造细节",
                "最终输出残留调试文字",
                "代码除了题目要求的答案外，还输出了变量名、提示语、调试数组或中间状态，导致格式错误。",
                "把本地调试输出当成无害信息，没有意识到评测只比较题目规定的输出内容。",
                "SK_V9_OUTPUT_CONSTRUCTION_FORMAT_CONTRACT",
                "IO_FORMAT",
                List.of("BASIC.IO.STDOUT.禁止多余调试输出", "ENG.ERROR.FORMAT.调试输出", "CONTEST.SUBMIT.CHECKLIST.输出格式检查"),
                List.of("BASIC.IO.STDOUT.按要求换行"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_OUTPUT_PATH_RECONSTRUCTION_REVERSED",
                "易错点/输出构造细节",
                "路径重建输出顺序反了",
                "通过前驱数组、递归返回或栈重建路径后，没有按题目要求从起点到终点输出，或漏掉起点/终点。",
                "只关注找到了路径，没有把内部回溯顺序转换成题面要求的展示顺序。",
                "SK_V9_OUTPUT_CONSTRUCTION_FORMAT_CONTRACT",
                "LOGIC",
                List.of("CONTEST.READING.OUTPUT.输出路径", "BASIC.STRING.BUILD.结果顺序", "DS.GRAPH.TRAVERSE.路径记录"),
                List.of("DS.LINEAR.STACK.后进先出"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V9_OUTPUT_MULTI_ANSWER_ORDER_IGNORED",
                "易错点/输出构造细节",
                "多答案题没有按规定顺序输出",
                "题面允许多个正确方案但规定字典序、编号最小、任意一个或全部输出，代码没有实现对应规则。",
                "以为求出一个可行答案就够了，没有继续读输出说明中的多答案约束。",
                "SK_V9_OUTPUT_CONSTRUCTION_FORMAT_CONTRACT",
                "MODELING",
                List.of("CONTEST.READING.OUTPUT.多答案要求", "BASIC.EXPR.COMPARE.字典序比较", "ALGO.SORT.BASIC.自定义比较"),
                List.of("CONTEST.READING.OUTPUT.输出是否可行"),
                "MEDIUM",
                LANGUAGES);
        improvement(seeds,
                "IP_V9_OUTPUT_SAMPLE_DIFF_CHECKLIST",
                "提升点/输出构造细节",
                "用输出差异清单检查格式和方案顺序",
                "适用于学生算法主体正确，但经常因为多余输出、空格换行、路径顺序或多答案规则丢分。",
                "修复后让学生逐字符对比样例输出，并额外构造路径长度为 1、多方案并列和无解三类输出。",
                "教师可要求学生把内部答案结构和最终输出格式分开说明，避免直接打印调试状态。",
                "SK_V9_OUTPUT_CONSTRUCTION_FORMAT_CONTRACT",
                List.of("MP_V9_OUTPUT_EXTRA_DEBUG_TEXT_LEFT", "MP_V9_OUTPUT_PATH_RECONSTRUCTION_REVERSED"),
                List.of("BASIC.IO.STDOUT.按要求换行", "CONTEST.READING.OUTPUT.输出路径"));
    }

    private static void improvement(List<AiStandardLibrarySeed> seeds,
                                    String code,
                                    String category,
                                    String name,
                                    String description,
                                    String studentBenefit,
                                    String teacherExplanation,
                                    String skillUnitCode,
                                    List<String> relatedMistakeCodes,
                                    List<String> knowledgeNodeCodes) {
        seeds.add(new AiStandardLibrarySeed(
                AiStandardLibraryLayer.IMPROVEMENT_POINT,
                code,
                category,
                name,
                description,
                "",
                teacherExplanation,
                skillUnitCode,
                "",
                "",
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                description,
                studentBenefit,
                "",
                "",
                "",
                skillUnitCode,
                "MEDIUM",
                LANGUAGES,
                relatedMistakeCodes,
                knowledgeNodeCodes,
                List.of(),
                "修复基础错误后，用结构化自测和复盘提升迁移能力。",
                AiStandardLibrarySeedCatalog.VERSION
        ));
    }
}
