package com.onlinejudge.learning.standardlibrary.application;

import com.onlinejudge.learning.standardlibrary.domain.AiStandardLibraryLayer;

import java.util.List;

final class AiStandardLibraryV12ArchiveValueSeeds {

    private static final List<String> LANGUAGES = List.of("PYTHON", "CPP17");

    private AiStandardLibraryV12ArchiveValueSeeds() {
    }

    static void addTo(List<AiStandardLibrarySeed> seeds) {
        addLoopControl(seeds);
        addPrefixStatistics(seeds);
        addStringBuild(seeds);
        addStackQueue(seeds);
        addHashModeling(seeds);
        addBranchCoverage(seeds);
        addDebugTrace(seeds);
        addSubmissionInitReview(seeds);
    }

    private static void addLoopControl(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V12_LOOP_CONTROL_EXIT_CONTRACT",
                "能力点/兜底榨取-A类循环控制",
                "维护 break、continue、标志变量和多层退出契约",
                "能说明循环何时跳过本轮、何时结束整体流程、哪些维护量必须在退出前更新，以及多层循环如何传递退出信号。",
                "写循环控制前先标注四个位置：进入条件、本轮维护、答案更新、退出或跳过动作。",
                List.of("BASIC.LOOP.CONTROL.break_使用", "BASIC.LOOP.CONTROL.continue_使用",
                        "BASIC.LOOP.CONTROL.提前结束", "BASIC.LOOP.CONTROL.标志变量",
                        "BASIC.LOOP.CONTROL.多层循环退出"),
                List.of("BASIC.LOOP.WHILE.状态推进"),
                "HIGH",
                List.of(
                        m("MP_V12_CONTINUE_SKIPS_REQUIRED_MAINTENANCE",
                                "continue 跳过了本轮必须维护的计数或指针",
                                "循环中提前 continue 前没有更新计数、下标、窗口状态或读入进度，下一轮仍基于旧状态运行。",
                                "只把 continue 当作跳过无用分支，没有检查跳过前哪些变量仍必须推进。",
                                "STATE",
                                List.of("BASIC.LOOP.CONTROL.continue_使用", "BASIC.LOOP.WHILE.状态推进"),
                                List.of("BASIC.TYPE.VARIABLE.赋值覆盖"),
                                "HIGH"),
                        m("MP_V12_BREAK_BEFORE_FINAL_ANSWER_UPDATE",
                                "break 发生在最终答案更新之前",
                                "代码遇到目标条件后立即 break，但当前元素、当前路径或当前区间的贡献还没有写入答案。",
                                "把找到条件和完成本轮处理混为一谈，没有标出退出前最后一次答案更新。",
                                "BOUNDARY",
                                List.of("BASIC.LOOP.CONTROL.break_使用", "BASIC.LOOP.CONTROL.提前结束"),
                                List.of("BASIC.LOOP.BOUNDARY.最后一次迭代"),
                                "HIGH"),
                        m("MP_V12_MULTILEVEL_EXIT_FLAG_NOT_PROPAGATED",
                                "多层循环退出信号没有传到外层",
                                "内层循环已经找到答案或非法状态，但外层循环继续执行，覆盖结果或重复处理后续数据。",
                                "只退出了当前循环，没有设计外层如何知道应该停止。",
                                "STATE",
                                List.of("BASIC.LOOP.CONTROL.多层循环退出", "BASIC.LOOP.CONTROL.标志变量"),
                                List.of("BASIC.BRANCH.CASE.覆盖所有情况"),
                                "HIGH")),
                "IP_V12_LOOP_CONTROL_TRACE_TABLE",
                "用循环控制轨迹表检查跳过、退出和维护动作",
                "适用于学生会写循环，但 break、continue、flag 或多层退出导致状态不同步。",
                "修复后让学生列出每个分支是否执行维护量、是否更新答案、是否退出本层或外层。",
                "教师可用轨迹表判断学生是边界没处理，还是退出动作破坏了状态。",
                List.of("MP_V12_CONTINUE_SKIPS_REQUIRED_MAINTENANCE", "MP_V12_MULTILEVEL_EXIT_FLAG_NOT_PROPAGATED"));
    }

    private static void addPrefixStatistics(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V12_PREFIX_STATISTICS_CONTRACT",
                "能力点/兜底榨取-A类前缀统计",
                "维护前缀定义、区间公式、差分还原和计数数组契约",
                "能定义 prefix[i]、diff[i] 和 count[x] 的含义，并根据含义推导查询公式、更新位置和值域边界。",
                "写公式前先说明数组每个下标代表前多少个元素、哪个位置开始生效、哪个位置停止生效。",
                List.of("BASIC.ARRAY.PREFIX.前缀和定义", "BASIC.ARRAY.PREFIX.区间和查询",
                        "BASIC.ARRAY.PREFIX.差分直觉", "BASIC.ARRAY.PREFIX.计数数组"),
                List.of("BASIC.ARRAY.INDEX.下标映射"),
                "HIGH",
                List.of(
                        m("MP_V12_PREFIX_ZERO_SLOT_OMITTED",
                                "前缀数组缺少 0 号空前缀",
                                "区间从第一个元素开始时，代码没有设置 prefix[0] 或等价空前缀，导致 l=0 或 l=1 的查询公式需要特殊绕开。",
                                "只记住前缀累计，没有先定义 prefix[i] 表示前几个元素。",
                                "BOUNDARY",
                                List.of("BASIC.ARRAY.PREFIX.前缀和定义", "BASIC.ARRAY.PREFIX.区间和查询"),
                                List.of("BASIC.ARRAY.INDEX.0_基下标"),
                                "HIGH"),
                        m("MP_V12_DIFF_STOP_POSITION_MISSING",
                                "差分更新缺少停止位置",
                                "区间加减只在左端做了增量，没有在右端后一位撤销，导致后续所有位置都被错误影响。",
                                "只理解了从 l 开始变化，没有写清变化应该在哪里停止。",
                                "BOUNDARY",
                                List.of("BASIC.ARRAY.PREFIX.差分直觉", "BASIC.ARRAY.PREFIX.区间和查询"),
                                List.of("BASIC.LOOP.BOUNDARY.最后一次迭代"),
                                "HIGH"),
                        m("MP_V12_COUNT_ARRAY_VALUE_RANGE_NOT_SHIFTED",
                                "计数数组没有处理值域偏移或负值",
                                "元素值可能为负、从 1 开始或超过数组长度，但代码直接把值当下标计数，导致越界或统计错位。",
                                "把值域和数组下标当成同一件事，没有设计映射或偏移。",
                                "VALUE_RANGE",
                                List.of("BASIC.ARRAY.PREFIX.计数数组", "BASIC.ARRAY.INDEX.越界访问"),
                                List.of("BASIC.TYPE.INTEGER.int_范围"),
                                "HIGH")),
                "IP_V12_PREFIX_MEANING_CARD",
                "用前缀统计含义卡复核公式和边界",
                "适用于学生会背前缀和公式，但遇到 0 号、右端后一位、负值计数就出错。",
                "修复后让学生写出 prefix、diff、count 三个数组的下标和值分别代表什么。",
                "教师可用含义卡区分公式记忆错误和状态定义错误。",
                List.of("MP_V12_PREFIX_ZERO_SLOT_OMITTED", "MP_V12_DIFF_STOP_POSITION_MISSING"));
    }

    private static void addStringBuild(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V12_STRING_BUILD_EDIT_CONTRACT",
                "能力点/兜底榨取-A类字符串构造",
                "维护字符串构造、格式化、删除替换和效率契约",
                "能判断字符串是逐步拼接、按格式输出、删除替换还是保留原位置，并选择不会破坏下标和复杂度的构造方式。",
                "字符串构造前先写目标格式、保留字符、删除字符和下一次扫描位置。",
                List.of("BASIC.STRING.BUILD.拼接效率", "BASIC.STRING.BUILD.格式化构造",
                        "BASIC.STRING.BUILD.删除替换"),
                List.of("BASIC.STRING.CHAR.字符遍历"),
                "MEDIUM",
                List.of(
                        m("MP_V12_STRING_CONCAT_IN_LOOP_TIMEOUT",
                                "循环内低效拼接导致字符串构造超时",
                                "代码每次循环都创建新字符串或反复移动大量字符，输入稍大时构造过程退化为二次复杂度。",
                                "只看到了拼接结果正确，没有估算每次拼接背后的复制成本。",
                                "COMPLEXITY",
                                List.of("BASIC.STRING.BUILD.拼接效率", "ENG.COMPLEXITY.TIME.NSQUARE"),
                                List.of("ENG.COMPLEXITY.TIME.数据范围反推"),
                                "MEDIUM"),
                        m("MP_V12_FORMAT_SEPARATOR_EXTRA_OR_MISSING",
                                "格式化构造中分隔符多输出或少输出",
                                "输出列表、路径或拼接结果时，没有区分首项、中间项和末项，导致多余逗号、空格或换行。",
                                "把每个元素后面都加分隔符，没有把格式要求当成构造状态。",
                                "IO_FORMAT",
                                List.of("BASIC.STRING.BUILD.格式化构造", "BASIC.IO.STDOUT.按要求换行"),
                                List.of("CONTEST.SUBMIT.CHECKLIST.输出格式检查"),
                                "HIGH"),
                        m("MP_V12_STRING_DELETE_SKIPS_NEXT_CHAR",
                                "删除或替换字符后扫描位置推进错误",
                                "在原字符串上删除、替换或压缩字符后，下一个待检查字符位置发生变化，但循环仍按旧下标推进，漏掉相邻目标。",
                                "把删除前后的下标看成不变，没有重新定义下一次扫描起点。",
                                "BOUNDARY",
                                List.of("BASIC.STRING.BUILD.删除替换", "BASIC.STRING.CHAR.字符遍历"),
                                List.of("BASIC.ARRAY.INDEX.下标映射"),
                                "HIGH")),
                "IP_V12_STRING_BUILD_PLAN",
                "用字符串构造计划分离目标格式和扫描推进",
                "适用于学生字符串结果看似接近，但分隔符、删除替换或性能反复出错。",
                "修复后让学生写出构造容器、分隔符规则、删除后下标变化和最终输出格式。",
                "教师可用构造计划判断错误来自格式状态、下标推进还是复杂度。",
                List.of("MP_V12_FORMAT_SEPARATOR_EXTRA_OR_MISSING", "MP_V12_STRING_DELETE_SKIPS_NEXT_CHAR"));
    }

    private static void addStackQueue(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V12_STACK_QUEUE_STATE_CONTRACT",
                "能力点/兜底榨取-B类栈队列状态",
                "维护栈顶、队首队尾、空结构保护和操作方向契约",
                "能把题目中的最近未匹配、先进先出、两端操作或显式调用栈，映射成栈/队列状态和每一步操作前置条件。",
                "使用栈队列前先写状态含义：容器里放什么、谁在顶部或队首、何时允许访问。",
                List.of("DS.LINEAR.STACK.括号匹配", "DS.LINEAR.STACK.单调栈雏形",
                        "DS.LINEAR.STACK.递归栈模拟", "DS.LINEAR.QUEUE.循环队列",
                        "DS.LINEAR.QUEUE.双端队列", "DS.LINEAR.QUEUE.队空判断"),
                List.of("DS.LINEAR.STACK.后进先出", "DS.LINEAR.QUEUE.先进先出"),
                "HIGH",
                List.of(
                        m("MP_V12_STACK_TOP_ACCESSED_WHEN_EMPTY",
                                "访问栈顶前没有确认栈非空",
                                "括号匹配、单调栈或递归栈模拟中，代码在空栈时读取 top/back，导致运行错误或错误匹配。",
                                "只考虑了有可匹配元素的路径，没有把空结构作为合法边界状态。",
                                "RUNTIME",
                                List.of("DS.LINEAR.STACK.括号匹配", "DS.LINEAR.STACK.后进先出", "DS.LINEAR.STACK.空栈检查"),
                                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                                "HIGH"),
                        m("MP_V12_MONOTONIC_STACK_POP_CONDITION_REVERSED",
                                "单调栈弹出条件方向写反",
                                "本应维护递增或递减关系，但弹栈比较符号反了，使栈内保留的候选对象不满足后续查询需要。",
                                "记住了要弹栈，没有说明栈中元素按什么属性保持单调。",
                                "MODELING",
                                List.of("DS.LINEAR.STACK.单调栈雏形", "ALGO.TWO_POINTERS.WINDOW.合法性判断"),
                                List.of("ALGO.SORT.BASIC.升序降序"),
                                "HIGH"),
                        m("MP_V12_QUEUE_FRONT_BACK_ROLE_MIXED",
                                "队首和队尾角色混用",
                                "BFS、循环队列或双端队列中，把取出位置和加入位置写反，导致遍历顺序、层次或窗口候选错乱。",
                                "只把队列当成普通数组，没有固定 front/back 各自承担的操作。",
                                "STATE",
                                List.of("DS.LINEAR.QUEUE.先进先出", "DS.LINEAR.QUEUE.双端队列", "DS.LINEAR.QUEUE.BFS_队列"),
                                List.of("ALGO.SEARCH.BFS.队列层次"),
                                "HIGH")),
                "IP_V12_STACK_QUEUE_STATE_SNAPSHOT",
                "用栈队列快照复盘每一步 push、pop 和访问",
                "适用于学生会套容器，但栈顶、队首或空结构保护经常出错。",
                "修复后让学生记录三步容器快照：操作前内容、执行动作、操作后顶部或队首。",
                "教师可用快照判断错误来自操作方向、空结构保护还是状态含义。",
                List.of("MP_V12_STACK_TOP_ACCESSED_WHEN_EMPTY", "MP_V12_QUEUE_FRONT_BACK_ROLE_MIXED"));
    }

    private static void addHashModeling(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V12_HASH_KEY_COMPLEXITY_CONTRACT",
                "能力点/兜底榨取-B类哈希建模",
                "维护哈希键设计、字符串规范化和均摊复杂度契约",
                "能判断 map/set 的 key 应该保存题面对象的哪个身份，字符串键是否需要规范化，以及哈希查找是否符合数据规模。",
                "写哈希前先说明 key、value、默认值、是否需要排序或大小写规范化。",
                List.of("DS.SET_MAP.HASH.均摊复杂度", "DS.SET_MAP.HASH.哈希冲突直觉",
                        "DS.SET_MAP.HASH.字符串键"),
                List.of("DS.SET_MAP.MAP.键值关系"),
                "MEDIUM",
                List.of(
                        m("MP_V12_HASH_KEY_MISSING_NORMALIZATION",
                                "字符串键没有按题意规范化",
                                "题目要求忽略大小写、空格、顺序或前导零，但代码直接用原字符串作为 key，导致等价对象被当作不同对象。",
                                "只看到字符串能放进 map，没有先定义两个对象何时算同一个 key。",
                                "MODELING",
                                List.of("DS.SET_MAP.HASH.字符串键", "BASIC.STRING.BUILD.格式化构造"),
                                List.of("BASIC.STRING.CHAR.大小写转换"),
                                "HIGH"),
                        m("MP_V12_HASH_VALUE_USED_AS_KEY",
                                "频次或答案值被误当成哈希键",
                                "本应按对象、状态或字符串查找，却把频次、位置或累计答案作为 key，导致查找关系和题意身份错位。",
                                "没有写清 key 表示谁，只凭变量名把 map 当成万能容器。",
                                "MODELING",
                                List.of("DS.SET_MAP.MAP.键值关系", "DS.SET_MAP.HASH.字符串键"),
                                List.of("ENG.STYLE.NAME.变量含义"),
                                "HIGH"),
                        m("MP_V12_HASH_COMPLEXITY_ASSUMED_WITH_BAD_OPERATION",
                                "以为用了哈希就自动满足复杂度",
                                "代码虽然使用 map/set，但每次操作还线性构造长字符串、扫描集合或嵌套查找，整体复杂度仍超过限制。",
                                "只看单次哈希查找是均摊常数，没有把构造 key 和外围循环计入复杂度。",
                                "COMPLEXITY",
                                List.of("DS.SET_MAP.HASH.均摊复杂度", "DS.SET_MAP.HASH.哈希冲突直觉"),
                                List.of("ENG.COMPLEXITY.TIME.数据范围反推"),
                                "MEDIUM")),
                "IP_V12_HASH_KEY_DESIGN_CARD",
                "用哈希键设计卡固定 key、value 和等价规则",
                "适用于学生知道要用 map/set，但 key 设计、默认值或复杂度仍不稳定。",
                "修复后让学生写出 key 的对象身份、value 的含义、等价对象如何规范化、单次操作成本。",
                "教师可用设计卡判断错误来自容器选择还是题面对象建模。",
                List.of("MP_V12_HASH_KEY_MISSING_NORMALIZATION", "MP_V12_HASH_VALUE_USED_AS_KEY"));
    }

    private static void addBranchCoverage(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V12_BRANCH_CASE_COVERAGE_CONTRACT",
                "能力点/兜底榨取-A类分支覆盖",
                "维护单分支、双分支、多分支和嵌套条件覆盖契约",
                "能判断题面情况是否互斥、是否有优先级、是否需要兜住默认分支，并保证条件变量在判断前已经准备好。",
                "写分支前先列情况表：每一行是一个输入类型，每一列是期望进入的分支。",
                List.of("BASIC.BRANCH.IF.单分支判断", "BASIC.BRANCH.IF.双分支判断",
                        "BASIC.BRANCH.IF.多分支链", "BASIC.BRANCH.IF.嵌套分支",
                        "BASIC.BRANCH.IF.条件变量准备"),
                List.of("BASIC.EXPR.LOGIC.条件组合"),
                "MEDIUM",
                List.of(
                        m("MP_V12_BRANCH_DEFAULT_CASE_MISSING",
                                "分支链没有覆盖默认情况",
                                "代码只处理样例中出现的几类输入，遇到其他合法情况时变量没有赋值或答案沿用旧值。",
                                "把已知样例情况当成完整分类，没有列出剩余合法输入。",
                                "INITIALIZATION",
                                List.of("BASIC.BRANCH.IF.多分支链", "BASIC.BRANCH.CASE.覆盖所有情况"),
                                List.of("BASIC.TYPE.VARIABLE.声明与初始化"),
                                "HIGH"),
                        m("MP_V12_BRANCH_PRIORITY_ORDER_REVERSED",
                                "特殊条件和一般条件顺序写反",
                                "本应先判断特殊情况、边界值或更严格条件，但代码先进入一般分支，使特殊情况永远没有机会处理。",
                                "只写了多个 if，没有按包含关系和优先级排列条件。",
                                "BOUNDARY",
                                List.of("BASIC.BRANCH.IF.多分支链", "BASIC.BRANCH.CASE.优先级条件前置"),
                                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                                "HIGH"),
                        m("MP_V12_BRANCH_CONDITION_VARIABLE_STALE",
                                "分支判断使用了尚未更新的条件变量",
                                "条件变量在进入分支前没有根据当前输入、当前循环或当前状态重新计算，导致分支使用上一轮判断结果。",
                                "把条件变量看成固定结论，没有把它和当前数据生命周期绑定。",
                                "STATE",
                                List.of("BASIC.BRANCH.IF.条件变量准备", "BASIC.TYPE.CHAR_BOOL.逻辑标志变量"),
                                List.of("BASIC.IO.MULTI_CASE.每组状态重置"),
                                "HIGH")),
                "IP_V12_BRANCH_CASE_TABLE",
                "用分支情况表检查覆盖、优先级和变量准备",
                "适用于学生分支写得多，但漏默认情况、顺序错或条件变量旧值残留。",
                "修复后让学生列出每类输入、期望分支、实际条件表达式和条件变量来源。",
                "教师可用情况表判断错误是分类不全、优先级不对还是变量未更新。",
                List.of("MP_V12_BRANCH_DEFAULT_CASE_MISSING", "MP_V12_BRANCH_PRIORITY_ORDER_REVERSED"));
    }

    private static void addDebugTrace(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V12_DEBUG_TRACE_FRAME_CONTRACT",
                "能力点/兜底榨取-B类调试追踪",
                "维护递归栈、DP 表和首个偏差追踪契约",
                "能把运行过程拆成调用帧、表格行列或状态快照，并用最小输入定位第一处和预期不同的位置。",
                "调试前先固定观测对象：参数、返回值、表格单元、转移来源和首个偏差。",
                List.of("ENG.DEBUG.TRACE.递归栈", "ENG.DEBUG.TRACE.DP_表变化"),
                List.of("ENG.DEBUG.SAMPLE.最小反例"),
                "MEDIUM",
                List.of(
                        m("MP_V12_RECURSION_TRACE_MISREADS_CALL_FRAME",
                                "递归调试时混淆不同调用帧的参数",
                                "打印或手推递归过程时，把上一层参数、当前层局部变量和下一层返回值混在一起，导致修错位置。",
                                "只看函数名重复调用，没有把每一层调用帧单独编号。",
                                "DEBUGGING",
                                List.of("ENG.DEBUG.TRACE.递归栈", "BASIC.RECURSION.STATE.调用栈理解"),
                                List.of("BASIC.FUNCTION.DEF.参数设计"),
                                "MEDIUM"),
                        m("MP_V12_DP_TRACE_OMITS_TRANSITION_SOURCE",
                                "DP 表调试只看结果不看来源状态",
                                "检查 DP 表时只看到某个单元格错误，却没有记录它由哪些上一层状态转移而来，导致无法定位初始化、遍历顺序或公式错误。",
                                "把表格值当成孤立数字，没有追踪每个值的来源。",
                                "DEBUGGING",
                                List.of("ENG.DEBUG.TRACE.DP_表变化", "ALGO.DP.TRANSITION.枚举决策"),
                                List.of("ALGO.DP.STATE.状态含义"),
                                "HIGH"),
                        m("MP_V12_TRACE_AFTER_FAILURE_TOO_LATE",
                                "只在最终答案处观察导致错过首个偏差",
                                "调试只打印最终答案或最后一轮状态，没有在第一次偏离预期的位置截断观察，修复过程靠猜。",
                                "把错误看成结果不对，没有追问哪一步第一次不对。",
                                "DEBUGGING",
                                List.of("ENG.DEBUG.TRACE.循环状态", "ENG.DEBUG.TRACE.DP_表变化"),
                                List.of("ENG.DEBUG.SAMPLE.最小反例"),
                                "MEDIUM")),
                "IP_V12_DEBUG_TRACE_SNAPSHOT",
                "用追踪快照定位递归、DP 或循环的首个偏差",
                "适用于学生知道答案错，但只能反复改代码，找不到第一处偏差。",
                "修复后让学生记录最小输入、每步关键变量、预期值、实际值和偏差出现位置。",
                "教师可用快照判断学生是否具备可迁移的调试方法。",
                List.of("MP_V12_DP_TRACE_OMITS_TRANSITION_SOURCE", "MP_V12_TRACE_AFTER_FAILURE_TOO_LATE"));
    }

    private static void addSubmissionInitReview(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V12_SUBMISSION_INIT_REVIEW_CONTRACT",
                "能力点/兜底榨取-B类提交初始化检查",
                "维护提交前初始化、清空和多组状态复查契约",
                "能在提交前检查每个变量、数组、容器和标志位是否在正确范围内初始化，并确认多组数据之间不会串状态。",
                "提交前先按变量表检查：谁需要每组重置、谁需要保留、谁必须在分支前赋值。",
                List.of("CONTEST.SUBMIT.CHECKLIST.初始化检查"),
                List.of("BASIC.IO.MULTI_CASE.每组状态重置"),
                "MEDIUM",
                List.of(
                        m("MP_V12_SUBMIT_ARRAY_NOT_CLEARED_BETWEEN_CASES",
                                "提交前没有发现数组或容器跨组残留",
                                "上一组数据写入的数组、邻接表、计数 map 或 visited 标记没有清空，下一组合法输入混入旧状态。",
                                "本地只测单组样例，没有把初始化检查放到每组数据开始处。",
                                "INITIALIZATION",
                                List.of("CONTEST.SUBMIT.CHECKLIST.初始化检查", "BASIC.IO.MULTI_CASE.每组状态重置"),
                                List.of("BASIC.ARRAY.UPDATE.累计更新"),
                                "HIGH"),
                        m("MP_V12_SUBMIT_BRANCH_VARIABLE_MAYBE_UNASSIGNED",
                                "提交前没有检查分支变量可能未赋值",
                                "某些合法输入路径不会进入任何赋值分支，但后续仍输出或计算该变量，隐藏数据触发默认值或旧值。",
                                "样例刚好经过赋值路径，没有把每个变量的赋值来源逐分支核对。",
                                "INITIALIZATION",
                                List.of("CONTEST.SUBMIT.CHECKLIST.初始化检查", "BASIC.BRANCH.CASE.覆盖所有情况"),
                                List.of("BASIC.TYPE.VARIABLE.声明与初始化"),
                                "HIGH"),
                        m("MP_V12_SUBMIT_RESET_DESTROYS_NEEDED_PRECOMPUTE",
                                "错误重置破坏了应保留的预处理结果",
                                "提交前为了清空状态，把跨测试共享的质数表、前缀表或预处理缓存也重置掉，导致后续查询缺数据或超时重算。",
                                "没有区分每组状态和全局预处理，看到变量就统一清空。",
                                "STATE",
                                List.of("CONTEST.SUBMIT.CHECKLIST.初始化检查", "ENG.COMPLEXITY.TRADEOFF.预处理"),
                                List.of("BASIC.TYPE.VARIABLE.作用域"),
                                "MEDIUM")),
                "IP_V12_SUBMISSION_INITIALIZATION_AUDIT",
                "用提交初始化审计表区分每组重置和全局保留",
                "适用于学生提交前只复测样例，却常因初始化、清空或多组残留失败。",
                "修复后让学生把关键状态分成每组重置、全局预处理、分支前必赋值三列。",
                "教师可用审计表判断错误来自漏清空、误清空还是未赋值。",
                List.of("MP_V12_SUBMIT_ARRAY_NOT_CLEARED_BETWEEN_CASES", "MP_V12_SUBMIT_BRANCH_VARIABLE_MAYBE_UNASSIGNED"));
    }

    private static MistakeSpec m(String code,
                                 String name,
                                 String description,
                                 String misconception,
                                 String mistakeType,
                                 List<String> knowledgeNodeCodes,
                                 List<String> prerequisites,
                                 String severity) {
        return new MistakeSpec(code, name, description, misconception, mistakeType,
                knowledgeNodeCodes, prerequisites, severity);
    }

    private static void addTheme(List<AiStandardLibrarySeed> seeds,
                                 String skillCode,
                                 String category,
                                 String skillName,
                                 String skillDescription,
                                 String learningGoal,
                                 List<String> skillKnowledgeNodes,
                                 List<String> skillPrerequisites,
                                 String severity,
                                 List<MistakeSpec> mistakes,
                                 String improvementCode,
                                 String improvementName,
                                 String improvementDescription,
                                 String studentBenefit,
                                 String teacherExplanation,
                                 List<String> relatedMistakeCodes) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                skillCode,
                category,
                skillName,
                skillDescription,
                learningGoal,
                skillKnowledgeNodes,
                skillPrerequisites,
                severity,
                LANGUAGES);
        mistakes.forEach(mistake -> AiStandardLibrarySeedCatalog.mistake(seeds,
                mistake.code(),
                category.replace("能力点/", "易错点/"),
                mistake.name(),
                mistake.description(),
                mistake.misconception(),
                skillCode,
                mistake.mistakeType(),
                mistake.knowledgeNodeCodes(),
                mistake.prerequisites(),
                mistake.severity(),
                LANGUAGES));
        seeds.add(new AiStandardLibrarySeed(
                AiStandardLibraryLayer.IMPROVEMENT_POINT,
                improvementCode,
                category.replace("能力点/", "提升点/"),
                improvementName,
                improvementDescription,
                "",
                teacherExplanation,
                skillCode,
                "",
                "",
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                improvementDescription,
                studentBenefit,
                "",
                "",
                "",
                skillCode,
                "MEDIUM",
                LANGUAGES,
                relatedMistakeCodes,
                skillKnowledgeNodes,
                skillPrerequisites,
                "把兜底存档的选题或错因类型重写为手写智能条目后，用复盘练习巩固迁移能力。",
                AiStandardLibrarySeedCatalog.VERSION
        ));
    }

    private record MistakeSpec(
            String code,
            String name,
            String description,
            String misconception,
            String mistakeType,
            List<String> knowledgeNodeCodes,
            List<String> prerequisites,
            String severity
    ) {
    }
}
