package com.onlinejudge.learning.standardlibrary.application;

import com.onlinejudge.learning.standardlibrary.domain.AiStandardLibraryLayer;

import java.util.List;

final class AiStandardLibraryV15DensityExpansionSeeds {

    private static final List<String> LANGUAGES = List.of("PYTHON", "CPP17");

    private AiStandardLibraryV15DensityExpansionSeeds() {
    }

    static void addTo(List<AiStandardLibrarySeed> seeds) {
        addStackExpression(seeds);
        addQueueCircular(seeds);
        addBinaryTreeTraversal(seeds);
        addBinaryTreeArrayIndex(seeds);
        addSlidingWindowCount(seeds);
        addBinaryIndexSearch(seeds);
        addRecursionDivideMerge(seeds);
    }

    private static void addStackExpression(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V15_STACK_EXPRESSION_ORDER",
                "能力点/V15栈与表达式",
                "维护栈顶含义、入栈出栈顺序和表达式计算方向",
                "能说明栈里保存的是操作数、运算符、括号还是调用状态，并在每次出栈前确认栈非空、操作数顺序和当前栈顶含义。",
                "做栈题先写栈元素含义，再按每一步 push、pop、top 画快照。",
                List.of("DS.LINEAR.STACK.后进先出", "DS.LINEAR.STACK.空栈检查",
                        "BASIC.EXPR.PRIORITY.括号明确意图"),
                List.of("BASIC.EXPR.ARITH.加减乘除顺序"),
                "HIGH",
                List.of(
                        m("MP_V15_STACK_POP_BEFORE_EMPTY_CHECK",
                                "空栈时先取栈顶或出栈",
                                "后缀表达式、括号匹配或栈模拟中，没有先判断栈非空就读取栈顶或弹出元素，遇到缺失操作数、空串或首个右括号时出错。",
                                "以为每次操作前栈里一定有元素，没有把空栈作为合法边界状态检查。",
                                "RUNTIME",
                                List.of("DS.LINEAR.STACK.空栈检查", "DS.LINEAR.STACK.后进先出"),
                                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                                "HIGH"),
                        m("MP_V15_STACK_TOP_MEANING_SWITCHED",
                                "栈顶含义在不同阶段被混用",
                                "代码一会儿把栈顶当作操作数，一会儿当作运算符或状态码，没有分清当前栈保存的对象类型，导致判断和计算落在错误元素上。",
                                "只记住了用栈，没有给栈元素建立统一含义。",
                                "STATE",
                                List.of("DS.LINEAR.STACK.后进先出", "BASIC.EXPR.PRIORITY.表达式拆分"),
                                List.of("ENG.DEBUG.TRACE.循环状态"),
                                "HIGH"),
                        m("MP_V15_POSTFIX_OPERAND_ORDER_REVERSED",
                                "后缀表达式出栈操作数顺序反了",
                                "计算减法、除法或比较类后缀表达式时，先弹出的右操作数和后弹出的左操作数被反用，导致非交换运算结果错误。",
                                "把两个操作数看成可随意交换，没有注意栈顶对应表达式右侧。",
                                "ORDER",
                                List.of("DS.LINEAR.STACK.后进先出", "BASIC.EXPR.ARITH.加减乘除顺序"),
                                List.of("BASIC.EXPR.PRIORITY.括号明确意图"),
                                "HIGH")),
                "IP_V15_STACK_OPERATION_SNAPSHOT",
                "用栈快照表检查表达式和匹配过程",
                "适用于学生知道要用栈，但经常在空栈、栈顶含义或操作数顺序上出错。",
                "修复后让学生逐步记录输入符号、执行动作、栈内容、栈顶含义和当前结果。",
                "教师可用快照表追问每一次出栈前栈里至少应有几个元素。",
                List.of("MP_V15_STACK_POP_BEFORE_EMPTY_CHECK", "MP_V15_POSTFIX_OPERAND_ORDER_REVERSED"));
    }

    private static void addQueueCircular(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V15_QUEUE_CIRCULAR_STATE",
                "能力点/V15队列与循环队列",
                "维护队首、队尾、长度和循环下标推进",
                "能把先进先出、循环队列、双端操作和 BFS 层次推进中的 front、rear、size、empty/full 条件写成一致状态。",
                "队列题先定义 front 指向谁、rear 指向谁、入队和出队后哪个变量变化。",
                List.of("DS.LINEAR.QUEUE.先进先出", "DS.LINEAR.QUEUE.循环队列",
                        "DS.LINEAR.QUEUE.队空判断"),
                List.of("BASIC.ARRAY.INDEX.下标映射"),
                "HIGH",
                List.of(
                        m("MP_V15_QUEUE_FRONT_BACK_ROLE_SWAPPED",
                                "队首和队尾职责写反",
                                "入队、出队或读取当前元素时混用了 front 和 rear，导致后进入的元素先被处理，或出队后仍读取旧队首。",
                                "只把队列当成数组区间，没有固定 front 负责读取、rear 负责写入的契约。",
                                "STATE",
                                List.of("DS.LINEAR.QUEUE.先进先出", "DS.LINEAR.QUEUE.BFS_队列"),
                                List.of("ENG.DEBUG.TRACE.队列变化"),
                                "HIGH"),
                        m("MP_V15_CIRCULAR_QUEUE_FULL_EMPTY_CONFLATED",
                                "循环队列队空和队满条件混淆",
                                "使用同一组 front、rear 下标判断队空和队满，但没有额外 size 或保留空位，导致满队列被当成空队列或相反。",
                                "看到 front 等于 rear 就直接下结论，没有说明这个状态对应空还是满。",
                                "BOUNDARY",
                                List.of("DS.LINEAR.QUEUE.循环队列", "DS.LINEAR.QUEUE.队空判断"),
                                List.of("BASIC.BRANCH.CASE.边界归属"),
                                "HIGH"),
                        m("MP_V15_QUEUE_MODULO_ADVANCE_MISSING",
                                "循环下标推进时漏取模",
                                "队首或队尾移动到数组末端后没有回到 0，继续访问数组外位置，或覆盖了不该覆盖的元素。",
                                "只在普通数组下标上思考，没有把循环队列的物理位置和逻辑顺序分开。",
                                "BOUNDARY",
                                List.of("DS.LINEAR.QUEUE.循环队列", "BASIC.ARRAY.INDEX.越界访问"),
                                List.of("BASIC.EXPR.ARITH.取模含义"),
                                "HIGH")),
                "IP_V15_QUEUE_STATE_TABLE",
                "用队列状态表检查 front、rear 和 size",
                "适用于学生能说出 FIFO，但循环队列、空满判断和下标回绕经常错。",
                "修复后让学生按操作列出 front、rear、size、队首元素、物理数组内容和逻辑队列顺序。",
                "教师可用状态表判断错误来自职责混用、空满条件还是下标推进。",
                List.of("MP_V15_QUEUE_FRONT_BACK_ROLE_SWAPPED", "MP_V15_CIRCULAR_QUEUE_FULL_EMPTY_CONFLATED"));
    }

    private static void addBinaryTreeTraversal(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V15_BINARY_TREE_TRAVERSAL_SEQUENCE",
                "能力点/V15二叉树遍历",
                "区分前序、中序、后序和递归访问顺序",
                "能根据根、左子树、右子树的访问顺序解释前中后序遍历，并在由遍历序列构造二叉树时正确划分左右子树区间。",
                "二叉树题先标根节点位置，再用中序划分左右子树，最后核对左右递归区间长度。",
                List.of("DS.TREE.TRAVERSAL.前中后序", "DS.TREE.TRAVERSAL.递归遍历",
                        "DS.TREE.BINARY.左右孩子"),
                List.of("BASIC.RECURSION.STATE.递归转移"),
                "HIGH",
                List.of(
                        m("MP_V15_TREE_PREORDER_ROOT_POSITION_MISREAD",
                                "前序序列根节点位置误读",
                                "由前序和中序构造二叉树时，没有把当前前序区间第一个元素当作根，导致整棵树的左右子树划分错位。",
                                "只记得前序包含根，没有把每个递归子区间里的首元素重新视为当前根。",
                                "MODELING",
                                List.of("DS.TREE.TRAVERSAL.前中后序", "DS.TREE.BINARY.左右孩子"),
                                List.of("BASIC.RECURSION.STATE.参数表示状态"),
                                "HIGH"),
                        m("MP_V15_TREE_INORDER_SPLIT_BOUNDARY_OFF",
                                "中序划分左右子树边界差一",
                                "用根在中序中的位置划分左右子树时，把根本身划入左子树或右子树，导致节点重复、漏节点或递归区间长度不一致。",
                                "没有把中序中根的左侧和右侧看成互不包含根的两个区间。",
                                "BOUNDARY",
                                List.of("DS.TREE.TRAVERSAL.前中后序", "BASIC.ARRAY.INDEX.长度与最后下标"),
                                List.of("BASIC.LOOP.BOUNDARY.左闭右闭"),
                                "HIGH"),
                        m("MP_V15_TREE_POSTORDER_LEFT_RIGHT_VISIT_REVERSED",
                                "后序遍历左右子树访问顺序反了",
                                "输出或重建后序遍历时，把左右子树访问顺序反写，导致每个子树内部节点集合正确但序列不符合题意。",
                                "只记住后序最后访问根，没有同时固定左子树先于右子树。",
                                "ORDER",
                                List.of("DS.TREE.TRAVERSAL.前中后序", "DS.TREE.TRAVERSAL.递归遍历"),
                                List.of("BASIC.RECURSION.STATE.递归转移"),
                                "MEDIUM")),
                "IP_V15_BINARY_TREE_SEQUENCE_SPLIT_TABLE",
                "用遍历序列划分表检查二叉树构造",
                "适用于学生会背前中后序定义，但由序列还原或判断遍历结果时经常错。",
                "修复后让学生记录当前根、前序区间、中序区间、左子树长度、右子树长度和返回结果。",
                "教师可用划分表检查根位置、左右边界和递归区间是否一一对应。",
                List.of("MP_V15_TREE_PREORDER_ROOT_POSITION_MISREAD", "MP_V15_TREE_INORDER_SPLIT_BOUNDARY_OFF"));
    }

    private static void addBinaryTreeArrayIndex(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V15_BINARY_TREE_ARRAY_INDEX",
                "能力点/V15二叉树数组表示",
                "维护完全二叉树数组下标、父子公式和边界节点",
                "能区分 0 基和 1 基数组表示下父节点、左孩子、右孩子公式，并判断最后一个节点、空孩子和越界访问。",
                "数组表示二叉树时先写清楚编号从 0 还是 1 开始，再推导父子下标。",
                List.of("DS.TREE.BINARY.数组表示", "DS.TREE.BINARY.完全二叉树",
                        "BASIC.ARRAY.INDEX.0_基下标", "BASIC.ARRAY.INDEX.1_基下标"),
                List.of("BASIC.ARRAY.INDEX.长度与最后下标"),
                "MEDIUM",
                List.of(
                        m("MP_V15_TREE_ARRAY_CHILD_FORMULA_BASE_MIXED",
                                "二叉树数组表示混用 0 基和 1 基公式",
                                "数组从 0 开始存储，却使用 1 基的左右孩子公式，或反过来，导致父子关系整体错位。",
                                "记住了公式外形，没有先确认当前题目或代码的编号体系。",
                                "BOUNDARY",
                                List.of("DS.TREE.BINARY.数组表示", "BASIC.ARRAY.INDEX.下标映射"),
                                List.of("BASIC.ARRAY.INDEX.0_基下标", "BASIC.ARRAY.INDEX.1_基下标"),
                                "HIGH"),
                        m("MP_V15_COMPLETE_TREE_LAST_NODE_BOUNDARY",
                                "完全二叉树最后节点边界判断错",
                                "判断某个节点是否存在左孩子或右孩子时，没有用数组长度限制孩子下标，导致访问不存在的最后一层节点。",
                                "以为完全二叉树每个非叶节点都有两个孩子，没有单独处理最后一层缺口。",
                                "BOUNDARY",
                                List.of("DS.TREE.BINARY.完全二叉树", "BASIC.ARRAY.INDEX.长度与最后下标"),
                                List.of("BASIC.BRANCH.GUARD.特殊情况前置"),
                                "HIGH"),
                        m("MP_V15_BST_LEFT_RIGHT_RULE_REVERSED",
                                "二叉搜索树左右子树规则反用",
                                "判断或插入二叉搜索树时，把小于根的值放到右边或把大于根的值放到左边，导致后续中序或查找性质失效。",
                                "只把二叉树当成左右孩子结构，没有区分二叉搜索树的大小关系不变量。",
                                "INVARIANT",
                                List.of("DS.TREE.BINARY.二叉搜索树直觉", "BASIC.EXPR.COMPARE.边界比较"),
                                List.of("ENG.STYLE.INVARIANT.循环不变量"),
                                "MEDIUM")),
                "IP_V15_BINARY_TREE_INDEX_MAP",
                "用编号映射表检查数组二叉树",
                "适用于学生能看懂二叉树图，但写到数组编号和最后一层边界时容易错。",
                "修复后让学生列出每个下标、节点值、父节点、左孩子、右孩子和是否越界。",
                "教师可用映射表追问当前公式对应的是 0 基还是 1 基。",
                List.of("MP_V15_TREE_ARRAY_CHILD_FORMULA_BASE_MIXED", "MP_V15_COMPLETE_TREE_LAST_NODE_BOUNDARY"));
    }

    private static void addSlidingWindowCount(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V15_WINDOW_COUNT_INVARIANT",
                "能力点/V15滑动窗口计数",
                "维护窗口合法性、计数变量和答案更新不变量",
                "能说明窗口当前包含哪些元素、计数变量表示什么、何时扩张和收缩，以及答案只在合法窗口上更新。",
                "滑动窗口题先写不变量：窗口范围、合法条件、计数字段和答案更新时机。",
                List.of("ALGO.TWO_POINTERS.WINDOW.计数维护", "ALGO.TWO_POINTERS.WINDOW.合法性判断",
                        "ALGO.TWO_POINTERS.WINDOW.答案更新时机"),
                List.of("BASIC.ARRAY.PREFIX.频次统计"),
                "HIGH",
                List.of(
                        m("MP_V15_WINDOW_VALID_COUNT_NOT_RESTORED",
                                "窗口收缩后合法计数没有恢复",
                                "left 移出元素后，违规数量、不同元素数、pH 分类计数或频次数组没有同步恢复，导致窗口合法性判断使用旧状态。",
                                "只移动了窗口端点，没有把窗口内统计量看成必须同步更新的状态。",
                                "STATE",
                                List.of("ALGO.TWO_POINTERS.WINDOW.计数维护", "ALGO.TWO_POINTERS.WINDOW.窗口收缩"),
                                List.of("BASIC.ARRAY.UPDATE.累计量同步更新"),
                                "HIGH"),
                        m("MP_V15_WINDOW_EQUAL_BOUNDARY_SHRINKS_TOO_EARLY",
                                "刚好满足条件的窗口被提前收缩",
                                "题目允许窗口内数量、差值或长度刚好等于阈值，但代码用严格比较把等于边界当成不合法，漏掉合法答案。",
                                "没有把至多、至少、恰好这些条件和比较符号逐一对应。",
                                "BOUNDARY",
                                List.of("ALGO.TWO_POINTERS.WINDOW.合法性判断", "BASIC.EXPR.COMPARE.边界比较"),
                                List.of("BASIC.BRANCH.CASE.边界归属"),
                                "HIGH"),
                        m("MP_V15_WINDOW_LONGEST_UPDATES_ON_INVALID_WINDOW",
                                "最长窗口答案在不合法状态下更新",
                                "窗口已经违反约束但还没有完成收缩，代码就在此时更新最大长度、最大和或计数，导致答案包含非法区间。",
                                "把 right 扩张后的窗口直接当作候选，没有先验证它是否恢复合法。",
                                "ORDER",
                                List.of("ALGO.TWO_POINTERS.WINDOW.答案更新时机", "ALGO.TWO_POINTERS.WINDOW.合法性判断"),
                                List.of("ENG.DEBUG.TRACE.循环状态"),
                                "HIGH")),
                "IP_V15_WINDOW_INVARIANT_CARD",
                "用窗口不变量卡检查计数和答案",
                "适用于学生能写双指针框架，但遇到计数、pH 序列或最长连续子序列时容易错。",
                "修复后让学生每一步记录 left、right、移入值、移出值、计数字段、是否合法和当前答案。",
                "教师可用不变量卡确认学生是否只在合法窗口上更新答案。",
                List.of("MP_V15_WINDOW_VALID_COUNT_NOT_RESTORED", "MP_V15_WINDOW_LONGEST_UPDATES_ON_INVALID_WINDOW"));
    }

    private static void addBinaryIndexSearch(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V15_BINARY_INDEX_BOUNDARY",
                "能力点/V15位置二分边界",
                "维护闭区间、半开区间和边界返回语义",
                "能根据查找目标选择闭区间或半开区间模板，说明 l、r、mid 的含义，以及循环结束后返回的是命中位置还是插入位置。",
                "二分题先写不变量：答案是否仍在区间内，区间端点是否包含，循环结束代表什么。",
                List.of("ALGO.BINARY.INDEX.闭区间模板", "ALGO.BINARY.INDEX.半开区间模板",
                        "ALGO.BINARY.INDEX.lower_bound", "ALGO.BINARY.INDEX.边界返回"),
                List.of("BASIC.EXPR.COMPARE.边界比较"),
                "HIGH",
                List.of(
                        m("MP_V15_BINARY_TEMPLATE_MIXES_CLOSED_AND_HALF_OPEN",
                                "二分混用闭区间和半开区间更新规则",
                                "循环条件按闭区间写，端点更新却按半开区间移动，或相反，导致候选位置被漏掉或死循环。",
                                "背了多个模板片段，没有给 l 和 r 写清楚是否包含端点。",
                                "BOUNDARY",
                                List.of("ALGO.BINARY.INDEX.闭区间模板", "ALGO.BINARY.INDEX.半开区间模板"),
                                List.of("BASIC.LOOP.WHILE.循环条件"),
                                "HIGH"),
                        m("MP_V15_BINARY_MID_STUCK_ON_TWO_ELEMENTS",
                                "二分剩两个元素时 mid 不推进",
                                "区间只剩两个候选时，mid 和端点更新没有排除旧 mid，导致 l、r 不变化并进入死循环。",
                                "只看一般情况缩小区间，没有专门检查相邻端点时更新后是否真的变短。",
                                "RUNTIME",
                                List.of("ALGO.BINARY.INDEX.边界返回", "BASIC.LOOP.WHILE.死循环识别"),
                                List.of("ENG.DEBUG.TRACE.循环状态"),
                                "HIGH"),
                        m("MP_V15_BINARY_RETURN_INSERT_POSITION_OFF_BY_ONE",
                                "lower_bound 返回插入位置差一",
                                "查找第一个满足条件的位置时，循环结束后返回了最后一个不满足的位置或相邻位置，导致插入、计数或区间判断整体偏一。",
                                "没有把循环结束时 l 和 r 各自代表的含义写出来。",
                                "BOUNDARY",
                                List.of("ALGO.BINARY.INDEX.lower_bound", "ALGO.BINARY.INDEX.边界返回"),
                                List.of("BASIC.ARRAY.INDEX.下标映射"),
                                "HIGH")),
                "IP_V15_BINARY_TRACE_TABLE",
                "用 l/r/mid 表检查二分不变量",
                "适用于学生会套二分模板，但经常在端点包含、返回位置和死循环边界上出错。",
                "修复后让学生列出每轮 l、r、mid、比较结果、保留区间和循环结束含义。",
                "教师可用追踪表判断学生是否能解释答案为什么没有被端点更新丢掉。",
                List.of("MP_V15_BINARY_TEMPLATE_MIXES_CLOSED_AND_HALF_OPEN", "MP_V15_BINARY_RETURN_INSERT_POSITION_OFF_BY_ONE"));
    }

    private static void addRecursionDivideMerge(List<AiStandardLibrarySeed> seeds) {
        addTheme(seeds,
                "SK_V15_RECURSION_DIVIDE_MERGE",
                "能力点/V15递归分治",
                "维护递归拆分、边界返回和结果合并契约",
                "能说明递归函数处理的子问题范围、如何拆成更小问题、边界返回什么，以及多个子结果如何合并成父问题答案。",
                "递归题先写函数契约，再画三层调用树，最后标出每层合并动作。",
                List.of("BASIC.RECURSION.DIVIDE.拆分问题", "BASIC.RECURSION.DIVIDE.合并结果",
                        "BASIC.RECURSION.DIVIDE.树形递归"),
                List.of("BASIC.RECURSION.BASE.边界返回值"),
                "HIGH",
                List.of(
                        m("MP_V15_RECURSION_SPLIT_DOES_NOT_COVER_ALL_PARTS",
                                "递归拆分没有覆盖完整区间",
                                "分治时左右子问题区间之间存在空洞或重叠，导致部分元素、节点或状态没有被处理，或被重复处理。",
                                "只看到要拆成两半，没有核对左右区间并起来是否等于原问题且互不重叠。",
                                "BOUNDARY",
                                List.of("BASIC.RECURSION.DIVIDE.拆分问题", "BASIC.ARRAY.INDEX.长度与最后下标"),
                                List.of("BASIC.LOOP.BOUNDARY.左闭右闭"),
                                "HIGH"),
                        m("MP_V15_RECURSION_MERGE_OMITS_ONE_BRANCH",
                                "递归合并时漏掉一个分支结果",
                                "左右子问题都递归计算了，但父层只返回其中一边，或只累加一部分结果，导致答案缺失。",
                                "把递归调用当成已经完成整个答案，没有明确父层要如何合并所有子结果。",
                                "LOGIC",
                                List.of("BASIC.RECURSION.DIVIDE.合并结果", "BASIC.RECURSION.STATE.递归转移"),
                                List.of("BASIC.FUNCTION.RETURN.完整返回路径"),
                                "HIGH"),
                        m("MP_V15_RECURSION_SHARED_ACCUMULATOR_LEAKS",
                                "树形递归共享累计变量串分支",
                                "递归左右分支共用同一个累计变量、列表或状态对象，父层合并前分支结果互相污染，导致计数或路径结果异常。",
                                "没有区分每个子问题的局部结果和全局累计结果。",
                                "STATE",
                                List.of("BASIC.RECURSION.DIVIDE.树形递归", "BASIC.RECURSION.STATE.回溯恢复"),
                                List.of("BASIC.FUNCTION.PARAM.可变对象风险"),
                                "HIGH")),
                "IP_V15_RECURSION_CALL_TREE_TABLE",
                "用调用树检查递归拆分和合并",
                "适用于学生会写递归，但边界返回、区间拆分和结果合并经常不稳定。",
                "修复后让学生画三层调用树，标出每个节点的输入范围、边界返回值和合并结果。",
                "教师可用调用树判断错误来自拆分覆盖、边界含义还是父层合并。",
                List.of("MP_V15_RECURSION_SPLIT_DOES_NOT_COVER_ALL_PARTS", "MP_V15_RECURSION_MERGE_OMITS_ONE_BRANCH"));
    }

    private static MistakeSpec m(String code,
                                 String name,
                                 String description,
                                 String misconception,
                                 String mistakeType,
                                 List<String> knowledgeNodeCodes,
                                 List<String> prerequisites,
                                 String severity) {
        return new MistakeSpec(code, name, description, misconception, mistakeType,
                knowledgeNodeCodes, prerequisites, severity);
    }

    private static void addTheme(List<AiStandardLibrarySeed> seeds,
                                 String skillCode,
                                 String category,
                                 String skillName,
                                 String skillDescription,
                                 String learningGoal,
                                 List<String> skillKnowledgeNodes,
                                 List<String> skillPrerequisites,
                                 String severity,
                                 List<MistakeSpec> mistakes,
                                 String improvementCode,
                                 String improvementName,
                                 String improvementDescription,
                                 String studentBenefit,
                                 String teacherExplanation,
                                 List<String> relatedMistakeCodes) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                skillCode,
                category,
                skillName,
                skillDescription,
                learningGoal,
                skillKnowledgeNodes,
                skillPrerequisites,
                severity,
                LANGUAGES);
        mistakes.forEach(mistake -> AiStandardLibrarySeedCatalog.mistake(seeds,
                mistake.code(),
                category.replace("能力点/", "易错点/"),
                mistake.name(),
                mistake.description(),
                mistake.misconception(),
                skillCode,
                mistake.mistakeType(),
                mistake.knowledgeNodeCodes(),
                mistake.prerequisites(),
                mistake.severity(),
                LANGUAGES));
        seeds.add(new AiStandardLibrarySeed(
                AiStandardLibraryLayer.IMPROVEMENT_POINT,
                improvementCode,
                category.replace("能力点/", "提升点/"),
                improvementName,
                improvementDescription,
                "",
                teacherExplanation,
                skillCode,
                "",
                "",
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                improvementDescription,
                studentBenefit,
                "",
                "",
                "",
                skillCode,
                "MEDIUM",
                LANGUAGES,
                relatedMistakeCodes,
                skillKnowledgeNodes,
                skillPrerequisites,
                "用结构表、状态表或追踪表把高频考点错误转化为可复盘的检查动作。",
                AiStandardLibrarySeedCatalog.VERSION
        ));
    }

    private record MistakeSpec(
            String code,
            String name,
            String description,
            String misconception,
            String mistakeType,
            List<String> knowledgeNodeCodes,
            List<String> prerequisites,
            String severity
    ) {
    }
}
