package com.onlinejudge.learning.standardlibrary.application;

import java.util.List;

final class AiStandardLibraryV7DetailSeeds {

    private static final List<String> LANGUAGES = List.of("PYTHON", "CPP17");

    private AiStandardLibraryV7DetailSeeds() {
    }

    static void addTo(List<AiStandardLibrarySeed> seeds) {
        addCountingDp(seeds);
        addStructuredDp(seeds);
        addBinarySearchDetail(seeds);
        addPrefixDifferenceDetail(seeds);
        addGraphSearchDetail(seeds);
        addGraphRelaxationAndTopo(seeds);
        addStringDetail(seeds);
        addMapFrequencyDetail(seeds);
        addNumericPrecisionDetail(seeds);
        addMultiCaseStateReset(seeds);
    }

    private static void addCountingDp(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V7_DP_COUNTING_BASE_ANSWER_CONTRACT",
                "能力点/DP计数",
                "定义计数 DP 的初值、转移含义和答案位置",
                "能说明空方案、非法状态、取模时机和最终答案下标，避免只把计数 DP 当成普通累加。",
                "计数 DP 先问“什么算一种方案”，再决定初始 1 放在哪里、答案从哪里取。",
                List.of("ALGO.DP.CLASSIC.计数_DP", "ALGO.DP.INIT.空方案", "ALGO.DP.STATE.答案位置", "MATH.COUNT.RECUR.递推式"),
                List.of("ALGO.DP.STATE.状态含义", "MATH.NUMBER.MOD.模意义保持"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_DP_COUNT_EMPTY_SCHEME_OMITTED",
                "易错点/DP计数",
                "计数 DP 漏掉空方案初值",
                "方案数 DP 中没有把空方案（不选任何元素）、长度为 0 或起点状态初始化为 1，导致后续所有合法方案都无法被递推出来。",
                "把初始值 1 看成某个真实元素贡献，没有理解它代表递推的起点和空方案。",
                "SK_V7_DP_COUNTING_BASE_ANSWER_CONTRACT",
                "INITIALIZATION",
                List.of("ALGO.DP.INIT.空方案", "ALGO.DP.CLASSIC.计数_DP", "MATH.COUNT.RECUR.初始项"),
                List.of("ALGO.DP.INIT.初始值"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_DP_COUNT_ANSWER_AT_WRONG_INDEX",
                "易错点/DP计数",
                "计数 DP 从错误状态取答案",
                "DP 表已经计算出多个终止状态，但代码从固定下标、最后一格或未完成状态取答案，导致漏掉合法方案或多算非法方案。",
                "只把 dp 数组填完，没有回到状态定义确认哪些状态才表示题目要求的终点。",
                "SK_V7_DP_COUNTING_BASE_ANSWER_CONTRACT",
                "STATE",
                List.of("ALGO.DP.STATE.答案位置", "ALGO.DP.TRANSITION.转移边界", "ALGO.DP.CLASSIC.计数_DP"),
                List.of("CONTEST.READING.OUTPUT.输出方案数"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_DP_COUNT_NEGATIVE_MOD_NOT_NORMALIZED",
                "易错点/DP计数",
                "计数转移中减法取模未修正负数",
                "容斥或区间计数 DP 出现减法后直接取模，语言保留负余数，导致后续方案数持续偏负或偏小。",
                "把取模当成最后格式化输出，没有保证每次加减后数值仍落在合法模范围内。",
                "SK_V7_DP_COUNTING_BASE_ANSWER_CONTRACT",
                "VALUE_RANGE",
                List.of("MATH.NUMBER.MOD.负数取模修正", "MATH.NUMBER.MOD.模意义保持", "ALGO.DP.CLASSIC.计数_DP"),
                List.of("BASIC.EXPR.ARITH.取模含义"),
                "HIGH",
                LANGUAGES);
    }

    private static void addStructuredDp(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V7_DP_STRUCTURED_STATE_DEPENDENCY",
                "能力点/DP结构化状态",
                "识别树形、掩码和滚动 DP 的依赖方向",
                "能根据父子关系、二进制集合和滚动层含义，判断转移来源、状态更新顺序和初始化边界。",
                "结构化 DP 先画依赖图：谁依赖谁、当前层能不能再次使用、mask 每一位代表什么。",
                List.of("ALGO.DP.CLASSIC.树形_DP_入门", "MATH.BIT.MASK.掩码转移", "ALGO.DP.STATE.状态压缩直觉", "ALGO.DP.INIT.滚动数组初始化"),
                List.of("ALGO.DP.STATE.状态含义", "DS.TREE.TRAVERSAL.DFS_遍历"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_TREE_DP_PARENT_CHILD_DIRECTION_REVERSED",
                "易错点/DP结构化状态",
                "树形 DP 父子转移方向写反",
                "树形 DP 需要先汇总子树再更新父节点，但代码让父节点状态提前覆盖子节点，导致子树贡献丢失或重复。",
                "只把树当成普通图 DFS，没有说明每个节点的 dp 值表示子树、父链还是全局结果。",
                "SK_V7_DP_STRUCTURED_STATE_DEPENDENCY",
                "TRANSITION",
                List.of("ALGO.DP.CLASSIC.树形_DP_入门", "DS.TREE.TRAVERSAL.DFS_遍历", "ALGO.DP.TRANSITION.枚举决策"),
                List.of("DS.TREE.BASIC.子树"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_DP_BITMASK_NEXT_STATE_NOT_UPDATED",
                "易错点/DP结构化状态",
                "状态压缩 DP 转移后没有更新 mask",
                "选择了新对象或完成了新条件，但转移时仍写回原 mask，导致状态没有推进或同一对象被重复选择。",
                "只关注当前 mask 是否可达，没有明确选择动作会把哪一位从 0 变成 1。",
                "SK_V7_DP_STRUCTURED_STATE_DEPENDENCY",
                "STATE",
                List.of("MATH.BIT.MASK.掩码转移", "MATH.BIT.MASK.状态判断", "ALGO.DP.STATE.状态压缩直觉"),
                List.of("MATH.BIT.OP.设置清除位"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_DP_ROLLING_INIT_CARRIED_TO_NEXT_CASE",
                "易错点/DP结构化状态",
                "滚动 DP 新一层没有重新初始化",
                "滚动数组进入下一层前保留了上一层不应存在的值，使旧状态混入当前层转移。",
                "只复用了数组空间，没有区分保留旧层作为来源和清空新层作为目标这两个动作。",
                "SK_V7_DP_STRUCTURED_STATE_DEPENDENCY",
                "INITIALIZATION",
                List.of("ALGO.DP.INIT.滚动数组初始化", "ALGO.DP.TRANSITION.从前往后", "ALGO.DP.TRANSITION.从后往前"),
                List.of("BASIC.ARRAY.UPDATE.临时数组"),
                "HIGH",
                LANGUAGES);
    }

    private static void addBinarySearchDetail(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V7_BINARY_TEMPLATE_PRECISION_CONTRACT",
                "能力点/二分细节",
                "区分位置二分、答案二分和精度二分契约",
                "能把闭区间、半开区间、返回位置、精度停止条件和 check 单调方向写成一致的不变量。",
                "二分前先写合同：查什么、保留什么、什么时候停、停下后哪个变量是答案。",
                List.of("ALGO.BINARY.INDEX.闭区间模板", "ALGO.BINARY.INDEX.半开区间模板", "ALGO.BINARY.INDEX.边界返回", "ALGO.BINARY.ANSWER.精度二分"),
                List.of("ALGO.BINARY.ANSWER.单调性证明", "BASIC.EXPR.COMPARE.边界比较"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_BINARY_FLOAT_STOPS_BY_EQUALITY",
                "易错点/二分细节",
                "浮点二分用相等作为停止条件",
                "精度二分中使用 left == right 或 check(mid) 恰好相等作为退出条件，浮点误差下循环无法稳定结束或答案精度不足。",
                "把整数二分的相等终止套到实数区间，没有设置 eps 或固定迭代次数。",
                "SK_V7_BINARY_TEMPLATE_PRECISION_CONTRACT",
                "RUNTIME",
                List.of("ALGO.BINARY.ANSWER.精度二分", "BASIC.TYPE.FLOAT.浮点误差", "BASIC.EXPR.COMPARE.浮点比较"),
                List.of("BASIC.TYPE.FLOAT.小数比较"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_BINARY_HALF_OPEN_RIGHT_USED_AS_VALID_INDEX",
                "易错点/二分细节",
                "半开区间右端被当成有效下标",
                "使用 [left, right) 模板时把 right 当作最后一个合法位置访问，导致越界或返回位置偏后一位。",
                "知道半开区间能简化循环，却没有坚持 right 表示第一个不在候选区间内的位置。",
                "SK_V7_BINARY_TEMPLATE_PRECISION_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.BINARY.INDEX.半开区间模板", "ALGO.BINARY.INDEX.边界返回", "BASIC.ARRAY.INDEX.长度与最后下标"),
                List.of("BASIC.LOOP.BOUNDARY.左闭右开"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_BINARY_MONOTONIC_DIRECTION_AFTER_SORT_MISREAD",
                "易错点/二分细节",
                "排序方向改变后单调判断方向仍沿用旧逻辑",
                "数组按降序或按自定义关键字排序后，check 的真假变化方向与升序模板相反，但代码仍按原方向移动边界。",
                "把二分模板和排序结果分开记，没有重新确认当前位置左侧和右侧分别满足什么性质。",
                "SK_V7_BINARY_TEMPLATE_PRECISION_CONTRACT",
                "MODELING",
                List.of("ALGO.BINARY.ANSWER.单调性证明", "ALGO.SORT.BASIC.升序降序", "ALGO.BINARY.ANSWER.check_函数"),
                List.of("ALGO.SORT.BASIC.自定义比较"),
                "HIGH",
                LANGUAGES);
    }

    private static void addPrefixDifferenceDetail(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V7_PREFIX_DIFF_DIMENSION_INDEX_CONTRACT",
                "能力点/前缀差分细节",
                "统一前缀差分的维度、补零和端点事件",
                "能说明一维前缀、二维前缀和差分数组的下标含义，并把区间端点转换成加减事件。",
                "前缀差分先定义数组含义，再写公式；公式每个加减号都要能指回一个区域或端点。",
                List.of("ALGO.PREFIX.SUM.空前缀", "ALGO.PREFIX.SUM.下标偏移", "ALGO.PREFIX.DIFF.边界加减", "ALGO.PREFIX.MATRIX.边界补零"),
                List.of("BASIC.ARRAY.INDEX.下标映射"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_PREFIX_ARRAY_NOT_PADDED_FOR_EMPTY_PREFIX",
                "易错点/前缀差分细节",
                "前缀数组没有预留空前缀",
                "需要使用 pre[0]=0 表示空前缀的场景中，代码直接用原数组长度存前缀，导致区间左端为 0 或 1 时公式分支混乱。",
                "只记住 pre[r]-pre[l-1]，没有统一前缀数组下标和原数组下标的对应关系。",
                "SK_V7_PREFIX_DIFF_DIMENSION_INDEX_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.PREFIX.SUM.空前缀", "ALGO.PREFIX.SUM.下标偏移", "BASIC.ARRAY.INDEX.下标映射"),
                List.of("BASIC.ARRAY.INDEX.0_基下标"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_DIFF_RECTANGLE_CORNER_UPDATE_INCOMPLETE",
                "易错点/前缀差分细节",
                "二维区间差分四个角更新不完整",
                "对矩形区域加值时只更新了左上和右下，漏掉另外两个角的反向事件，导致还原后整行或整列被错误影响。",
                "把二维差分当成一维差分简单类比，没有画出矩形四个边界事件。",
                "SK_V7_PREFIX_DIFF_DIMENSION_INDEX_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.PREFIX.DIFF.区间加", "ALGO.PREFIX.DIFF.边界加减", "ALGO.PREFIX.MATRIX.坐标偏移"),
                List.of("BASIC.ARRAY.MATRIX.行列含义"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_PREFIX_MATRIX_BUILD_ROW_COL_ORDER_WRONG",
                "易错点/前缀差分细节",
                "二维前缀构建时行列累计方向混乱",
                "构建二维前缀时把上方、左方和左上角的依赖位置写错，导致整张前缀表从某一行列开始偏差。",
                "背了容斥公式，但没有确认 pre[i][j] 表示的是哪个矩形区域。",
                "SK_V7_PREFIX_DIFF_DIMENSION_INDEX_CONTRACT",
                "BOUNDARY",
                List.of("ALGO.PREFIX.MATRIX.容斥公式", "ALGO.PREFIX.MATRIX.行列混淆", "BASIC.ARRAY.MATRIX.行列含义"),
                List.of("ALGO.PREFIX.MATRIX.边界补零"),
                "HIGH",
                LANGUAGES);
    }

    private static void addGraphSearchDetail(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V7_GRAPH_SEARCH_LAYER_VISITED_CONTRACT",
                "能力点/图搜索细节",
                "定义 BFS 层次、起点集合和状态判重维度",
                "能区分单源和多源、节点和状态、入队和出队标记，以及距离层数如何推进。",
                "BFS 的队列里放的不是变量名，而是一个完整状态；距离含义和 visited 维度必须跟状态一致。",
                List.of("ALGO.SEARCH.BFS.队列层次", "ALGO.SEARCH.BFS.多源_BFS", "ALGO.SEARCH.BFS.访问标记", "ALGO.SEARCH.STATE.状态编码"),
                List.of("DS.LINEAR.QUEUE.BFS_队列"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_BFS_MULTI_SOURCE_ENQUEUES_ONLY_ONE_START",
                "易错点/图搜索细节",
                "多源 BFS 只把一个起点入队",
                "题目有多个等价起点或多个感染源，但代码只从第一个起点开始搜索，没有把所有源作为第 0 层同时入队，导致其他源的最短距离和覆盖范围缺失。",
                "把多源 BFS 当成重复运行单源 BFS，没有意识到所有源应同时作为第 0 层入队。",
                "SK_V7_GRAPH_SEARCH_LAYER_VISITED_CONTRACT",
                "INITIALIZATION",
                List.of("ALGO.SEARCH.BFS.多源_BFS", "ALGO.SEARCH.BFS.队列层次", "DS.LINEAR.QUEUE.BFS_队列"),
                List.of("ALGO.SEARCH.BFS.状态入队"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_BFS_DISTANCE_INCREMENTS_PER_NODE",
                "易错点/图搜索细节",
                "BFS 距离按出队节点数递增",
                "代码每弹出一个节点就把步数加一，而不是按层推进或由父状态距离加一，导致同一层节点距离不同。",
                "只看到队列在不断弹出，没有维护当前层大小或每个状态自己的距离。",
                "SK_V7_GRAPH_SEARCH_LAYER_VISITED_CONTRACT",
                "STATE",
                List.of("ALGO.SEARCH.BFS.最短步数", "ALGO.SEARCH.BFS.队列层次", "ENG.DEBUG.TRACE.队列变化"),
                List.of("DS.LINEAR.QUEUE.先进先出"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_SEARCH_VISITED_KEY_MISSING_RESOURCE_DIMENSION",
                "易错点/图搜索细节",
                "搜索判重键少了资源或阶段维度",
                "状态中除了位置还包含剩余钥匙、体力、方向或已用次数，但 visited 只按位置记录，导致不同状态被错误合并。",
                "把“到达同一格子”当成同一状态，没有判断后续能力是否也相同。",
                "SK_V7_GRAPH_SEARCH_LAYER_VISITED_CONTRACT",
                "STATE",
                List.of("ALGO.SEARCH.STATE.状态编码", "ALGO.SEARCH.STATE.判重", "ALGO.DP.STATE.维度选择"),
                List.of("ALGO.SEARCH.STATE.状态转移生成"),
                "HIGH",
                LANGUAGES);
    }

    private static void addGraphRelaxationAndTopo(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V7_GRAPH_RELAXATION_AND_TOPO_CONTRACT",
                "能力点/图算法细节",
                "维护最短路松弛和拓扑推进的状态契约",
                "能说明距离初值、松弛条件、堆中陈旧状态处理、入度变化和多解顺序要求。",
                "图算法每个状态变量都要有不变量：dist 是否最终确定、入度何时减少、队列顺序是否有题目约束。",
                List.of("ALGO.GRAPH.SHORTEST.距离初始化", "ALGO.GRAPH.SHORTEST.松弛操作", "ALGO.GRAPH.SHORTEST.Dijkstra", "ALGO.GRAPH.TOPO.多解顺序"),
                List.of("DS.GRAPH.MODEL.权值含义"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_DIJKSTRA_STALE_HEAP_STATE_NOT_SKIPPED",
                "易错点/图算法细节",
                "Dijkstra 没有跳过堆中的陈旧距离",
                "同一节点多次入堆后，代码弹出旧的较大距离仍继续松弛，可能造成复杂度膨胀或覆盖辅助状态。",
                "只把堆当成自动更新的容器，没有意识到旧条目仍会留在优先队列里。",
                "SK_V7_GRAPH_RELAXATION_AND_TOPO_CONTRACT",
                "COMPLEXITY",
                List.of("ALGO.GRAPH.SHORTEST.Dijkstra", "ALGO.GRAPH.SHORTEST.松弛操作", "DS.TREE.BINARY.堆结构直觉"),
                List.of("DS.SET_MAP.MAP.键值关系"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_SHORTEST_DISTANCE_INITIALIZED_TO_ZERO",
                "易错点/图算法细节",
                "最短路距离数组全部初始化为 0",
                "除起点外的距离也被初始化为 0，导致松弛条件无法区分未到达节点和真实零距离。",
                "把数值数组默认 0 当成安全初值，没有用无穷大表示暂不可达状态。",
                "SK_V7_GRAPH_RELAXATION_AND_TOPO_CONTRACT",
                "INITIALIZATION",
                List.of("ALGO.GRAPH.SHORTEST.距离初始化", "ALGO.DP.INIT.无穷大", "DS.GRAPH.MODEL.权值含义"),
                List.of("BASIC.TYPE.INTEGER.long_long_范围"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_TOPO_MULTIPLE_ORDER_TIE_RULE_IGNORED",
                "易错点/图算法细节",
                "拓扑排序多解时忽略题目指定顺序",
                "题目要求字典序最小、编号最小优先或特定稳定顺序，但代码使用普通队列导致合法顺序不符合输出规则。",
                "只判断是否存在拓扑序，没有继续阅读多解情况下的输出要求。",
                "SK_V7_GRAPH_RELAXATION_AND_TOPO_CONTRACT",
                "MODELING",
                List.of("ALGO.GRAPH.TOPO.多解顺序", "ALGO.GRAPH.TOPO.队列推进", "ALGO.SORT.BASIC.自定义比较"),
                List.of("CONTEST.READING.OUTPUT.多答案要求"),
                "MEDIUM",
                LANGUAGES);
    }

    private static void addStringDetail(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V7_STRING_BOUNDARY_ENCODING_CONTRACT",
                "能力点/字符串细节",
                "统一字符转换、子串边界和匹配推进规则",
                "能说明字符串下标、切片长度、字符编码、数字字符转换和匹配后下一次查找的起点。",
                "字符串题先把位置、长度和字符值分开；字符 '3'、数字 3 和下标 3 不是同一个东西。",
                List.of("BASIC.STRING.CHAR.数字字符转换", "BASIC.STRING.SUBSTRING.起止位置", "BASIC.STRING.SUBSTRING.长度参数", "BASIC.STRING.MATCH.统计出现次数"),
                List.of("BASIC.ARRAY.INDEX.下标映射"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_SUBSTRING_LENGTH_USED_AS_END_INDEX",
                "易错点/字符串细节",
                "子串长度参数被当作结束下标",
                "语言 API 要求传入起点和长度时，代码把第二个参数当成右端下标，导致截取范围过长或过短。",
                "只用自然语言理解“从 l 到 r”，没有核对当前语言的 substring/slice 参数含义。",
                "SK_V7_STRING_BOUNDARY_ENCODING_CONTRACT",
                "BOUNDARY",
                List.of("BASIC.STRING.SUBSTRING.长度参数", "BASIC.STRING.SUBSTRING.起止位置", "BASIC.STRING.SUBSTRING.越界保护"),
                List.of("BASIC.ARRAY.INDEX.长度与最后下标"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_CHAR_DIGIT_USED_AS_NUMERIC_VALUE",
                "易错点/字符串细节",
                "数字字符没有转换就参与数值计算",
                "代码把字符 '0' 到 '9' 直接当作数值 0 到 9 使用，实际参与运算的是字符编码或字符串片段。",
                "看到字符长得像数字，就忽略了字符类型到整数类型的显式转换。",
                "SK_V7_STRING_BOUNDARY_ENCODING_CONTRACT",
                "VALUE_RANGE",
                List.of("BASIC.STRING.CHAR.数字字符转换", "BASIC.TYPE.CHAR_BOOL.字符编码", "BASIC.TYPE.CHAR_BOOL.字符数字转换"),
                List.of("BASIC.TYPE.INTEGER.int_范围"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_STRING_OVERLAPPING_MATCH_SKIPPED",
                "易错点/字符串细节",
                "统计子串出现次数时跳过重叠匹配",
                "题目允许重叠出现，但代码每次命中后直接跳过整个模式串长度，导致重叠位置没有被统计。",
                "没有先确认两个匹配共享字符时是否算作两次出现。",
                "SK_V7_STRING_BOUNDARY_ENCODING_CONTRACT",
                "BOUNDARY",
                List.of("BASIC.STRING.MATCH.统计出现次数", "BASIC.STRING.MATCH.查找出现位置", "BASIC.STRING.MATCH.逐位比较"),
                List.of("BASIC.LOOP.FOR.步长变化"),
                "MEDIUM",
                LANGUAGES);
    }

    private static void addMapFrequencyDetail(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V7_MAP_FREQUENCY_KEY_CONTRACT",
                "能力点/映射频次细节",
                "定义 map 的键值含义、默认值和重复贡献",
                "能说明 map 的 key 表示哪个状态或对象，value 表示是否出现、次数、位置还是累计贡献，并处理首次出现。",
                "写 map 前先写表头：key 是什么，value 是什么，重复元素如何改变 value。",
                List.of("DS.SET_MAP.MAP.键值关系", "DS.SET_MAP.MAP.频次统计", "DS.SET_MAP.MAP.默认值", "DS.SET_MAP.HASH.自定义键风险"),
                List.of("DS.SET_MAP.SET.去重"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_MAP_DEFAULT_VALUE_DROPS_FIRST_OCCURRENCE",
                "易错点/映射频次细节",
                "map 首次出现默认值处理丢掉第一次贡献",
                "频次或累计 map 中第一次遇到 key 时没有从 1 或当前贡献开始，导致每个不同 key 都少算一次。",
                "只处理了 key 已存在时如何累加，没有定义 key 不存在时 value 的初始含义。",
                "SK_V7_MAP_FREQUENCY_KEY_CONTRACT",
                "INITIALIZATION",
                List.of("DS.SET_MAP.MAP.默认值", "DS.SET_MAP.MAP.键不存在处理", "DS.SET_MAP.MAP.频次统计"),
                List.of("BASIC.BRANCH.CASE.默认分支"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_MAP_KEY_MISSING_STATE_DIMENSION",
                "易错点/映射频次细节",
                "map 键少了一维状态信息",
                "题目状态需要由多个变量共同确定，但代码只用其中一个变量作 key，导致不同对象被合并到同一桶。",
                "把某个数值相同当成状态相同，没有把位置、类别、时间或方向等维度纳入键。",
                "SK_V7_MAP_FREQUENCY_KEY_CONTRACT",
                "STATE",
                List.of("DS.SET_MAP.MAP.键值关系", "DS.SET_MAP.HASH.自定义键风险", "ALGO.SEARCH.STATE.状态编码"),
                List.of("ALGO.DP.STATE.维度选择"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_SET_USED_WHEN_DUPLICATE_COUNT_MATTERS",
                "易错点/映射频次细节",
                "需要重复次数时误用 set 去重",
                "题目答案依赖元素出现次数、重复贡献或多重集合关系，但代码用 set 只保留是否出现。",
                "把“是否存在”当成“出现了几次”，没有判断重复元素是否会改变答案。",
                "SK_V7_MAP_FREQUENCY_KEY_CONTRACT",
                "MODELING",
                List.of("DS.SET_MAP.SET.去重", "DS.SET_MAP.MAP.频次统计", "DS.SET_MAP.SET.重复插入"),
                List.of("CONTEST.READING.OUTPUT.输出方案数"),
                "HIGH",
                LANGUAGES);
    }

    private static void addNumericPrecisionDetail(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V7_NUMERIC_RANGE_PRECISION_CONTRACT",
                "能力点/数值边界细节",
                "估算中间表达式范围并处理浮点比较",
                "能估算乘法、累计、除法和浮点比较的中间值范围，选择正确类型、转换时机和 eps 策略。",
                "数值题不只看答案范围，还要看计算过程中最大会长到多少。",
                List.of("BASIC.TYPE.INTEGER.整型溢出", "BASIC.TYPE.INTEGER.long_long_范围", "BASIC.TYPE.FLOAT.小数比较", "BASIC.EXPR.ARITH.整数除法"),
                List.of("CONTEST.READING.CONSTRAINT.值域范围"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_LONG_LONG_CAST_AFTER_MULTIPLICATION",
                "易错点/数值边界细节",
                "乘法溢出后才转换为 long long",
                "表达式先用 int 完成乘法再赋给 long long，溢出已经发生，最终变量类型无法恢复正确值。",
                "只看左侧变量类型，没有检查右侧表达式每一步使用的运算类型。",
                "SK_V7_NUMERIC_RANGE_PRECISION_CONTRACT",
                "VALUE_RANGE",
                List.of("BASIC.TYPE.INTEGER.整型溢出", "BASIC.TYPE.INTEGER.long_long_范围", "MATH.NUMBER.MOD.大数防溢出"),
                List.of("BASIC.EXPR.PRIORITY.括号明确意图"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_INTEGER_DIVISION_USED_FOR_RATIO",
                "易错点/数值边界细节",
                "需要比例时误用整数除法",
                "平均值、概率、斜率或比例计算中两个整数直接相除，小数部分被截断后再转成浮点也无法恢复。",
                "把结果变量设成 double 就以为整条表达式都是浮点计算。",
                "SK_V7_NUMERIC_RANGE_PRECISION_CONTRACT",
                "VALUE_RANGE",
                List.of("BASIC.EXPR.ARITH.整数除法", "BASIC.TYPE.FLOAT.整数除法误用", "BASIC.TYPE.FLOAT.浮点误差"),
                List.of("BASIC.TYPE.FLOAT.小数比较"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_FLOAT_EPS_COMPARISON_DIRECTION_WRONG",
                "易错点/数值边界细节",
                "浮点 eps 比较方向写反",
                "判断 a 是否不小于 b、是否相等或是否超过阈值时 eps 加减方向错误，把临界值附近的结果归到相反分支。",
                "只知道浮点要加 eps，没有先写清楚边界点应该判真还是判假。",
                "SK_V7_NUMERIC_RANGE_PRECISION_CONTRACT",
                "BOUNDARY",
                List.of("BASIC.TYPE.FLOAT.小数比较", "BASIC.EXPR.COMPARE.浮点比较", "BASIC.TYPE.FLOAT.精度输出"),
                List.of("BASIC.EXPR.COMPARE.边界比较"),
                "MEDIUM",
                LANGUAGES);
    }

    private static void addMultiCaseStateReset(List<AiStandardLibrarySeed> seeds) {
        AiStandardLibrarySeedCatalog.skill(seeds,
                "SK_V7_MULTICASE_STATE_RESET_CONTRACT",
                "能力点/多组状态细节",
                "确定多组数据中每个状态的生命周期",
                "能区分跨组共享配置、每组输入数据、每组临时状态和输出编号，并把初始化放在正确层级。",
                "多组数据先给变量贴生命周期标签：全局常量、每组重置、每次循环更新。",
                List.of("BASIC.IO.MULTI_CASE.每组状态重置", "BASIC.IO.MULTI_CASE.显式_T_组循环", "BASIC.IO.MULTI_CASE.多组输出格式", "ENG.ERROR.WRONG_ANSWER.状态未重置"),
                List.of("BASIC.LOOP.NESTED.重复初始化位置"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_MULTICASE_GRAPH_NOT_CLEARED_BETWEEN_CASES",
                "易错点/多组状态细节",
                "多组图数据之间邻接表没有清空",
                "上一组测试的边仍留在邻接表或边数组中，下一组搜索或最短路使用了不存在的旧边。",
                "只在程序开始初始化一次图结构，没有把图数据视为每组输入的一部分。",
                "SK_V7_MULTICASE_STATE_RESET_CONTRACT",
                "STATE",
                List.of("BASIC.IO.MULTI_CASE.每组状态重置", "DS.GRAPH.STORE.邻接表", "ENG.ERROR.WRONG_ANSWER.状态未重置"),
                List.of("CONTEST.READING.INPUT.图结构"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_MULTICASE_ACCUMULATOR_NOT_RESET",
                "易错点/多组状态细节",
                "跨组累加变量没有重新置零",
                "答案、计数、最大值或标志变量在多组循环外初始化，导致上一组结果继续影响下一组。",
                "把变量能被后面覆盖和必须每组重置混为一谈。",
                "SK_V7_MULTICASE_STATE_RESET_CONTRACT",
                "INITIALIZATION",
                List.of("BASIC.IO.MULTI_CASE.每组状态重置", "BASIC.TYPE.VARIABLE.赋值覆盖", "BASIC.LOOP.NESTED.重复初始化位置"),
                List.of("BASIC.TYPE.VARIABLE.作用域"),
                "HIGH",
                LANGUAGES);
        AiStandardLibrarySeedCatalog.mistake(seeds,
                "MP_V7_MULTICASE_OUTPUT_CASE_NUMBER_OFF_BY_ONE",
                "易错点/多组状态细节",
                "Case 编号和循环下标偏移一位",
                "题目要求 Case #1 开始输出，但代码使用 0 基循环下标或提前自增，导致组号偏移。",
                "只关注答案内容，没有把每组输出前缀也作为格式要求检查。",
                "SK_V7_MULTICASE_STATE_RESET_CONTRACT",
                "IO_FORMAT",
                List.of("BASIC.IO.MULTI_CASE.多组输出格式", "BASIC.LOOP.FOR.循环次数计算", "BASIC.IO.STDOUT.按要求换行"),
                List.of("ENG.ERROR.FORMAT.大小写错误"),
                "MEDIUM",
                LANGUAGES);
    }
}
