ALTER TABLE class_groups ADD COLUMN IF NOT EXISTS join_code_hash VARCHAR(100);

CREATE TABLE IF NOT EXISTS student_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_group_id BIGINT,
    display_name VARCHAR(255) NOT NULL,
    student_no VARCHAR(255),
    note VARCHAR(255),
    identity_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'NEEDS_REVIEW';
UPDATE student_profiles SET student_no = UPPER(TRIM(student_no))
WHERE student_no IS NOT NULL AND TRIM(student_no) <> '';
UPDATE student_profiles SET status = CASE
    WHEN student_no IS NULL OR TRIM(student_no) = '' THEN 'NEEDS_REVIEW'
    ELSE 'ACTIVE'
END WHERE status IS NULL OR status = 'NEEDS_REVIEW';
ALTER TABLE student_profiles ALTER COLUMN status SET NOT NULL;
UPDATE student_profiles SET student_no = NULL, status = 'NEEDS_REVIEW'
WHERE id IN (
    SELECT duplicate_profile.id
    FROM student_profiles duplicate_profile
    WHERE duplicate_profile.student_no IS NOT NULL
      AND TRIM(duplicate_profile.student_no) <> ''
      AND EXISTS (
          SELECT 1 FROM student_profiles canonical_profile
          WHERE canonical_profile.class_group_id = duplicate_profile.class_group_id
            AND LOWER(canonical_profile.student_no) = LOWER(duplicate_profile.student_no)
            AND canonical_profile.id < duplicate_profile.id
      )
);
DROP INDEX IF EXISTS idx_student_profiles_class_no;
CREATE UNIQUE INDEX IF NOT EXISTS uk_student_profiles_class_no ON student_profiles (class_group_id, student_no);

ALTER TABLE assignments ADD COLUMN IF NOT EXISTS target_mode VARCHAR(20) DEFAULT 'CLASS';
UPDATE assignments SET target_mode = 'CLASS' WHERE target_mode IS NULL;
ALTER TABLE assignments ALTER COLUMN target_mode SET NOT NULL;

CREATE TABLE IF NOT EXISTS assignment_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_assignment_recipient UNIQUE (assignment_id, student_profile_id)
);
CREATE INDEX IF NOT EXISTS idx_assignment_recipients_student ON assignment_recipients (student_profile_id);

CREATE TABLE IF NOT EXISTS student_sessions (
    id UUID PRIMARY KEY,
    student_profile_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ip_address VARCHAR(80),
    user_agent VARCHAR(300)
);
CREATE INDEX IF NOT EXISTS idx_student_sessions_student ON student_sessions (student_profile_id);
