CREATE TABLE IF NOT EXISTS problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    time_limit INTEGER NOT NULL,
    memory_limit INTEGER NOT NULL,
    ai_prompt_direction TEXT,
    starter_code TEXT,
    knowledge_points TEXT,
    algorithm_strategies TEXT,
    common_mistakes TEXT,
    boundary_types TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE problems ADD COLUMN IF NOT EXISTS owner_teacher_id UUID;
ALTER TABLE problems ADD COLUMN IF NOT EXISTS scope VARCHAR(20) DEFAULT 'PUBLIC';
ALTER TABLE problems ADD COLUMN IF NOT EXISTS version_state VARCHAR(30) DEFAULT 'PUBLISHED';
ALTER TABLE problems ADD COLUMN IF NOT EXISTS series_id UUID;
ALTER TABLE problems ADD COLUMN IF NOT EXISTS version_no INTEGER DEFAULT 1;
ALTER TABLE problems ADD COLUMN IF NOT EXISTS source_problem_id BIGINT;
ALTER TABLE problems ADD COLUMN IF NOT EXISTS reviewed_by UUID;
ALTER TABLE problems ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP;
ALTER TABLE problems ADD COLUMN IF NOT EXISTS review_reason VARCHAR(500);
ALTER TABLE problems ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP;
UPDATE problems SET owner_teacher_id = CAST('00000000-0000-0000-0000-000000000001' AS UUID)
WHERE owner_teacher_id IS NULL;
UPDATE problems SET scope = 'PUBLIC' WHERE scope IS NULL;
UPDATE problems SET version_state = 'PUBLISHED' WHERE version_state IS NULL;
UPDATE problems
SET series_id = CAST(('00000000-0000-0000-0000-' || LPAD(CAST(id AS VARCHAR), 12, '0')) AS UUID)
WHERE series_id IS NULL;
UPDATE problems SET version_no = 1 WHERE version_no IS NULL;
ALTER TABLE problems ALTER COLUMN scope SET NOT NULL;
ALTER TABLE problems ALTER COLUMN version_state SET NOT NULL;
ALTER TABLE problems ALTER COLUMN series_id SET NOT NULL;
ALTER TABLE problems ALTER COLUMN version_no SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_problems_scope_state ON problems (scope, version_state, archived_at);
CREATE INDEX IF NOT EXISTS idx_problems_owner ON problems (owner_teacher_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_problems_series_version ON problems (series_id, version_no);
