CREATE TABLE IF NOT EXISTS teacher_ai_quotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id UUID NOT NULL,
    quota_month VARCHAR(7) NOT NULL,
    base_units INTEGER NOT NULL DEFAULT 500,
    additional_units INTEGER NOT NULL DEFAULT 0,
    used_units INTEGER NOT NULL DEFAULT 0,
    reserved_units INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_teacher_ai_quota_month UNIQUE (teacher_id, quota_month)
);

CREATE TABLE IF NOT EXISTS ai_usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id UUID NOT NULL,
    student_profile_id BIGINT,
    assignment_id BIGINT,
    submission_id BIGINT,
    usage_purpose VARCHAR(60) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    provider VARCHAR(80),
    model VARCHAR(160),
    attempt_no INTEGER NOT NULL DEFAULT 1,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    charged BOOLEAN NOT NULL DEFAULT FALSE,
    input_tokens INTEGER,
    output_tokens INTEGER,
    quota_units INTEGER NOT NULL DEFAULT 0,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_usage_teacher_month ON ai_usage_events (teacher_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_usage_idempotency
    ON ai_usage_events (teacher_id, idempotency_key);
