CREATE TABLE IF NOT EXISTS schools (
    id UUID PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    registration_code_hash VARCHAR(64) NOT NULL UNIQUE,
    admin_account_id UUID NOT NULL UNIQUE,
    created_by UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE teacher_accounts ADD COLUMN IF NOT EXISTS school_id UUID;
CREATE INDEX IF NOT EXISTS idx_teacher_accounts_school_role ON teacher_accounts (school_id, role);

CREATE TABLE IF NOT EXISTS school_ai_quotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID NOT NULL,
    quota_month VARCHAR(7) NOT NULL,
    base_units INTEGER NOT NULL DEFAULT 0,
    additional_units INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_school_ai_quota_month UNIQUE (school_id, quota_month)
);

ALTER TABLE ai_usage_events ADD COLUMN IF NOT EXISTS school_id UUID;
CREATE INDEX IF NOT EXISTS idx_ai_usage_school_month ON ai_usage_events (school_id, created_at);

CREATE TABLE IF NOT EXISTS legacy_teacher_purge_manifests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_count BIGINT NOT NULL,
    class_count BIGINT NOT NULL,
    student_count BIGINT NOT NULL,
    assignment_count BIGINT NOT NULL,
    submission_count BIGINT NOT NULL,
    private_problem_count BIGINT NOT NULL,
    preserved_problem_count BIGINT NOT NULL,
    backup_proof_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
