-- 学科质量第一批修正：范围映射、关系完整性、分类治理和高引用知识点精修。
-- 稳定 code 不改名；历史失效对象保留但退出启用导航。

CREATE TABLE public.informatics_discipline_scope_mappings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_node_code character varying(160) NOT NULL,
    framework_code character varying(80) NOT NULL,
    scope_code character varying(120) NOT NULL,
    coverage_role character varying(40) NOT NULL,
    source_reference character varying(1000) NOT NULL,
    evidence_note character varying(1200) NOT NULL,
    review_status character varying(40) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_discipline_scope_knowledge_node
        FOREIGN KEY (knowledge_node_code)
        REFERENCES public.informatics_knowledge_nodes(code)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uk_discipline_scope_mapping
        UNIQUE (knowledge_node_code, framework_code, scope_code),
    CONSTRAINT ck_discipline_scope_coverage_role
        CHECK (coverage_role IN ('FOUNDATION', 'EXTENSION', 'PRACTICE')),
    CONSTRAINT ck_discipline_scope_review_status
        CHECK (review_status IN ('SOURCE_ANCHORED', 'TEACHER_REVIEWED', 'INFERRED'))
);

CREATE INDEX idx_discipline_scope_framework
    ON public.informatics_discipline_scope_mappings(framework_code, scope_code)
    WHERE enabled = true;

CREATE INDEX idx_discipline_scope_knowledge
    ON public.informatics_discipline_scope_mappings(knowledge_node_code)
    WHERE enabled = true;

-- 本地统一学科框架只表达领域角色，不制造高中库和竞赛库两套节点。
INSERT INTO public.informatics_discipline_scope_mappings (
    knowledge_node_code, framework_code, scope_code, coverage_role,
    source_reference, evidence_note, review_status
)
SELECT n.code,
       'LOCAL_UNIFIED_INFORMATICS',
       CASE n.code
           WHEN 'BASIC' THEN 'PROGRAMMING_FOUNDATION'
           WHEN 'DS' THEN 'DATA_STRUCTURE'
           WHEN 'ALGO' THEN 'ALGORITHM'
           WHEN 'MATH' THEN 'MATHEMATICS_AND_MODELING'
           WHEN 'ENG' THEN 'DEBUGGING_AND_ENGINEERING'
           WHEN 'CONTEST' THEN 'PROBLEM_SOLVING_PRACTICE'
       END,
       CASE n.code
           WHEN 'BASIC' THEN 'FOUNDATION'
           WHEN 'ENG' THEN 'FOUNDATION'
           WHEN 'CONTEST' THEN 'PRACTICE'
           ELSE 'EXTENSION'
       END,
       'openspec/specs/informatics-knowledge-tree-quality/spec.md',
       '统一信息学知识树的领域锚点；下级节点按最近祖先继承，不创建平行学科库。',
       'TEACHER_REVIEWED'
FROM public.informatics_knowledge_nodes n
WHERE n.enabled = true
  AND n.type = 'DOMAIN'
  AND n.code IN ('BASIC', 'DS', 'ALGO', 'MATH', 'ENG', 'CONTEST')
ON CONFLICT (knowledge_node_code, framework_code, scope_code) DO NOTHING;

-- 教育部高中信息技术课程框架：只落高置信领域锚点，避免伪造逐叶出处。
INSERT INTO public.informatics_discipline_scope_mappings (
    knowledge_node_code, framework_code, scope_code, coverage_role,
    source_reference, evidence_note, review_status
)
SELECT n.code,
       'MOE_HIGH_SCHOOL_IT_2020',
       CASE n.code
           WHEN 'BASIC' THEN 'DATA_AND_COMPUTING'
           WHEN 'ALGO' THEN 'ALGORITHM_AND_PROGRAM_IMPLEMENTATION'
           WHEN 'ENG' THEN 'COMPUTATIONAL_THINKING_PRACTICE'
       END,
       CASE n.code WHEN 'ALGO' THEN 'EXTENSION' ELSE 'FOUNDATION' END,
       'https://www.moe.gov.cn/srcsite/A26/s8001/202006/t20200603_462199.html',
       CASE n.code
           WHEN 'BASIC' THEN '高中信息技术以数据、算法和程序实现支撑计算思维，本领域作为程序设计基础入口。'
           WHEN 'ALGO' THEN '算法描述、问题抽象和程序实现属于计算思维主线，本领域作为算法扩展入口。'
           WHEN 'ENG' THEN '调试、验证和规范表达作为计算实践能力，不与算法知识点混为同一层级。'
       END,
       'SOURCE_ANCHORED'
FROM public.informatics_knowledge_nodes n
WHERE n.enabled = true AND n.code IN ('BASIC', 'ALGO', 'ENG')
ON CONFLICT (knowledge_node_code, framework_code, scope_code) DO NOTHING;

-- CCF NOI 2025 大纲：入门级覆盖 C++、数据结构、算法与数学，具体难度留给后续章节审校。
INSERT INTO public.informatics_discipline_scope_mappings (
    knowledge_node_code, framework_code, scope_code, coverage_role,
    source_reference, evidence_note, review_status
)
SELECT n.code,
       'CCF_NOI_2025',
       CASE n.code
           WHEN 'BASIC' THEN 'ENTRY_CPP_PROGRAMMING'
           WHEN 'DS' THEN 'ENTRY_DATA_STRUCTURE'
           WHEN 'ALGO' THEN 'ENTRY_ALGORITHM'
           WHEN 'MATH' THEN 'ENTRY_MATHEMATICS_AND_OTHER'
       END,
       CASE n.code WHEN 'BASIC' THEN 'FOUNDATION' ELSE 'EXTENSION' END,
       'https://www.noi.cn/upload/resources/file/2025/04/18/NOI_Syllabus_Edition_2025.pdf',
       CASE n.code
           WHEN 'BASIC' THEN 'NOI 2025 入门级 C++ 程序设计覆盖基本类型、语句、数组、字符串、函数与递归。'
           WHEN 'DS' THEN 'NOI 2025 入门级数据结构覆盖线性结构、树和图的基础表示与遍历。'
           WHEN 'ALGO' THEN 'NOI 2025 入门级算法覆盖枚举、模拟、排序、搜索、图遍历和动态规划基础。'
           WHEN 'MATH' THEN 'NOI 2025 入门级数学与其他覆盖数制、初等数学、数论及组合基础。'
       END,
       'SOURCE_ANCHORED'
FROM public.informatics_knowledge_nodes n
WHERE n.enabled = true AND n.code IN ('BASIC', 'DS', 'ALGO', 'MATH')
ON CONFLICT (knowledge_node_code, framework_code, scope_code) DO NOTHING;

-- parent_code 是目录归属，不是学习前置；历史数据把两者机械复制时清空伪前置。
UPDATE public.informatics_knowledge_nodes
SET prerequisites = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE parent_code IS NOT NULL
  AND btrim(COALESCE(prerequisites, '')) = btrim(parent_code);

-- aliases 只保存不同叫法；主名自指不提供任何检索增量。
UPDATE public.informatics_knowledge_nodes
SET aliases = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE btrim(COALESCE(aliases, '')) = btrim(name);

-- 首批按“学科中心性 × 当前正式标准库引用密度”人工精修 24 个知识点。
UPDATE public.informatics_knowledge_nodes n
SET description = curated.description,
    learning_objectives = curated.learning_objectives,
    typical_problems = curated.typical_problems,
    aliases = curated.aliases,
    prerequisites = curated.prerequisites,
    library_version = 'informatics-knowledge-discipline-v1',
    updated_at = CURRENT_TIMESTAMP
FROM (VALUES
    ('DS.SET_MAP.MAP.键值关系',
     '键值关系用键定位对应值；同一键再次写入时会更新原值，读取不存在的键时必须区分“未找到”和容器自动创建默认值”。',
     E'能说明键、值和一对一定位关系。\n能在频次统计与编号查询中检查重复写入和不存在键。',
     E'单词频次统计\n编号到属性查询\n默认插入导致的状态污染',
     E'映射\n字典\nmap\ndictionary', NULL),
    ('ALGO.SIM.STATE.多数投票算法',
     '多数投票用候选值和票数表示尚未被不同元素抵消的剩余状态；它只能产生候选，题目未保证多数存在时还要二次计数验证。',
     E'能逐项解释候选和票数的变化。\n能判断题目是否需要最终出现次数验证。',
     E'数组中过半元素\n不存在多数元素时的候选验证\n候选票数轨迹表',
     E'摩尔投票法\nBoyer-Moore 多数投票\nmajority vote',
     'BASIC.ARRAY.TRAVERSE.全量遍历'),
    ('BASIC.STRING.BUILD.游程编码',
     '游程编码把相邻且相同的字符合并为“字符 + 连续长度”；段切换和字符串结束都是结算当前段的时机。',
     E'能维护当前段字符、长度和输出时机。\n能处理空串、单字符和最后一段。',
     E'连续字符压缩\n最后一段漏输出\n段计数重置顺序',
     E'运行长度编码\nRLE\nrun-length encoding',
     'BASIC.STRING.CHAR.字符遍历'),
    ('ALGO.GRAPH.CONNECT.并查集',
     '并查集维护元素所属集合的代表元，通过查找代表元判断连通，通过合并代表元连接两个集合；路径压缩只改变存储形态，不改变集合归属。',
     E'能解释 parent 数组保存的是集合代表关系。\n能区分查找、合并与连通性查询。',
     E'动态连通性\n重复合并\n路径压缩后代表元检查',
     E'不相交集合\nDSU\nunion-find', NULL),
    ('ALGO.GRAPH.TOPO.入度',
     '有向图中节点的入度是指向该节点的边数；拓扑推进时，每处理完一个前置节点，只减少其后继节点的入度。',
     E'能从依赖语句确定边方向并计算入度。\n能解释节点何时可以进入拓扑队列。',
     E'课程先修关系\n任务依赖排序\n入度更新与环检测',
     E'入边数\nin-degree',
     'DS.GRAPH.MODEL.有向无向'),
    ('ALGO.GREEDY.INTERVAL.按右端点排序',
     '求最多不相交区间时，按右端点从小到大选择可为后续保留最大空间；该排序依据不等同于区间合并时常用的左端点排序。',
     E'能先识别目标是选择还是合并。\n能用交换论证解释最早结束优先。',
     E'最多活动安排\n闭区间端点是否冲突\n错误按起点排序的反例',
     E'最早结束时间优先\n区间调度\ninterval scheduling',
     'ALGO.SORT.BASIC.自定义比较'),
    ('ALGO.SORT.BASIC.计数排序',
     '计数排序在值域可控时用下标表示取值、数组元素表示频次，再按值域顺序还原结果；负数或非零起点需要显式偏移。',
     E'能根据数据范围判断计数数组大小。\n能区分桶下标、桶内频次和还原输出。',
     E'小值域整数排序\n负数值域偏移\n频次数组还原有序序列',
     E'桶计数排序\ncounting sort',
     'BASIC.ARRAY.PREFIX.计数数组'),
    ('DS.LINEAR.LIST.前驱后继',
     '链式结构用前驱和后继表达节点间相邻关系；插入或删除前必须先保存仍要使用的连接，避免覆盖后丢失剩余链条。',
     E'能画出修改前后的 prev/next 连接。\n能单独处理头、尾和空链边界。',
     E'删除中间节点\n头尾插入\n数组模拟链表的指针覆盖',
     E'前驱节点\n后继节点\nprev/next', NULL),
    ('ALGO.BINARY.INDEX.闭区间模板',
     '闭区间二分始终维护答案位于当前 [left,right]；循环条件、取中点方式和舍弃哪一侧必须共同保持这一不变量。',
     E'能在每轮写出闭区间仍保留的候选。\n能从区间收缩推导循环条件和返回位置。',
     E'有序数组查找\n首个满足条件的位置\n空区间与单元素区间',
     E'闭区间二分\n[left,right] 二分\nbinary search closed interval',
     'BASIC.LOOP.BOUNDARY.左闭右闭'),
    ('ALGO.GREEDY.CHOICE.排序依据',
     '贪心排序依据决定每一步优先处理哪个候选，必须由目标函数和可交换性推出，不能只凭样例中某个字段看起来更小或更大。',
     E'能写出排序关键字对应的局部选择。\n能用最小反例检查错误排序依据。',
     E'区间调度排序\n资源分配优先级\n相同主关键字的次关键字',
     E'贪心排序关键字\ngreedy ordering',
     'ALGO.SORT.BASIC.自定义比较'),
    ('BASIC.ARRAY.MATRIX.行列含义',
     '二维数组的第一维和第二维分别对应行与列；输入顺序、坐标系和访问表达式必须使用同一约定。',
     E'能为 matrix[row][column] 标注两维含义。\n能检查题目坐标与数组下标是否需要交换或偏移。',
     E'矩阵输入转置\n网格坐标映射\n行列边界写反',
     E'行列索引\nrow/column',
     'BASIC.ARRAY.INDEX.下标映射'),
    ('BASIC.ARRAY.UPDATE.读旧写新分离',
     '当同一轮多个新值都依赖更新前状态时，读取旧数组与写入新数组必须分离；原地写入会让后面的计算混入本轮新状态。',
     E'能判断更新公式依赖旧状态还是最新状态。\n能选择临时数组、倒序遍历或保存旧值。',
     E'细胞状态同步更新\n一维 DP 滚动顺序\n原地覆盖导致传播过快',
     E'双缓冲更新\n旧状态与新状态分离\nold/new state separation',
     'BASIC.ARRAY.UPDATE.覆盖风险'),
    ('BASIC.FUNCTION.DEF.参数设计',
     '函数参数应只携带完成单一职责所需的输入与可变状态，并明确按值复制、按引用共享或返回新结果的边界。',
     E'能为每个参数说明输入、输出或可变状态角色。\n能识别不必要的全局变量和隐藏副作用。',
     E'数组是否按引用传递\n递归状态参数\n函数修改外部变量导致串组',
     E'形参设计\n函数接口设计\nparameter design', NULL),
    ('DS.LINEAR.STACK.后进先出',
     '栈只允许在同一端压入和弹出，最后压入的元素最先弹出；栈顶代表当前最晚尚未完成的对象。',
     E'能用 push、top、pop 描述状态变化。\n能在弹出前检查空栈并解释处理顺序。',
     E'括号匹配\n表达式求值\n撤销最近操作',
     E'后入先出\nLIFO\nlast in first out', NULL),
    ('ALGO.DP.STATE.状态含义',
     '动态规划状态必须说明下标对应的子问题、已经处理的范围和状态值代表的最优量或方案数；转移和答案位置都由这一定义推出。',
     E'能用完整句子定义 dp 下标与取值。\n能用小规模手算验证初值、转移和答案位置。',
     E'线性 DP 状态定义\n背包容量含义\n计数 DP 的空方案',
     E'DP 状态定义\ndynamic programming state',
     'ALGO.SIM.STATE.状态变量选择'),
    ('ALGO.GRAPH.SHORTEST.BFS_最短路',
     '当每条边代价相同，BFS 按距离层次首次到达节点即可得到最少边数；边权不同或状态代价不等时不能直接套用。',
     E'能说明队列层次与最短步数的对应关系。\n能先检查边权条件再选择 BFS。',
     E'迷宫最少步数\n多源 BFS\n带权图误用普通 BFS',
     E'无权最短路\n单位边权最短路\nunweighted shortest path',
     'ALGO.SEARCH.BFS.队列层次'),
    ('ALGO.PREFIX.MATRIX.容斥公式',
     '二维前缀和查询矩形时，用右下前缀减去上方和左方区域，再加回被重复减去的左上交集；各项坐标必须采用同一补零约定。',
     E'能在图上标出四个前缀区域。\n能用单格和首行首列验证符号与偏移。',
     E'子矩形求和\n首行首列查询\n容斥交集重复减去',
     E'二维前缀和容斥\ninclusion-exclusion',
     'ALGO.PREFIX.SUM.区间查询'),
    ('ALGO.PREFIX.SUM.区间查询',
     '前缀和把从起点到当前位置的累计量预先保存，区间和由两个前缀之差得到；公式取决于 prefix[i] 是否包含第 i 个元素。',
     E'能先写出 prefix 数组定义再推导查询式。\n能用单点区间和首段区间检查下标。',
     E'多次区间求和\n空前缀补零\n累计值溢出',
     E'前缀和查询\nprefix sum query',
     'ALGO.PREFIX.SUM.前缀定义'),
    ('BASIC.LOOP.BOUNDARY.左闭右开',
     '左闭右开区间 [l,r) 包含 l 但不包含 r，元素个数恒为 r-l；它适合表达从 0 开始的数组切片和循环上界。',
     E'能列出 [l,r) 的首项、末项和长度。\n能在空区间与单元素区间上检查循环条件。',
     E'遍历数组下标 0 到 n-1\n字符串切片\n区间长度与右端点混淆',
     E'半开区间\n[l,r)\nleft-closed right-open interval', NULL),
    ('ENG.COMPLEXITY.TIME.数据范围反推',
     '数据范围给出允许的操作数量级；应把 n、查询次数、状态维度和循环嵌套共同代入，判断枚举、排序或更高效算法是否可行。',
     E'能估算主循环的数量级。\n能依据时间限制排除明显不可行方案并说明常数与语言差异。',
     E'n=10^5 时的双重循环\n多次查询的预处理取舍\n状态维度导致复杂度漏乘',
     E'按数据规模选算法\nconstraint-driven complexity', NULL),
    ('ENG.DEBUG.SAMPLE.最小反例',
     '最小反例是在仍能触发错误的前提下尽量减少元素、边界或步骤，使第一处状态偏差可以手算和定位。',
     E'能从失败输入逐步删除无关部分。\n能记录期望状态与实际状态第一次分叉的位置。',
     E'缩小错误数组\n简化失败图路径\n边界条件的单元素反例',
     E'最小失败样例\nminimal counterexample',
     'ENG.DEBUG.SAMPLE.手算对照'),
    ('MATH.NUMBER.PRIME.试除判定',
     '试除法依据合数必有不大于平方根的因子，只需检查到 i*i<=n；0、1 和负数必须先排除，批量查询时应评估是否改用筛法。',
     E'能说明试除上界为何包含平方根。\n能处理 1、完全平方数和多次查询。',
     E'判断单个整数是否为质数\n平方数边界\n批量质数查询超时',
     E'试除法\ntrial division',
     'MATH.NUMBER.DIVISIBILITY.因子枚举'),
    ('CONTEST.SUBMIT.CHECKLIST.初始化检查',
     '提交前初始化检查要逐一确认累计量、最值、距离、访问标记和多组数据容器的初始含义与题目值域一致。',
     E'能按变量角色列出合法初值。\n能检查每组数据开始时哪些状态必须重置。',
     E'最大值用 0 初始化但数据全负\n距离数组未设无穷大\n多组数据沿用旧状态',
     E'初始化复查\ninitialization checklist', NULL),
    ('ALGO.GRAPH.SHORTEST.松弛操作',
     '松弛操作用一条边尝试改进目标节点的当前最优距离；候选距离必须由“到达当前节点的距离 + 本边真实代价”计算，时间依赖边还要明确等待发生在何时。',
     E'能写出候选距离与当前距离的比较。\n能区分行驶时间、等待时间和到达时刻，避免重复计入。',
     E'Dijkstra 边松弛\n周期开放道路的等待时间\n旧堆项与当前距离比较',
     E'松弛\nrelaxation',
     'ALGO.GRAPH.SHORTEST.距离初始化')
) AS curated(code, description, learning_objectives, typical_problems, aliases, prerequisites)
WHERE n.code = curated.code
  AND n.enabled = true
  AND n.type = 'KNOWLEDGE_POINT';

-- 教师批准内容保留审核来源，但从占位路径重挂到合法的最短路松弛能力与知识点。
UPDATE public.ai_standard_mistake_points
SET name = '周期等待边把行驶时间重复计入等待公式',
    category = '易错点/最短路松弛',
    description = '在时间依赖最短路中，到达时刻已经包含本段行驶时间，代码又把 current_time + cost 作为等待函数输入，造成同一段代价被重复计算。',
    skill_unit_code = 'SK_SHORTEST_DISTANCE_RELAX',
    mistake_type = 'STATE',
    misconception = '没有区分出发时刻、行驶后到达时刻和等待结束时刻，把同一段行驶代价同时放进松弛式和等待函数。',
    symptom = '路径包含周期等待边时结果系统性偏大；不需要等待的样例可能仍然通过。',
    repair_strategy = '先写出三个时刻变量的含义，再只用到达时刻计算下一次可通行时刻，最后用等待后的时刻参与松弛。',
    severity = 'HIGH',
    primary_knowledge_node_code = 'ALGO.GRAPH.SHORTEST.松弛操作',
    knowledge_node_codes = E'ALGO.GRAPH.SHORTEST.松弛操作\nALGO.GRAPH.SHORTEST.Dijkstra',
    prerequisite_knowledge_codes = 'ALGO.GRAPH.SHORTEST.距离初始化',
    library_version = 'standard-library-discipline-v1',
    updated_at = CURRENT_TIMESTAMP
WHERE code = 'MP_最短路_周期等待_等待时间计算_参数误用';

UPDATE public.ai_standard_library_items
SET name = '周期等待边把行驶时间重复计入等待公式',
    category = '易错点/最短路松弛',
    description = '在时间依赖最短路中，到达时刻已经包含本段行驶时间，代码又把 current_time + cost 作为等待函数输入，造成同一段代价被重复计算。',
    ability_point = '维护时间依赖边的到达时刻',
    skill_unit_code = 'SK_SHORTEST_DISTANCE_RELAX',
    mistake_type = 'STATE',
    common_misconception = '没有区分出发时刻、行驶后到达时刻和等待结束时刻，把同一段行驶代价重复计入。',
    student_explanation = '先给出发、到达和等待结束三个时刻命名，再检查每段代价只进入公式一次。',
    teacher_explanation = '该条目来自教师批准候选；修正只重挂学科归属并澄清时间状态，不改变审核结论和来源证据。',
    severity = 'HIGH',
    primary_knowledge_node_code = 'ALGO.GRAPH.SHORTEST.松弛操作',
    knowledge_node_codes = E'ALGO.GRAPH.SHORTEST.松弛操作\nALGO.GRAPH.SHORTEST.Dijkstra',
    prerequisite_knowledge_codes = 'ALGO.GRAPH.SHORTEST.距离初始化',
    library_version = 'standard-library-discipline-v1',
    updated_at = CURRENT_TIMESTAMP
WHERE layer = 'MISTAKE_POINT'
  AND code = 'MP_最短路_周期等待_等待时间计算_参数误用';

-- 同锚点同名错因收敛为一个正式主条目；旧 code 保留为停用记录和兼容映射入口。
WITH redirects(old_code, canonical_code) AS (VALUES
    ('MP_V16_TOPO_EDGE_DIRECTION_REVERSED', 'MP_TOPO_EDGE_DIRECTION_REVERSED'),
    ('MP_V16_RLE_LAST_RUN_NOT_FLUSHED', 'MP_V14_RLE_MISSES_LAST_RUN_FLUSH'),
    ('MP_V7_SUBSTRING_LENGTH_USED_AS_END_INDEX', 'MP_V11_SUBSTRING_LENGTH_TREATED_AS_END_INDEX')
)
UPDATE public.ai_standard_mistake_points m
SET enabled = false,
    updated_at = CURRENT_TIMESTAMP
FROM redirects r
WHERE m.code = r.old_code;

WITH redirects(old_code, canonical_code) AS (VALUES
    ('MP_V16_TOPO_EDGE_DIRECTION_REVERSED', 'MP_TOPO_EDGE_DIRECTION_REVERSED'),
    ('MP_V16_RLE_LAST_RUN_NOT_FLUSHED', 'MP_V14_RLE_MISSES_LAST_RUN_FLUSH'),
    ('MP_V7_SUBSTRING_LENGTH_USED_AS_END_INDEX', 'MP_V11_SUBSTRING_LENGTH_TREATED_AS_END_INDEX')
)
UPDATE public.ai_standard_library_items i
SET enabled = false,
    updated_at = CURRENT_TIMESTAMP
FROM redirects r
WHERE i.layer IN ('MISTAKE_POINT', 'BASIC_CAUSE')
  AND i.code = r.old_code;

WITH redirects(old_code, canonical_code) AS (VALUES
    ('MP_V16_TOPO_EDGE_DIRECTION_REVERSED', 'MP_TOPO_EDGE_DIRECTION_REVERSED'),
    ('MP_V16_RLE_LAST_RUN_NOT_FLUSHED', 'MP_V14_RLE_MISSES_LAST_RUN_FLUSH'),
    ('MP_V7_SUBSTRING_LENGTH_USED_AS_END_INDEX', 'MP_V11_SUBSTRING_LENGTH_TREATED_AS_END_INDEX')
)
UPDATE public.ai_standard_library_legacy_mappings m
SET target_code = r.canonical_code,
    target_type = 'MISTAKE_POINT',
    migration_status = 'MAPPED',
    confidence = 1.0,
    source_version = 'standard-library-discipline-v1',
    updated_at = CURRENT_TIMESTAMP
FROM redirects r
WHERE m.legacy_layer IN ('MISTAKE_POINT', 'BASIC_CAUSE')
  AND m.legacy_code = r.old_code;

UPDATE public.ai_standard_improvement_points
SET related_mistake_codes = replace(
        replace(related_mistake_codes,
                'MP_V16_TOPO_EDGE_DIRECTION_REVERSED', 'MP_TOPO_EDGE_DIRECTION_REVERSED'),
        'MP_V16_RLE_LAST_RUN_NOT_FLUSHED', 'MP_V14_RLE_MISSES_LAST_RUN_FLUSH'),
    updated_at = CURRENT_TIMESTAMP
WHERE related_mistake_codes LIKE '%MP_V16_TOPO_EDGE_DIRECTION_REVERSED%'
   OR related_mistake_codes LIKE '%MP_V16_RLE_LAST_RUN_NOT_FLUSHED%';

UPDATE public.ai_standard_library_items
SET related_items = replace(
        replace(related_items,
                'MP_V16_TOPO_EDGE_DIRECTION_REVERSED', 'MP_TOPO_EDGE_DIRECTION_REVERSED'),
        'MP_V16_RLE_LAST_RUN_NOT_FLUSHED', 'MP_V14_RLE_MISSES_LAST_RUN_FLUSH'),
    updated_at = CURRENT_TIMESTAMP
WHERE enabled = true
  AND (related_items LIKE '%MP_V16_TOPO_EDGE_DIRECTION_REVERSED%'
    OR related_items LIKE '%MP_V16_RLE_LAST_RUN_NOT_FLUSHED%');

-- 分类只表达学科主题，移除实现版本和兜底来源；稳定 code 不改名。
UPDATE public.ai_standard_skill_units
SET category = replace(replace(replace(
        regexp_replace(category, '/V[0-9]+[[:space:]]*', '/', 'gi'),
        '兜底吸收-', ''), '兜底榨取-A类', ''), '兜底榨取-B类', ''),
    updated_at = CURRENT_TIMESTAMP
WHERE enabled = true
  AND category ~* '/V[0-9]+|兜底吸收|兜底榨取-(A类|B类)';

UPDATE public.ai_standard_mistake_points
SET category = replace(replace(replace(
        regexp_replace(category, '/V[0-9]+[[:space:]]*', '/', 'gi'),
        '兜底吸收-', ''), '兜底榨取-A类', ''), '兜底榨取-B类', ''),
    updated_at = CURRENT_TIMESTAMP
WHERE enabled = true
  AND category ~* '/V[0-9]+|兜底吸收|兜底榨取-(A类|B类)';

UPDATE public.ai_standard_improvement_points
SET category = replace(replace(replace(
        regexp_replace(category, '/V[0-9]+[[:space:]]*', '/', 'gi'),
        '兜底吸收-', ''), '兜底榨取-A类', ''), '兜底榨取-B类', ''),
    updated_at = CURRENT_TIMESTAMP
WHERE enabled = true
  AND category ~* '/V[0-9]+|兜底吸收|兜底榨取-(A类|B类)';

UPDATE public.ai_standard_library_items
SET category = replace(replace(replace(
        regexp_replace(category, '/V[0-9]+[[:space:]]*', '/', 'gi'),
        '兜底吸收-', ''), '兜底榨取-A类', ''), '兜底榨取-B类', ''),
    updated_at = CURRENT_TIMESTAMP
WHERE enabled = true
  AND category ~* '/V[0-9]+|兜底吸收|兜底榨取-(A类|B类)';

-- 为修正后的教师批准条目补齐规范关系。
INSERT INTO public.ai_standard_library_relations (
    enabled, created_at, updated_at, relation_type,
    source_type, source_code, target_type, target_code, description
)
SELECT true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'EXTENDS',
       'MISTAKE_POINT', m.code, 'SKILL_UNIT', m.skill_unit_code,
       '教师批准易错点归属能力点'
FROM public.ai_standard_mistake_points m
WHERE m.enabled = true
  AND m.code = 'MP_最短路_周期等待_等待时间计算_参数误用'
ON CONFLICT (source_type, source_code, relation_type, target_type, target_code)
DO UPDATE SET enabled = true, description = EXCLUDED.description, updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_standard_library_relations (
    enabled, created_at, updated_at, relation_type,
    source_type, source_code, target_type, target_code, description
)
SELECT true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'PREREQUISITE',
       'MISTAKE_POINT', m.code, 'KNOWLEDGE_NODE', m.primary_knowledge_node_code,
       '教师批准易错点的主知识锚点'
FROM public.ai_standard_mistake_points m
WHERE m.enabled = true
  AND m.code = 'MP_最短路_周期等待_等待时间计算_参数误用'
ON CONFLICT (source_type, source_code, relation_type, target_type, target_code)
DO UPDATE SET enabled = true, description = EXCLUDED.description, updated_at = CURRENT_TIMESTAMP;

-- 启用关系只允许连接启用对象；历史失效关系保留但停用。
WITH active_objects(entity_type, code) AS (
    SELECT 'KNOWLEDGE_NODE', code FROM public.informatics_knowledge_nodes WHERE enabled = true
    UNION ALL SELECT 'SKILL_UNIT', code FROM public.ai_standard_skill_units WHERE enabled = true
    UNION ALL SELECT 'MISTAKE_POINT', code FROM public.ai_standard_mistake_points WHERE enabled = true
    UNION ALL SELECT 'IMPROVEMENT_POINT', code FROM public.ai_standard_improvement_points WHERE enabled = true
)
UPDATE public.ai_standard_library_relations r
SET enabled = false,
    updated_at = CURRENT_TIMESTAMP
WHERE r.enabled = true
  AND (
      NOT EXISTS (
          SELECT 1 FROM active_objects a
          WHERE a.entity_type = r.source_type AND a.code = r.source_code
      )
      OR NOT EXISTS (
          SELECT 1 FROM active_objects a
          WHERE a.entity_type = r.target_type AND a.code = r.target_code
      )
  );

-- 兼容映射不删除；目标已停用时退出 MAPPED，便于审计历史来源。
WITH active_objects(entity_type, code) AS (
    SELECT 'KNOWLEDGE_NODE', code FROM public.informatics_knowledge_nodes WHERE enabled = true
    UNION ALL SELECT 'SKILL_UNIT', code FROM public.ai_standard_skill_units WHERE enabled = true
    UNION ALL SELECT 'MISTAKE_POINT', code FROM public.ai_standard_mistake_points WHERE enabled = true
    UNION ALL SELECT 'IMPROVEMENT_POINT', code FROM public.ai_standard_improvement_points WHERE enabled = true
)
UPDATE public.ai_standard_library_legacy_mappings m
SET migration_status = 'ARCHIVED_DISABLED_TARGET',
    updated_at = CURRENT_TIMESTAMP
WHERE m.migration_status = 'MAPPED'
  AND NOT EXISTS (
      SELECT 1 FROM active_objects a
      WHERE a.entity_type = m.target_type AND a.code = m.target_code
  );
