CREATE TABLE IF NOT EXISTS teacher_accounts (
    id UUID PRIMARY KEY,
    username_normalized VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    school_name VARCHAR(200) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    reviewed_by UUID,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    review_reason VARCHAR(500),
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO teacher_accounts (
    id, username_normalized, password_hash, display_name, school_name,
    role, status, must_change_password, failed_login_count, created_at, updated_at
)
SELECT CAST('00000000-0000-0000-0000-000000000001' AS UUID),
       '__bootstrap_admin__', '!BOOTSTRAP_REQUIRED!', '平台管理员', '平台',
       'ADMIN', 'BOOTSTRAP_REQUIRED', TRUE, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM teacher_accounts
    WHERE id = CAST('00000000-0000-0000-0000-000000000001' AS UUID)
);

CREATE TABLE IF NOT EXISTS teacher_sessions (
    id UUID PRIMARY KEY,
    teacher_id UUID NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ip_address VARCHAR(80),
    user_agent VARCHAR(300)
);
CREATE INDEX IF NOT EXISTS idx_teacher_sessions_teacher ON teacher_sessions (teacher_id);
CREATE INDEX IF NOT EXISTS idx_teacher_sessions_token ON teacher_sessions (token_hash);

CREATE TABLE IF NOT EXISTS platform_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_teacher_id UUID,
    event_type VARCHAR(80) NOT NULL,
    target_type VARCHAR(80),
    target_id VARCHAR(100),
    detail VARCHAR(1000),
    ip_address VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS class_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    grade VARCHAR(255),
    teacher_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE class_groups ADD COLUMN IF NOT EXISTS owner_teacher_id UUID;
UPDATE class_groups SET owner_teacher_id = CAST('00000000-0000-0000-0000-000000000001' AS UUID)
WHERE owner_teacher_id IS NULL;
ALTER TABLE class_groups ALTER COLUMN owner_teacher_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_class_groups_owner ON class_groups (owner_teacher_id);

CREATE TABLE IF NOT EXISTS assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    class_group_id BIGINT,
    hint_policy VARCHAR(20) NOT NULL DEFAULT 'L2',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    starts_at TIMESTAMP,
    ends_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS owner_teacher_id UUID;
UPDATE assignments SET owner_teacher_id = CAST('00000000-0000-0000-0000-000000000001' AS UUID)
WHERE owner_teacher_id IS NULL;
ALTER TABLE assignments ALTER COLUMN owner_teacher_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_assignments_owner ON assignments (owner_teacher_id);

