-- 学科质量第二批精修：优先修复 MATH、ENG、BASIC 高引用模板节点，
-- 并为已有正式错因但缺少提升点的能力补齐可执行教学闭环。
-- 不新增知识树节点，不修改稳定 code，不触碰提交、题目和课堂业务数据。

UPDATE public.informatics_knowledge_nodes n
SET description = curated.description,
    learning_objectives = curated.learning_objectives,
    typical_problems = curated.typical_problems,
    aliases = curated.aliases,
    prerequisites = curated.prerequisites,
    library_version = 'informatics-knowledge-discipline-v2',
    updated_at = CURRENT_TIMESTAMP
FROM (VALUES
    ('MATH.NUMBER.PRIME.1_不是质数',
     '质数必须是大于 1 且只有 1 和自身两个正因数的整数；1 只有一个正因数，因此既不是质数也不是合数，判定函数应在试除前单独处理。',
     E'能用正因数个数解释 1 为什么不是质数。\n能在质数判定中先处理 n<=1，再进入试除循环。',
     E'判断 0、1、2 和完全平方数是否为质数\n统计区间质数时的下界处理\n质数判定函数的特殊值测试',
     E'质数定义边界\n非素数 1\none is not prime', NULL),
    ('MATH.GEOMETRY.COORD.x_y_坐标',
     '平面坐标通常用 x 表示水平方向、y 表示竖直方向；映射到二维数组时常对应 column 和 row，必须先确定原点位置、正方向以及访问顺序。',
     E'能写出题面 (x,y) 与 grid[row][column] 的对应关系。\n能检查坐标原点、方向和下标偏移是否一致。',
     E'笛卡尔坐标映射到矩阵\n左下原点与左上原点转换\n方向数组中 dx/dy 与 dr/dc 对照',
     E'横纵坐标\nCartesian coordinates\nx-axis/y-axis',
     'BASIC.ARRAY.MATRIX.行列含义'),
    ('MATH.NUMBER.PRIME.筛法',
     '筛法通过已确认的质数批量标记其倍数为合数；从 p*p 开始标记可避免重复处理更小质因子已经覆盖的倍数，数组边界必须覆盖目标上限。',
     E'能说明为什么从 p*p 开始标记仍不会漏掉合数。\n能根据查询上限建立标记数组并处理 0、1。',
     E'生成不超过 n 的全部质数\n多次质数查询预处理\n筛数组长度和标记起点错误',
     E'埃拉托斯特尼筛法\n素数筛\nSieve of Eratosthenes',
     'MATH.NUMBER.PRIME.试除判定'),
    ('MATH.BIT.MASK.状态判断',
     '掩码状态判断先确定第 i 位代表的对象，再用 (mask >> i) & 1 或 mask & (1<<i) 检查该位；结果只表达成员或条件是否存在，不等同于对象编号。',
     E'能把每一位与题面对象逐项对齐。\n能用括号明确位移、按位与和比较的执行顺序。',
     E'判断集合是否包含第 i 个对象\n检查若干条件是否全部满足\n对象编号从 1 开始时的位偏移',
     E'位状态检查\nbit test\nmembership test',
     'MATH.BIT.MASK.集合掩码'),
    ('MATH.BIT.MASK.集合掩码',
     '集合掩码用二进制每一位表示一个对象是否属于集合；对象到位编号的映射、整数位宽和全集掩码共同决定可表示的状态范围。',
     E'能画出对象编号与二进制位的对应表。\n能根据对象数量选择位宽并构造空集、单元素集和全集。',
     E'枚举对象子集\n保存已访问条件集合\n超过整数位宽导致状态丢失',
     E'位集合\nbitmask set\nsubset mask',
     'MATH.BIT.OP.取某一位'),
    ('MATH.COUNT.INCLUSION.集合重叠',
     '多个集合的数量直接相加时，交集元素会被重复计算；两个集合需要减去一次交集，更多集合则按交集层数交替加减。',
     E'能在维恩图中标出被重复计算的区域。\n能从目标全集和条件集合推导需要加减的交集。',
     E'满足至少一个条件的对象数\n同时被两种规则命中的样本\n遗漏三集合交集的容斥计数',
     E'交集重复计数\n集合容斥\noverlapping sets', NULL),
    ('MATH.COUNT.PERM.顺序是否重要',
     '计数对象若交换先后位置会形成不同结果，则顺序重要并属于排列或有序序列；若只关心选中了哪些对象，则顺序不重要并属于组合或集合。',
     E'能用交换两个已选对象是否改变结果判断顺序性。\n能把同一题目的排列模型和组合模型列出反例对照。',
     E'选队员与排座位的区别\n密码序列与元素集合\n路径步骤顺序对结果的影响',
     E'有序选择与无序选择\norder matters\npermutation versus combination', NULL),
    ('MATH.NUMBER.MOD.大数防溢出',
     '取模可以限制保存结果的范围，但乘法或累计表达式可能在执行取模前已经溢出；必须估算中间值，并选择更宽类型、分步取模或安全乘法。',
     E'能同时估算最终答案和中间乘积的最大量级。\n能把加法、乘法和累计过程改写为不会先溢出的取模步骤。',
     E'大组合数逐步取模\nlong long 乘法后再取模溢出\n快速幂中的乘法范围',
     E'模运算防溢出\nmodular overflow protection',
     'BASIC.TYPE.INTEGER.整型溢出'),
    ('MATH.NUMBER.MOD.负数取模修正',
     '不同语言的余数结果可能保留被除数符号，负数直接 % m 可能得到负值；当题目要求 0 到 m-1 的标准剩余类时，应在 m>0 前提下规范化。',
     E'能区分语言余数运算与数学标准剩余类。\n能用边界值验证规范化结果始终位于 [0,m)。',
     E'循环下标向左移动\n带负差值的模方程\nPython 与 C++ 负数取模差异',
     E'标准化余数\npositive modulo\nmod normalization', NULL),
    ('MATH.BIT.MASK.掩码转移',
     '掩码转移通过设置、清除或翻转特定位生成新状态；每个操作必须匹配题意中的加入、移除或切换，并检查该转移是否满足前置条件。',
     E'能分别写出加入、删除和翻转一位的状态变化。\n能在转移前检查对象是否已在集合及是否允许重复操作。',
     E'状态压缩 DP 加入新对象\n访问集合中移除对象\n误用异或导致已存在位被清除',
     E'位掩码状态转移\nbitmask transition',
     'MATH.BIT.MASK.集合掩码'),
    ('MATH.BIT.OP.取某一位',
     '读取整数第 i 位通常构造 1<<i 的单位掩码再按位与，或先右移再取最低位；位编号、整数类型宽度和运算优先级必须明确。',
     E'能从二进制位权推导取位表达式。\n能检查 i 的合法范围并用括号消除优先级歧义。',
     E'提取二进制第 i 位\n判断奇偶与特定位\n1<<i 使用窄类型溢出',
     E'位提取\nbit extraction\nbit test',
     'MATH.BIT.BINARY.位权'),
    ('MATH.COUNT.PERM.重复选择',
     '重复选择表示同一对象可在不同选择位置再次出现；是否允许重复会改变候选空间、状态记录和计数公式，不能从样例重复情况猜测。',
     E'能从题目约束判断选择是有放回还是无放回。\n能比较允许重复与禁止重复时的最小计数结果。',
     E'可重复数字组成序列\n有放回抽取\n枚举时错误使用 visited 禁止重复',
     E'有放回选择\nselection with repetition\nrepetition allowed',
     'MATH.COUNT.PERM.顺序是否重要'),
    ('ENG.DEBUG.BOUNDARY.最小输入',
     '最小输入是题目约束允许的最小规模或最少结构，用来暴露初始化、空循环、首元素和单元素边界；若 0 合法，还必须区分空输入与规模为 0。',
     E'能从约束中列出最小合法输入而不是只测试样例。\n能预测循环、数组和返回值在最小规模下是否仍有定义。',
     E'n=0 或 n=1 的循环\n只有一个节点或一条记录\n空字符串与单字符输入',
     E'最小规模测试\nminimum valid input\nboundary case', NULL),
    ('ENG.DEBUG.TRACE.循环状态',
     '循环状态追踪按迭代记录进入前状态、当前输入、执行分支和离开后状态，目标是找到期望值与实际值第一次分叉的那一轮。',
     E'能选择决定循环正确性的少量关键变量。\n能用表格定位第一轮错误而不是只观察最终答案。',
     E'双指针移动轨迹\n累计变量首次偏差\n循环边界最后一轮状态',
     E'循环变量跟踪\niteration trace\nstate trace',
     'BASIC.LOOP.BOUNDARY.最后一次迭代'),
    ('ENG.COMPLEXITY.TRADEOFF.空间换时间边界',
     '空间换时间只有在额外内存不超过限制且预处理能被足够多查询复用时才有收益；应同时估算元素数、每项字节、容器开销和访问次数。',
     E'能把内存限制换算为可存储元素数量级。\n能比较直接计算、预处理和缓存方案的总时间与空间。',
     E'频次数组替代重复扫描\n多次查询的前缀预处理\n值域过大导致计数数组不可行',
     E'时空权衡边界\nspace-time tradeoff',
     'ENG.COMPLEXITY.SPACE.数组规模'),
    ('ENG.DEBUG.SAMPLE.手算对照',
     '手算对照用一个足够小的输入同时记录期望状态和程序状态，并从第一处不同开始回查转移、边界或初始化，而不是只比较最终输出。',
     E'能手工计算最小样例的中间状态。\n能指出期望与实际第一次不同的变量和语句。',
     E'前缀和逐项对照\n排序一轮后的数组状态\n图搜索队列进出顺序',
     E'人工推演\ndry run\nexpected-versus-actual trace', NULL),
    ('ENG.DEBUG.TRACE.DP_表变化',
     'DP 表变化追踪必须先写明每个维度和单元格的含义，再按转移顺序记录旧值、候选值和最终值；滚动数组还要区分本轮与上轮。',
     E'能为代表性单元格标注状态含义和转移来源。\n能从更新顺序判断是否错误读取了本轮新值。',
     E'背包 DP 表格手算\n二维 DP 边界行列\n滚动数组正序与逆序更新',
     E'DP 状态表追踪\ndynamic programming table trace',
     'ALGO.DP.STATE.状态含义'),
    ('ENG.STYLE.INVARIANT.循环不变量',
     '循环不变量是在每轮开始或结束都必须成立的状态陈述；初始化建立它、循环体保持它、终止条件再把它转换成最终结论。',
     E'能用一句可验证的话写出循环不变量。\n能分别检查初始化、保持和终止三个环节。',
     E'二分区间始终包含答案\n前缀累计已覆盖的范围\n双指针窗口满足的约束',
     E'循环保持条件\nloop invariant',
     'BASIC.LOOP.BOUNDARY.左闭右开'),
    ('ENG.COMPLEXITY.SPACE.数组规模',
     '数组内存由元素数量乘以单个元素字节数决定，还要计入数组份数、二维展开、栈上分配和语言容器开销，不能只看下标上限。',
     E'能根据类型和维度估算数组基础内存。\n能识别多份数组、二维结构和栈分配带来的额外风险。',
     E'10^7 个 int 的内存估算\n二维 DP 表超内存\n局部大数组导致栈空间不足',
     E'数组内存估算\narray memory footprint',
     'BASIC.TYPE.INTEGER.int_范围'),
    ('ENG.DEBUG.TRACE.递归栈',
     '递归栈的每一层保存本层参数、局部状态和返回位置；追踪时应按调用深度记录进入参数、子调用返回值和本层合并结果。',
     E'能画出前几层调用帧及其参数变化。\n能判断递归深度、终止推进和返回值合并是否正确。',
     E'阶乘与斐波那契调用树\n树遍历递归返回顺序\n深度过大引发栈溢出',
     E'调用栈跟踪\nrecursion stack\ncall frame trace',
     'BASIC.RECURSION.STATE.递归转移'),
    ('ENG.ERROR.COMPILE.语法拼写',
     '语法或拼写错误使代码无法通过编译或解释；报错位置可能只是解析器发现问题的位置，应同时检查前一行的括号、引号、分隔符、类型名和标识符。',
     E'能从第一条编译错误开始定位而不是被后续连锁错误干扰。\n能按成对符号、关键字和标识符逐类检查。',
     E'括号或引号未闭合\n变量名大小写不一致\nC++ 分号与模板尖括号错误',
     E'编译语法错误\nsyntax error\nidentifier typo', NULL),
    ('ENG.ERROR.RUNTIME.数组越界',
     '数组越界是访问下标落在合法范围之外；下标等于长度、负下标语义差异、邻格偏移和空数组访问都可能触发异常或无声破坏内存。',
     E'能在每次访问前写出合法下标区间。\n能用最小输入和边界位置检查所有下标来源。',
     E'i<=n 导致访问 a[n]\n网格邻居先访问后判界\n空 vector 读取第一个元素',
     E'下标越界\nindex out of bounds\nout-of-range access',
     'BASIC.ARRAY.INDEX.长度与最后下标'),
    ('BASIC.EXPR.COMPARE.边界比较',
     '边界比较把题目中的小于、不超过、至少和区间端点翻译成 <、<=、>= 等关系；是否包含等号必须与区间定义和循环终止条件一致。',
     E'能把自然语言边界先写成数学不等式。\n能用恰好等于边界的输入验证比较符。',
     E'分数等级临界值\n区间是否包含右端点\n允许相等时误用严格不等号',
     E'临界值比较\nboundary comparison\nendpoint inclusion', NULL),
    ('BASIC.ARRAY.PREFIX.频次统计',
     '频次统计用数组下标或映射键表示类别，用存储值表示出现次数；必须确认值域、初始化、重复累计和查询不存在类别时的结果。',
     E'能说明每个下标或键代表什么类别。\n能根据值域选择计数数组或映射，并验证总频次。',
     E'字符或整数出现次数\n众数与重复元素统计\n值域过大仍开直接计数数组',
     E'计数统计\nfrequency counting\nhistogram',
     'BASIC.ARRAY.INDEX.下标映射'),
    ('BASIC.IO.MULTI_CASE.每组状态重置',
     '多组数据中，每组输入、临时数组、累计值和访问标记必须在外层组循环内部重新初始化；只有题目明确跨组共享的常量或预处理结果才能保留。',
     E'能给变量标注全局共享、每组重置或每次迭代更新的生命周期。\n能在第二组最小输入上检查上一组状态是否残留。',
     E'多测试用例累计值串组\nvisited 数组没有清空\n预处理表与每组答案的生命周期区分',
     E'测试用例状态清理\nper-case reset\ntest case isolation',
     'BASIC.IO.MULTI_CASE.显式_T_组循环'),
    ('BASIC.ARRAY.INDEX.下标映射',
     '下标映射把题面编号、坐标或值域转换为数组位置；转换公式必须在读入、存储、访问和输出各处保持一致，并明确是否存在偏移。',
     E'能写出外部编号到内部下标及其逆映射。\n能用第一个和最后一个对象验证映射边界。',
     E'1 基编号转 0 基数组\n离散值映射到计数下标\n坐标偏移后输出原编号',
     E'索引映射\nindex mapping\nbase conversion', NULL),
    ('BASIC.FUNCTION.PARAM.可变对象风险',
     '数组、列表、映射等可变对象可能以引用或共享状态传入函数；函数内修改、别名指向和可变默认参数会让调用者或后续调用看到意外变化。',
     E'能判断参数修改是否会影响调用方对象。\n能区分共享、浅拷贝、深拷贝和返回新对象的适用边界。',
     E'Python 可变默认列表跨调用累积\n函数原地修改数组\n两个变量指向同一容器',
     E'可变参数共享\nmutable aliasing\npass-by-reference risk',
     'BASIC.FUNCTION.DEF.参数设计'),
    ('BASIC.RECURSION.STATE.回溯恢复',
     '回溯在进入子问题前做选择并修改状态，返回后必须把所有共享状态恢复到进入前；恢复顺序应与修改对应，提前返回也不能跳过清理。',
     E'能列出一次选择修改的全部变量。\n能验证 choose、recurse、undo 三步在每条返回路径上成对出现。',
     E'路径数组 push 后漏 pop\nvisited 标记未恢复\n计数变量在剪枝返回时残留',
     E'撤销选择\nbacktracking state restoration\nchoose-unchoose',
     'BASIC.RECURSION.STATE.递归转移'),
    ('BASIC.ARRAY.INDEX.长度与最后下标',
     '长度为 n 的 0 基序列合法下标是 0 到 n-1；空序列没有最后下标，使用 length-1 前必须先确认序列非空。',
     E'能同时写出长度、元素个数和最后合法下标。\n能用 n=0、n=1 检查循环与尾元素访问。',
     E'遍历 i<n 与 i<=n 的区别\n访问最后一个元素\n空数组上计算 n-1',
     E'末下标\nlast valid index\nlength versus index', NULL),
    ('BASIC.STRING.MATCH.未找到结果哨兵',
     '字符串查找失败通常返回 -1、npos、null 或其他哨兵值；该值不是合法位置，必须先分支判断，再进行切片、索引或下一次查找。',
     E'能说出所用语言查找 API 的失败返回值。\n能在查找失败时阻止哨兵进入下标运算。',
     E'find 返回 npos 后继续加一\nPython find 返回 -1 被当作末尾下标\n不存在分隔符时的切片',
     E'查找失败标记\nnot-found sentinel\nnpos',
     'BASIC.STRING.MATCH.查找出现位置')
) AS curated(code, description, learning_objectives, typical_problems, aliases, prerequisites)
WHERE n.code = curated.code
  AND n.enabled = true
  AND n.type = 'KNOWLEDGE_POINT';

CREATE TEMP TABLE discipline_quality_v2_improvements (
    code character varying(100) PRIMARY KEY,
    category character varying(80) NOT NULL,
    name character varying(120) NOT NULL,
    description character varying(800) NOT NULL,
    skill_unit_code character varying(160) NOT NULL,
    primary_knowledge_node_code character varying(160) NOT NULL,
    knowledge_node_codes character varying(2400) NOT NULL,
    related_mistake_codes character varying(1600) NOT NULL,
    improvement_goal character varying(1200) NOT NULL,
    practice_strategy character varying(1200) NOT NULL,
    student_benefit character varying(800) NOT NULL,
    teacher_explanation character varying(1200) NOT NULL,
    teaching_action character varying(120) NOT NULL,
    applicable_languages character varying(800) NOT NULL
) ON COMMIT DROP;

INSERT INTO discipline_quality_v2_improvements (
    code, category, name, description, skill_unit_code,
    primary_knowledge_node_code, knowledge_node_codes, related_mistake_codes,
    improvement_goal, practice_strategy, student_benefit, teacher_explanation,
    teaching_action, applicable_languages
) VALUES
    ('IP_DQ2_MATH_DEFINITION_BOUNDARY_CHECKLIST',
     '提升点/数学定义边界', '用定义表检查计数与数论边界',
     '适用于公式能够写出，但仍容易把顺序、重复、交集、特殊值或取模时机读错的学生。',
     'SK_V6_MATH_COUNT_NUMBER_BOUNDARY', 'MATH.COUNT.PERM.顺序是否重要',
     E'MATH.COUNT.PERM.顺序是否重要\nMATH.COUNT.PERM.重复选择\nMATH.COUNT.INCLUSION.集合重叠\nMATH.NUMBER.PRIME.1_不是质数\nMATH.NUMBER.GCD.除零边界\nMATH.NUMBER.MOD.模意义保持',
     E'MP_V6_COUNT_ORDER_IMPORTANCE_MISREAD\nMP_V6_INCLUSION_EXCLUSION_OVERLAP_COUNTED_TWICE\nMP_V6_MOD_APPLIED_ONLY_AT_FINAL_OVERFLOWS',
     '在套公式前先把计数对象、顺序、是否重复、全集边界、特殊值和取模位置写成定义表。',
     '选择三道最小题面，逐题填写“对象、顺序、重复、交集、特殊值、取模时机”六格表，再用交换两个对象和加入特殊值构造反例。',
     '把模型读错与公式计算错分开，能在写代码前发现排列组合、容斥和模运算边界问题。',
     '让学生先口述六格定义表，再说明一个反例为什么能排除错误模型；只有定义稳定后才允许写公式。',
     '填写定义表并用最小反例验模', E'PYTHON\nCPP17'),
    ('IP_DQ2_BITMASK_OBJECT_BIT_TABLE',
     '提升点/位掩码', '建立对象与二进制位对照表',
     '适用于能使用位运算语法，但对象编号、位偏移和操作含义仍会混淆的学生。',
     'SK_BITMASK_STATE_MEANING', 'MATH.BIT.MASK.集合掩码',
     E'MATH.BIT.MASK.集合掩码\nMATH.BIT.MASK.状态判断\nMATH.BIT.OP.取某一位\nMATH.BIT.OP.设置清除位',
     E'MP_BITMASK_INDEX_OFF_BY_ONE\nMP_BIT_SHIFT_PRECEDENCE_WRONG',
     '让每一个位运算表达式都能回译为明确的对象、集合操作和前置条件。',
     '用 4 个对象画出编号、位号、单位掩码和二进制状态四列表；分别执行查询、加入、移除、翻转，并检查编号从 1 开始的偏移。',
     '减少位偏移、优先级和异或误用，使状态压缩代码可以被逐位验证。',
     '随机给出两个掩码，要求学生不运行代码就解释每一位和每次操作；重点检查括号与对象编号。',
     '画位表并逐项回译位运算', E'PYTHON\nCPP17'),
    ('IP_DQ2_NUMBER_THEORY_SPECIAL_VALUE_TABLE',
     '提升点/数论边界', '建立数论特殊值测试表',
     '适用于掌握质数、gcd、lcm 和取模算法，但常遗漏 0、1、负数或中间溢出的学生。',
     'SK_NUMBER_THEORY_BOUNDARY', 'MATH.NUMBER.PRIME.1_不是质数',
     E'MATH.NUMBER.PRIME.1_不是质数\nMATH.NUMBER.GCD.除零边界\nMATH.NUMBER.MOD.负数取模修正\nMATH.NUMBER.MOD.模意义保持',
     E'MP_LCM_OVERFLOW_BEFORE_DIVIDE\nMP_PRIME_ONE_TREATED_AS_PRIME',
     '把数论定义的特殊输入和表达式中间范围变成固定自测，而不是依赖样例碰到。',
     '为质数、gcd/lcm、取模各列出 0、1、负数、相等数、完全平方数和大乘积；先写期望，再运行函数逐项比对。',
     '能稳定处理数学定义边界，并在 lcm 或模乘执行前识别中间溢出。',
     '要求学生解释每个特殊值由哪条定义决定；对 lcm 让其比较先除后乘与先乘后除的中间量级。',
     '建立特殊值表并逐项复测', E'PYTHON\nCPP17'),
    ('IP_DQ2_DEBUG_FAILURE_REPRODUCTION_LOOP',
     '提升点/提交调试', '形成复现、修复、扩展复测闭环',
     '适用于看到 CE、RE、WA 或 TLE 后直接改代码，修复依据和复测范围都不清楚的学生。',
     'SK_V6_DEBUG_SUBMISSION_FEEDBACK_LOOP', 'ENG.ERROR.COMPILE.语法拼写',
     E'ENG.ERROR.COMPILE.语法拼写\nENG.ERROR.RUNTIME.数组越界\nENG.ERROR.WRONG_ANSWER.边界遗漏\nENG.ERROR.TIME.复杂度过高\nENG.DEBUG.SAMPLE.最小反例\nCONTEST.SUBMIT.REVIEW.再次提交策略',
     E'MP_V6_DEBUG_FIX_WITHOUT_REPRODUCING_FAILURE\nMP_V6_DEBUG_ONLY_CHECKS_CHANGED_SAMPLE\nMP_V6_TLE_OPTIMIZES_CONSTANT_NOT_COMPLEXITY',
     '每次失败都留下可复现证据、单一修复假设和覆盖相邻风险的复测记录。',
     '按“失败类型、最小复现、第一处分叉、修复假设、原失败复测、边界复测、最大规模复测”填写一次提交卡，再决定是否再次提交。',
     '避免盲改和只过当前样例，把一次提交失败转化为可复用的调试过程。',
     '检查学生能否指出修复前后的唯一差异及三类复测证据；TLE 必须给出数量级变化而非只说常数变小。',
     '填写提交复盘卡并完成三类复测', E'PYTHON\nCPP17'),
    ('IP_DQ2_COMPLEXITY_BUDGET_ESTIMATION',
     '提升点/复杂度', '把数据范围换算为操作预算',
     '适用于知道复杂度符号，却不能结合 n、m、q、状态维度和语言判断方案是否可行的学生。',
     'SK_COMPLEXITY_CONSTRAINT_READING', 'ENG.COMPLEXITY.TIME.数据范围反推',
     E'ENG.COMPLEXITY.TIME.数据范围反推\nCONTEST.READING.CONSTRAINT.数据范围\nALGO.ENUM.COMPLEXITY.数据范围反推',
     'MP_COMPLEXITY_IGNORES_MAX_CONSTRAINTS',
     '把题目最大约束代入主循环和状态维度，形成可解释的数量级预算。',
     '对同一题分别估算 O(n)、O(n log n)、O(n^2) 和 O(nm) 的最大操作量；再补入查询次数、常数级容器操作和内存，写出淘汰理由。',
     '能在编码前排除明显不可行方案，并区分预处理成本、单次查询和总成本。',
     '要求学生展示代入后的数值，不接受只写 O 符号；再追问哪个维度被遗漏会让预算失真。',
     '代入最大约束并写方案预算', E'PYTHON\nCPP17'),
    ('IP_DQ2_MINIMAL_COUNTEREXAMPLE_TRACE',
     '提升点/调试方法', '用最小反例定位第一处分叉',
     '适用于只反复运行题目样例、能看到答案错误却无法定位中间状态偏差的学生。',
     'SK_DEBUG_MINIMAL_COUNTEREXAMPLE', 'ENG.DEBUG.SAMPLE.最小反例',
     E'ENG.DEBUG.SAMPLE.最小反例\nENG.DEBUG.SAMPLE.手算对照\nENG.DEBUG.BOUNDARY.最小输入\nENG.DEBUG.TRACE.循环状态',
     'MP_DEBUG_ONLY_RETESTS_SAMPLE',
     '把失败输入缩到仍会出错的最小结构，并用期望/实际双列找到第一处状态分叉。',
     '从一个失败输入逐项删除元素或步骤；每次保留仍失败的版本，最后为关键变量写“迭代、输入、期望、实际”表并圈出第一处差异。',
     '降低调试噪音，让错误从最终答案问题变成可定位的状态转移问题。',
     '让学生说明每次删减为何不改变错误本质，并只从第一处分叉向前检查，不允许先猜最后一行。',
     '缩小反例并标记首个状态分叉', E'PYTHON\nCPP17'),
    ('IP_DQ2_ARRAY_OLD_NEW_STATE_AUDIT',
     '提升点/数组更新', '审计数组更新中的旧值与新值',
     '适用于遍历与更新同一数组时，容易覆盖后续仍需读取的旧状态或让多个数组下标错位的学生。',
     'SK_ARRAY_TRAVERSAL_UPDATE_SAFETY', 'BASIC.ARRAY.TRAVERSE.同步遍历',
     E'BASIC.ARRAY.TRAVERSE.同步遍历\nBASIC.ARRAY.TRAVERSE.逆序遍历\nBASIC.ARRAY.UPDATE.原地修改\nBASIC.ARRAY.UPDATE.临时数组\nBASIC.ARRAY.UPDATE.覆盖风险',
     E'MP_ARRAY_ACCUMULATOR_NOT_RESET_PER_CASE\nMP_ARRAY_IN_PLACE_UPDATE_OVERWRITES_SOURCE\nMP_ARRAY_PARALLEL_TRAVERSE_MISALIGNED',
     '让每条数组赋值都标明读取的是旧状态还是本轮新状态，并选择与依赖方向一致的更新方式。',
     '对一轮更新画 old/new 两行，给每个右值来源连线；分别尝试临时数组、正序和逆序，使用 3 个元素手算哪种方式保持依赖。',
     '减少原地覆盖和同步遍历错位，能解释为什么需要临时数组或特定遍历方向。',
     '要求学生逐条标注读旧或写新，并在多组数据场景额外指出累计量何时清零。',
     '画 old/new 依赖图并选择更新顺序', E'PYTHON\nCPP17'),
    ('IP_DQ2_LOOP_ENDPOINT_TABLE',
     '提升点/循环边界', '建立区间与循环端点对照表',
     '适用于能写循环，但包含关系、range 右端和最后一次迭代经常差一位的学生。',
     'SK_LOOP_ENDPOINT_INCLUSION', 'BASIC.LOOP.BOUNDARY.左闭右开',
     E'BASIC.LOOP.BOUNDARY.左闭右开\nBASIC.LOOP.BOUNDARY.左闭右闭\nBASIC.EXPR.COMPARE.边界比较',
     E'MP_LOOP_LAST_ELEMENT_SKIPPED\nMP_LOOP_RANGE_RIGHT_ENDPOINT_MISREAD\nMP_LOOP_STRICT_INEQUALITY_WHEN_EQUAL_ALLOWED',
     '把题面区间、数学区间、循环条件、第一次和最后一次迭代放进同一张表。',
     '分别对空区间、单元素和两个元素填写 [l,r)、[l,r] 的元素集合与循环写法；再用恰好等于边界的输入逐项验证。',
     '能从区间语义推导循环，而不是靠修改 < 和 <= 试错。',
     '随机给出一个区间口述，要求学生写出元素数、首尾元素和代码条件；四项必须互相一致。',
     '填写端点表并测试空与单元素区间', E'PYTHON\nCPP17'),
    ('IP_DQ2_STRING_SEARCH_BOUNDARY_MATRIX',
     '提升点/字符串', '建立字符串查找边界矩阵',
     '适用于字符串查找和构造基本逻辑正确，但会遗漏失败哨兵、重叠匹配、前后缀和结果顺序的学生。',
     'SK_STRING_SEARCH_AND_BUILD', 'BASIC.STRING.MATCH.查找出现位置',
     E'BASIC.STRING.MATCH.查找出现位置\nBASIC.STRING.MATCH.统计出现次数\nBASIC.STRING.MATCH.前后缀判断\nBASIC.STRING.BUILD.追加字符\nBASIC.STRING.BUILD.结果顺序',
     E'MP_STRING_BUILD_ORDER_REVERSED\nMP_STRING_FIND_NOT_FOUND_USED_AS_INDEX\nMP_STRING_OVERLAPPING_MATCH_SKIPPED',
     '让查找失败、开头、结尾、重叠、空模式和构造顺序成为固定自测维度。',
     '用“是否找到、起点、下一次起点、是否允许重叠、结果追加方向”五列测试六类短字符串，并显式记录 API 的失败返回值。',
     '能在索引或切片前处理哨兵，并稳定控制重叠计数与结果构造顺序。',
     '让学生先预测每个测试的所有匹配位置，再运行代码；若只给计数而说不出位置，说明边界仍未掌握。',
     '填写查找矩阵并预测全部匹配位置', E'PYTHON\nCPP17'),
    ('IP_DQ2_FUNCTION_RECURSION_CONTRACT_TABLE',
     '提升点/函数递归', '为函数与递归写输入输出契约',
     '适用于函数参数、副作用、返回路径和递归结果合并互相混在一起的学生。',
     'SK_V6_FUNCTION_RECURSION_CONTRACT', 'BASIC.FUNCTION.DEF.参数设计',
     E'BASIC.FUNCTION.DEF.参数设计\nBASIC.FUNCTION.DEF.返回值设计\nBASIC.FUNCTION.PARAM.可变对象风险\nBASIC.FUNCTION.RETURN.完整返回路径\nBASIC.RECURSION.STATE.递归转移',
     E'MP_V6_FUNCTION_MISSING_RETURN_ON_BRANCH\nMP_V6_FUNCTION_MUTABLE_DEFAULT_STATE_LEAKS\nMP_V6_RECURSION_MERGE_IGNORES_CHILD_RESULT',
     '把参数角色、可变状态、返回值、终止条件和子结果合并方式写成调用者可检查的契约。',
     '为两个普通函数和一个递归函数填写“输入、共享修改、返回、所有返回路径、规模推进、子结果合并”六列，再用连续调用两次检查状态泄漏。',
     '减少隐藏副作用、漏 return 和递归结果丢失，使函数可以独立测试。',
     '要求学生只看契约预测两次调用结果；若实际不一致，必须定位是共享状态、返回路径还是合并规则破坏契约。',
     '填写函数契约并做连续调用测试', E'PYTHON\nCPP17'),
    ('IP_DQ2_GRID_COORDINATE_CONVENTION',
     '提升点/网格坐标', '统一网格坐标与方向约定',
     '适用于题面 x/y、数组 row/column、方向增量和边界判断经常交换的学生。',
     'SK_V6_GRID_COORDINATE_TRANSFORM', 'BASIC.ARRAY.MATRIX.行列含义',
     E'BASIC.ARRAY.MATRIX.行列含义\nBASIC.ARRAY.MATRIX.方向遍历\nBASIC.ARRAY.MATRIX.边界检查\nMATH.GEOMETRY.COORD.x_y_坐标\nMATH.GEOMETRY.COORD.方向数组\nMATH.GEOMETRY.COORD.坐标偏移',
     E'MP_V6_GRID_DIRECTION_DELTA_PAIR_SWAPPED\nMP_V6_GRID_INPUT_COORDINATE_NOT_NORMALIZED\nMP_V6_GRID_OBSTACLE_CHECK_AFTER_VISIT',
     '在访问网格前固定题面坐标、数组下标、原点、正方向和方向数组的统一约定。',
     '画一个 2×3 网格，标注四角的题面坐标和数组下标；逐个方向计算新位置，并按“先判界、再判障碍、后访问”执行。',
     '减少行列交换、偏移漏做和先访问后判界，让网格算法的坐标转换可视化。',
     '让学生现场把一个题面坐标转成数组下标并走四个方向；任何一步都要同时说出 row/column 与 x/y。',
     '绘制坐标对照网格并逐方向验算', E'PYTHON\nCPP17'),
    ('IP_DQ2_MULTICASE_LIFECYCLE_CHECKLIST',
     '提升点/多组输入', '给多组数据变量标注生命周期',
     '适用于能读取单组输入，但 T 组、EOF、每组输出格式和状态重置容易互相串位的学生。',
     'SK_V6_IO_MULTICASE_FORMAT_CONTRACT', 'BASIC.IO.MULTI_CASE.显式_T_组循环',
     E'BASIC.IO.MULTI_CASE.显式_T_组循环\nBASIC.IO.MULTI_CASE.未知组数读到_EOF\nBASIC.IO.MULTI_CASE.每组状态重置\nBASIC.IO.MULTI_CASE.多组输出格式\nBASIC.IO.STDOUT.按要求换行',
     E'MP_V6_IO_CASE_OUTPUT_SEPARATOR_WRONG\nMP_V6_IO_EOF_LOOP_DROPS_LAST_RECORD\nMP_V6_IO_TREATED_T_AS_DATA_VALUE',
     '把输入控制变量、每组数据、临时状态、跨组预处理和输出编号放到正确循环层级。',
     '给代码中的变量贴“全局常量、一次预处理、每组重置、组内更新、输出编号”标签；用两组不同大小输入和 EOF 末记录检查生命周期。',
     '减少把 T 当数据、漏最后一组、状态串组和输出分隔错误。',
     '要求学生指出每个初始化语句为何位于当前层级，再删除或移动一处初始化，让其预测第二组会出现什么残留。',
     '标注变量生命周期并用两组输入复测', E'PYTHON\nCPP17');

INSERT INTO public.ai_standard_improvement_points (
    applicable_languages, category, code, created_at, description, enabled,
    improvement_goal, knowledge_node_codes, library_version, name,
    practice_strategy, primary_knowledge_node_code, related_mistake_codes,
    skill_unit_code, student_benefit, teacher_explanation, updated_at
)
SELECT v.applicable_languages, v.category, v.code, CURRENT_TIMESTAMP, v.description, true,
       v.improvement_goal, v.knowledge_node_codes, 'informatics-discipline-quality-v2', v.name,
       v.practice_strategy, v.primary_knowledge_node_code, v.related_mistake_codes,
       v.skill_unit_code, v.student_benefit, v.teacher_explanation, CURRENT_TIMESTAMP
FROM discipline_quality_v2_improvements v
JOIN public.ai_standard_skill_units s
  ON s.code = v.skill_unit_code AND s.enabled = true
JOIN public.informatics_knowledge_nodes n
  ON n.code = v.primary_knowledge_node_code AND n.enabled = true AND n.type = 'KNOWLEDGE_POINT'
WHERE NOT EXISTS (
    SELECT 1
    FROM regexp_split_to_table(v.related_mistake_codes, E'\n') ref
    LEFT JOIN public.ai_standard_mistake_points m
      ON m.code = btrim(ref) AND m.enabled = true
    WHERE btrim(ref) <> '' AND m.code IS NULL
)
ON CONFLICT (code) DO UPDATE SET
    applicable_languages = EXCLUDED.applicable_languages,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    enabled = EXCLUDED.enabled,
    improvement_goal = EXCLUDED.improvement_goal,
    knowledge_node_codes = EXCLUDED.knowledge_node_codes,
    library_version = EXCLUDED.library_version,
    name = EXCLUDED.name,
    practice_strategy = EXCLUDED.practice_strategy,
    primary_knowledge_node_code = EXCLUDED.primary_knowledge_node_code,
    related_mistake_codes = EXCLUDED.related_mistake_codes,
    skill_unit_code = EXCLUDED.skill_unit_code,
    student_benefit = EXCLUDED.student_benefit,
    teacher_explanation = EXCLUDED.teacher_explanation,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_standard_library_items (
    ability_point, applicable_languages, category, code, created_at, description,
    enabled, knowledge_node_codes, layer, library_version, name, related_items,
    severity, skill_unit_code, student_benefit, teacher_explanation, teaching_action,
    updated_at, when_to_use, primary_knowledge_node_code, related_knowledge_node_codes
)
SELECT v.name, v.applicable_languages, v.category, v.code, CURRENT_TIMESTAMP, v.description,
       true, v.knowledge_node_codes, 'IMPROVEMENT_POINT', 'informatics-discipline-quality-v2',
       v.name, v.related_mistake_codes, 'MEDIUM', v.skill_unit_code, v.student_benefit,
       v.teacher_explanation, v.teaching_action, CURRENT_TIMESTAMP, v.description,
       v.primary_knowledge_node_code, v.knowledge_node_codes
FROM discipline_quality_v2_improvements v
JOIN public.ai_standard_improvement_points i
  ON i.code = v.code AND i.enabled = true
ON CONFLICT (layer, code) DO UPDATE SET
    ability_point = EXCLUDED.ability_point,
    applicable_languages = EXCLUDED.applicable_languages,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    enabled = EXCLUDED.enabled,
    knowledge_node_codes = EXCLUDED.knowledge_node_codes,
    library_version = EXCLUDED.library_version,
    name = EXCLUDED.name,
    related_items = EXCLUDED.related_items,
    severity = EXCLUDED.severity,
    skill_unit_code = EXCLUDED.skill_unit_code,
    student_benefit = EXCLUDED.student_benefit,
    teacher_explanation = EXCLUDED.teacher_explanation,
    teaching_action = EXCLUDED.teaching_action,
    updated_at = CURRENT_TIMESTAMP,
    when_to_use = EXCLUDED.when_to_use,
    primary_knowledge_node_code = EXCLUDED.primary_knowledge_node_code,
    related_knowledge_node_codes = EXCLUDED.related_knowledge_node_codes;

INSERT INTO public.ai_standard_library_legacy_mappings (
    confidence, created_at, legacy_code, legacy_layer, migration_status,
    source_version, target_code, target_type, updated_at
)
SELECT 1.0, CURRENT_TIMESTAMP, v.code, 'IMPROVEMENT_POINT', 'MAPPED',
       'informatics-discipline-quality-v2', v.code, 'IMPROVEMENT_POINT', CURRENT_TIMESTAMP
FROM discipline_quality_v2_improvements v
JOIN public.ai_standard_improvement_points i
  ON i.code = v.code AND i.enabled = true
ON CONFLICT (legacy_layer, legacy_code) DO UPDATE SET
    confidence = EXCLUDED.confidence,
    migration_status = EXCLUDED.migration_status,
    source_version = EXCLUDED.source_version,
    target_code = EXCLUDED.target_code,
    target_type = EXCLUDED.target_type,
    updated_at = CURRENT_TIMESTAMP;
