-- 学科质量第三批精修：按生产结构引用和有限行为证据精修 ALGO/DS 分支，
-- 并为已有正式错因但缺少提升点的非兼容能力补齐可执行教学闭环。
-- 不新增知识树节点，不修改稳定 code，不触碰题目、提交、诊断事实和课堂业务数据。

UPDATE public.informatics_knowledge_nodes n
SET description = curated.description,
    learning_objectives = curated.learning_objectives,
    typical_problems = curated.typical_problems,
    aliases = curated.aliases,
    prerequisites = curated.prerequisites,
    library_version = 'informatics-knowledge-discipline-v3',
    updated_at = CURRENT_TIMESTAMP
FROM (VALUES
    ('ALGO.GRAPH.SHORTEST.Dijkstra',
     'Dijkstra 算法在边权非负时维护起点到各点的暂定最短距离，每次处理当前距离最小的未确定状态并松弛出边；使用优先队列时，同一节点可能有多个历史状态，弹出后必须跳过已经过期的距离。',
     E'能说明 dist、已确定状态和优先队列元素各自表示什么。\n能检查非负边权前提，并用当前弹出距离与 dist 对比过滤陈旧状态。',
     E'非负带权图单源最短路\n优先队列中同一节点存在多个距离\n含负权边时判断 Dijkstra 不适用',
     E'戴克斯特拉算法\nDijkstra algorithm\n非负权最短路',
     'ALGO.GRAPH.SHORTEST.松弛操作'),
    ('ALGO.DP.CLASSIC.区间_DP_入门',
     '区间 DP 用 dp[l][r] 表示一个连续区间上的最优值、方案数或可行性，通常按区间长度从短到长计算，并枚举最后一次合并位置、分割点或两端决策，使所有子区间先于当前区间完成。',
     E'能用一句话定义 dp[l][r] 的区间与数值含义。\n能从依赖的子区间推导长度顺序、分割点范围和最终答案位置。',
     E'石子相邻合并最小代价\n回文区间状态转移\n长度顺序或分割点边界错误',
     E'区间动态规划\ninterval dynamic programming\ninterval DP',
     'ALGO.DP.STATE.状态含义'),
    ('ALGO.GREEDY.INTERVAL.区间合并',
     '区间合并先按左端点排序，再维护当前合并段的左右边界；新段与当前段是否相交或接触取决于题目采用闭区间还是半开区间，不能把“合并覆盖范围”误当成“求最优合并顺序”的区间 DP。',
     E'能写出当前合并段在扫描过程中的不变量。\n能根据端点包含关系判断接触区间是否合并，并区分覆盖合并与代价合并。',
     E'合并重叠区间\n闭区间接触端点是否连成一段\n把相邻合并最小代价误写成普通区间合并',
     E'合并区间\nmerge intervals\ninterval union',
     'ALGO.SORT.BASIC.自定义比较'),
    ('ALGO.SORT.BASIC.自定义比较',
     '自定义比较把题意中的主关键字、副关键字、升降序和并列规则转成一致的先后关系；比较器必须满足严格弱序，两个元素相等时不能同时判定彼此在前，否则排序结果可能不稳定或行为未定义。',
     E'能把题目排序规则写成逐级比较表。\n能用相等元素、并列关键字和极端值验证比较器的严格性与完整性。',
     E'按结束时间再按开始时间排序\n分数相同按编号升序\n比较器使用 <= 导致非严格顺序',
     E'比较函数\ncomparator\ncustom sort order', NULL),
    ('ALGO.DP.TRANSITION.枚举决策',
     'DP 转移中的枚举决策是在固定当前状态后，遍历所有可能的最后一步、分割点、选择对象或资源用量，再从合法前驱状态更新；枚举范围必须覆盖全部可行决策且避免把同一决策重复计数。',
     E'能指出转移循环枚举的对象及每个候选对应的前驱状态。\n能用最小状态检查枚举起止、重复贡献和非法前驱过滤。',
     E'区间 DP 枚举分割点\n背包枚举物品或容量\n遗漏最后一个决策或重复计算同一方案',
     E'决策枚举\ntransition choice enumeration\nsplit enumeration',
     'ALGO.DP.STATE.状态含义'),
    ('ALGO.GRAPH.TOPO.队列推进',
     '拓扑排序把当前入度为 0 的节点加入队列；每取出一个节点，只遍历它的出边并把对应后继入度减一，后继首次降到 0 时入队。最终处理节点数少于总节点数说明仍有环或依赖未解除。',
     E'能逐步记录队列、入度和已处理节点数。\n能解释为什么一条边只贡献一次入度减少以及如何用处理数量检测环。',
     E'课程先修顺序\n工序依赖推进\n重复减入度或遗漏环检测',
     E'Kahn 算法\n拓扑队列\nKahn topological sort',
     'ALGO.GRAPH.TOPO.入度'),
    ('ALGO.GREEDY.INTERVAL.边界重叠',
     '判断区间重叠必须先固定端点语义：闭区间 [l,r] 在端点相等时共享位置，半开区间 [l,r) 在前一段右端等于后一段左端时通常不重叠；选择、合并和资源占用问题对接触边界的规则可能不同。',
     E'能把题面区间翻译成闭区间或半开区间。\n能用端点恰好相等的两个区间验证合并或冲突条件。',
     E'会议首尾相接是否冲突\n合并闭区间的接触端点\n离散整数区间与连续时间区间差异',
     E'区间相交\noverlap at endpoints\ninterval boundary conflict',
     'BASIC.LOOP.BOUNDARY.左闭右开'),
    ('ALGO.TWO_POINTERS.WINDOW.合法性判断',
     '滑动窗口合法性是一个可由当前窗口状态判断的不变量，例如不同字符数不超过 k、窗口和不小于目标或重复次数满足限制；右端扩张后若失效，应按单调条件移动左端直到重新合法。',
     E'能用计数、和或最大最小值明确写出窗口合法条件。\n能说明何时需要 while 收缩，以及收缩结束后为何重新满足不变量。',
     E'至多包含 k 种字符的最长子串\n窗口和达到阈值的最短区间\n只收缩一次仍然不合法',
     E'窗口约束\nwindow validity\nsliding window invariant',
     'ALGO.TWO_POINTERS.WINDOW.窗口扩张'),
    ('ALGO.BINARY.ANSWER.左右边界',
     '答案二分的左右边界应分别代表已知不可行、已知可行或尚待搜索的区间端点，初值必须覆盖真实答案且满足约定；边界过窄会漏解，边界含义混乱会让循环和返回值失去证明。',
     E'能为 left、right 写出循环前后的真假含义。\n能从约束构造保证覆盖答案的上下界，并用最小与最大答案验证。',
     E'最小可行容量\n最大可承受距离\n上界取值不足导致答案不在搜索区间',
     E'答案搜索区间\nanswer bounds\nbinary search bounds',
     'ALGO.BINARY.ANSWER.单调性证明'),
    ('ALGO.SEARCH.STATE.状态编码',
     '搜索状态编码必须包含所有会影响后续转移和目标判断的信息，并让不同语义状态得到不同键；只记录位置而忽略钥匙、剩余资源、方向或时间等维度，会把仍需探索的状态错误合并。',
     E'能列出决定未来选择的最小状态维度。\n能设计无歧义元组或编码，并验证 encode/decode 与 visited 键一致。',
     E'位置加钥匙集合的 BFS\n棋盘位置加方向状态\n压缩编码冲突导致错误判重',
     E'状态表示\nstate encoding\nsearch state key',
     'ALGO.SEARCH.STATE.判重'),
    ('ALGO.SIM.STATE.状态同步',
     '模拟中多个状态变量若描述同一时刻，必须从同一旧状态或明确的事件顺序更新；先修改一个变量再让其他变量读取新旧混合值，会产生题面中不存在的中间状态。',
     E'能画出一次事件前后的完整状态快照。\n能区分同步更新与顺序更新，并使用临时变量保持题目规定的时序。',
     E'多个对象同时移动\n库存、价格与订单状态联动\n原地更新让后续变量读取到新状态',
     E'同步状态更新\nsynchronous state update\nstate snapshot',
     'ALGO.SIM.STATE.状态变量选择'),
    ('ALGO.TWO_POINTERS.WINDOW.计数维护',
     '滑动窗口的频次、总和或满足条件数量必须与 [left,right] 的实际元素集合完全一致：右端进入时增加，左端离开时减少，并在计数跨过阈值时同步更新派生指标。',
     E'能为每次指针移动写出加入或删除的唯一更新。\n能用重复元素窗口验证频次、不同元素数和答案统计没有失步。',
     E'字符频次数组维护\n不同元素数量随窗口变化\n左端移动后忘记减少计数',
     E'窗口频次维护\nwindow frequency maintenance\nsliding counter',
     'ALGO.TWO_POINTERS.WINDOW.合法性判断'),
    ('ALGO.GREEDY.CHOICE.反例检查',
     '反例检查通过构造最小输入，验证某个局部最优选择是否可能阻断更优的全局方案；应围绕并列选择、边界接触、后续资源冲突和交换顺序设计，而不是只增加随机大样例。',
     E'能指出贪心选择隐含的必要性质。\n能系统改变两个候选的顺序、代价或边界，寻找使局部最优失败的最小反例。',
     E'按左端点选择区间的反例\n相邻合并使用最小当前代价失败\n并列关键字缺少规则导致不同结果',
     E'贪心反例\ngreedy counterexample\nadversarial case',
     'ALGO.GREEDY.CHOICE.排序依据'),
    ('ALGO.GREEDY.STRUCTURE.优先队列辅助',
     '优先队列只保证快速取出当前比较键最优的候选，不会自动删除已经失效的历史状态；使用懒删除时，应在弹出后用版本、当前距离、时间或有效标记判断候选是否仍可用。',
     E'能说明堆中元素的排序键和业务有效条件。\n能构造同一对象多次入堆的轨迹，并在弹出时过滤陈旧状态。',
     E'Dijkstra 过滤旧距离\n区间任务中过期候选\n堆顶最优但业务状态已失效',
     E'堆辅助贪心\npriority queue with lazy deletion\nheap candidate filtering', NULL),
    ('ALGO.BINARY.ANSWER.check_函数',
     '答案二分的 check(x) 必须只回答候选 x 是否可行，并在整个搜索区间保持单调；它需要完整处理等号和边界，不能依赖上一次调用遗留状态，也不能把优化目标混进可行性判断。',
     E'能写出 check 输入、返回真假和单调方向。\n能用连续三个候选验证真假只发生一次转折，并检查重复调用结果一致。',
     E'容量是否能在限定组数内完成\n距离是否允许放置足够对象\ncheck 复用数组但未清空状态',
     E'可行性函数\nfeasibility predicate\nmonotone check',
     'ALGO.BINARY.ANSWER.单调性证明'),
    ('ALGO.BINARY.INDEX.边界返回',
     '位置二分结束后返回 left、right、mid 或插入位置取决于不变量和循环退出条件；应先定义目标是第一个满足、最后一个满足还是精确命中，再从终止状态推导返回变量。',
     E'能在循环结束时说明 left/right 分别指向什么。\n能用空数组、全部不满足、全部满足和重复值验证返回位置。',
     E'查找第一个不小于目标的位置\n查找最后一个不大于目标的位置\n循环正确但返回 mid 导致边界错误',
     E'二分返回契约\nbinary search return contract\nboundary index',
     'ALGO.BINARY.INDEX.闭区间模板'),
    ('ALGO.DP.STATE.维度选择',
     'DP 状态维度应保留会影响未来决策的最小信息：遗漏维度会把未来不同的情况错误合并，冗余维度则扩大状态数和转移成本。可以用“两个前缀状态的未来选择是否完全相同”检验能否合并。',
     E'能从题目约束列出影响后续的变量。\n能解释每个维度为何必要，并估算加入该维度后的状态规模。',
     E'路径问题遗漏剩余资源维度\n背包状态是否需要物品编号\n状态维度过多导致内存超限',
     E'DP 状态设计\nstate dimension selection\nsufficient state',
     'ALGO.DP.STATE.状态含义'),
    ('ALGO.GRAPH.SHORTEST.距离初始化',
     '最短路初始化通常令起点距离为 0、其余为无穷大；多源最短路需要把所有源点同时置 0。把未访问点初始化为 0 会让松弛条件失效，无穷大参与加法前还要避免溢出。',
     E'能写出起点、普通点和不可达点的初始含义。\n能处理多源初始化，并在 INF 加权前检查当前距离可达。',
     E'单源最短路 dist 初始化\n多源 BFS 或 Dijkstra\nINF 加边权溢出或未达点误设为 0',
     E'最短距离初值\ndistance initialization\ninfinity sentinel',
     'ALGO.GRAPH.SHORTEST.松弛操作'),
    ('ALGO.GRAPH.TOPO.依赖关系',
     '拓扑依赖必须把“先完成 A 才能做 B”建成 A 指向 B 的有向边，并让 B 的入度增加；边方向颠倒会得到相反顺序，重复依赖还可能重复计算入度。',
     E'能从自然语言写出前置者、后继者和边方向。\n能用三节点依赖图核对入度、可开始节点和输出顺序。',
     E'课程先修关系建图\n任务工序排序\n把依赖边方向反建',
     E'先修关系\ndependency edge\nprecedence relation',
     'DS.GRAPH.MODEL.有向无向'),
    ('ALGO.PREFIX.SUM.下标偏移',
     '前缀和常用 prefix[0]=0，使原数组前 i 个元素对应 prefix[i]；原数组闭区间 [l,r] 的查询式取决于原数组和 prefix 的基准，下标偏移必须在建表、查询和输出中保持一致。',
     E'能画出原数组下标、元素个数和 prefix 下标的对应表。\n能从前缀定义推导区间公式，并用首元素、末元素和完整区间验证。',
     E'0 基数组配 1 基前缀和\n查询第一个元素时访问负下标\n二维前缀坐标整体偏移一位',
     E'前缀索引转换\nprefix index offset\nzero padding',
     'ALGO.PREFIX.SUM.前缀定义'),
    ('DS.GRAPH.MODEL.有向无向',
     '有向边只允许沿规定方向到达，无向边表示两个方向都可通行；建图时无向关系通常加入两条邻接记录，有向关系只加入一条，方向还会改变入度、连通性和最短路含义。',
     E'能从题面关系判断边是否有向。\n能画出邻接表，并说明方向对可达、入度和路径的影响。',
     E'道路是否双向\n先修关系有向建图\n无向边只存一次导致反向不可达',
     E'有向图与无向图\ndirected versus undirected graph\nedge direction',
     'DS.GRAPH.MODEL.点的定义'),
    ('DS.LINEAR.LIST.插入删除',
     '链表插入和删除通过重连前驱、当前节点和后继之间的链接完成；修改链接前要保存仍会使用的旧后继或前驱，并分别处理空链、头部、尾部和中间位置。',
     E'能画出操作前后的链接变化并按依赖顺序写赋值。\n能在空链、单节点、头尾操作下保持所有前后关系一致。',
     E'在指定节点后插入\n删除头节点或尾节点\n先覆盖 next 导致剩余链表丢失',
     E'链表增删\nlinked list insertion and deletion\nrelink nodes',
     'DS.LINEAR.LIST.前驱后继'),
    ('DS.SET_MAP.MAP.频次统计',
     '用 map 统计频次时，key 表示被分类的对象，value 表示已出现次数；首次出现从 0 增加到 1，每读入一个对象总频次应恰好增加 1，查询不存在键时要区分默认 0 与实际插入。',
     E'能写出 key、value 和总频次三个不变量。\n能用重复对象、未出现对象和空输入验证首次计数与默认值。',
     E'单词或整数出现次数\n统计众数与去重后种类数\n首次出现没有计入或不存在键被意外插入',
     E'映射计数\nfrequency map\ncounting dictionary',
     'DS.SET_MAP.MAP.键值关系'),
    ('DS.GRAPH.MODEL.权值含义',
     '图边权必须对应题面中的时间、距离、费用、容量、概率或其他量，并决定路径上如何聚合：求和、取最大最小或相乘不能混用。相同图结构在不同权值语义下可能需要不同算法。',
     E'能为每条边写出权值单位和路径聚合规则。\n能根据非负性、是否统一权值和优化目标选择匹配算法。',
     E'时间最短与距离最短的区别\n容量路径取瓶颈值\n把带权图当作无权图处理',
     E'边权语义\nedge weight semantics\nweighted graph modeling',
     'DS.GRAPH.MODEL.有向无向'),
    ('DS.LINEAR.LIST.指针_下标模拟',
     '数组模拟链表时，下标承担指针角色，next/prev 数组保存的是另一个节点下标而不是节点值；需要约定空指针哨兵、当前可用下标和删除后的链接处理，避免把编号、值和下标混淆。',
     E'能解释每个数组位置和 next/prev 值的语义。\n能用下标轨迹完成插入、删除和遍历，并识别空指针哨兵。',
     E'静态链表数组实现\n用 -1 表示空后继\n把节点值误当作 next 下标',
     E'静态链表\n数组模拟链表\nindex-based linked list',
     'DS.LINEAR.LIST.前驱后继'),
    ('DS.LINEAR.LIST.边界节点',
     '链表边界节点包括头、尾以及可选的哨兵节点；它们没有普通的前驱或后继，使用虚拟头尾可以统一操作，但必须明确哨兵不属于真实数据，空链和单节点链仍需满足边界不变量。',
     E'能区分真实节点与哨兵节点。\n能写出空链、单节点和多节点时头尾链接必须满足的条件。',
     E'虚拟头节点简化删除\n删除唯一节点后恢复空链\n把哨兵计入答案',
     E'哨兵节点\nsentinel node\nboundary node',
     'DS.LINEAR.LIST.前驱后继'),
    ('DS.LINEAR.LIST.头尾节点',
     '头节点是遍历入口，尾节点是最后一个真实节点；插入或删除改变首尾时必须同时更新 head、tail 和相邻链接，空链应有统一表示，单节点链中 head 与 tail 指向同一节点。',
     E'能列出空链、单节点和多节点的 head/tail 不变量。\n能在头插、尾插、删头、删尾后同步更新首尾引用。',
     E'队列式链表尾插头删\n删除最后一个节点\n尾指针仍指向已删除节点',
     E'链表首尾\nhead and tail pointers\nfirst and last node',
     'DS.LINEAR.LIST.边界节点'),
    ('DS.LINEAR.QUEUE.先进先出',
     '队列遵循先进先出：元素从队尾加入、从队头取出，队头始终是等待最久的有效元素。它适合按到达顺序或层次推进，不等同于按键值最优弹出的优先队列。',
     E'能用入队序列预测完整出队序列。\n能区分普通队列、栈和优先队列的取出规则。',
     E'BFS 按层扩展\n任务按到达顺序处理\n误用栈导致遍历顺序改变',
     E'FIFO\nfirst in first out\nqueue order', NULL),
    ('DS.LINEAR.QUEUE.循环队列',
     '循环队列用取模让头尾下标在固定数组中回绕；必须用 size、额外空位或其他约定区分 head==tail 时的空与满，并保证入队、出队后下标和元素数量同步。',
     E'能画出 head、tail、size 在回绕前后的变化。\n能用容量 1、刚好装满和反复出入队验证空满条件。',
     E'固定容量缓冲区\n尾下标回绕到 0\nhead==tail 时混淆空队列和满队列',
     E'环形队列\ncircular queue\nring buffer',
     'DS.LINEAR.QUEUE.先进先出'),
    ('DS.SET_MAP.MAP.键不存在处理',
     '访问 map 中不存在的键时，不同 API 可能返回失败标记、默认值、抛出异常或直接插入默认条目；代码必须区分“键不存在”和“键存在但值恰好为 0”，并避免只为查询而改变容器。',
     E'能说明所用语言查询 API 在缺键时的行为。\n能选择 contains/find/get 等方式区分不存在、默认值和真实零值。',
     E'查询未出现单词的次数\n字典下标访问意外插入键\n把值为 0 误判为键不存在',
     E'缺失键处理\nmissing key handling\nmap lookup default',
     'DS.SET_MAP.MAP.键值关系')
) AS curated(code, description, learning_objectives, typical_problems, aliases, prerequisites)
WHERE n.code = curated.code
  AND n.enabled = true
  AND n.type = 'KNOWLEDGE_POINT';

CREATE TEMP TABLE discipline_quality_v3_improvements (
    code character varying(100) PRIMARY KEY,
    category character varying(80) NOT NULL,
    name character varying(120) NOT NULL,
    description character varying(800) NOT NULL,
    skill_unit_code character varying(160) NOT NULL,
    primary_knowledge_node_code character varying(160) NOT NULL,
    knowledge_node_codes character varying(2400) NOT NULL,
    related_mistake_codes character varying(1600) NOT NULL,
    improvement_goal character varying(1200) NOT NULL,
    practice_strategy character varying(1200) NOT NULL,
    student_benefit character varying(800) NOT NULL,
    teacher_explanation character varying(1200) NOT NULL,
    teaching_action character varying(120) NOT NULL,
    applicable_languages character varying(800) NOT NULL
) ON COMMIT DROP;

INSERT INTO discipline_quality_v3_improvements (
    code, category, name, description, skill_unit_code,
    primary_knowledge_node_code, knowledge_node_codes, related_mistake_codes,
    improvement_goal, practice_strategy, student_benefit, teacher_explanation,
    teaching_action, applicable_languages
) VALUES
    ('IP_DQ3_UNION_FIND_ROOT_TRACE',
     '提升点/并查集', '画代表元轨迹验证合并',
     '适用于会写 parent 数组，但查询时直接比较父节点、合并方向和有向关系语义仍会混淆的学生。',
     'SK_UNION_FIND_COMPONENT', 'ALGO.GRAPH.CONNECT.并查集',
     E'ALGO.GRAPH.CONNECT.并查集\nALGO.GRAPH.CONNECT.连通块\nDS.GRAPH.MODEL.有向无向',
     E'MP_UNION_FIND_PARENT_WITHOUT_FIND\nMP_UNION_FIND_REVERSES_DIRECTED_MEANING',
     '让每次连通查询都基于代表元，并明确并查集只表达等价连通关系，不能替代有向依赖。',
     '用 6 个节点依次执行 4 次 union 和 3 次查询，逐步填写“操作前 parent、find 后根、合并后 parent、连通块数”表；再构造 A 指向 B 但 B 不指向 A 的关系，说明为什么不能用普通并查集表达。',
     '能区分直接父节点与集合代表元，避免把有向关系错误压成无向连通。',
     '随机指定两个节点，要求学生先画 find 路径再回答连通；随后给出有向依赖，检查其能否拒绝使用并查集并说明原因。',
     '填写代表元轨迹并验证关系类型', E'PYTHON\nCPP17'),
    ('IP_DQ3_DP_STATE_CONTRACT_TABLE',
     '提升点/DP 状态', '用状态合同推导 DP 转移',
     '适用于能写出类似转移式，却说不清 dp 每个维度、初值、非法状态和答案位置的学生。',
     'SK_DP_STATE_MEANING', 'ALGO.DP.CLASSIC.区间_DP_入门',
     E'ALGO.DP.STATE.状态含义\nALGO.DP.STATE.维度选择\nALGO.DP.TRANSITION.枚举决策\nALGO.DP.CLASSIC.区间_DP_入门',
     E'MP_DP_INIT_UNREACHABLE_AS_ZERO\nMP_DP_ROLLING_ARRAY_WRONG_ORDER\nMP_DP_STATE_MISSING_DIMENSION',
     '让状态定义、合法范围、初值、转移来源、遍历顺序和答案位置形成一份可检查合同。',
     '为一个序列 DP 和一个区间 DP 填写六列表：“状态一句话、维度范围、不可达表示、初值、依赖状态、答案位置”；用长度 1、2、3 手算表格，再删除一个维度构造两个未来不同却被合并的反例。',
     '能从状态含义推导公式和顺序，而不是先套数组再解释。',
     '只展示状态表中的三个单元格，要求学生指出每格对应的对象和所有转移来源；任何公式若无法回译为状态语义则不算通过。',
     '填写 DP 状态合同并手算小规模表', E'PYTHON\nCPP17'),
    ('IP_DQ3_SHORTEST_PATH_RELAXATION_TRACE',
     '提升点/最短路', '手算距离松弛与队列轨迹',
     '适用于能调用 BFS 或 Dijkstra 模板，但距离初值、算法前提、松弛参数和陈旧堆状态仍会出错的学生。',
     'SK_SHORTEST_DISTANCE_RELAX', 'ALGO.GRAPH.SHORTEST.Dijkstra',
     E'ALGO.GRAPH.SHORTEST.Dijkstra\nALGO.GRAPH.SHORTEST.距离初始化\nALGO.GRAPH.SHORTEST.松弛操作\nDS.GRAPH.MODEL.权值含义',
     E'MP_SHORTEST_DIST_INITIALIZED_AS_ZERO\nMP_SHORTEST_WEIGHTED_GRAPH_USES_BFS\nMP_最短路_周期等待_等待时间计算_参数误用',
     '把边权前提、dist 含义、候选距离计算和队列状态变成可逐步验证的最短路合同。',
     '对同一张 5 点图分别设置全 1 边权、非负不同边权和一条负权边；填写“弹出状态、当前 dist、边权、候选距离、是否松弛、是否陈旧”轨迹表，并选择 BFS、Dijkstra 或拒绝两者。',
     '能根据图模型选择算法，并定位距离错误究竟来自初始化、松弛公式还是状态过滤。',
     '要求学生解释每次未松弛的原因，且必须主动指出负权场景不满足 Dijkstra 前提；只报最终距离不算掌握。',
     '手算最短路轨迹并核对算法前提', E'PYTHON\nCPP17'),
    ('IP_DQ3_BINARY_INVARIANT_BOUNDARY_TABLE',
     '提升点/二分', '填写二分不变量与返回表',
     '适用于背过二分模板，但 check 方向、循环停滞、lower/upper bound 和最终返回变量经常混用的学生。',
     'SK_V6_BINARY_BOUND_RETURN_CONTRACT', 'ALGO.BINARY.INDEX.边界返回',
     E'ALGO.BINARY.INDEX.闭区间模板\nALGO.BINARY.INDEX.边界返回\nALGO.BINARY.ANSWER.左右边界\nALGO.BINARY.ANSWER.check_函数',
     E'MP_V6_BINARY_CHECK_DIRECTION_REVERSED\nMP_V6_BINARY_LOOP_STALLS_ON_MID\nMP_V6_BINARY_LOWER_UPPER_BOUND_MIXED',
     '让搜索目标、不变量、mid 归属、区间收缩和循环结束后的返回含义完全一致。',
     '分别为“第一个 >= x”和“最后一个 <= x”填写“目标、区间语义、真值方向、mid 满足后移动哪侧、停止条件、返回变量”六列表；用空数组、单元素、全小、全大和重复值逐轮记录 left/mid/right。',
     '能从问题定义推导二分代码，减少通过改 <、<= 和返回值反复试错。',
     '随机抽一个边界样例，在每轮追问答案仍位于哪个区间；学生必须在循环结束时先口述变量含义，再给出返回值。',
     '填写二分合同并逐轮验证边界', E'PYTHON\nCPP17'),
    ('IP_DQ3_DP_TRAVERSAL_DEPENDENCY_GRAPH',
     '提升点/DP 顺序', '画 DP 依赖图选择遍历顺序',
     '适用于能识别背包或区间 DP，却会让当前轮新值错误参与、阻断重复选择或在子区间未完成前计算大区间的学生。',
     'SK_V6_DP_CLASSIC_TRANSITION_ORDER', 'ALGO.DP.TRANSITION.枚举决策',
     E'ALGO.DP.TRANSITION.枚举决策\nALGO.DP.CLASSIC.区间_DP_入门\nALGO.DP.STATE.维度选择\nALGO.DP.STATE.状态压缩直觉',
     E'MP_V6_DP_01_KNAPSACK_FORWARD_REUSES_ITEM\nMP_V6_DP_COMPLETE_KNAPSACK_REVERSE_BLOCKS_REUSE\nMP_V6_DP_INTERVAL_LENGTH_ORDER_WRONG',
     '根据状态依赖判断正序、逆序、分层或按区间长度遍历，而不是记忆孤立模板。',
     '给 01 背包、完全背包和区间 DP 各画三个状态的依赖箭头；分别用正序与逆序手算一轮，圈出哪种顺序读取了本轮新值，再为区间 DP 标注长度 1 到 3 的计算先后。',
     '能解释遍历顺序如何保护旧层或允许本层复用，并迁移到陌生 DP。',
     '让学生只看依赖箭头选择循环方向并说明反方向会重复还是漏用；区间 DP 必须指出每个子区间何时已经可用。',
     '绘制依赖图并验证 DP 遍历方向', E'PYTHON\nCPP17'),
    ('IP_DQ3_GRAPH_PRECONDITION_MATRIX',
     '提升点/图算法', '建立图算法前提矩阵',
     '适用于看到图就套 BFS、Dijkstra 或最小生成树，却没有先检查方向、边权、连通性和访问状态契约的学生。',
     'SK_V6_GRAPH_ALGORITHM_PRECONDITIONS', 'ALGO.GRAPH.SHORTEST.Dijkstra',
     E'DS.GRAPH.MODEL.有向无向\nDS.GRAPH.MODEL.权值含义\nALGO.GRAPH.SHORTEST.Dijkstra\nALGO.GRAPH.TOPO.依赖关系',
     E'MP_V6_BFS_MARKS_VISITED_AFTER_POP_DUPLICATES\nMP_V6_DIJKSTRA_NEGATIVE_EDGE_USED\nMP_V6_MST_DOES_NOT_VERIFY_CONNECTED',
     '在选算法前完成方向、边权、目标、连通性、状态标记和失败条件检查。',
     '为六个小图填写“有向性、边权类型、目标、是否要求覆盖所有点、visited 时机、不可用算法”矩阵；其中加入负权图、非连通图和多条重复入队路径，再手算一个算法的关键状态。',
     '减少算法名称匹配题面表象的误用，能从图模型和前提推导算法。',
     '给出新图时，学生必须先完成矩阵再写算法名；教师随机改变一条边的方向或权值，检查其是否重新评估前提。',
     '填写图算法前提矩阵并做变式检查', E'PYTHON\nCPP17'),
    ('IP_DQ3_GREEDY_ENUM_COUNTEREXAMPLE_LOG',
     '提升点/贪心枚举', '维护反例与剪枝安全日志',
     '适用于能写排序或剪枝，却不能证明贪心选择可靠、枚举范围完整和被剪分支确实不可能产生答案的学生。',
     'SK_V6_GREEDY_ENUM_PROOF_AND_PRUNE', 'ALGO.GREEDY.CHOICE.反例检查',
     E'ALGO.GREEDY.CHOICE.反例检查\nALGO.GREEDY.INTERVAL.边界重叠\nALGO.DP.TRANSITION.枚举决策\nALGO.GREEDY.INTERVAL.区间合并',
     E'MP_V6_ENUM_OBJECT_RANGE_MISSING_CASE\nMP_V6_GREEDY_INTERVAL_SORTS_BY_LEFT_ENDPOINT\nMP_V6_PRUNE_CONDITION_REMOVES_VALID_BRANCH',
     '让每个贪心依据接受最小反例挑战，让每条剪枝条件有覆盖范围和安全理由。',
     '选择一个区间问题，枚举 n<=7 的全部小输入，与贪心结果对照并记录最小失败样例；再为两条剪枝写“被删除分支、下界或上界、为何不可能更优”，故意放宽和收紧一次观察漏解。',
     '能区分经过验证的局部选择与只在样例上成立的猜测，并保护枚举完整性。',
     '要求学生展示一个未找到反例的搜索范围和一条剪枝的数学依据；只说“这样更快”或“样例能过”不算通过。',
     '生成小规模对拍并记录剪枝依据', E'PYTHON\nCPP17'),
    ('IP_DQ3_PREFIX_DIFF_REGION_DRAWING',
     '提升点/前缀差分', '用区域图推导前缀差分公式',
     '适用于会背一维前缀、差分和二维容斥公式，但下标补零、右端加一和加减符号经常错位的学生。',
     'SK_V6_PREFIX_DIFF_BOUNDARY_FORMULA', 'ALGO.PREFIX.SUM.下标偏移',
     E'ALGO.PREFIX.SUM.前缀定义\nALGO.PREFIX.SUM.下标偏移\nALGO.PREFIX.DIFF.区间加\nALGO.PREFIX.MATRIX.边界补零',
     E'MP_V6_DIFF_RESTORE_START_INDEX_WRONG\nMP_V6_DIFF_RIGHT_PLUS_ONE_MISSING\nMP_V6_PREFIX_MATRIX_INCLUSION_SIGN_WRONG',
     '让每个公式的下标和正负号都能指回一个端点事件或几何区域。',
     '在长度 5 的数组上画 [l,r] 区间事件，标出 l 加、r+1 减及恢复起点；再在 3×3 网格上给目标矩形着色，依次减上方、减左方、补回重复区域，最后用单点和整表查询验证。',
     '能从定义重建公式，即使下标体系或维度变化也不依赖死记。',
     '教师随机改变 0/1 基、闭/半开区间或矩形边界，要求学生重新画图并推导，不允许直接套原公式。',
     '画端点与区域图再推导公式', E'PYTHON\nCPP17'),
    ('IP_DQ3_SEARCH_STATE_LIFECYCLE_TRACE',
     '提升点/搜索', '追踪搜索状态的生成与恢复',
     '适用于搜索框架基本完整，但候选列表跨分支污染、目标判断太晚或非法状态进入后才过滤的学生。',
     'SK_V6_SEARCH_RECURSION_STATE_SPACE', 'ALGO.SEARCH.STATE.状态编码',
     E'ALGO.SEARCH.STATE.状态编码\nALGO.SEARCH.STATE.判重\nALGO.SEARCH.DFS.递归参数\nBASIC.RECURSION.STATE.回溯恢复',
     E'MP_V6_DFS_CHOICE_LIST_MUTATED_ACROSS_BRANCHES\nMP_V6_SEARCH_GOAL_CHECK_AFTER_EXPANSION\nMP_V6_SEARCH_INVALID_STATE_FILTER_TOO_LATE',
     '把状态编码、候选生成、合法性、目标判断、标记和恢复放到正确生命周期。',
     '对深度 3 的搜索树给每个节点填写“进入状态、合法性、是否目标、候选、选择修改、子调用、恢复后状态”；故意提前或延后一个检查，比较扩展节点数和遗漏结果。',
     '减少跨分支状态污染和无效扩展，能解释搜索顺序而非只模仿模板。',
     '随机暂停在一个递归层，要求学生说出共享状态进入前和返回后必须相同的字段，并指出非法状态最早可以在哪一步拒绝。',
     '填写搜索生命周期表并核对恢复', E'PYTHON\nCPP17'),
    ('IP_DQ3_SORT_INTERVAL_COMPARATOR_AUDIT',
     '提升点/排序区间', '审计比较器与区间扫描合同',
     '适用于排序后分组、合并或选择区间时，漏掉最后一组、接触边界处理错误或比较器不满足严格顺序的学生。',
     'SK_V6_SORT_INTERVAL_CONTRACT', 'ALGO.SORT.BASIC.自定义比较',
     E'ALGO.SORT.BASIC.自定义比较\nALGO.GREEDY.INTERVAL.区间合并\nALGO.GREEDY.INTERVAL.边界重叠\nALGO.GREEDY.INTERVAL.不相交选择',
     E'MP_V6_GROUP_AFTER_SORT_FORGETS_LAST_GROUP\nMP_V6_INTERVAL_TOUCHING_BOUNDARY_MERGED_WRONG\nMP_V6_SORT_COMPARATOR_NOT_STRICT_WEAK_ORDER',
     '让比较器、并列规则、区间端点语义和扫描结算时机形成统一合同。',
     '用包含相等主键、相等区间端点和最后一组的 8 条记录，填写“两元素比较结果、排序后顺序、当前组或区间、何时结算”表；检查 cmp(a,a) 为 false，并分别测试闭区间与半开区间。',
     '能稳定处理排序并列和扫描边界，避免算法逻辑正确却被比较器或最后结算破坏。',
     '要求学生给任意三元素说明比较关系是否自洽，再用端点相等的两个区间口述合并规则；最后检查循环结束后的显式结算。',
     '填写比较与扫描合同并测试边界', E'PYTHON\nCPP17'),
    ('IP_DQ3_DATA_STRUCTURE_OPERATION_REPLAY',
     '提升点/数据结构', '按操作语义回放容器状态',
     '适用于知道栈、队列、堆、set 和 map 名称，却会混淆入出顺序、优先级方向或遍历中删除规则的学生。',
     'SK_V6_DATA_STRUCTURE_OPERATION_CONTRACT', 'DS.LINEAR.QUEUE.先进先出',
     E'DS.LINEAR.QUEUE.先进先出\nDS.LINEAR.QUEUE.循环队列\nDS.SET_MAP.MAP.频次统计\nALGO.GREEDY.STRUCTURE.优先队列辅助',
     E'MP_V6_HEAP_PRIORITY_DIRECTION_REVERSED\nMP_V6_SET_MAP_ERASE_WHILE_ITERATING\nMP_V6_STACK_QUEUE_ORDER_CONFUSED',
     '根据题目动作选择容器，并让每次 push、pop、top、erase 和查找的结果可预测。',
     '把同一组 8 个操作分别放入栈、队列、最小堆和最大堆，逐步记录容器内容与下一次取出值；再对 set/map 遍历删除设计安全版本，比较直接 erase 当前迭代器的风险。',
     '能从操作语义而非容器名字选择结构，并提前发现顺序和失效迭代器问题。',
     '教师隐藏容器名只给操作要求，要求学生选择结构并完整回放；堆场景必须明确比较键和最先弹出的元素。',
     '回放容器操作并核对取出契约', E'PYTHON\nCPP17'),
    ('IP_DQ3_MAP_KEY_VALUE_INVARIANT_TABLE',
     '提升点/映射计数', '建立 map 键值与贡献不变量',
     '适用于能使用 map，却会漏记首次出现、缺少关键状态维度或在需要重复次数时误用 set 的学生。',
     'SK_V7_MAP_FREQUENCY_KEY_CONTRACT', 'DS.SET_MAP.MAP.频次统计',
     E'DS.SET_MAP.MAP.键值关系\nDS.SET_MAP.MAP.频次统计\nDS.SET_MAP.MAP.键不存在处理\nDS.SET_MAP.SET.成员判断',
     E'MP_V7_MAP_DEFAULT_VALUE_DROPS_FIRST_OCCURRENCE\nMP_V7_MAP_KEY_MISSING_STATE_DIMENSION\nMP_V7_SET_USED_WHEN_DUPLICATE_COUNT_MATTERS',
     '让 key 的完整状态、value 的业务含义、默认值和每次重复贡献保持一致。',
     '为频次、最后位置和二维状态计数各写一张“key 字段、value 含义、缺键默认值、首次更新、重复更新、总量校验”表；用 A,A,B 和两个同位置不同状态的输入，比较 map 与 set 的结果。',
     '能区分存在性与次数，避免缺维 key 合并不同状态和首次贡献丢失。',
     '随机给出一条输入，要求学生预测更新前后 key 是否存在、value 变化和总频次；若只会写 map[x]++ 而说不出表头则不算掌握。',
     '填写键值不变量表并验证重复贡献', E'PYTHON\nCPP17');

INSERT INTO public.ai_standard_improvement_points (
    applicable_languages, category, code, created_at, description, enabled,
    improvement_goal, knowledge_node_codes, library_version, name,
    practice_strategy, primary_knowledge_node_code, related_mistake_codes,
    skill_unit_code, student_benefit, teacher_explanation, updated_at
)
SELECT v.applicable_languages, v.category, v.code, CURRENT_TIMESTAMP, v.description, true,
       v.improvement_goal, v.knowledge_node_codes, 'informatics-discipline-quality-v3', v.name,
       v.practice_strategy, v.primary_knowledge_node_code, v.related_mistake_codes,
       v.skill_unit_code, v.student_benefit, v.teacher_explanation, CURRENT_TIMESTAMP
FROM discipline_quality_v3_improvements v
JOIN public.ai_standard_skill_units s
  ON s.code = v.skill_unit_code
 AND s.enabled = true
 AND s.code NOT LIKE 'SK_COMPAT_%'
 AND s.description NOT LIKE '%用于兼容旧 AI 标准库标签%'
JOIN public.informatics_knowledge_nodes n
  ON n.code = v.primary_knowledge_node_code AND n.enabled = true AND n.type = 'KNOWLEDGE_POINT'
WHERE NOT EXISTS (
    SELECT 1
    FROM regexp_split_to_table(v.related_mistake_codes, E'\n') ref
    LEFT JOIN public.ai_standard_mistake_points m
      ON m.code = btrim(ref) AND m.enabled = true AND m.skill_unit_code = v.skill_unit_code
    WHERE btrim(ref) <> '' AND m.code IS NULL
)
ON CONFLICT (code) DO UPDATE SET
    applicable_languages = EXCLUDED.applicable_languages,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    enabled = EXCLUDED.enabled,
    improvement_goal = EXCLUDED.improvement_goal,
    knowledge_node_codes = EXCLUDED.knowledge_node_codes,
    library_version = EXCLUDED.library_version,
    name = EXCLUDED.name,
    practice_strategy = EXCLUDED.practice_strategy,
    primary_knowledge_node_code = EXCLUDED.primary_knowledge_node_code,
    related_mistake_codes = EXCLUDED.related_mistake_codes,
    skill_unit_code = EXCLUDED.skill_unit_code,
    student_benefit = EXCLUDED.student_benefit,
    teacher_explanation = EXCLUDED.teacher_explanation,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_standard_library_items (
    ability_point, applicable_languages, category, code, created_at, description,
    enabled, knowledge_node_codes, layer, library_version, name, related_items,
    severity, skill_unit_code, student_benefit, teacher_explanation, teaching_action,
    updated_at, when_to_use, primary_knowledge_node_code, related_knowledge_node_codes
)
SELECT v.name, v.applicable_languages, v.category, v.code, CURRENT_TIMESTAMP, v.description,
       true, v.knowledge_node_codes, 'IMPROVEMENT_POINT', 'informatics-discipline-quality-v3',
       v.name, v.related_mistake_codes, 'MEDIUM', v.skill_unit_code, v.student_benefit,
       v.teacher_explanation, v.teaching_action, CURRENT_TIMESTAMP, v.description,
       v.primary_knowledge_node_code, v.knowledge_node_codes
FROM discipline_quality_v3_improvements v
JOIN public.ai_standard_improvement_points i
  ON i.code = v.code AND i.enabled = true
ON CONFLICT (layer, code) DO UPDATE SET
    ability_point = EXCLUDED.ability_point,
    applicable_languages = EXCLUDED.applicable_languages,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    enabled = EXCLUDED.enabled,
    knowledge_node_codes = EXCLUDED.knowledge_node_codes,
    library_version = EXCLUDED.library_version,
    name = EXCLUDED.name,
    related_items = EXCLUDED.related_items,
    severity = EXCLUDED.severity,
    skill_unit_code = EXCLUDED.skill_unit_code,
    student_benefit = EXCLUDED.student_benefit,
    teacher_explanation = EXCLUDED.teacher_explanation,
    teaching_action = EXCLUDED.teaching_action,
    updated_at = CURRENT_TIMESTAMP,
    when_to_use = EXCLUDED.when_to_use,
    primary_knowledge_node_code = EXCLUDED.primary_knowledge_node_code,
    related_knowledge_node_codes = EXCLUDED.related_knowledge_node_codes;

INSERT INTO public.ai_standard_library_legacy_mappings (
    confidence, created_at, legacy_code, legacy_layer, migration_status,
    source_version, target_code, target_type, updated_at
)
SELECT 1.0, CURRENT_TIMESTAMP, v.code, 'IMPROVEMENT_POINT', 'MAPPED',
       'informatics-discipline-quality-v3', v.code, 'IMPROVEMENT_POINT', CURRENT_TIMESTAMP
FROM discipline_quality_v3_improvements v
JOIN public.ai_standard_improvement_points i
  ON i.code = v.code AND i.enabled = true
ON CONFLICT (legacy_layer, legacy_code) DO UPDATE SET
    confidence = EXCLUDED.confidence,
    migration_status = EXCLUDED.migration_status,
    source_version = EXCLUDED.source_version,
    target_code = EXCLUDED.target_code,
    target_type = EXCLUDED.target_type,
    updated_at = CURRENT_TIMESTAMP;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.informatics_knowledge_nodes)
       AND (SELECT count(*) FROM public.informatics_knowledge_nodes
            WHERE enabled = true AND type = 'KNOWLEDGE_POINT'
              AND library_version = 'informatics-knowledge-discipline-v3'
              AND description NOT LIKE '细颗粒知识点：%') <> 30 THEN
        RAISE EXCEPTION 'V4 expected exactly 30 curated knowledge points';
    END IF;

    IF EXISTS (SELECT 1 FROM public.ai_standard_skill_units)
       AND (SELECT count(*) FROM public.ai_standard_improvement_points
            WHERE enabled = true AND library_version = 'informatics-discipline-quality-v3') <> 12 THEN
        RAISE EXCEPTION 'V4 expected exactly 12 normalized improvement points';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.ai_standard_improvement_points i
        JOIN public.ai_standard_skill_units s ON s.code = i.skill_unit_code
        WHERE i.enabled = true
          AND i.library_version = 'informatics-discipline-quality-v3'
          AND (s.code LIKE 'SK_COMPAT_%' OR s.description LIKE '%用于兼容旧 AI 标准库标签%')
    ) THEN
        RAISE EXCEPTION 'V4 improvement points must not target compatibility skills';
    END IF;
END $$;
