-- 学科质量第五批：在统一“知识点 -> 能力点 -> 易错点 / 提升点”结构下，
-- 新增可被教师导航和 AI 建议真实读取的课堂—竞赛应用场景层。
-- 内容依据高中信息技术课程标准、CCF NOI 2025 大纲、官方 CSP-J/S 题目知识构成分析，
-- 以及生产 V6 的 17 个正式无提升路径能力缺口进行人工审校。

CREATE TABLE IF NOT EXISTS public.ai_standard_application_scenarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(160) NOT NULL,
    transfer_pair_code character varying(120) NOT NULL,
    context_type character varying(24) NOT NULL,
    learning_phase character varying(40) NOT NULL,
    title character varying(160) NOT NULL,
    knowledge_point_code character varying(160) NOT NULL,
    skill_unit_code character varying(160) NOT NULL,
    linked_mistake_codes character varying(2400),
    linked_improvement_codes character varying(2400),
    task_context character varying(2400) NOT NULL,
    student_task character varying(2000) NOT NULL,
    observable_evidence character varying(2000) NOT NULL,
    common_failure character varying(2000) NOT NULL,
    teacher_move character varying(2000) NOT NULL,
    student_check character varying(1600) NOT NULL,
    constraint_profile character varying(1600) NOT NULL,
    success_criteria character varying(2000) NOT NULL,
    transfer_note character varying(1600) NOT NULL,
    difficulty_level character varying(24) NOT NULL,
    applicable_languages character varying(800),
    source_framework character varying(80) NOT NULL,
    source_reference character varying(1000) NOT NULL,
    review_status character varying(40) NOT NULL,
    sort_order integer NOT NULL,
    enabled boolean NOT NULL,
    library_version character varying(80) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_ai_standard_application_scenario_code UNIQUE (code),
    CONSTRAINT uk_ai_standard_application_scenario_pair_context
        UNIQUE (transfer_pair_code, context_type),
    CONSTRAINT ck_ai_standard_application_scenario_context
        CHECK (context_type IN ('CLASSROOM', 'CONTEST')),
    CONSTRAINT fk_ai_standard_application_scenario_knowledge
        FOREIGN KEY (knowledge_point_code) REFERENCES public.informatics_knowledge_nodes(code),
    CONSTRAINT fk_ai_standard_application_scenario_skill
        FOREIGN KEY (skill_unit_code) REFERENCES public.ai_standard_skill_units(code)
);

CREATE INDEX IF NOT EXISTS idx_ai_standard_application_scenario_knowledge
    ON public.ai_standard_application_scenarios
       (knowledge_point_code, enabled, sort_order, code);

CREATE INDEX IF NOT EXISTS idx_ai_standard_application_scenario_skill
    ON public.ai_standard_application_scenarios
       (skill_unit_code, enabled, sort_order, code);

CREATE INDEX IF NOT EXISTS idx_ai_standard_application_scenario_pair
    ON public.ai_standard_application_scenarios
       (transfer_pair_code, enabled);

DROP TABLE IF EXISTS discipline_quality_v5_improvements;
CREATE TEMP TABLE discipline_quality_v5_improvements (
    code text PRIMARY KEY,
    category text NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    skill_unit_code text NOT NULL,
    primary_knowledge_node_code text NOT NULL,
    knowledge_node_codes text NOT NULL,
    related_mistake_codes text NOT NULL,
    improvement_goal text NOT NULL,
    practice_strategy text NOT NULL,
    student_benefit text NOT NULL,
    teacher_explanation text NOT NULL,
    teaching_action text NOT NULL,
    applicable_languages text NOT NULL
);

INSERT INTO discipline_quality_v5_improvements (
    code, category, name, description, skill_unit_code,
    primary_knowledge_node_code, knowledge_node_codes, related_mistake_codes,
    improvement_goal, practice_strategy, student_benefit,
    teacher_explanation, teaching_action, applicable_languages
) VALUES
    ('IP_DQ5_BINARY_FEASIBILITY_BOUNDARY_TABLE',
     '提升点/二分答案', '用可行性边界表校验 check 单调性',
     '把候选答案、必要条件、check 结果和相邻值写成边界表，先证明真假只发生一次切换，再确定等号归属和搜索方向。',
     'SK_BINARY_ANSWER_CHECK', 'ALGO.BINARY.ANSWER.check_函数',
     'ALGO.BINARY.ANSWER.check_函数',
     E'MP_BINARY_CHECK_EQUAL_CASE_REJECTED\nMP_BINARY_LOWER_BOUND_TOO_LOOSE',
     '能从题意证明 check 的单调区间，并让答案上下界和等号语义与该证明一致。',
     '选择一个不可行值、临界值和可行值，逐项手算 check；再把上下界分别收紧到题意必需范围，记录第一次真假切换。',
     '避免只背二分框架，能在边界值、答案下界和搜索方向变化时自行验证。',
     '要求学生先口述“候选值越大，条件更容易还是更难满足”，再检查临界值两侧；无法说明单调方向时不能进入模板编码。',
     '填写临界值三列表并解释唯一真假切换', E'PYTHON\nCPP17'),

    ('IP_DQ5_BINARY_MODEL_CONTRACT_COMPARISON',
     '提升点/二分模型', '对照位置、答案与精度二分合同',
     '用同一张合同表区分搜索对象、区间含义、循环不变量、端点合法性、停止条件和返回语义，避免在三类二分之间机械搬模板。',
     'SK_V7_BINARY_TEMPLATE_PRECISION_CONTRACT', 'ALGO.BINARY.INDEX.闭区间模板',
     'ALGO.BINARY.INDEX.闭区间模板',
     E'MP_V7_BINARY_FLOAT_STOPS_BY_EQUALITY\nMP_V7_BINARY_HALF_OPEN_RIGHT_USED_AS_VALID_INDEX\nMP_V7_BINARY_MONOTONIC_DIRECTION_AFTER_SORT_MISREAD',
     '面对任意二分题先辨认模型合同，再选择与区间、精度和单调方向一致的实现。',
     '分别为位置二分、答案二分和浮点精度二分填写六项合同；交换排序方向或区间表示后，重新推导而不是复用旧判断。',
     '减少端点越界、相等停不下和单调方向反转等模板迁移错误。',
     '教师随机改变一个条件，例如升序改降序或闭区间改半开区间，要求学生指出必须同步改变的合同项。',
     '完成三类二分六项合同对照并通过条件变式', E'PYTHON\nCPP17'),

    ('IP_DQ5_DP_DEPENDENCY_GRAPH_AUDIT',
     '提升点/动态规划', '画出结构化 DP 的状态依赖图',
     '把树形、状态压缩和滚动 DP 的每个状态画成“旧状态 -> 新状态”依赖边，显式标注遍历顺序、初始化时机和可覆盖条件。',
     'SK_V7_DP_STRUCTURED_STATE_DEPENDENCY', 'ALGO.DP.CLASSIC.树形_DP_入门',
     'ALGO.DP.CLASSIC.树形_DP_入门',
     E'MP_V7_DP_BITMASK_NEXT_STATE_NOT_UPDATED\nMP_V7_DP_ROLLING_INIT_CARRIED_TO_NEXT_CASE\nMP_V7_TREE_DP_PARENT_CHILD_DIRECTION_REVERSED',
     '能用依赖图证明状态计算顺序，并判断树方向、mask 更新和滚动覆盖是否安全。',
     '对一个小树、三位 mask 和两层滚动数组分别画依赖边；逐状态标记“何时已知、何时写入、何时可丢弃”。',
     '从记忆转移式升级为检查依赖关系，遇到结构变化时仍能重建正确顺序。',
     '教师遮住代码只展示状态定义，要求学生恢复一条合法拓扑计算顺序，并指出一个不能提前覆盖的状态。',
     '依赖图覆盖全部读取边且遍历顺序无逆向引用', E'PYTHON\nCPP17'),

    ('IP_DQ5_COUNTING_DP_SEMANTIC_LEDGER',
     '提升点/计数动态规划', '建立计数 DP 语义总账',
     '同时记录状态所计对象、空方案初值、每条转移新增的方案集合、取模规范和最终答案位置，避免只核对公式形状。',
     'SK_V7_DP_COUNTING_BASE_ANSWER_CONTRACT', 'ALGO.DP.CLASSIC.计数_DP',
     'ALGO.DP.CLASSIC.计数_DP',
     E'MP_V7_DP_COUNT_ANSWER_AT_WRONG_INDEX\nMP_V7_DP_COUNT_EMPTY_SCHEME_OMITTED\nMP_V7_DP_COUNT_NEGATIVE_MOD_NOT_NORMALIZED',
     '能以方案集合解释初值、转移和答案，保证每个合法方案恰计一次。',
     '用规模 0、1、2 的实例枚举真实方案，再逐格对照 DP 表；对含减法的转移单独检查负余数规范化。',
     '减少“公式看似正确但计数对象错位”的隐蔽错误，并能用小规模枚举验证。',
     '教师追问任意一个非零格“这里具体包含哪些方案”，学生必须能列举而非只复述转移式。',
     '小规模枚举计数与每个 DP 状态逐格一致', E'PYTHON\nCPP17'),

    ('IP_DQ5_GRAPH_RELAXATION_LIFECYCLE_TRACE',
     '提升点/图算法', '追踪距离与队列状态生命周期',
     '把最短路初始化、候选松弛、堆中旧状态淘汰和拓扑并列规则放进事件轨迹，区分当前最优状态与历史候选。',
     'SK_V7_GRAPH_RELAXATION_AND_TOPO_CONTRACT', 'ALGO.GRAPH.SHORTEST.距离初始化',
     'ALGO.GRAPH.SHORTEST.距离初始化',
     E'MP_V7_DIJKSTRA_STALE_HEAP_STATE_NOT_SKIPPED\nMP_V7_SHORTEST_DISTANCE_INITIALIZED_TO_ZERO\nMP_V7_TOPO_MULTIPLE_ORDER_TIE_RULE_IGNORED',
     '能解释每次状态入队、出队、失效和更新的条件，并让初始化与题目并列规则进入同一合同。',
     '在含重复松弛和并列可选点的小图上记录“事件、旧值、候选值、是否更新、是否过期”；再切换题面并列规则复跑。',
     '能定位零初始化、陈旧堆项和顺序要求遗漏，不再把容器操作当成黑盒。',
     '教师在轨迹中插入一个陈旧堆项或并列节点，要求学生判断是否处理以及依据哪个合同。',
     '所有出队事件均能说明有效性，最终距离与手算一致', E'PYTHON\nCPP17'),

    ('IP_DQ5_TOPO_DEPENDENCY_LEDGER',
     '提升点/拓扑排序', '用依赖语句校验边方向和入度守恒',
     '把“完成 A 后才能做 B”统一翻译为 A 指向 B，并用入度变化总账检查每条边只消费一次，最后以处理节点数识别有向环。',
     'SK_TOPO_INDEGREE_PROCESS', 'ALGO.GRAPH.TOPO.入度',
     'ALGO.GRAPH.TOPO.入度',
     E'MP_TOPO_CYCLE_NOT_CHECKED\nMP_TOPO_EDGE_DIRECTION_REVERSED',
     '能从自然语言稳定建立依赖边，维护入度守恒并显式判断是否存在环。',
     '为四个依赖语句画图并列初始入度；每弹出一个点就勾销其出边，比较最终处理数与节点总数。',
     '减少边方向凭感觉和把“队列空”误当正常完成，能解释拓扑序是否存在。',
     '教师把一个语句改成逆向依赖或加入闭环，要求学生只根据入度总账指出首次异常。',
     '边方向与语句一致、每条边消费一次且环被识别', E'PYTHON\nCPP17'),

    ('IP_DQ5_GREEDY_EXCHANGE_COUNTEREXAMPLE_PROTOCOL',
     '提升点/贪心', '执行交换论证与最小反例双检',
     '先写局部选择规则，再尝试把任意最优解的首个不同选择交换成贪心选择；若无法保持可行性和目标值，则主动搜索最小反例。',
     'SK_GREEDY_EXCHANGE_REASONING', 'ALGO.GREEDY.CHOICE.排序依据',
     'ALGO.GREEDY.CHOICE.排序依据',
     E'MP_GREEDY_NO_COUNTEREXAMPLE_CHECK\nMP_GREEDY_SORT_KEY_REVERSED',
     '能为贪心排序方向给出可核验依据，并在依据不成立时及时否定策略。',
     '用三到五个元素枚举所有顺序，比较贪心结果；再写一段交换步骤，检查可行性和目标是否保持。',
     '避免样例通过就认定贪心正确，能够区分经验规则和可证明策略。',
     '教师要求学生同时提交一个交换说明和一次小规模穷举；二者任一冲突即回到建模阶段。',
     '交换说明成立且小规模枚举找不到反例', E'PYTHON\nCPP17'),

    ('IP_DQ5_PREFIX_INTERVAL_CONTRACT_TABLE',
     '提升点/前缀和', '用区间合同表统一前缀定义与查询',
     '固定原数组下标、前缀数组含义、空前缀位置、查询区间和数值上界，逐项推导左右端转换而不是背一个减法公式。',
     'SK_PREFIX_RANGE_QUERY', 'ALGO.PREFIX.SUM.前缀定义',
     'ALGO.PREFIX.SUM.前缀定义',
     E'MP_PREFIX_ACCUMULATE_INT_OVERFLOW\nMP_PREFIX_QUERY_LEFT_OFFSET_WRONG',
     '能从区间语义推导查询式并同时保证下标与累计类型安全。',
     '为长度 4 的数组同时写出 0-based 和 1-based 前缀表；检查单点、全区间、左端为首位和最大值累计。',
     '减少左端偏移和中间量溢出，迁移到二维或差分时保持同一坐标语义。',
     '教师只给一个查询区间，让学生先标出前缀表中被保留和被减去的范围，再允许写表达式。',
     '四类边界查询与朴素求和一致且累计范围可证明', E'PYTHON\nCPP17'),

    ('IP_DQ5_PREFIX_DIFF_COORDINATE_AUDIT',
     '提升点/前缀差分', '审核二维前缀与差分的坐标事件',
     '把行列方向、空前缀、矩形四角事件和恢复顺序画在同一坐标图上，每次更新都说明影响区域和抵消边界。',
     'SK_V7_PREFIX_DIFF_DIMENSION_INDEX_CONTRACT', 'ALGO.PREFIX.SUM.空前缀',
     'ALGO.PREFIX.SUM.空前缀',
     E'MP_V7_DIFF_RECTANGLE_CORNER_UPDATE_INCOMPLETE\nMP_V7_PREFIX_ARRAY_NOT_PADDED_FOR_EMPTY_PREFIX\nMP_V7_PREFIX_MATRIX_BUILD_ROW_COL_ORDER_WRONG',
     '能从几何影响区域推导四角更新和二维累计顺序，避免靠符号记忆。',
     '在 4×5 非方阵上标出一个触边矩形，逐格写朴素增量，再与四角事件恢复结果对照。',
     '能发现行列互换、漏角和空前缀缺失，迁移到更高维时有统一事件视角。',
     '教师选择贴上边、贴左边和单格矩形三个变式，要求学生解释每个角为何存在或被边界吸收。',
     '非方阵三种边界矩形的恢复结果逐格一致', E'PYTHON\nCPP17'),

    ('IP_DQ5_BFS_LAYER_START_VISITED_AUDIT',
     '提升点/图搜索', '审核 BFS 的层、起点集合和判重键',
     '分别声明距离随边数增长、所有零层起点、完整状态维度和入队即判重规则，用分层队列快照验证实现。',
     'SK_V7_GRAPH_SEARCH_LAYER_VISITED_CONTRACT', 'ALGO.SEARCH.BFS.队列层次',
     'ALGO.SEARCH.BFS.队列层次',
     E'MP_V7_BFS_DISTANCE_INCREMENTS_PER_NODE\nMP_V7_BFS_MULTI_SOURCE_ENQUEUES_ONLY_ONE_START\nMP_V7_SEARCH_VISITED_KEY_MISSING_RESOURCE_DIMENSION',
     '能在单源、多源和带资源状态的 BFS 中保持距离、初始化和判重合同一致。',
     '用两个起点和一个带资源维度的小图记录每层队列内容；比较只按位置判重与按完整状态判重的差异。',
     '减少把出队次数当距离、漏多源初始化和过度剪枝造成的不可达误判。',
     '教师要求学生在任意队列快照中指出每个状态属于哪一层、由哪个前驱进入以及判重键包含什么。',
     '同层距离一致、全部起点在零层且合法状态不被误剪', E'PYTHON\nCPP17'),

    ('IP_DQ5_SEARCH_STATE_SIGNATURE',
     '提升点/搜索状态', '设计可证明的搜索状态签名',
     '从“未来决策还依赖哪些信息”反推 visited 键，区分位置相同但资源、阶段、方向或已选集合不同的状态。',
     'SK_SEARCH_VISITED_STATE', 'ALGO.SEARCH.STATE.判重',
     'ALGO.SEARCH.STATE.判重',
     'MP_SEARCH_VISITED_DIMENSION_INCOMPLETE',
     '能证明两个状态何时可安全合并，何时必须保留为不同搜索节点。',
     '列出状态候选字段，逐个删除并构造会导致未来可达性不同的反例；只保留有区分价值的最小签名。',
     '避免 visited 过粗漏解或过细爆炸，能在正确性与状态规模之间做有证据的取舍。',
     '教师指定两个位置相同的状态，要求学生比较所有未来合法动作；未来集合不同则不得合并。',
     '状态签名既不合并未来不同状态，也不保留无效维度', E'PYTHON\nCPP17'),

    ('IP_DQ5_SIMULATION_EVENT_STATE_LEDGER',
     '提升点/模拟', '建立事件—读状态—写状态总账',
     '按事件顺序记录每一步读取的旧状态、同时写入的新状态、对象身份和终止检查时机，明确原地更新与同步更新的差异。',
     'SK_SIMULATION_STATE_SYNC', 'ALGO.SIM.STATE.状态变量选择',
     'ALGO.SIM.STATE.状态变量选择',
     E'MP_SIM_MULTI_OBJECT_STATE_DESYNC\nMP_SIM_TERMINATION_ONE_STEP_EARLY_OR_LATE\nMP_SIM_UPDATE_ORDER_USES_STALE_STATE',
     '能证明多对象状态在每个事件后保持一致，并把终止条件放在正确时间点。',
     '用三对象两轮事件填写“时间、事件、读集合、写集合、终止判断”表；交换两个事件顺序观察结果是否变化。',
     '减少状态漏更新、读新旧混杂和早停晚停，复杂模拟仍可逐步审计。',
     '教师随机抽取一个时间点，要求学生恢复全部对象状态和下一事件；无法恢复说明状态合同不完整。',
     '每步状态可唯一恢复且与朴素逐事件模拟一致', E'PYTHON\nCPP17'),

    ('IP_DQ5_SORT_TOTAL_ORDER_KEY_TABLE',
     '提升点/排序', '把题面顺序写成完整关键字表',
     '逐级列出主关键字、方向、并列关键字、稳定性需求和原始身份，验证比较关系满足严格弱序并覆盖所有并列情况。',
     'SK_SORT_COMPARATOR_CONTRACT', 'ALGO.SORT.BASIC.自定义比较',
     'ALGO.SORT.BASIC.自定义比较',
     E'MP_SORT_ORIGINAL_INDEX_LOST\nMP_SORT_TIE_BREAKER_MISSING',
     '能把自然语言排序规则转换为完整可传递的关键字合同。',
     '为五条含并列数据先手排，再写关键字元组；检查任意三项的传递性并确认输出是否需要原始下标。',
     '避免只处理第一关键字、丢身份和比较器不传递导致的隐蔽错误。',
     '教师增加一个并列规则或要求恢复原位置，学生必须指出关键字表和保存字段的同步变化。',
     '手排顺序、关键字排序和全部并列规则完全一致', E'PYTHON\nCPP17'),

    ('IP_DQ5_WINDOW_INVARIANT_LEDGER',
     '提升点/双指针', '维护窗口不变量与计数守恒表',
     '明确窗口表示的闭开区间、合法条件、扩张后必须更新的计数、收缩触发条件和每次移动后的守恒关系。',
     'SK_WINDOW_INVARIANT', 'ALGO.TWO_POINTERS.WINDOW.窗口扩张',
     'ALGO.TWO_POINTERS.WINDOW.窗口扩张',
     E'MP_WINDOW_COUNTER_NOT_SYNCED\nMP_WINDOW_SHRINK_CONDITION_TOO_LATE',
     '能在每次左右指针移动后证明窗口内容、计数和合法性一致。',
     '对含重复值的短序列记录 left、right、窗口元素、频次、合法性和当前答案；每移动一次只更新对应事件。',
     '减少指针与计数不同步、收缩过晚和答案更新时机错误。',
     '教师暂停在一次扩张之后，要求学生先判断合法性和需要收缩几次，再继续执行。',
     '每行频次总和等于窗口长度且答案只在合同允许时更新', E'PYTHON\nCPP17'),

    ('IP_DQ5_GRAPH_MODELING_DICTIONARY',
     '提升点/图建模', '建立题面关系到点边属性的建模字典',
     '先定义点代表什么、边代表什么、方向如何、边权计量什么、重复边和自环如何处理，再选择算法。',
     'SK_GRAPH_EDGE_MODELING', 'DS.GRAPH.MODEL.点的定义',
     'DS.GRAPH.MODEL.点的定义',
     E'MP_GRAPH_UNDIRECTED_EDGE_ADDED_ONCE\nMP_GRAPH_WEIGHT_MEANING_IGNORED',
     '能从题面语义构造方向和权值正确的图，并解释每条算法操作在原问题中的含义。',
     '把同一组关系分别尝试建为有向图、无向图和带权图，用可达性或路径代价反例淘汰错误模型。',
     '避免图建错后在算法细节上反复调试，能更早识别方向和权值语义。',
     '教师逐项追问“反向是否成立、权值能否相加、两条关系能否合并”，答案必须回到题面。',
     '点边字典能重建题面关系且反例排除错误方向和权值', E'PYTHON\nCPP17'),

    ('IP_DQ5_HASH_KEY_VALUE_DEFAULT_PROTOCOL',
     '提升点/映射', '校验键—值—默认值三元合同',
     '为每次 map 操作明确键的身份、值的统计含义、不存在键的默认状态和更新后的守恒量。',
     'SK_HASH_FREQUENCY_MAPPING', 'DS.SET_MAP.MAP.键值关系',
     'DS.SET_MAP.MAP.键值关系',
     E'MP_HASH_KEY_VALUE_ROLE_REVERSED\nMP_HASH_MISSING_DEFAULT_VALUE',
     '能稳定实现频次、分组和索引映射，并正确处理首次出现。',
     '对一段含重复与新键的数据流逐步记录查询前值、默认值、更新后值和全表总量；再交换键值角色验证为何不成立。',
     '减少首次访问异常、键值颠倒和累计守恒破坏，能解释 map 中每个字段。',
     '教师抽取任意一步，要求学生说出不存在键时的逻辑值以及更新后总频次为何增加一。',
     '每步默认值明确且所有值之和等于已处理元素数', E'PYTHON\nCPP17'),

    ('IP_DQ5_SET_MAP_SORT_OPERATION_MATRIX',
     '提升点/数据结构选择', '按操作与信息需求选择 set、map 或排序',
     '用“是否保留次数、是否在线更新、是否需要顺序、查询次数和复杂度”矩阵比较 set、map 与排序方案。',
     'SK_SET_MAP_OPERATION_CHOICE', 'DS.SET_MAP.SET.成员判断',
     'DS.SET_MAP.SET.成员判断',
     'MP_SET_MAP_IGNORES_DUPLICATES',
     '能根据题目真正需要的信息和操作频率选择结构，而不是只因“要查找”就使用 set。',
     '为成员判断、频次统计、离线去重和有序输出四类任务填写操作矩阵，并用同一输入比较三种结构丢失的信息。',
     '避免去重后丢频次或为了在线查询承担不必要开销，结构选择更可解释。',
     '教师改变“只问是否存在”为“问出现次数”，要求学生立即指出数据结构和状态字段变化。',
     '选择结果保留全部必需信息且复杂度满足操作上限', E'PYTHON\nCPP17');

INSERT INTO public.ai_standard_improvement_points (
    applicable_languages, category, code, created_at, description, enabled,
    improvement_goal, knowledge_node_codes, library_version, name,
    practice_strategy, primary_knowledge_node_code, related_mistake_codes,
    skill_unit_code, student_benefit, teacher_explanation, updated_at
)
SELECT v.applicable_languages, v.category, v.code, CURRENT_TIMESTAMP, v.description, true,
       v.improvement_goal, v.knowledge_node_codes, 'informatics-discipline-quality-v5', v.name,
       v.practice_strategy, v.primary_knowledge_node_code, v.related_mistake_codes,
       v.skill_unit_code, v.student_benefit, v.teacher_explanation, CURRENT_TIMESTAMP
FROM discipline_quality_v5_improvements v
JOIN public.ai_standard_skill_units s
  ON s.code = v.skill_unit_code
 AND s.enabled = true
 AND s.code NOT LIKE 'SK_COMPAT_%'
JOIN public.informatics_knowledge_nodes n
  ON n.code = v.primary_knowledge_node_code
 AND n.enabled = true
 AND n.type = 'KNOWLEDGE_POINT'
WHERE NOT EXISTS (
    SELECT 1
    FROM regexp_split_to_table(v.related_mistake_codes, E'\n') ref
    LEFT JOIN public.ai_standard_mistake_points m
      ON m.code = btrim(ref)
     AND m.enabled = true
     AND m.skill_unit_code = v.skill_unit_code
    WHERE btrim(ref) <> '' AND m.code IS NULL
)
ON CONFLICT (code) DO UPDATE SET
    applicable_languages = EXCLUDED.applicable_languages,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    enabled = EXCLUDED.enabled,
    improvement_goal = EXCLUDED.improvement_goal,
    knowledge_node_codes = EXCLUDED.knowledge_node_codes,
    library_version = EXCLUDED.library_version,
    name = EXCLUDED.name,
    practice_strategy = EXCLUDED.practice_strategy,
    primary_knowledge_node_code = EXCLUDED.primary_knowledge_node_code,
    related_mistake_codes = EXCLUDED.related_mistake_codes,
    skill_unit_code = EXCLUDED.skill_unit_code,
    student_benefit = EXCLUDED.student_benefit,
    teacher_explanation = EXCLUDED.teacher_explanation,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_standard_library_items (
    ability_point, applicable_languages, category, code, created_at, description,
    enabled, knowledge_node_codes, layer, library_version, name, related_items,
    severity, skill_unit_code, student_benefit, teacher_explanation, teaching_action,
    updated_at, when_to_use, primary_knowledge_node_code, related_knowledge_node_codes
)
SELECT v.name, v.applicable_languages, v.category, v.code, CURRENT_TIMESTAMP, v.description,
       true, v.knowledge_node_codes, 'IMPROVEMENT_POINT', 'informatics-discipline-quality-v5',
       v.name, v.related_mistake_codes, 'MEDIUM', v.skill_unit_code, v.student_benefit,
       v.teacher_explanation, v.teaching_action, CURRENT_TIMESTAMP, v.improvement_goal,
       v.primary_knowledge_node_code, v.knowledge_node_codes
FROM discipline_quality_v5_improvements v
JOIN public.ai_standard_improvement_points i
  ON i.code = v.code AND i.enabled = true
ON CONFLICT (layer, code) DO UPDATE SET
    ability_point = EXCLUDED.ability_point,
    applicable_languages = EXCLUDED.applicable_languages,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    enabled = EXCLUDED.enabled,
    knowledge_node_codes = EXCLUDED.knowledge_node_codes,
    library_version = EXCLUDED.library_version,
    name = EXCLUDED.name,
    related_items = EXCLUDED.related_items,
    severity = EXCLUDED.severity,
    skill_unit_code = EXCLUDED.skill_unit_code,
    student_benefit = EXCLUDED.student_benefit,
    teacher_explanation = EXCLUDED.teacher_explanation,
    teaching_action = EXCLUDED.teaching_action,
    updated_at = CURRENT_TIMESTAMP,
    when_to_use = EXCLUDED.when_to_use,
    primary_knowledge_node_code = EXCLUDED.primary_knowledge_node_code,
    related_knowledge_node_codes = EXCLUDED.related_knowledge_node_codes;

INSERT INTO public.ai_standard_library_legacy_mappings (
    confidence, created_at, legacy_code, legacy_layer, migration_status,
    source_version, target_code, target_type, updated_at
)
SELECT 1.0, CURRENT_TIMESTAMP, v.code, 'IMPROVEMENT_POINT', 'MAPPED',
       'informatics-discipline-quality-v5', v.code, 'IMPROVEMENT_POINT', CURRENT_TIMESTAMP
FROM discipline_quality_v5_improvements v
JOIN public.ai_standard_improvement_points i
  ON i.code = v.code AND i.enabled = true
ON CONFLICT (legacy_layer, legacy_code) DO UPDATE SET
    confidence = EXCLUDED.confidence,
    migration_status = EXCLUDED.migration_status,
    source_version = EXCLUDED.source_version,
    target_code = EXCLUDED.target_code,
    target_type = EXCLUDED.target_type,
    updated_at = CURRENT_TIMESTAMP;

DROP TABLE IF EXISTS discipline_quality_v5_scenarios;
CREATE TEMP TABLE discipline_quality_v5_scenarios (
    code text PRIMARY KEY,
    transfer_pair_code text NOT NULL,
    context_type text NOT NULL,
    learning_phase text NOT NULL,
    title text NOT NULL,
    knowledge_point_code text NOT NULL,
    skill_unit_code text NOT NULL,
    linked_mistake_codes text NOT NULL,
    linked_improvement_codes text NOT NULL,
    task_context text NOT NULL,
    student_task text NOT NULL,
    observable_evidence text NOT NULL,
    common_failure text NOT NULL,
    teacher_move text NOT NULL,
    student_check text NOT NULL,
    constraint_profile text NOT NULL,
    success_criteria text NOT NULL,
    transfer_note text NOT NULL,
    difficulty_level text NOT NULL,
    applicable_languages text NOT NULL,
    sort_order integer NOT NULL
);

INSERT INTO discipline_quality_v5_scenarios (
    code, transfer_pair_code, context_type, learning_phase, title,
    knowledge_point_code, skill_unit_code, linked_mistake_codes, linked_improvement_codes,
    task_context, student_task, observable_evidence, common_failure, teacher_move,
    student_check, constraint_profile, success_criteria, transfer_note,
    difficulty_level, applicable_languages, sort_order
) VALUES
    ('SC_DQ5_BINARY_ANSWER_CLASSROOM', 'PAIR_DQ5_BINARY_ANSWER', 'CLASSROOM',
     'GUIDED_PRACTICE', '课堂：为临界承重设计可行性表',
     'ALGO.BINARY.ANSWER.check_函数', 'SK_BINARY_ANSWER_CHECK',
     E'MP_BINARY_CHECK_EQUAL_CASE_REJECTED\nMP_BINARY_LOWER_BOUND_TOO_LOOSE',
     'IP_DQ5_BINARY_FEASIBILITY_BOUNDARY_TABLE',
     '给出若干木板长度和“每段至少达到候选长度”的生活化切分任务，只要求判断候选值是否可行，不先给二分模板。',
     '为三个连续候选值填写必要条件、可切段数、check 真值和等号归属，再写出最紧的上下界。',
     '学生能口述候选值变化时可行性如何变化，并在表中呈现唯一一次真假切换；临界值与相邻值手算一致。',
     '只套 while 模板；把“恰好满足”判成失败；上下界直接抄 0 和大常数而无法解释。',
     '追问“把候选值再增大一格，原可行方案是否仍可行”，并让学生指出临界值两侧哪一格首先改变。',
     '遮住代码，只看三行真值能否判断单调方向、等号归属和最终答案是哪一侧。',
     '15 分钟；候选范围 1～20；至少包含不可行、临界可行、临界后一值三类；评价分基本项与解释奖励项。',
     '三行边界表无矛盾，上下界都能由题意推出，check 对临界等号处理与答案语义一致。',
     '课堂先把 check 当作可证伪的数学命题；竞赛再把同一命题放入大范围搜索，模板只负责缩小范围。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_BINARY_ANSWER_CONTEST', 'PAIR_DQ5_BINARY_ANSWER', 'CONTEST',
     'PROBLEM_READING', '竞赛：从数据范围证明答案二分合同',
     'ALGO.BINARY.ANSWER.check_函数', 'SK_BINARY_ANSWER_CHECK',
     E'MP_BINARY_CHECK_EQUAL_CASE_REJECTED\nMP_BINARY_LOWER_BOUND_TOO_LOOSE',
     'IP_DQ5_BINARY_FEASIBILITY_BOUNDARY_TABLE',
     '一道“最小化最大负载”题给出 n≤2×10^5、值域≤10^9；小数据可枚举答案，大数据必须利用可行性单调性。',
     '从题面写出候选答案 x 的 check 语义、O(n) 检查过程、必要下界与充分上界，并用临界值 x-1、x、x+1 自测。',
     '学生能把数据范围与总复杂度相乘，check 真值随 x 只单向变化，边界样例覆盖等于限制和单元素输入。',
     '把“能否不超过 x”写成“是否恰好等于 x”；下界过松；二分方向与 check 真值方向相反。',
     '要求先估算枚举、二分加线性 check 的操作数量，再审查临界值；不接受只有模板没有单调性说明的提交。',
     '若所有输入值相等、答案恰等于单个最大值，check(x) 与 check(x-1) 分别应是什么。',
     'n 从 20 的部分分递增到 2×10^5；答案值域到 10^9；总操作目标约 O(n log V)；内存 O(n) 或更低。',
     '小规模与枚举答案一致；最大规模预算可通过；临界等号、最小 n 和最大值均有回归用例。',
     '竞赛场景把课堂三行真值表扩展为复杂度合同：证明单调、收紧边界、验证临界，再编码。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_BINARY_MODEL_CLASSROOM', 'PAIR_DQ5_BINARY_MODEL', 'CLASSROOM',
     'CONCEPT_DISCOVERY', '课堂：三类二分合同辨析站',
     'ALGO.BINARY.INDEX.闭区间模板', 'SK_V7_BINARY_TEMPLATE_PRECISION_CONTRACT',
     E'MP_V7_BINARY_FLOAT_STOPS_BY_EQUALITY\nMP_V7_BINARY_HALF_OPEN_RIGHT_USED_AS_VALID_INDEX\nMP_V7_BINARY_MONOTONIC_DIRECTION_AFTER_SORT_MISREAD',
     'IP_DQ5_BINARY_MODEL_CONTRACT_COMPARISON',
     '设置“有序名单找首位”“阈值是否可行”“测量值逼近”三个小站，故意让搜索对象、区间和停止条件不同。',
     '每站填写搜索对象、区间含义、合法端点、单调方向、停止条件和返回值六项合同，再交换排序方向重填一站。',
     '学生不会混用数组下标、答案值域和浮点区间；能解释半开区间右端为何不是有效元素。',
     '看见“二分”就复制同一模板；浮点等待相等；降序数据仍沿用升序判断方向。',
     '随机替换一个条件，让学生圈出六项合同中受影响的项目，并用一个长度为 1 的例子验证。',
     '当区间写成 [l,r) 时，r 能否直接访问；当精度要求 1e-6 时，什么条件代表结束。',
     '20 分钟轮转；每站 4 个数据；必须包含空结果、单元素、降序和浮点近似；不要求完整竞赛代码。',
     '三张合同表字段齐全，条件变式后同步更新，四类边界手算无越界或死循环。',
     '课堂先形成“先辨模型再选实现”的元规则，竞赛读题时据此阻止模板误迁移。',
     'FOUNDATION', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_BINARY_MODEL_CONTEST', 'PAIR_DQ5_BINARY_MODEL', 'CONTEST',
     'IMPLEMENTATION', '竞赛：模型变式下重建二分不变量',
     'ALGO.BINARY.INDEX.闭区间模板', 'SK_V7_BINARY_TEMPLATE_PRECISION_CONTRACT',
     E'MP_V7_BINARY_FLOAT_STOPS_BY_EQUALITY\nMP_V7_BINARY_HALF_OPEN_RIGHT_USED_AS_VALID_INDEX\nMP_V7_BINARY_MONOTONIC_DIRECTION_AFTER_SORT_MISREAD',
     'IP_DQ5_BINARY_MODEL_CONTRACT_COMPARISON',
     '题目包含降序数组首个满足位置、整数答案阈值和实数精度三个子任务；不同子任务提供不同部分分。',
     '先为每个子任务选模型和区间，再写循环不变量；用空答案、首尾命中、全部满足和接近精度边界的用例对拍。',
     '学生提交能根据子任务改变单调判断和终止条件；返回位置或答案的语义与题面一致。',
     '位置二分访问半开右端；降序仍按升序移动；实数二分因永不相等而超时。',
     '审查只看“不变量在初始化成立、每轮保持、结束推出答案”三步，不以模板长相判断正确。',
     '把数据从升序改为降序后，哪一个谓词保持单调，移动方向必须如何由真值重新推出。',
     '整数 n≤2×10^5、值域≤10^18；浮点误差≤1e-6；部分分分别覆盖线性扫描、整数二分和精度二分。',
     '所有边界与朴素算法一致；实数迭代次数有上界；无任何无效下标访问。',
     '竞赛不是多背模板，而是在新排序、新区间和新精度下重新证明课堂六项合同。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_DP_DEPENDENCY_CLASSROOM', 'PAIR_DQ5_DP_DEPENDENCY', 'CLASSROOM',
     'GUIDED_PRACTICE', '课堂：三种 DP 依赖图拼图',
     'ALGO.DP.CLASSIC.树形_DP_入门', 'SK_V7_DP_STRUCTURED_STATE_DEPENDENCY',
     E'MP_V7_DP_BITMASK_NEXT_STATE_NOT_UPDATED\nMP_V7_DP_ROLLING_INIT_CARRIED_TO_NEXT_CASE\nMP_V7_TREE_DP_PARENT_CHILD_DIRECTION_REVERSED',
     'IP_DQ5_DP_DEPENDENCY_GRAPH_AUDIT',
     '用五节点树、三位集合状态和两层滚动表构成三个拼图，只给状态含义和依赖卡片，不给转移代码。',
     '连接旧状态到新状态，标出父子方向、mask 新状态、每层初始化和最早可覆盖时刻。',
     '学生画出的边方向与语义一致；每个状态在使用前已计算；滚动层不会带入上一组残值。',
     '把父状态错误依赖未完成的子状态；计算出 nextMask 却仍写旧 mask；滚动数组只清一次。',
     '抽取一条依赖边追问“源状态何时稳定、目标状态何时可写、旧值何时可丢弃”。',
     '若删除某一维或提前交换滚动层，能否构造一个状态读取未完成值的最小反例。',
     '25 分钟；树 5 点、mask 3 位、两组输入；用纸面依赖图和 3×8 状态表，不要求复杂代码。',
     '所有依赖边形成合法计算顺序，三类初始化时机明确，两个最小反例能复现错误。',
     '课堂把 DP 看成依赖图；竞赛遇到树形、状压或滚动优化时仍从图重建顺序。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_DP_DEPENDENCY_CONTEST', 'PAIR_DQ5_DP_DEPENDENCY', 'CONTEST',
     'PROBLEM_READING', '竞赛：从约束选择结构化 DP 与计算顺序',
     'ALGO.DP.CLASSIC.树形_DP_入门', 'SK_V7_DP_STRUCTURED_STATE_DEPENDENCY',
     E'MP_V7_DP_BITMASK_NEXT_STATE_NOT_UPDATED\nMP_V7_DP_ROLLING_INIT_CARRIED_TO_NEXT_CASE\nMP_V7_TREE_DP_PARENT_CHILD_DIRECTION_REVERSED',
     'IP_DQ5_DP_DEPENDENCY_GRAPH_AUDIT',
     '题目按子任务给出树结构、k≤18 的集合状态和内存限制，要求判断树形 DP、状态压缩与滚动优化分别何时成立。',
     '写出状态语义、依赖方向、遍历顺序和状态规模；为滚动优化列出仍需保留的边，再与小规模暴力对拍。',
     '学生能用 n、2^k 和转移度估算复杂度，优化前后依赖集合不变，跨测试用例状态被重新初始化。',
     '先做滚动优化再确认依赖；mask 更新写回旧状态；树根化后父子方向与 DFS 返回顺序相反。',
     '要求提交一张依赖图和一张资源表；任何覆盖优化都必须指出“被覆盖值之后不会再被哪条边读取”。',
     '若把输入根节点改变或增加第二组数据，计算顺序与初始化是否仍成立。',
     'n≤2×10^5；k≤18；内存 256MB；部分分含 n≤20 暴力和链形树；正式解需通过最大状态预算。',
     '随机小例与暴力一致；最大状态数量和峰值内存可解释；换根、空集合、重复测试均通过。',
     '竞赛把课堂依赖拼图扩展到资源约束：正确依赖先成立，滚动与压缩才是合法优化。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_COUNTING_DP_CLASSROOM', 'PAIR_DQ5_COUNTING_DP', 'CLASSROOM',
     'GUIDED_PRACTICE', '课堂：用方案卡片解释计数 DP',
     'ALGO.DP.CLASSIC.计数_DP', 'SK_V7_DP_COUNTING_BASE_ANSWER_CONTRACT',
     E'MP_V7_DP_COUNT_ANSWER_AT_WRONG_INDEX\nMP_V7_DP_COUNT_EMPTY_SCHEME_OMITTED\nMP_V7_DP_COUNT_NEGATIVE_MOD_NOT_NORMALIZED',
     'IP_DQ5_COUNTING_DP_SEMANTIC_LEDGER',
     '以用若干小面额组成目标数为情境，先枚举空方案和小目标全部方案，再让 DP 表中的每个数对应一组卡片。',
     '填写状态“统计了什么”、空方案初值、转移新增集合、最终答案格和取模后的非负表示。',
     '学生能列出 dp[0] 的唯一空方案，任意小格数值都能由实际方案集合解释。',
     '把 dp[0] 设为 0；从目标旁边错误格取答案；含减法时保留负余数。',
     '任意指一个非零状态，要求学生展开所计方案；若两个转移产生同一方案，必须说明去重依据。',
     '目标为 0、只有一种面额、完全不可达时，答案格和空方案语义分别是什么。',
     '20 分钟；目标≤8；先手工枚举再填表；基本项检查计数，奖励项解释为什么没有重计。',
     '所有小规模状态与枚举集合一一对应，初值和答案位置有完整语义。',
     '课堂建立“数值背后是方案集合”的习惯，竞赛再在大状态和取模条件下保持同一语义。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_COUNTING_DP_CONTEST', 'PAIR_DQ5_COUNTING_DP', 'CONTEST',
     'IMPLEMENTATION', '竞赛：计数状态、取模和答案位置联合验收',
     'ALGO.DP.CLASSIC.计数_DP', 'SK_V7_DP_COUNTING_BASE_ANSWER_CONTRACT',
     E'MP_V7_DP_COUNT_ANSWER_AT_WRONG_INDEX\nMP_V7_DP_COUNT_EMPTY_SCHEME_OMITTED\nMP_V7_DP_COUNT_NEGATIVE_MOD_NOT_NORMALIZED',
     'IP_DQ5_COUNTING_DP_SEMANTIC_LEDGER',
     '一道方案计数题给出 n≤2×10^5 和模数，部分分允许枚举，小数据可展示真实方案，大数据依赖计数 DP。',
     '先写每一维状态对应的方案集合，再用 n≤12 枚举对拍；检查空输入、不可达、减法转移和最终聚合位置。',
     '学生能证明每个方案恰由一条转移产生，所有中间值规范到合法模区间，答案从语义正确的状态取出。',
     '只看样例数值调初值；取模减法为负；把“恰好完成”与“至多完成”答案格混淆。',
     '审查时要求展示一个方案从初始状态到答案状态的完整路径，以及一个非法方案为何不会进入。',
     '把目标改成 0 或把“恰好”改成“至多”后，初值、转移或答案聚合哪些字段必须变化。',
     'n≤2×10^5；模数≤10^9+7；部分分 n≤20 可枚举；正式总复杂度目标 O(n) 或 O(n log n)。',
     'n≤12 与枚举完全一致；模边界、空方案、不可达和最大规模均通过。',
     '竞赛验证沿用课堂方案卡片，只是用自动枚举替代手工枚举并加入规模与取模合同。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_GRAPH_RELAX_CLASSROOM', 'PAIR_DQ5_GRAPH_RELAX', 'CLASSROOM',
     'GUIDED_PRACTICE', '课堂：最短路与依赖队列事件剧场',
     'ALGO.GRAPH.SHORTEST.距离初始化', 'SK_V7_GRAPH_RELAXATION_AND_TOPO_CONTRACT',
     E'MP_V7_DIJKSTRA_STALE_HEAP_STATE_NOT_SKIPPED\nMP_V7_SHORTEST_DISTANCE_INITIALIZED_TO_ZERO\nMP_V7_TOPO_MULTIPLE_ORDER_TIE_RULE_IGNORED',
     'IP_DQ5_GRAPH_RELAXATION_LIFECYCLE_TRACE',
     '用六点带权路线和一组并列课程依赖卡片，学生扮演堆、距离表和可选队列，逐事件更新。',
     '记录每次出队值、当前最优值、是否陈旧、松弛结果；依赖卡片同时按题面并列规则选择下一项。',
     '学生能拒绝陈旧堆项，只有源点距离为 0；并列可选项按指定规则稳定输出。',
     '所有距离初始化为 0；堆中旧距离再次扩展；拓扑多解时使用任意容器顺序。',
     '在事件表中插入一条过期记录和两个并列节点，要求学生依据状态合同处理。',
     '为什么“记录来自堆”不等于“记录仍是当前最优”；题面要求最小编号时容器必须支持什么选择。',
     '25 分钟；图 6 点 8 边；至少一次重复松弛和一次并列选择；纸面轨迹不超过 15 行。',
     '事件轨迹与手算最短距离一致，陈旧记录不扩展，并列顺序满足题面。',
     '课堂把容器中的候选与正式状态分开；竞赛在大图和严格顺序下复用同一生命周期判断。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_GRAPH_RELAX_CONTEST', 'PAIR_DQ5_GRAPH_RELAX', 'CONTEST',
     'POST_SUBMISSION_REVIEW', '竞赛：用事件轨迹定位最短路与顺序失分',
     'ALGO.GRAPH.SHORTEST.距离初始化', 'SK_V7_GRAPH_RELAXATION_AND_TOPO_CONTRACT',
     E'MP_V7_DIJKSTRA_STALE_HEAP_STATE_NOT_SKIPPED\nMP_V7_SHORTEST_DISTANCE_INITIALIZED_TO_ZERO\nMP_V7_TOPO_MULTIPLE_ORDER_TIE_RULE_IGNORED',
     'IP_DQ5_GRAPH_RELAXATION_LIFECYCLE_TRACE',
     '图题 n,m≤2×10^5，既有最短距离子任务，也有要求字典序最小的依赖输出；隐藏数据包含大量重复松弛和并列选择。',
     '为一个最小失败图生成出队事件日志，标注 current distance 与 popped distance；再验证并列节点选择结构是否满足题面。',
     '学生能把 TLE 或 WA 定位到陈旧扩展、初始化或并列规则，而不是笼统归因于图算法。',
     '重复扩展使复杂度放大；不可达点因零初始化变成已到达；队列顺序在样例巧合正确。',
     '要求先构造 4 点最小反例，再对最大稠密候选流估算堆操作次数；修复后保留反例为回归。',
     '同一节点先以长距离入堆、后以短距离入堆时，旧记录出队应满足什么判断。',
     'n,m≤2×10^5；边权非负；并列规则为最小编号；部分分无重复松弛或唯一拓扑序。',
     '最小反例修复、不可达值正确、并列序正确，堆操作预算不被陈旧扩展放大。',
     '竞赛复盘把判题表象还原成课堂事件轨迹，先找第一条违反生命周期合同的事件。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_TOPO_CLASSROOM', 'PAIR_DQ5_TOPO', 'CLASSROOM',
     'CONCEPT_DISCOVERY', '课堂：用课程先修语句维护入度总账',
     'ALGO.GRAPH.TOPO.入度', 'SK_TOPO_INDEGREE_PROCESS',
     E'MP_TOPO_CYCLE_NOT_CHECKED\nMP_TOPO_EDGE_DIRECTION_REVERSED',
     'IP_DQ5_TOPO_DEPENDENCY_LEDGER',
     '把“学完 A 才能学 B”等自然语言写在卡片上，学生先画边，再按可开始课程集合推进。',
     '逐条翻译依赖边，填写初始入度；每完成一门课勾销对应出边，最后比较处理数和课程总数。',
     '边方向能回译为原句；每条边只让一个入度减一；有环时处理数不足。',
     '把“B 依赖 A”画成 B 指向 A；队列空就直接报告成功，不检查是否仍有节点。',
     '让学生对每条边读成一句话；加入 A→B→C→A 后追问哪些节点永远不会进入可开始集合。',
     '处理结束后还有节点时，怎样区分“漏加节点”和“确实有环”。',
     '15 分钟；5 门课程、6 条依赖；含一个无环版本和一个最小环变式。',
     '无环版本处理全部节点；有环版本明确报告剩余节点；入度减量总和等于边数。',
     '课堂用依赖语句固定边方向和守恒，竞赛只是在更大依赖图上自动维护同一总账。',
     'FOUNDATION', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_TOPO_CONTEST', 'PAIR_DQ5_TOPO', 'CONTEST',
     'IMPLEMENTATION', '竞赛：依赖建模、环检测与输出顺序联合检查',
     'ALGO.GRAPH.TOPO.入度', 'SK_TOPO_INDEGREE_PROCESS',
     E'MP_TOPO_CYCLE_NOT_CHECKED\nMP_TOPO_EDGE_DIRECTION_REVERSED',
     'IP_DQ5_TOPO_DEPENDENCY_LEDGER',
     '任务调度题 n,m≤2×10^5，要求若可完成则输出合法顺序，否则报告冲突；部分分保证无环。',
     '从两种相反措辞各抽一条依赖验证边方向；用 processedCount 检测环，并对输出顺序逐边验收。',
     '学生输出中每条边的起点都早于终点；有环数据不伪造完整序列；方向改变时测试能立即失败。',
     '读题措辞反向导致全图建反；只在部分分无环数据上通过；输出长度不检查。',
     '要求写一个独立验收器：检查长度、节点唯一性和每条依赖相对次序，再用于随机小图对拍。',
     '若输入说“任务 x 必须在 y 之前”与“任务 x 依赖 y”，两者边方向分别是什么。',
     'n,m≤2×10^5；部分分为 DAG；正式数据含自环、长环、多连通块和并列可选点。',
     '随机小图与枚举一致；自环和长环被识别；输出验收器检查全部边。',
     '竞赛把课堂入度总账加上自动验收器，让边方向和环检测都能被反例立即证伪。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_GREEDY_CLASSROOM', 'PAIR_DQ5_GREEDY', 'CLASSROOM',
     'CONCEPT_DISCOVERY', '课堂：活动安排的交换与反例实验',
     'ALGO.GREEDY.CHOICE.排序依据', 'SK_GREEDY_EXCHANGE_REASONING',
     E'MP_GREEDY_NO_COUNTEREXAMPLE_CHECK\nMP_GREEDY_SORT_KEY_REVERSED',
     'IP_DQ5_GREEDY_EXCHANGE_COUNTEREXAMPLE_PROTOCOL',
     '给出五个时间区间，学生提出“最早开始、最短时长、最早结束”三种局部规则并比较。',
     '枚举小规模最优解，为候选规则写一次交换说明；找出错误规则的最小反例并解释排序方向。',
     '学生能区分样例表现与一般正确性；正确规则有交换依据，错误规则有明确反例。',
     '看一组数据正确就断言贪心；排序方向写反；交换后没有检查可行性。',
     '让学生把最优解中第一个不同选择替换为贪心选择，逐项检查是否仍可行且目标不差。',
     '如果一个规则无法完成交换证明，最少需要几个区间构造反例。',
     '25 分钟；区间数 4～6；允许全排列核对；必须提交一份证明草图和一份反例。',
     '正确规则与枚举最优一致，交换步骤无可行性破坏，错误规则被最小反例否定。',
     '课堂同时训练证明和反例；竞赛面对陌生贪心时先做这两道门禁再提交。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_GREEDY_CONTEST', 'PAIR_DQ5_GREEDY', 'CONTEST',
     'PROBLEM_READING', '竞赛：从部分分枚举到可证明贪心',
     'ALGO.GREEDY.CHOICE.排序依据', 'SK_GREEDY_EXCHANGE_REASONING',
     E'MP_GREEDY_NO_COUNTEREXAMPLE_CHECK\nMP_GREEDY_SORT_KEY_REVERSED',
     'IP_DQ5_GREEDY_EXCHANGE_COUNTEREXAMPLE_PROTOCOL',
     '排序贪心题 n≤2×10^5，n≤9 的部分分可全排列，正式解需要确定关键字方向并说明局部选择。',
     '先实现小规模最优基准，随机生成 n≤9 数据比较多个排序规则；对通过的规则补交换说明。',
     '学生不依赖单一样例选择规则；候选规则经随机反例和证明双检，复杂度满足大数据。',
     '只在随机数据少时“看起来正确”；把升序降序写反；证明跳过交换后的目标变化。',
     '检查报告必须同时包含反例搜索次数、最小反例或交换式；只有 AC 样例不算依据。',
     '将两个相邻选择交换后，目标函数变化量的符号是否支持当前排序方向。',
     'n≤2×10^5；部分分 n≤9；值域到 10^9；正式复杂度 O(n log n)。',
     'n≤9 与全排列一致，边界和重复值通过，交换差值支持排序方向。',
     '竞赛用部分分作为课堂枚举实验的自动化版本，再把经验候选提升为可证明策略。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_PREFIX_RANGE_CLASSROOM', 'PAIR_DQ5_PREFIX_RANGE', 'CLASSROOM',
     'GUIDED_PRACTICE', '课堂：用每日数据解释前缀区间合同',
     'ALGO.PREFIX.SUM.前缀定义', 'SK_PREFIX_RANGE_QUERY',
     E'MP_PREFIX_ACCUMULATE_INT_OVERFLOW\nMP_PREFIX_QUERY_LEFT_OFFSET_WRONG',
     'IP_DQ5_PREFIX_INTERVAL_CONTRACT_TABLE',
     '以一周步数为数组，同时给出按天编号和按数组下标两套说法，让学生回答单日、前三日和任意连续日期总量。',
     '填写原数组下标、prefix[k] 所覆盖范围和查询区间映射；用朴素逐项相加核对四类边界。',
     '学生能画出被保留与被减去的两段，左端为首日时使用空前缀，累计上界估算正确。',
     '把 l 直接用于减法导致少减或多减；prefix 与原数组同长却访问空前缀；累计使用窄类型。',
     '不给公式，只让学生在数轴上涂色“查询段”和“要减掉的前段”，再从图写表达式。',
     '查询第一天到第一天、第一天到最后一天时，被减前段分别是什么。',
     '20 分钟；数组长度 7；同时使用 0-based 与 1-based 标注；数值含接近整型边界的变式。',
     '四类查询与朴素和一致，区间转换能口述，累计类型覆盖最大可能总和。',
     '课堂用涂色区间建立语义，竞赛在大量查询中只是复用同一合同并增加复杂度预算。',
     'FOUNDATION', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_PREFIX_RANGE_CONTEST', 'PAIR_DQ5_PREFIX_RANGE', 'CONTEST',
     'IMPLEMENTATION', '竞赛：高频区间查询的下标与数值双验收',
     'ALGO.PREFIX.SUM.前缀定义', 'SK_PREFIX_RANGE_QUERY',
     E'MP_PREFIX_ACCUMULATE_INT_OVERFLOW\nMP_PREFIX_QUERY_LEFT_OFFSET_WRONG',
     'IP_DQ5_PREFIX_INTERVAL_CONTRACT_TABLE',
     '静态数组有 q≤2×10^5 次闭区间求和，元素绝对值≤10^9；小数据允许逐次扫描。',
     '先算前缀最大绝对值选择类型，再用随机短数组把所有区间与朴素算法对拍，最后做最大规模压力测试。',
     '学生能覆盖 l=1、l=r、r=n 和负数累计；每个查询 O(1)，前缀构建 O(n)。',
     '样例小值掩盖溢出；把输入闭区间当半开区间；只测中间区间不测首尾。',
     '要求自动枚举 n≤30 的全部区间，而不是手选三组样例；首个分叉打印 l、r 和两种答案。',
     '当 n=2×10^5 且每项为 10^9 时，前缀最大量级和所需类型是什么。',
     'n,q≤2×10^5；值绝对值≤10^9；部分分 q≤1000 可扫描；正式解 O(n+q)。',
     '全区间对拍 0 分叉，最大累计不溢出，最大规模运行时间稳定。',
     '竞赛把课堂四个边界扩展为“全部小区间”自动验收，同时加入最大数值合同。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_PREFIX_DIFF_CLASSROOM', 'PAIR_DQ5_PREFIX_DIFF', 'CLASSROOM',
     'GUIDED_PRACTICE', '课堂：在非方阵热力图上画四角事件',
     'ALGO.PREFIX.SUM.空前缀', 'SK_V7_PREFIX_DIFF_DIMENSION_INDEX_CONTRACT',
     E'MP_V7_DIFF_RECTANGLE_CORNER_UPDATE_INCOMPLETE\nMP_V7_PREFIX_ARRAY_NOT_PADDED_FOR_EMPTY_PREFIX\nMP_V7_PREFIX_MATRIX_BUILD_ROW_COL_ORDER_WRONG',
     'IP_DQ5_PREFIX_DIFF_COORDINATE_AUDIT',
     '用 4×5 教室座位热力图，对三个矩形区域增加不同温度，包含贴上边、贴左边和单格区域。',
     '先逐格涂色得到朴素结果，再在带空前缀的坐标图标四角事件，按行列累计恢复并对照。',
     '学生每个角都能解释影响与抵消区域，行列不会因非方阵互换，边界事件不越界。',
     '只写左上和右下两个角；把 rows 与 cols 混用；没有额外边界导致右下事件丢失。',
     '指向任一角追问“从这里往哪个方向的影响应被开始或取消”，要求用区域而非符号口诀回答。',
     '如果矩形贴右边或下边，取消事件落在哪里；数组为什么需要多一行一列。',
     '25 分钟；4×5 非方阵；3 次更新；同时提交朴素网格、事件网格和恢复网格。',
     '三张网格逐格一致，四角事件完整，任何行列交换都会被非方阵用例发现。',
     '课堂从几何区域推出事件；竞赛面对大 q 时保留同一图像，只把朴素涂色替换为差分累计。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_PREFIX_DIFF_CONTEST', 'PAIR_DQ5_PREFIX_DIFF', 'CONTEST',
     'IMPLEMENTATION', '竞赛：二维批量更新的坐标与内存合同',
     'ALGO.PREFIX.SUM.空前缀', 'SK_V7_PREFIX_DIFF_DIMENSION_INDEX_CONTRACT',
     E'MP_V7_DIFF_RECTANGLE_CORNER_UPDATE_INCOMPLETE\nMP_V7_PREFIX_ARRAY_NOT_PADDED_FOR_EMPTY_PREFIX\nMP_V7_PREFIX_MATRIX_BUILD_ROW_COL_ORDER_WRONG',
     'IP_DQ5_PREFIX_DIFF_COORDINATE_AUDIT',
     '矩阵 n,m≤2000，有 q≤2×10^5 次矩形增量，最后输出全图；部分分 n,m≤50 可逐格更新。',
     '明确输入坐标到内部坐标的映射、四角事件和恢复顺序；用非方阵随机小例与朴素二维更新对拍并计算内存。',
     '学生能处理触边、单行、单列、单格和重叠矩形；峰值内存在限制内，恢复结果无方向错误。',
     '四角少一个导致整片泄漏；下标补零不一致；使用 n×n 假设；二维容器内存估算不足。',
     '要求对拍生成器强制 n≠m 且一半矩形贴边；首个错误输出事件网格和恢复网格。',
     '若 n=1、m=2000，四角更新与恢复循环仍分别使用哪些维度。',
     'n,m≤2000；q≤2×10^5；内存 256MB；部分分允许 O(qnm)，正式解 O(nm+q)。',
     '随机非方阵对拍通过，最大内存预算明确，所有触边变式逐格正确。',
     '竞赛用规模迫使采用课堂四角事件，但正确性的核心仍是区域影响和坐标合同。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_BFS_LAYER_CLASSROOM', 'PAIR_DQ5_BFS_LAYER', 'CLASSROOM',
     'GUIDED_PRACTICE', '课堂：多起点迷宫的分层队列快照',
     'ALGO.SEARCH.BFS.队列层次', 'SK_V7_GRAPH_SEARCH_LAYER_VISITED_CONTRACT',
     E'MP_V7_BFS_DISTANCE_INCREMENTS_PER_NODE\nMP_V7_BFS_MULTI_SOURCE_ENQUEUES_ONLY_ONE_START\nMP_V7_SEARCH_VISITED_KEY_MISSING_RESOURCE_DIMENSION',
     'IP_DQ5_BFS_LAYER_START_VISITED_AUDIT',
     '在 5×6 迷宫放置两个消防站和一张一次性通行证，状态由位置和通行证是否使用组成。',
     '把所有消防站放入第 0 层，逐层记录队列；比较只按位置判重与按“位置+通行证状态”判重的结果。',
     '同一层状态距离相同，两个起点都参与扩散；同一位置的两种资源状态在未来动作不同时均被保留。',
     '距离按出队节点个数增长；漏掉第二起点；visited 只记录坐标导致带通行证路径被剪掉。',
     '每轮封存当前层队列后再扩展，要求学生为每个新状态写前驱和完整判重键。',
     '同一格在“有通行证”和“已使用”两种状态下，未来可通过的边集合是否相同。',
     '25 分钟；5×6 网格；2 个起点；1 个资源位；队列快照最多 6 层。',
     '全部起点距离为 0，每条边使距离加 1，完整状态判重得到手算最短距离。',
     '课堂把 BFS 距离、初始化和状态身份分开；竞赛增大图和资源维度时沿用这三项合同。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_BFS_LAYER_CONTEST', 'PAIR_DQ5_BFS_LAYER', 'CONTEST',
     'PROBLEM_READING', '竞赛：多源与资源状态下的 BFS 规模审计',
     'ALGO.SEARCH.BFS.队列层次', 'SK_V7_GRAPH_SEARCH_LAYER_VISITED_CONTRACT',
     E'MP_V7_BFS_DISTANCE_INCREMENTS_PER_NODE\nMP_V7_BFS_MULTI_SOURCE_ENQUEUES_ONLY_ONE_START\nMP_V7_SEARCH_VISITED_KEY_MISSING_RESOURCE_DIMENSION',
     'IP_DQ5_BFS_LAYER_START_VISITED_AUDIT',
     '网格最短路题 n×m≤2×10^5，有多个起点和 k≤10 的资源状态；部分分只有一个起点或 k=0。',
     '定义状态键和零层起点集合，估算状态总数；用小网格枚举完整状态图对拍，并检查入队时判重。',
     '学生能解释复杂度 O(nmk) 的来源，不把不同资源状态合并，也不重复入队造成爆炸。',
     '代码在部分分单源正确，正式数据漏其他起点；visited 维度不足；出队后才判重导致队列膨胀。',
     '要求把每个部分分放宽条件映射到状态合同，指出从单源到多源、从位置到位置+资源各新增什么。',
     '如果两个状态位置相同但剩余资源不同，何时可以证明其中一个支配另一个。',
     'n×m≤2×10^5；k≤10；起点数≤n×m；内存需容纳完整状态或有证明的支配剪枝。',
     '小状态图对拍一致，所有起点入队，峰值队列和 visited 内存满足预算。',
     '竞赛通过部分分逐步揭示课堂合同的缺项：先层次，再多源，最后完整状态身份。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_SEARCH_STATE_CLASSROOM', 'PAIR_DQ5_SEARCH_STATE', 'CLASSROOM',
     'CONCEPT_DISCOVERY', '课堂：钥匙门迷宫的最小状态签名',
     'ALGO.SEARCH.STATE.判重', 'SK_SEARCH_VISITED_STATE',
     'MP_SEARCH_VISITED_DIMENSION_INCOMPLETE',
     'IP_DQ5_SEARCH_STATE_SIGNATURE',
     '一张小迷宫含钥匙和门，同一位置可能在持有不同钥匙集合时到达，后续可走路径不同。',
     '列出位置、钥匙集合、方向和步数等候选字段；逐一删除并尝试构造未来可达性改变的反例。',
     '学生保留位置和必要资源，删除不影响未来的历史字段；能证明哪些状态可安全合并。',
     'visited 只记位置漏解；把完整路径历史放进状态导致数量爆炸；无法解释字段作用。',
     '选择两条到达同一格的路径，要求只比较未来合法动作集合，而不比较已经走过的故事。',
     '若两个状态未来可走边完全相同且目标代价规则相同，它们是否需要分别保留。',
     '20 分钟；迷宫不超过 5×5；钥匙 2 把；所有可能状态可人工枚举。',
     '最小状态签名不误合并未来不同状态，状态数可由维度乘积准确估算。',
     '课堂学习从未来决策定义状态；竞赛面对新资源或阶段时用同一反例法扩展签名。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_SEARCH_STATE_CONTEST', 'PAIR_DQ5_SEARCH_STATE', 'CONTEST',
     'IMPLEMENTATION', '竞赛：判重维度与状态爆炸的双向验证',
     'ALGO.SEARCH.STATE.判重', 'SK_SEARCH_VISITED_STATE',
     'MP_SEARCH_VISITED_DIMENSION_INCOMPLETE',
     'IP_DQ5_SEARCH_STATE_SIGNATURE',
     '搜索题包含位置、阶段和有限资源，n≤10^5、资源值≤20；部分分资源固定，可只按位置判重。',
     '从未来转移写出状态签名，计算理论状态上限；为删减某一维构造反例，为新增某一维证明其必要性。',
     '学生既不会因过粗判重漏解，也不会无依据携带全历史；状态上限与内存、时间预算一致。',
     '沿用部分分 visited 到正式数据；为保险加入过多字段导致 MLE；把代价当身份造成重复状态。',
     '评审时要求一份“字段—未来影响—删除反例”表；没有反例或证明的字段不能直接进入签名。',
     '如果资源更多永远不劣，能否做支配剪枝；剪枝条件是否在所有未来转移下保持。',
     '基础位置数≤10^5；阶段≤4；资源≤20；内存 256MB；部分分固定阶段和资源。',
     '随机小状态图与完整枚举一致，状态上限可控，所有剪枝都有支配证明。',
     '竞赛把课堂最小签名加入资源预算：每一维既要有正确性证据，也要有成本说明。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_SIMULATION_CLASSROOM', 'PAIR_DQ5_SIMULATION', 'CLASSROOM',
     'GUIDED_PRACTICE', '课堂：多人传球的事件—状态总账',
     'ALGO.SIM.STATE.状态变量选择', 'SK_SIMULATION_STATE_SYNC',
     E'MP_SIM_MULTI_OBJECT_STATE_DESYNC\nMP_SIM_TERMINATION_ONE_STEP_EARLY_OR_LATE\nMP_SIM_UPDATE_ORDER_USES_STALE_STATE',
     'IP_DQ5_SIMULATION_EVENT_STATE_LEDGER',
     '三名学生按规则同时传递标记物，规则包含同轮读取旧状态、下一轮统一生效和达到条件后停止。',
     '逐轮填写事件、每人旧状态、待写新状态和终止判断；比较原地更新与双缓冲结果。',
     '学生能恢复任意轮结束状态，所有对象同步变化，终止检查发生在题意规定的时刻。',
     '先更新的人影响同轮后更新的人；漏更新某个对象；达到条件前后多执行一轮。',
     '暂停在一轮中间，追问后续对象应读取轮初还是当前状态，并要求用题面“同时”语义回答。',
     '初始即满足终止条件、最后一次事件刚好触发条件时，应执行多少轮。',
     '20 分钟；3 个对象、4～6 轮；包含同时更新和顺序更新两种对照规则。',
     '总账每一行可唯一推出下一行，原地与同步差异被明确，两个终止边界正确。',
     '课堂用事件总账固定时序；竞赛复杂模拟只是对象更多、事件更长，合同不变。',
     'FOUNDATION', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_SIMULATION_CONTEST', 'PAIR_DQ5_SIMULATION', 'CONTEST',
     'POST_SUBMISSION_REVIEW', '竞赛：长事件流中的状态同步与终止复盘',
     'ALGO.SIM.STATE.状态变量选择', 'SK_SIMULATION_STATE_SYNC',
     E'MP_SIM_MULTI_OBJECT_STATE_DESYNC\nMP_SIM_TERMINATION_ONE_STEP_EARLY_OR_LATE\nMP_SIM_UPDATE_ORDER_USES_STALE_STATE',
     'IP_DQ5_SIMULATION_EVENT_STATE_LEDGER',
     '多对象事件模拟 n,q≤2×10^5，样例短且无冲突，隐藏数据包含同时间事件、对象交叉更新和边界轮次。',
     '为最小失败输入输出事件日志，标注每次读取版本和写入版本；用随机小 q 与朴素时间线对拍。',
     '学生能定位第一条状态分叉，处理同时间事件的规则一致，终止条件与题面轮次语义相符。',
     '状态数组只更新主对象；同时间事件按输入顺序错误串行化；修复失败样例时加特判。',
     '要求先缩小到不超过 5 个事件的反例，并用总账说明根因；没有第一处分叉不允许加条件。',
     '把两个同时间事件交换输入顺序，若题面定义同时发生，最终结果是否应改变。',
     'n,q≤2×10^5；事件时间可相同；部分分事件互不影响；正式解需 O((n+q) log n) 或更优。',
     '随机对拍 0 分叉，交换同时间输入顺序满足题意不变量，最大事件流通过。',
     '竞赛复盘沿用课堂事件表，把不可见长流程缩成第一条违反读写版本合同的事件。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_SORT_CLASSROOM', 'PAIR_DQ5_SORT', 'CLASSROOM',
     'GUIDED_PRACTICE', '课堂：班级排名的完整关键字表',
     'ALGO.SORT.BASIC.自定义比较', 'SK_SORT_COMPARATOR_CONTRACT',
     E'MP_SORT_ORIGINAL_INDEX_LOST\nMP_SORT_TIE_BREAKER_MISSING',
     'IP_DQ5_SORT_TOTAL_ORDER_KEY_TABLE',
     '班级记录按总分降序、数学分降序、姓名升序排列，最终还要回到原座位发放结果。',
     '先手排含并列的五条记录，再写主关键字、方向、并列关键字、稳定性和原始位置字段。',
     '学生生成的关键字顺序与手排一致；并列规则全部覆盖；排序后仍能恢复原座位。',
     '只比较总分；并列时返回不确定结果；排序后丢失原始索引。',
     '增加一条与前两关键字相同的记录，要求学生指出最终由哪个字段决定并验证传递性。',
     '若题面删除姓名规则但要求保持原顺序，应使用什么身份信息表达稳定性需求。',
     '20 分钟；5～8 条记录；至少三组并列；同时检查排序结果和原位映射。',
     '手排、关键字排序、并列次序与原位恢复全部一致，任意三记录比较无环。',
     '课堂把自然语言排序转成总合同；竞赛面对更多字段和数据时只需扩展同一关键字表。',
     'FOUNDATION', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_SORT_CONTEST', 'PAIR_DQ5_SORT', 'CONTEST',
     'IMPLEMENTATION', '竞赛：多关键字排序与身份保持验收',
     'ALGO.SORT.BASIC.自定义比较', 'SK_SORT_COMPARATOR_CONTRACT',
     E'MP_SORT_ORIGINAL_INDEX_LOST\nMP_SORT_TIE_BREAKER_MISSING',
     'IP_DQ5_SORT_TOTAL_ORDER_KEY_TABLE',
     '记录排序题 n≤2×10^5，题面给出三层升降序规则，输出还依赖原始编号；部分分关键字互异。',
     '把题面逐句翻译为关键字元组，生成大量并列记录测试比较器；排序后用独立验收器检查每对相邻记录。',
     '学生比较器满足严格弱序，所有题面并列规则可观察，原始编号不会在重排中丢失。',
     '在部分分无并列时通过；比较器用小于等于破坏严格性；只保存值不保存身份。',
     '要求验收器报告第一对违反题面次序的相邻记录，并检查相等记录的原始身份。',
     '当三个关键字都相等时，题面要求稳定还是任意；该选择应由哪个字段体现。',
     'n≤2×10^5；字段值≤10^9；部分分无并列；正式复杂度 O(n log n)，内存 O(n)。',
     '并列压力数据通过，相邻验收 0 违规，原始编号完整且比较器无自反。',
     '竞赛把课堂手排变为自动相邻验收，重点仍是合同完整而不是比较器语法。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_WINDOW_CLASSROOM', 'PAIR_DQ5_WINDOW', 'CLASSROOM',
     'GUIDED_PRACTICE', '课堂：彩色卡片窗口的指针—计数守恒',
     'ALGO.TWO_POINTERS.WINDOW.窗口扩张', 'SK_WINDOW_INVARIANT',
     E'MP_WINDOW_COUNTER_NOT_SYNCED\nMP_WINDOW_SHRINK_CONDITION_TOO_LATE',
     'IP_DQ5_WINDOW_INVARIANT_LEDGER',
     '一列彩色卡片中寻找至多含 k 种颜色的最长连续段，学生用两个夹子表示窗口边界。',
     '每移动一个夹子就更新颜色频次、窗口长度、合法性和答案；把全过程填成守恒表。',
     '每行频次总和等于窗口长度；扩张后若非法立即收缩；答案只在合法窗口上更新。',
     '右指针移动但忘记加频次；左指针移动后未减到零；收缩晚一轮导致非法窗口计入答案。',
     '随机暂停在扩张后，要求学生先判断合法性、收缩次数和更新答案时机，再允许下一步。',
     '当某颜色频次从 1 降到 0 时，distinct 应在何时变化。',
     '20 分钟；序列长度 10～15；k=1、2；含连续重复和交替颜色。',
     '守恒表每行一致，所有合法窗口与朴素枚举对照，最长值正确。',
     '课堂用实体夹子看见不变量；竞赛把同一表压缩进 O(n) 指针事件。',
     'FOUNDATION', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_WINDOW_CONTEST', 'PAIR_DQ5_WINDOW', 'CONTEST',
     'IMPLEMENTATION', '竞赛：最大数据下的滑窗不变量对拍',
     'ALGO.TWO_POINTERS.WINDOW.窗口扩张', 'SK_WINDOW_INVARIANT',
     E'MP_WINDOW_COUNTER_NOT_SYNCED\nMP_WINDOW_SHRINK_CONDITION_TOO_LATE',
     'IP_DQ5_WINDOW_INVARIANT_LEDGER',
     '最长合法子数组题 n≤2×10^5，合法条件由频次或代价上限决定；小数据可枚举所有区间。',
     '先明确窗口区间和合法谓词，再用 n≤80 的随机序列与 O(n²) 枚举对拍；记录首个指针—计数分叉。',
     '学生能证明左右指针各只前进 n 次，频次与窗口同步，答案更新不包含非法状态。',
     '复杂条件下收缩一次就停止；计数删除不完整；把“至少”条件误套为单调收缩。',
     '要求先证明合法性随左端右移如何变化；若不具单调性，不允许直接使用滑窗。',
     '若当前窗口非法，连续移动 left 到合法的过程中，哪些统计量必须逐次更新。',
     'n≤2×10^5；值域可到 10^9；部分分 n≤2000 可枚举；正式目标 O(n) 或 O(n log n)。',
     '随机对拍 0 分叉，最大规模线性事件数，最小空窗和全合法边界通过。',
     '竞赛在课堂守恒表之外增加单调性证明和复杂度计数，防止把所有区间题都误判为滑窗。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_GRAPH_MODEL_CLASSROOM', 'PAIR_DQ5_GRAPH_MODEL', 'CLASSROOM',
     'CONCEPT_DISCOVERY', '课堂：交通关系的点边属性字典',
     'DS.GRAPH.MODEL.点的定义', 'SK_GRAPH_EDGE_MODELING',
     E'MP_GRAPH_UNDIRECTED_EDGE_ADDED_ONCE\nMP_GRAPH_WEIGHT_MEANING_IGNORED',
     'IP_DQ5_GRAPH_MODELING_DICTIONARY',
     '给出公交站、单行路、双向步道和票价/时间两种权值，让学生为不同问题选择图模型。',
     '填写点、边、方向、权值单位、重复关系和路径含义；用反向可达与最短费用反例检查模型。',
     '学生能从模型中的一条边准确回译题面关系，双向关系建立双向可达，权值进入目标函数。',
     '无向边只存一次单向邻接；把距离权值用于费用目标；点代表站还是线路前后不一致。',
     '逐项追问“反向是否成立、两条边能否合并、权值相加后代表什么”，要求答案引用题面。',
     '若同一站间有两条不同票价线路，它们是重复边还是必须保留的不同选择。',
     '25 分钟；6 个站、8 条关系；同一素材分别求可达、最少换乘和最低费用。',
     '三个任务的点边字典不同且均能重建题意，反例可淘汰错误模型。',
     '课堂先保证图是原问题的可执行翻译；竞赛选算法前继续完成同一字典。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_GRAPH_MODEL_CONTEST', 'PAIR_DQ5_GRAPH_MODEL', 'CONTEST',
     'PROBLEM_READING', '竞赛：从关系叙述到可验证图模型',
     'DS.GRAPH.MODEL.点的定义', 'SK_GRAPH_EDGE_MODELING',
     E'MP_GRAPH_UNDIRECTED_EDGE_ADDED_ONCE\nMP_GRAPH_WEIGHT_MEANING_IGNORED',
     'IP_DQ5_GRAPH_MODELING_DICTIONARY',
     '题面用人物、状态转换或道路关系叙述，n,m≤2×10^5，既有方向又有代价；部分分关系对称。',
     '先写点边字典，再构造能区分有向/无向、带权/无权和重复边处理的四个最小用例。',
     '学生选择的图能逐边回译题意，算法目标与边权单位一致，部分分对称性不会掩盖正式方向。',
     '看到“关系”默认无向；边权读入却算法忽略；合并重边时丢掉有意义的不同代价。',
     '在看代码前先审模型字典和四个区分用例；模型不闭合时不讨论 BFS、最短路等后续实现。',
     '删除方向或权值后，哪一个最小用例的期望答案必须改变。',
     'n,m≤2×10^5；权值≤10^9；部分分关系对称或权值相同；正式数据含反向不可达和重边。',
     '四个区分用例全部通过，模型字段与题面逐项对应，最大图存储预算合理。',
     '竞赛把课堂多任务模型选择变成读题第一张表，防止在错误图上优化正确算法。',
     'ADVANCED', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_HASH_CLASSROOM', 'PAIR_DQ5_HASH', 'CLASSROOM',
     'GUIDED_PRACTICE', '课堂：词频流的键—值—默认值总账',
     'DS.SET_MAP.MAP.键值关系', 'SK_HASH_FREQUENCY_MAPPING',
     E'MP_HASH_KEY_VALUE_ROLE_REVERSED\nMP_HASH_MISSING_DEFAULT_VALUE',
     'IP_DQ5_HASH_KEY_VALUE_DEFAULT_PROTOCOL',
     '逐个读入包含重复的新词，维护每个词的出现次数，并在任意时刻回答已处理总词数。',
     '每步记录键、查询前值、不存在时默认值、更新后值和所有频次之和。',
     '新词第一次出现从 0 开始，键和值角色稳定，频次总和等于已处理元素数。',
     '把次数当键、词当值；访问新键报错；更新后总量与输入长度不守恒。',
     '抽取任一步让学生预测更新前后 map 内容，并要求用总频次守恒检查。',
     '如果任务改成“次数对应哪些词”，原键值关系能否直接交换，重复次数键如何保存多个词。',
     '15 分钟；数据流 10 个词；至少 4 个新键和 3 次重复；允许纸面模拟。',
     '每一步默认值明确，最终频次与人工计数一致，总频次守恒。',
     '课堂把 map 看成有语义的状态表；竞赛在线查询只增加操作数量，不改变三元合同。',
     'FOUNDATION', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_HASH_CONTEST', 'PAIR_DQ5_HASH', 'CONTEST',
     'IMPLEMENTATION', '竞赛：在线频次映射的首次出现与守恒验证',
     'DS.SET_MAP.MAP.键值关系', 'SK_HASH_FREQUENCY_MAPPING',
     E'MP_HASH_KEY_VALUE_ROLE_REVERSED\nMP_HASH_MISSING_DEFAULT_VALUE',
     'IP_DQ5_HASH_KEY_VALUE_DEFAULT_PROTOCOL',
     '有 q≤2×10^5 次加入、删除和频次查询，键值域大且稀疏；部分分只有加入。',
     '定义每种操作前后 map 不变量，处理首次出现和删除到零；用随机操作流与朴素列表对拍。',
     '学生能正确处理不存在键、频次归零和重复删除，键空间只保存必要条目。',
     '查询新键抛错；删除不存在键产生负数；键值角色在不同操作中不一致。',
     '要求对拍同时检查每个键频次和全局频次总和，首个分叉输出导致异常的操作前状态。',
     '当某键频次降为 0 时，保留零值与删除键分别会影响哪些后续语义和内存。',
     'q≤2×10^5；键值≤10^18 或字符串；部分分无删除；平均操作目标 O(1) 或 O(log q)。',
     '随机操作对拍 0 分叉，不存在键有明确定义，最大稀疏键流内存可控。',
     '竞赛沿用课堂逐步总账，并用自动对拍覆盖大量首次出现与归零事件。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 20),

    ('SC_DQ5_SET_MAP_CHOICE_CLASSROOM', 'PAIR_DQ5_SET_MAP_CHOICE', 'CLASSROOM',
     'CONCEPT_DISCOVERY', '课堂：四类任务的数据结构操作矩阵',
     'DS.SET_MAP.SET.成员判断', 'SK_SET_MAP_OPERATION_CHOICE',
     'MP_SET_MAP_IGNORES_DUPLICATES',
     'IP_DQ5_SET_MAP_SORT_OPERATION_MATRIX',
     '用同一批号码分别完成成员判断、出现次数、去重后有序输出和批量离线查询四个任务。',
     '为 set、map、排序填写保留信息、支持操作、在线性、顺序性和复杂度矩阵，再为每个任务选择方案。',
     '学生能指出 set 丢失次数、map 保存键值、排序适合离线顺序处理，不因“都能查找”混为一谈。',
     '频次任务误用 set；只看单次查询不看更新；为有序输出额外维护不必要结构。',
     '把任务从“是否出现”改成“出现几次”，要求学生立即更新所需信息和结构选择。',
     '如果所有查询在数据读完后一次给出，在线结构是否仍是唯一方案。',
     '20 分钟；数据 12 个含重复号码；四类任务共用输入；不要求完整代码。',
     '每个选择都保留任务所需全部信息，复杂度估算包含构建和全部查询。',
     '课堂建立操作矩阵；竞赛读约束时据此在 set、map 与排序之间做成本可解释的选择。',
     'FOUNDATION', E'PYTHON\nCPP17', 10),

    ('SC_DQ5_SET_MAP_CHOICE_CONTEST', 'PAIR_DQ5_SET_MAP_CHOICE', 'CONTEST',
     'PROBLEM_READING', '竞赛：按信息需求与操作频率选结构',
     'DS.SET_MAP.SET.成员判断', 'SK_SET_MAP_OPERATION_CHOICE',
     'MP_SET_MAP_IGNORES_DUPLICATES',
     'IP_DQ5_SET_MAP_SORT_OPERATION_MATRIX',
     '题目给出 n,q≤2×10^5，操作可能是成员判断、频次查询、动态更新或最终有序输出；子任务逐步增加操作类型。',
     '从题面列出必须保留的信息和每类操作次数，比较 set、map、排序与离线扫描的总成本，再用重复值数据验收。',
     '学生选择不会丢失频次或顺序需求，能解释构建、更新、查询和输出的总复杂度。',
     '只凭熟悉程度选结构；set 去重后无法回答次数；排序方案用于动态更新却每次重排。',
     '要求提交操作矩阵和最大操作数预算；若两种方案都可行，选择更简单且满足全部信息的一种。',
     '把 q 从 1 改成 2×10^5，或加入动态更新后，原方案的哪项成本首先失效。',
     'n,q≤2×10^5；值域可稀疏；部分分只有静态成员判断；正式数据含大量重复与更新。',
     '重复值、空集合、最大 q 和有序输出均正确，总复杂度与内存不超过预算。',
     '竞赛把课堂四类任务混合在一题中，操作矩阵用于识别真正变化的是信息需求还是频率。',
     'INTERMEDIATE', E'PYTHON\nCPP17', 20);

INSERT INTO public.ai_standard_application_scenarios (
    code, transfer_pair_code, context_type, learning_phase, title,
    knowledge_point_code, skill_unit_code, linked_mistake_codes,
    linked_improvement_codes, task_context, student_task, observable_evidence,
    common_failure, teacher_move, student_check, constraint_profile,
    success_criteria, transfer_note, difficulty_level, applicable_languages,
    source_framework, source_reference, review_status, sort_order,
    enabled, library_version, created_at, updated_at
)
SELECT v.code, v.transfer_pair_code, v.context_type, v.learning_phase, v.title,
       v.knowledge_point_code, v.skill_unit_code, v.linked_mistake_codes,
       v.linked_improvement_codes, v.task_context, v.student_task, v.observable_evidence,
       v.common_failure, v.teacher_move, v.student_check, v.constraint_profile,
       v.success_criteria, v.transfer_note, v.difficulty_level, v.applicable_languages,
       CASE
           WHEN v.context_type = 'CLASSROOM' THEN 'MOE_HIGH_SCHOOL_IT_2020'
           ELSE 'CCF_NOI_2025'
       END,
       CASE
           WHEN v.context_type = 'CLASSROOM'
               THEN 'https://jyj.changdu.gov.cn/cdsjyj/c101476/202205/764ee1914e3c45aaba8e372f1b628a34/files/f97a4fa12a6c4acf94d34755a16a9d22.pdf'
           ELSE 'https://www.noi.cn/upload/resources/file/2025/04/18/NOI_Syllabus_Edition_2025.pdf'
       END,
       'INFERRED_REVIEWED', v.sort_order, true,
       'informatics-discipline-application-v1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM discipline_quality_v5_scenarios v
JOIN public.informatics_knowledge_nodes n
  ON n.code = v.knowledge_point_code AND n.enabled = true AND n.type = 'KNOWLEDGE_POINT'
JOIN public.ai_standard_skill_units s
  ON s.code = v.skill_unit_code
 AND s.enabled = true
 AND s.code NOT LIKE 'SK_COMPAT_%'
 AND s.primary_knowledge_node_code = v.knowledge_point_code
ON CONFLICT (code) DO UPDATE SET
    transfer_pair_code = EXCLUDED.transfer_pair_code,
    context_type = EXCLUDED.context_type,
    learning_phase = EXCLUDED.learning_phase,
    title = EXCLUDED.title,
    knowledge_point_code = EXCLUDED.knowledge_point_code,
    skill_unit_code = EXCLUDED.skill_unit_code,
    linked_mistake_codes = EXCLUDED.linked_mistake_codes,
    linked_improvement_codes = EXCLUDED.linked_improvement_codes,
    task_context = EXCLUDED.task_context,
    student_task = EXCLUDED.student_task,
    observable_evidence = EXCLUDED.observable_evidence,
    common_failure = EXCLUDED.common_failure,
    teacher_move = EXCLUDED.teacher_move,
    student_check = EXCLUDED.student_check,
    constraint_profile = EXCLUDED.constraint_profile,
    success_criteria = EXCLUDED.success_criteria,
    transfer_note = EXCLUDED.transfer_note,
    difficulty_level = EXCLUDED.difficulty_level,
    applicable_languages = EXCLUDED.applicable_languages,
    source_framework = EXCLUDED.source_framework,
    source_reference = EXCLUDED.source_reference,
    review_status = EXCLUDED.review_status,
    sort_order = EXCLUDED.sort_order,
    enabled = EXCLUDED.enabled,
    library_version = EXCLUDED.library_version,
    updated_at = CURRENT_TIMESTAMP;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.ai_standard_skill_units) THEN
        IF (SELECT count(*)
            FROM public.ai_standard_improvement_points
            WHERE enabled = true
              AND library_version = 'informatics-discipline-quality-v5') <> 17 THEN
            RAISE EXCEPTION 'V7 expected exactly 17 normalized improvement points';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM public.ai_standard_improvement_points i
            JOIN public.ai_standard_skill_units s ON s.code = i.skill_unit_code
            WHERE i.enabled = true
              AND i.library_version = 'informatics-discipline-quality-v5'
              AND s.code LIKE 'SK_COMPAT_%'
        ) THEN
            RAISE EXCEPTION 'V7 formal improvement points must not target compatibility skills';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM public.ai_standard_improvement_points i
            CROSS JOIN LATERAL regexp_split_to_table(COALESCE(i.related_mistake_codes, ''), E'\n') ref
            LEFT JOIN public.ai_standard_mistake_points m
              ON m.code = btrim(ref)
             AND m.enabled = true
             AND m.skill_unit_code = i.skill_unit_code
            WHERE i.enabled = true
              AND i.library_version = 'informatics-discipline-quality-v5'
              AND btrim(ref) <> ''
              AND m.code IS NULL
        ) THEN
            RAISE EXCEPTION 'V7 improvement contains invalid or cross-skill mistake reference';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM public.ai_standard_improvement_points i
            LEFT JOIN public.ai_standard_library_items item
              ON item.layer = 'IMPROVEMENT_POINT' AND item.code = i.code
            LEFT JOIN public.ai_standard_library_legacy_mappings map
              ON map.legacy_layer = 'IMPROVEMENT_POINT' AND map.legacy_code = i.code
            WHERE i.enabled = true
              AND i.library_version = 'informatics-discipline-quality-v5'
              AND (item.id IS NULL
                OR item.enabled IS DISTINCT FROM true
                OR item.skill_unit_code IS DISTINCT FROM i.skill_unit_code
                OR item.primary_knowledge_node_code IS DISTINCT FROM i.primary_knowledge_node_code
                OR item.related_items IS DISTINCT FROM i.related_mistake_codes
                OR map.id IS NULL
                OR map.migration_status <> 'MAPPED'
                OR map.target_type <> 'IMPROVEMENT_POINT'
                OR map.target_code <> i.code)
        ) THEN
            RAISE EXCEPTION 'V7 improvement normalized, snapshot or mapping structures are inconsistent';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM public.ai_standard_skill_units s
            WHERE s.enabled = true
              AND s.code NOT LIKE 'SK_COMPAT_%'
              AND NOT EXISTS (
                  SELECT 1
                  FROM public.ai_standard_improvement_points i
                  WHERE i.enabled = true AND i.skill_unit_code = s.code
              )
        ) THEN
            RAISE EXCEPTION 'V7 requires every formal non-compatibility skill to have an improvement path';
        END IF;

        IF (SELECT count(*)
        FROM public.ai_standard_application_scenarios
        WHERE enabled = true
          AND library_version = 'informatics-discipline-application-v1') <> 34 THEN
            RAISE EXCEPTION 'V7 expected exactly 34 application scenarios';
        END IF;

        IF (SELECT count(DISTINCT transfer_pair_code)
        FROM public.ai_standard_application_scenarios
        WHERE enabled = true
          AND library_version = 'informatics-discipline-application-v1') <> 17 THEN
            RAISE EXCEPTION 'V7 expected exactly 17 teaching-contest transfer pairs';
        END IF;

        IF EXISTS (
        SELECT transfer_pair_code
        FROM public.ai_standard_application_scenarios
        WHERE enabled = true
          AND library_version = 'informatics-discipline-application-v1'
        GROUP BY transfer_pair_code
        HAVING count(*) <> 2
           OR count(*) FILTER (WHERE context_type = 'CLASSROOM') <> 1
           OR count(*) FILTER (WHERE context_type = 'CONTEST') <> 1
           OR count(DISTINCT skill_unit_code) <> 1
           OR count(DISTINCT knowledge_point_code) <> 1
        ) THEN
            RAISE EXCEPTION 'V7 application scenario pairs must contain one classroom and one contest context for one skill';
        END IF;

        IF EXISTS (
        SELECT 1
        FROM public.ai_standard_application_scenarios a
        LEFT JOIN public.informatics_knowledge_nodes n
          ON n.code = a.knowledge_point_code AND n.enabled = true AND n.type = 'KNOWLEDGE_POINT'
        LEFT JOIN public.ai_standard_skill_units s
          ON s.code = a.skill_unit_code AND s.enabled = true
        WHERE a.enabled = true
          AND a.library_version = 'informatics-discipline-application-v1'
          AND (n.code IS NULL
            OR s.code IS NULL
            OR s.code LIKE 'SK_COMPAT_%'
            OR s.primary_knowledge_node_code IS DISTINCT FROM a.knowledge_point_code)
        ) THEN
            RAISE EXCEPTION 'V7 application scenario must reference one formal skill under its primary knowledge point';
        END IF;

        IF EXISTS (
        SELECT 1
        FROM public.ai_standard_application_scenarios a
        CROSS JOIN LATERAL regexp_split_to_table(COALESCE(a.linked_mistake_codes, ''), E'\n') ref
        LEFT JOIN public.ai_standard_mistake_points m
          ON m.code = btrim(ref)
         AND m.enabled = true
         AND m.skill_unit_code = a.skill_unit_code
        WHERE a.enabled = true
          AND a.library_version = 'informatics-discipline-application-v1'
          AND btrim(ref) <> ''
          AND m.code IS NULL
        ) THEN
            RAISE EXCEPTION 'V7 application scenario contains invalid or cross-skill mistake reference';
        END IF;

        IF EXISTS (
        SELECT 1
        FROM public.ai_standard_application_scenarios a
        CROSS JOIN LATERAL regexp_split_to_table(COALESCE(a.linked_improvement_codes, ''), E'\n') ref
        LEFT JOIN public.ai_standard_improvement_points i
          ON i.code = btrim(ref)
         AND i.enabled = true
         AND i.skill_unit_code = a.skill_unit_code
        WHERE a.enabled = true
          AND a.library_version = 'informatics-discipline-application-v1'
          AND btrim(ref) <> ''
          AND i.code IS NULL
        ) THEN
            RAISE EXCEPTION 'V7 application scenario contains invalid or cross-skill improvement reference';
        END IF;

        IF EXISTS (
        SELECT 1
        FROM public.ai_standard_application_scenarios a
        WHERE a.enabled = true
          AND a.library_version = 'informatics-discipline-application-v1'
          AND (length(btrim(a.task_context)) < 30
            OR length(btrim(a.student_task)) < 30
            OR length(btrim(a.observable_evidence)) < 30
            OR length(btrim(a.common_failure)) < 20
            OR length(btrim(a.teacher_move)) < 25
            OR length(btrim(a.student_check)) < 20
            OR length(btrim(a.constraint_profile)) < 25
            OR length(btrim(a.success_criteria)) < 25
            OR length(btrim(a.transfer_note)) < 25
            OR a.task_context LIKE '%待补%'
            OR a.teacher_move LIKE '%加强练习%'
            OR a.success_criteria LIKE '%待定%')
        ) THEN
            RAISE EXCEPTION 'V7 application scenario contains thin or placeholder teaching content';
        END IF;

        IF EXISTS (
        SELECT 1
        FROM public.ai_standard_application_scenarios a
        WHERE a.enabled = true
          AND a.library_version = 'informatics-discipline-application-v1'
          AND ((a.context_type = 'CLASSROOM'
                AND (a.source_framework <> 'MOE_HIGH_SCHOOL_IT_2020'
                  OR a.source_reference NOT LIKE 'https://jyj.changdu.gov.cn/%'))
            OR (a.context_type = 'CONTEST'
                AND (a.source_framework <> 'CCF_NOI_2025'
                  OR a.source_reference <> 'https://www.noi.cn/upload/resources/file/2025/04/18/NOI_Syllabus_Edition_2025.pdf'))
            OR a.review_status <> 'INFERRED_REVIEWED')
        ) THEN
            RAISE EXCEPTION 'V7 application scenario source or review status is inconsistent';
        END IF;

        IF EXISTS (
        SELECT 1
        FROM discipline_quality_v5_improvements i
        WHERE (SELECT count(*)
               FROM public.ai_standard_application_scenarios a
               WHERE a.enabled = true
                 AND a.library_version = 'informatics-discipline-application-v1'
                 AND a.skill_unit_code = i.skill_unit_code) <> 2
        ) THEN
            RAISE EXCEPTION 'V7 every improved formal skill must own one classroom-contest scenario pair';
        END IF;
    END IF;
END $$;

DROP TABLE discipline_quality_v5_scenarios;
DROP TABLE discipline_quality_v5_improvements;
